export type MentorMode='teacher'|'coach'|'motivator'|'performance_director'|'career_mentor'|'encourager';
export type MentorInput={firstName:string;hour?:number;practiceStreak:number;averageProgress:number;creativeHealth?:number;confidence?:number;careerReadiness?:number;activeCourses:number;certificateCount:number;achievementCount:number;missionTitle?:string;missionMinutes?:number;missionXp?:number;missionCourse?:string};
export type MentorPlan={mode:MentorMode;modeLabel:string;greeting:string;message:string;mission:{title:string;detail:string;minutes:number;xp:number;to:string};signals:{label:string;value:number;trend:'building'|'steady'|'attention'}[];memoryKey:string};
const labels:Record<MentorMode,string>={teacher:'Teacher',coach:'Creative Coach',motivator:'Motivator',performance_director:'Performance Director',career_mentor:'Career Mentor',encourager:'Encourager'};
function timeGreeting(hour:number){if(hour<12)return'Good morning';if(hour<17)return'Good afternoon';return'Good evening'}
function selectMode(input:MentorInput):MentorMode{if((input.confidence??60)<45)return'encourager';if(input.practiceStreak>=5)return'motivator';if((input.averageProgress>=75)||(input.creativeHealth??0)>=80)return'performance_director';if((input.careerReadiness??0)>=55)return'career_mentor';if(input.activeCourses>0)return'coach';return'teacher'}
export function buildMentorPlan(input:MentorInput):MentorPlan{const hour=input.hour??new Date().getHours();const mode=selectMode(input);const missionTitle=input.missionTitle||'Focused Creative Practice';const minutes=input.missionMinutes||15;const xp=input.missionXp||250;let message='Choose one creative path today, and I will begin shaping guidance around how you learn best.';if(mode==='encourager')message='You do not have to master everything today. Let’s make one small adjustment, practice it with purpose, and finish with a win.';else if(mode==='motivator')message=`Your ${input.practiceStreak}-day practice streak is building real momentum. Protect that consistency with one focused session today.`;else if(mode==='performance_director')message='Your recent progress suggests you are ready to move from practice into performance. Complete today’s mission, then record one confident run.';else if(mode==='career_mentor')message='Your skills are beginning to connect to your career direction. Today’s work should produce one piece of evidence for your Creative Passport.';else if(mode==='coach')message=`You are averaging ${input.averageProgress}% progress across your active learning. Let’s strengthen the next skill instead of rushing ahead.`;
const courseText=input.missionCourse?` in ${input.missionCourse}`:'';return{mode,modeLabel:labels[mode],greeting:`${timeGreeting(hour)}, ${input.firstName}.`,message,mission:{title:missionTitle,detail:`Spend ${minutes} focused minutes${courseText}. Record or reflect on one improvement before you finish.`,minutes,xp,to:'/studio'},signals:[{label:'Confidence',value:Math.round(input.confidence??60),trend:(input.confidence??60)<45?'attention':'building'},{label:'Consistency',value:Math.min(100,Math.max(20,input.practiceStreak*12)),trend:input.practiceStreak>=3?'building':'steady'},{label:'Creative health',value:Math.round(input.creativeHealth??Math.max(50,input.averageProgress)),trend:(input.creativeHealth??input.averageProgress)>=70?'building':'steady'}],memoryKey:`${new Date().toISOString().slice(0,10)}:${mode}:${missionTitle}`}}
export function rememberMentorSession(studentId:string,plan:MentorPlan){try{localStorage.setItem(`jpac:aria:mentor:${studentId}`,JSON.stringify({at:new Date().toISOString(),mode:plan.mode,mission:plan.mission.title,memoryKey:plan.memoryKey}))}catch{}}
export function readMentorSession(studentId:string){try{const value=localStorage.getItem(`jpac:aria:mentor:${studentId}`);return value?JSON.parse(value)as{at:string;mode:MentorMode;mission:string;memoryKey:string}:null}catch{return null}}
