import{parseCurriculumImportPreview,summarizeImportPreviewDecisions,validateCurriculumImportFile}from'./curriculumImportPreview';
import{CURRICULUM_IMPORT_MAX_BYTES}from'../types/curriculumImportPreview';
import type{ImportPreviewContext}from'../types/curriculumImportPreview';

const lesson=(title='Lesson',sort_order=1)=>({sort_order,title,description:'Draft lesson',status:'draft',duration_minutes:20,short_summary:'Summary',learning_objective:'Learn safely <script>alert(1)</script>',content_blocks:['Concept'],technique_cues:['Relax'],common_mistakes:['Rush'],self_check:'Reflect',resource_url:null});
const bands={Exceeds:'Exceeds.',Meets:'Meets.',Developing:'Developing.','Not Yet':'Not yet.'};
const rubric={criteria:[['Technique',30],['Accuracy',25],['Timing',20],['Reflection',15],['Completeness',10]].map(([name,weight])=>({name,weight,bands}))};
const activity=(title:string,role:string)=>({role,title,description:'Draft activity',instructions:'Complete the activity.',activity_type:role==='practice'?'practice':'performance',submission_type:role==='practice'?'none':'video',status:'draft',required:role!=='practice',xp_reward:role==='practice'?0:350,xp_type:role==='practice'?'bonus':'core',passing_score:70,allows_resubmission:true,portfolio_candidate:false,rubric:role==='practice'?{}:rubric});
const module=(number:number,title=`Module ${number}`)=>({module_number:number,sort_order:number,title,description:'Draft module',status:'draft',mission:{short_intro:'Intro',career_connection:'',real_world_activity:{},aria_coaching_targets:{},career_mission_ideas:[],portfolio_moment:false,portfolio_ready_threshold:null,review_notes:'Review'},xp:{intro:50,instructional_media:100,core_challenge:350,mastery:125,module_total:625,unlock_threshold:438,passing_score:70},lessons:[lesson('Lesson 1',1),lesson('Lesson 2',2),lesson('Lesson 3',3)],activities:{practice:[activity('Practice','practice')],core_challenge:[activity('Challenge','core_challenge')],other:[]},media:{review_status:'NEEDS_REVIEW',legacy_projection:{url:null,provider:null,title:null,duration_seconds:null,brief:'Needs review'},versions:[]},tool:{review_status:'NEEDS_CATALOG_REVIEW',activity_configuration:{},catalog_reference:null},career_path_attachments:{status:'NOT_CONFIGURED',items:[]}});
const level=(number:number,count=2)=>({level_number:number,title:`Level ${number}`,status:'draft',modules:Array.from({length:count},(_,index)=>module(index+1))});
const envelope=(scope:Record<string,unknown>)=>({contract:'jpac-curriculum-export',contract_version:'1.2.0',export_scope:scope,options:{include_database_ids:false},warnings:[{code:'MEDIA_NEEDS_REVIEW',message:'Review media'}],course:{course_slug:'piano',title:'Piano',description:'<img src=x onerror=alert(1)>',status:'draft'}});
export const validModuleImportFixture={...envelope({type:'module',course_slug:'piano',level_number:1,module_number:1}),level:{level_number:1,title:'Beginner',status:'draft'},module:module(1,'Piano Posture')};
export const validLevelImportFixture={...envelope({type:'level',course_slug:'piano',level_number:1}),level:level(1)};
export const validCourseImportFixture={...envelope({type:'course',course_slug:'piano'}),summary:{level_count:99,module_count:99,lesson_count:99,activity_count:99,warning_count:99},course:{...envelope({}).course,database_id:'course-id',levels:[level(2),level(1)]}};
export const piano48ImportFixture={...envelope({type:'course',course_slug:'piano'}),course:{...envelope({}).course,levels:Array.from({length:4},(_,index)=>level(index+1,12))}};
const context:ImportPreviewContext={selected_course_slug:'piano',modules:[{level_number:1,module_number:1,title:'Piano Posture'}]};
const code=(value:unknown,ctx=context)=>{const result=parseCurriculumImportPreview(typeof value==='string'?value:JSON.stringify(value),ctx);return result.ok?'OK':result.findings[0]?.code};

export function verifyCurriculumImportPreviewFixtures(){
  const reused=parseCurriculumImportPreview(JSON.stringify(validModuleImportFixture),context);
  const created=parseCurriculumImportPreview(JSON.stringify({...validModuleImportFixture,export_scope:{type:'module',course_slug:'piano',level_number:1,module_number:2},module:module(2)}),context);
  const conflict=parseCurriculumImportPreview(JSON.stringify({...validModuleImportFixture,module:module(1,'Different title')}),context);
  const mismatch=parseCurriculumImportPreview(JSON.stringify({...validModuleImportFixture,export_scope:{type:'module',course_slug:'guitar',level_number:1,module_number:1},course:{...validModuleImportFixture.course,course_slug:'guitar'}}),context);
  const course=parseCurriculumImportPreview(JSON.stringify(validCourseImportFixture),context);
  const pianoContext:ImportPreviewContext={selected_course_slug:'piano',modules:Array.from({length:4},(_,levelIndex)=>Array.from({length:12},(_,moduleIndex)=>({level_number:levelIndex+1,module_number:moduleIndex+1,title:`Module ${moduleIndex+1}`}))).flat()};
  const piano=parseCurriculumImportPreview(JSON.stringify(piano48ImportFixture),pianoContext);
  const duplicate={...validLevelImportFixture,level:{...validLevelImportFixture.level,modules:[module(1),module(1)]}};
  const malformed={...validModuleImportFixture,module:{...validModuleImportFixture.module,lessons:{}}};
  const missingIdentifiers={...validModuleImportFixture,export_scope:{type:'module',course_slug:'piano'}};
  const ids=course.ok&&course.preview.contains_database_ids;
  const reuseSummary=reused.ok?summarizeImportPreviewDecisions(reused.preview):null,createSummary=created.ok?summarizeImportPreviewDecisions(created.preview):null,conflictSummary=conflict.ok?summarizeImportPreviewDecisions(conflict.preview):null,mismatchSummary=mismatch.ok?summarizeImportPreviewDecisions(mismatch.preview):null,pianoSummary=piano.ok?summarizeImportPreviewDecisions(piano.preview):null;
  const uncheckedContext:ImportPreviewContext={selected_course_slug:null,modules:[]};const unchecked=parseCurriculumImportPreview(JSON.stringify(validModuleImportFixture),uncheckedContext);const uncheckedSummary=unchecked.ok?summarizeImportPreviewDecisions(unchecked.preview):null;
  const mixedPreview=reused.ok?{...reused.preview,levels:[{...reused.preview.levels[0],modules:[{...reused.preview.levels[0].modules[0],comparison_status:'WOULD_REUSE' as const},{...reused.preview.levels[0].modules[0],module_number:2,comparison_status:'WOULD_CREATE' as const},{...reused.preview.levels[0].modules[0],module_number:3,comparison_status:'POSSIBLE_CONFLICT' as const},{...reused.preview.levels[0].modules[0],module_number:4,comparison_status:'COURSE_MISMATCH' as const},{...reused.preview.levels[0].modules[0],module_number:5,comparison_status:'NOT_CHECKED' as const}]}],counts:{...reused.preview.counts,modules:5}}:null;const mixedSummary=mixedPreview?summarizeImportPreviewDecisions(mixedPreview):null;
  const incomplete=mixedPreview?summarizeImportPreviewDecisions({...mixedPreview,counts:{...mixedPreview.counts,modules:6}}):null;
  const duplicateResult=parseCurriculumImportPreview(JSON.stringify(duplicate),context);const duplicateSummary=duplicateResult.ok?summarizeImportPreviewDecisions(duplicateResult.preview):null;
  return reused.ok&&reuseSummary?.would_reuse===1&&reuseSummary.complete&&created.ok&&createSummary?.would_create===1&&conflict.ok&&conflictSummary?.possible_conflicts===1&&mismatch.ok&&mismatchSummary?.course_mismatch===1&&uncheckedSummary?.not_checked===1&&mixedSummary?.total===5&&mixedSummary.would_reuse===1&&mixedSummary.would_create===1&&mixedSummary.possible_conflicts===1&&mixedSummary.course_mismatch===1&&mixedSummary.not_checked===1&&incomplete?.complete===false&&course.ok&&course.preview.levels[0].level_number===1&&course.preview.findings.some(item=>item.code==='SUMMARY_MISMATCH')&&ids&&piano.ok&&piano.preview.counts.levels===4&&piano.preview.counts.modules===48&&piano.preview.counts.lessons===144&&piano.preview.counts.activities===96&&pianoSummary?.would_reuse===48&&pianoSummary.total===48&&duplicateSummary?.possible_conflicts===2&&code('{')==='INVALID_JSON'&&code([])==='TOP_LEVEL_OBJECT_REQUIRED'&&code({...validModuleImportFixture,contract:'wrong'})==='UNSUPPORTED_CONTRACT'&&code({...validModuleImportFixture,contract_version:'1.1.0'})==='UNSUPPORTED_VERSION'&&code({...validModuleImportFixture,export_scope:{type:'unknown',course_slug:'piano'}})==='INVALID_SCOPE'&&code(missingIdentifiers)==='LEVEL_NUMBER_MISSING'&&code(malformed)==='LESSONS_ARRAY_INVALID'&&code(duplicate)==='OK'&&validateCurriculumImportFile('course.txt',1)?.code==='FILE_TYPE_UNSUPPORTED'&&validateCurriculumImportFile('course.json',CURRICULUM_IMPORT_MAX_BYTES+1)?.code==='FILE_TOO_LARGE'&&code('x'.repeat(CURRICULUM_IMPORT_MAX_BYTES+1))==='PASTE_TOO_LARGE'&&reused.preview.course.description.includes('<img');
}
