import{supabase}from'./supabase';
import type{AssignmentSwapActivity,AssignmentSwapBands,AssignmentSwapContext,AssignmentSwapForm,AssignmentSwapPayload,AssignmentSwapResponse,AssignmentSwapRole,AssignmentSwapRubric}from'../types/curriculumAssignmentSwap';

const bandSets=[['Exceeds','Meets','Developing','Not Yet'],['exceeds','meets','developing','not_yet']]as const;
const object=(value:unknown):Record<string,unknown>=>value!==null&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
const text=(value:unknown)=>typeof value==='string'?value:'';
export function assignmentSwapRole(activity:AssignmentSwapActivity):AssignmentSwapRole|null{
  if(activity.lesson_id!==null||activity.status!=='draft'||activity.portfolio_candidate||activity.certificate_eligible)return null;
  if(activity.activity_type==='performance'&&activity.required&&activity.xp_reward===350&&activity.xp_type==='core')return'core_challenge';
  if(activity.activity_type==='practice'&&!activity.required&&activity.xp_reward===0&&activity.xp_type==='bonus')return'practice';
  return null;
}
export function normalizeAssignmentSwapRubric(value:unknown):AssignmentSwapRubric|null{const criteria=object(value).criteria;if(!Array.isArray(criteria)||criteria.length!==5)return null;const names=new Set<string>();let total=0;const normalized=[] as AssignmentSwapRubric['criteria'];for(const raw of criteria){const row=object(raw),name=text(row.name),weight=Number(row.weight),bands=object(row.bands),keys=Object.keys(bands);const set=bandSets.find(candidate=>candidate.length===keys.length&&candidate.every(key=>keys.includes(key)));if(!name.trim()||names.has(name)||!Number.isFinite(weight)||weight<=0||!set)return null;const mapped:AssignmentSwapBands={Exceeds:text(bands[set[0]]),Meets:text(bands[set[1]]),Developing:text(bands[set[2]]),'Not Yet':text(bands[set[3]])};if(Object.values(mapped).some(value=>!value.trim()))return null;names.add(name);total+=weight;normalized.push({name,weight,bands:mapped})}return total===100?{criteria:normalized}:null}
export function assignmentSwapBlockers(context:AssignmentSwapContext,form?:AssignmentSwapForm){const result:string[]=[];const role=assignmentSwapRole(context.activity);if(!context.can_swap)result.push('Administrator or developer access is required.');if(context.course.slug==='singing')result.push('Singing is protected.');if(context.module.status!=='draft')result.push('Only draft modules are supported.');if(!role)result.push('Select one eligible draft Core Challenge or optional Practice.');if(context.module.core_xp!==625||context.module.intro_core_xp!==50||context.module.video_core_xp!==100||context.module.assignment_core_xp!==350||context.module.mastery_core_xp!==125||context.module.core_unlock_threshold!==438)result.push('Module XP does not match the protected JPAC contract.');if(form){if(!form.title.trim()||!form.instructions.trim())result.push('Title and instructions are required.');if(!['none','text','audio','video','file','link','teacher_verification'].includes(form.submission_type))result.push('Submission type is unsupported.');if(form.passing_score!==70||!form.allows_resubmission)result.push('Passing score 70 and resubmission are required.');if(role==='core_challenge'&&!normalizeAssignmentSwapRubric(form.rubric))result.push('Core Challenge rubric must contain five complete criteria totaling 100.');if(role==='practice'&&form.rubric!==undefined)result.push('Practice rubric replacement is not supported.')}return result}
export function initialAssignmentSwapForm(activity:AssignmentSwapActivity):AssignmentSwapForm{const role=assignmentSwapRole(activity);return{title:activity.title,description:activity.description||'',instructions:activity.instructions||'',submission_type:activity.submission_type,passing_score:activity.passing_score,allows_resubmission:activity.allows_resubmission,...(role==='core_challenge'?{rubric:normalizeAssignmentSwapRubric(activity.rubric)||undefined}:{})}}
export function buildAssignmentSwapPayload(context:AssignmentSwapContext,form:AssignmentSwapForm):AssignmentSwapPayload{const role=assignmentSwapRole(context.activity);if(!role||assignmentSwapBlockers(context,form).length)throw new Error('Assignment Swap payload is not eligible.');const replacement:AssignmentSwapForm={title:form.title.trim(),description:form.description,instructions:form.instructions,submission_type:form.submission_type,passing_score:70,allows_resubmission:true,...(role==='core_challenge'?{rubric:normalizeAssignmentSwapRubric(form.rubric)!}:{})};return{contract:'jpac-assignment-swap',contract_version:'1.0.0',target_course_id:context.course.id,target_module_id:context.module.id,target_activity_id:context.activity.id,assignment_role:role,expected_current:{course_slug:context.course.slug,level_number:context.level.level_number,module_number:context.module.level_module_number,module_title:context.module.title,module_sort_order:context.module.sort_order,module_status:context.module.status,activity_snapshot:{title:context.activity.title,description:context.activity.description,instructions:context.activity.instructions,submission_type:context.activity.submission_type,passing_score:context.activity.passing_score,allows_resubmission:context.activity.allows_resubmission,rubric:context.activity.rubric}},replacement,acknowledged_warning_codes:[],confirmation:{draft_only:true,preserve_activity_identity:true,no_student_evidence:true}}}
export async function executeAssignmentSwap(payload:AssignmentSwapPayload):Promise<AssignmentSwapResponse>{if(!supabase)throw new Error('Curriculum service is unavailable.');const{data,error}=await supabase.rpc('curriculum_swap_module_assignment_v1',{swap_payload:payload});if(error)throw new Error(error.message);const row=object(data);if(row.status!=='applied'||typeof row.operation_id!=='string'||row.target_activity_id!==payload.target_activity_id)throw new Error('Assignment Swap returned an unexpected response.');return data as AssignmentSwapResponse}
export function safeAssignmentSwapError(error:unknown){const message=error instanceof Error?error.message:'Assignment Swap failed.';return message.length<=240?message:'Assignment Swap failed. Refresh Curriculum Studio before trying again.'}
