import{buildSaveDraftRpcPayload,evaluateSaveDraftEligibility,extractSourceWarningCodes,sanitizeSaveDraftError,validateSaveDraftRpcResponse}from'./curriculumSaveDraft';
import{parseCurriculumImportPreview}from'./curriculumImportPreview';
import{validModuleImportFixture,validLevelImportFixture,validCourseImportFixture}from'./curriculumImportPreview.fixtures';
import type{ImportPreviewContext,SaveDraftContext}from'../types/curriculumImportPreview';

const source=(value:unknown)=>JSON.stringify(value);const context:ImportPreviewContext={selected_course_slug:'piano',modules:[]};
const base:SaveDraftContext={selected_course_id:'11111111-1111-4111-8111-111111111111',selected_course_slug:'piano',can_save_draft:true,acknowledged_warning_codes:['MEDIA_NEEDS_REVIEW'],confirmed:true,pending:false};
const preview=(value:unknown,ctx=context)=>{const result=parseCurriculumImportPreview(source(value),ctx);if(!result.ok)throw new Error(result.findings[0]?.code);return result.preview};
const eligible=(value:unknown,saveContext=base,ctx=context)=>evaluateSaveDraftEligibility(source(value),preview(value,ctx),saveContext);
const mutate=(patch:Record<string,unknown>)=>({...validModuleImportFixture,module:{...validModuleImportFixture.module,...patch}});
export function curriculumSaveDraftFixtureResults(){const validPreview=preview(validModuleImportFixture);const payload=buildSaveDraftRpcPayload(source(validModuleImportFixture),validPreview,base);const module=validModuleImportFixture.module;
  const statuses=['WOULD_REUSE','POSSIBLE_CONFLICT','COURSE_MISMATCH','NOT_CHECKED']as const;const statusBlocked=statuses.every(status=>{const changed={...validPreview,levels:[{...validPreview.levels[0],modules:[{...validPreview.levels[0].modules[0],comparison_status:status}]}]};return!evaluateSaveDraftEligibility(source(validModuleImportFixture),changed,base).eligible});
  const success={operation_id:'22222222-2222-4222-8222-222222222222',module_id:'33333333-3333-4333-8333-333333333333',lesson_ids:['44444444-4444-4444-8444-444444444444'],activity_ids:['55555555-5555-4555-8555-555555555555'],status:'draft',created_counts:{modules:1,lessons:1,activities:1},unresolved_review_statuses:['MEDIA_NEEDS_REVIEW']};
  const badXp=mutate({xp:{...module.xp,intro:51}}),badRubric=mutate({activities:{...module.activities,core_challenge:[{...module.activities.core_challenge[0],rubric:{criteria:[]}}]}}),activeMedia=mutate({media:{...module.media,versions:[{database_id:'x'}]}}),tool=mutate({tool:{...module.tool,catalog_reference:{database_id:'x'}}}),career=mutate({career_path_attachments:{status:'CONFIGURED',items:[{id:'x'}]}}),portfolio=mutate({mission:{...module.mission,portfolio_moment:true}}),other=mutate({activities:{...module.activities,other:[module.activities.practice[0]]}}),multiPractice=mutate({activities:{...module.activities,practice:[module.activities.practice[0],module.activities.practice[0]]}}),notDraft=mutate({status:'published'}),prohibited={...validModuleImportFixture,student_id:'x'},malformedWarnings={...validModuleImportFixture,warnings:[{message:'No code'}]};
  return{eligible:eligible(validModuleImportFixture).eligible,statusBlocked,levelBlocked:!eligible(validLevelImportFixture).eligible,courseBlocked:!eligible(validCourseImportFixture).eligible,badXpBlocked:!eligible(badXp).eligible,badRubricBlocked:!eligible(badRubric).eligible,activeMediaBlocked:!eligible(activeMedia).eligible,toolBlocked:!eligible(tool).eligible,careerBlocked:!eligible(career).eligible,portfolioBlocked:!eligible(portfolio).eligible,otherBlocked:!eligible(other).eligible,multiPracticeBlocked:!eligible(multiPractice).eligible,notDraftBlocked:!eligible(notDraft).eligible,prohibitedBlocked:!eligible(prohibited).eligible,malformedWarningsBlocked:!eligible(malformedWarnings).eligible,teacherBlocked:!eligible(validModuleImportFixture,{...base,can_save_draft:false}).eligible,confirmationBlocked:!eligible(validModuleImportFixture,{...base,confirmed:false}).eligible,pendingBlocked:!eligible(validModuleImportFixture,{...base,pending:true}).eligible,warningBlocked:!eligible(validModuleImportFixture,{...base,acknowledged_warning_codes:[]}).eligible,warningExtracted:extractSourceWarningCodes(source(validModuleImportFixture)).codes.length===1,payloadStripped:!JSON.stringify(payload).includes('"database_id":'),payloadDraft:(payload.module as Record<string,unknown>).status==='draft',validResponse:Boolean(validateSaveDraftRpcResponse(success)),invalidResponse:!validateSaveDraftRpcResponse({...success,status:'published'}),safeError:sanitizeSaveDraftError({message:'network timeout'}).includes('Refresh Curriculum Studio')};
}
export function verifyCurriculumSaveDraftFixtures(){return Object.values(curriculumSaveDraftFixtureResults()).every(Boolean)}
