import{summarizeImportPreviewDecisions}from'./curriculumImportPreview';
import type{CurriculumImportPreview,SaveDraftContext,SaveDraftEligibility,SaveDraftRpcResponse}from'../types/curriculumImportPreview';

type Row=Record<string,unknown>;
const object=(value:unknown):value is Row=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value);
const text=(value:unknown)=>typeof value==='string'?value:'';
const finite=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)?value:null;
const array=(value:unknown)=>Array.isArray(value)?value:[];
const uuid=(value:unknown)=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const prohibitedKeys=new Set(['database_id','student_id','enrollment_id','submission_id','review_id','approved_by','approved_at','certificate_id','portfolio_project_id','evidence_id','xp_ledger_id','progress','unlock','published_at','completed_at','mastered_at','workflow_function','award_xp','lab_tool_id','tool_id','catalog_id','launch_url','active_instructional_media_id','media_id','provider_media_id','replaces_media_id']);
const canonicalModuleXpPath=(path:string)=>path==='$.module.xp'||/^\$\.level\.modules\[\d+\]\.xp$/.test(path)||/^\$\.course\.levels\[\d+\]\.modules\[\d+\]\.xp$/.test(path);
function findProhibited(value:unknown,path='$'):string[]{if(Array.isArray(value))return value.flatMap((item,index)=>findProhibited(item,`${path}[${index}]`));if(!object(value))return[];return Object.entries(value).flatMap(([key,item])=>[...(prohibitedKeys.has(key)||(key==='mastery'&&!canonicalModuleXpPath(path))?[`${path}.${key}`]:[]),...findProhibited(item,`${path}.${key}`)])}
function parsed(source:string):Row|null{try{const value=JSON.parse(source)as unknown;return object(value)?value:null}catch{return null}}
function warningRows(source:string):Row[]|null{const root=parsed(source);return root&&Array.isArray(root.warnings)&&root.warnings.every(object)?root.warnings as Row[]:null}
export function extractSourceWarningCodes(source:string):{codes:string[];malformed:boolean}{const warnings=warningRows(source);if(!warnings)return{codes:[],malformed:true};const codes:string[]=[];for(const warning of warnings){const code=text(warning.code).trim();if(!code)return{codes:[],malformed:true};if(!codes.includes(code))codes.push(code)}return{codes,malformed:false}}

const titleBandKeys=['Exceeds','Meets','Developing','Not Yet']as const;
const databaseBandKeys=['exceeds','meets','developing','not_yet']as const;
function rubricBandShape(bands:Row){const keys=Object.keys(bands);if(keys.length!==4)return null;if(titleBandKeys.every(key=>keys.includes(key)&&Boolean(text(bands[key]).trim())))return'title' as const;if(databaseBandKeys.every(key=>keys.includes(key)&&Boolean(text(bands[key]).trim())))return'database' as const;return null}
function rubricValid(value:unknown){if(!object(value)||!Array.isArray(value.criteria)||value.criteria.length!==5)return false;const names=new Set<string>();let total=0;for(const item of value.criteria){if(!object(item))return false;const name=text(item.name).trim(),weight=finite(item.weight);if(!name||weight===null||weight<=0||names.has(name)||!object(item.bands)||!rubricBandShape(item.bands))return false;names.add(name);total+=weight}return total===100}
function normalizeRubric(value:unknown){const rubric=value as Row;return{criteria:(rubric.criteria as Row[]).map(item=>{const bands=item.bands as Row;const shape=rubricBandShape(bands);return{name:item.name,weight:item.weight,bands:shape==='database'?{Exceeds:bands.exceeds,Meets:bands.meets,Developing:bands.developing,'Not Yet':bands.not_yet}:{Exceeds:bands.Exceeds,Meets:bands.Meets,Developing:bands.Developing,'Not Yet':bands['Not Yet']}}})}}
function sourceStructureBlockers(source:string):Array<{code:string;message:string}>{const root=parsed(source);if(!root)return[{code:'SOURCE_INVALID',message:'The original JSON must remain valid.'}];const blockers:Array<{code:string;message:string}>=[];const add=(code:string,message:string)=>blockers.push({code,message});
  if(root.contract!=='jpac-curriculum-export'||root.contract_version!=='1.2.0')add('CONTRACT_INVALID','Only JPAC curriculum export 1.2.0 is supported.');
  const scope=object(root.export_scope)?root.export_scope:null;if(!scope||scope.type!=='module')add('MODULE_SCOPE_REQUIRED','Save as Draft v1 supports one module only.');
  if(root.options&&(!object(root.options)||root.options.include_database_ids!==false))add('DATABASE_IDS_ENABLED','Include database IDs must be off.');
  const prohibited=findProhibited(root);if(prohibited.length)add('PROHIBITED_FIELDS',`Prohibited fields were found: ${prohibited.slice(0,5).join(', ')}${prohibited.length>5?'…':''}`);
  const module=object(root.module)?root.module:null;if(!module){add('MODULE_REQUIRED','A module payload is required.');return blockers}
  if(module.status!=='draft')add('MODULE_NOT_DRAFT','The module must be draft.');
  const xp=object(module.xp)?module.xp:null;if(!xp||xp.intro!==50||xp.instructional_media!==100||xp.core_challenge!==350||xp.mastery!==125||xp.module_total!==625||xp.unlock_threshold!==438||xp.passing_score!==70)add('XP_CONTRACT_INVALID','The locked JPAC XP and passing-score contract must match exactly.');
  const lessons=array(module.lessons);if(lessons.length!==3||lessons.some(item=>!object(item)||item.status!=='draft'||!text(item.title).trim()||!text(item.learning_objective).trim()||!Array.isArray(item.content_blocks)||!Array.isArray(item.technique_cues)||!Array.isArray(item.common_mistakes)||Boolean(text(item.resource_url))))add('LESSONS_INVALID','Exactly three complete, inactive draft lessons are required.');
  const activities=object(module.activities)?module.activities:null;const practice=activities?array(activities.practice):[],core=activities?array(activities.core_challenge):[],other=activities?array(activities.other):[];
  if(!activities||practice.length>1||core.length!==1||other.length)add('ACTIVITY_SHAPE_INVALID','Allow zero or one Practice, exactly one Core Challenge, and no other activities.');
  if(practice.some(item=>!object(item)||item.status!=='draft'||item.role!=='practice'||item.activity_type!=='practice'||item.required!==false||item.xp_reward!==0||item.xp_type!=='bonus'||item.passing_score!==70||item.allows_resubmission!==true||item.portfolio_candidate!==false))add('PRACTICE_INVALID','Practice must be optional, draft, zero-XP bonus, non-portfolio, and resubmittable.');
  const challenge=core[0];if(!object(challenge)||challenge.status!=='draft'||challenge.role!=='core_challenge'||challenge.activity_type!=='performance'||challenge.required!==true||challenge.xp_reward!==350||challenge.xp_type!=='core'||challenge.passing_score!==70||challenge.allows_resubmission!==true||challenge.portfolio_candidate!==false||!rubricValid(challenge.rubric))add('CORE_CHALLENGE_INVALID','The required draft Core Challenge and 100-point rubric must match the v1 contract.');
  const media=object(module.media)?module.media:null;if(!media||media.review_status!=='NEEDS_REVIEW'||array(media.versions).length||!object(media.legacy_projection)||Boolean(text((media.legacy_projection as Row).url)))add('MEDIA_ACTIVE_OR_INVALID','Media must be inactive, empty, and marked NEEDS_REVIEW.');
  const tool=object(module.tool)?module.tool:null;if(!tool||tool.review_status!=='NEEDS_CATALOG_REVIEW'||tool.catalog_reference!==null)add('TOOL_ACTIVE_OR_INVALID','Tools must be unbound and marked NEEDS_CATALOG_REVIEW.');
  const career=object(module.career_path_attachments)?module.career_path_attachments:null;if(!career||career.status!=='NOT_CONFIGURED'||array(career.items).length)add('CAREER_PATH_ACTIVE_OR_INVALID','Career Path items must remain unconfigured.');
  const mission=object(module.mission)?module.mission:null;if(!mission||mission.portfolio_moment!==false)add('PORTFOLIO_ACTIVATION_BLOCKED','Portfolio activation is not supported.');
  const warnings=extractSourceWarningCodes(source);if(warnings.malformed)add('WARNINGS_MALFORMED','Every source warning must have a non-empty code.');return blockers}

export function evaluateSaveDraftEligibility(source:string,preview:CurriculumImportPreview|null,context:SaveDraftContext):SaveDraftEligibility{const blockers:Array<{code:string;message:string}>=[];const add=(code:string,message:string)=>blockers.push({code,message});if(!preview){add('PREVIEW_REQUIRED','Parse and preview valid JSON first.');return{eligible:false,blockers}}const decisions=summarizeImportPreviewDecisions(preview);if(preview.scope.type!=='module')add('MODULE_SCOPE_REQUIRED','Level and course imports remain preview-only.');if(!context.selected_course_id||!context.selected_course_slug)add('SELECTED_COURSE_REQUIRED','Select a course before saving.');if(preview.scope.course_slug!==context.selected_course_slug)add('COURSE_MISMATCH','Imported and selected course slugs must match.');if(preview.counts.modules!==1)add('ONE_MODULE_REQUIRED','Exactly one module is required.');if(!decisions.complete||decisions.would_create!==1||decisions.would_reuse||decisions.possible_conflicts||decisions.course_mismatch||decisions.not_checked)add('DECISION_NOT_ELIGIBLE','The local decision must be exactly one WOULD_CREATE and zero other statuses.');if(preview.findings.some(item=>item.severity==='ERROR'||['SUMMARY_MISMATCH','DUPLICATE_MODULE_IDENTITY','DECISION_SUMMARY_INCOMPLETE'].includes(item.code)))add('PREVIEW_FINDINGS_BLOCK_SAVE','Resolve parser, summary, or identity findings first.');blockers.push(...sourceStructureBlockers(source));if(!context.can_save_draft)add('ADMIN_REQUIRED','Save as Draft requires an administrator or developer account.');const warnings=extractSourceWarningCodes(source);if(!warnings.malformed&&warnings.codes.some(code=>!context.acknowledged_warning_codes.includes(code)))add('WARNINGS_UNACKNOWLEDGED','Review and acknowledge every source warning.');if(!context.confirmed)add('CONFIRMATION_REQUIRED','Confirm the one-module draft-only operation.');if(context.pending)add('REQUEST_PENDING','A Save as Draft request is already pending.');return{eligible:blockers.length===0,blockers}}

const lessonPayload=(item:Row)=>({sort_order:item.sort_order,title:text(item.title),description:text(item.description),status:'draft',duration_minutes:item.duration_minutes??null,short_summary:text(item.short_summary),learning_objective:text(item.learning_objective),content_blocks:array(item.content_blocks),technique_cues:array(item.technique_cues).filter(x=>typeof x==='string'),common_mistakes:array(item.common_mistakes).filter(x=>typeof x==='string'),self_check:text(item.self_check),resource_url:null});
const activityPayload=(item:Row)=>({role:text(item.role),title:text(item.title),description:text(item.description),instructions:text(item.instructions),activity_type:text(item.activity_type),submission_type:text(item.submission_type),status:'draft',required:item.required,xp_reward:item.xp_reward,xp_type:text(item.xp_type),passing_score:item.passing_score,allows_resubmission:item.allows_resubmission,portfolio_candidate:false,rubric:object(item.rubric)&&Array.isArray(item.rubric.criteria)&&item.rubric.criteria.length?normalizeRubric(item.rubric):{}});
export function buildSaveDraftRpcPayload(source:string,preview:CurriculumImportPreview,context:SaveDraftContext):Row{const eligibility=evaluateSaveDraftEligibility(source,preview,context);if(!eligibility.eligible)throw new Error(eligibility.blockers[0]?.message||'Save as Draft is blocked.');const root=parsed(source)!;const scope=root.export_scope as Row,course=root.course as Row,level=root.level as Row,module=root.module as Row,mission=module.mission as Row,media=module.media as Row,legacy=media.legacy_projection as Row,tool=module.tool as Row,activities=module.activities as Row;const warnings=(root.warnings as Row[]).map(item=>({course_slug:text(item.course_slug)||text(scope.course_slug),level_number:item.level_number??scope.level_number,module_number:item.module_number??scope.module_number,code:text(item.code).trim(),message:text(item.message)}));return{target_course_id:context.selected_course_id,contract:'jpac-curriculum-export',contract_version:'1.2.0',export_scope:{type:'module',course_slug:context.selected_course_slug,level_number:scope.level_number,module_number:scope.module_number},options:{include_database_ids:false},warnings,acknowledged_warning_codes:[...context.acknowledged_warning_codes].sort(),course:{course_slug:context.selected_course_slug,title:text(course.title),description:text(course.description),status:text(course.status)},level:{level_number:level.level_number,title:text(level.title),status:text(level.status)},module:{module_number:module.module_number,sort_order:module.sort_order,title:text(module.title),description:text(module.description),status:'draft',mission:{short_intro:text(mission.short_intro),career_connection:text(mission.career_connection),real_world_activity:object(mission.real_world_activity)?mission.real_world_activity:{},aria_coaching_targets:object(mission.aria_coaching_targets)?mission.aria_coaching_targets:{},career_mission_ideas:array(mission.career_mission_ideas),portfolio_moment:false,portfolio_ready_threshold:mission.portfolio_ready_threshold??null,review_notes:text(mission.review_notes)},xp:{intro:50,instructional_media:100,core_challenge:350,mastery:125,module_total:625,unlock_threshold:438,passing_score:70},lessons:(module.lessons as Row[]).map(lessonPayload),activities:{practice:(activities.practice as Row[]).map(activityPayload),core_challenge:(activities.core_challenge as Row[]).map(activityPayload),other:[]},media:{review_status:'NEEDS_REVIEW',legacy_projection:{url:null,provider:null,title:null,duration_seconds:null,brief:text(legacy.brief)},versions:[]},tool:{review_status:'NEEDS_CATALOG_REVIEW',activity_configuration:object(tool.activity_configuration)?tool.activity_configuration:{},catalog_reference:null},career_path_attachments:{status:'NOT_CONFIGURED',items:[]}}}}
export function sanitizeSaveDraftError(error:unknown){const message=error&&typeof error==='object'&&'message'in error?String((error as{message:unknown}).message):'';if(/fetch|network|timeout|connection/i.test(message))return'The request result is uncertain because the connection was interrupted. Refresh Curriculum Studio before trying again.';if(/already exists|overwrite|identity|sort order/i.test(message))return'A module now occupies this identity or sort order. Refresh Curriculum Studio and review the comparison.';if(/administrator|developer|access|permission|authorized/i.test(message))return'Administrator or developer authorization is required.';return'The draft module was not created. Review the import and refresh Curriculum Studio before trying again.'}
export function validateSaveDraftRpcResponse(value:unknown):SaveDraftRpcResponse|null{if(!object(value)||!uuid(value.operation_id)||!uuid(value.module_id)||value.status!=='draft'||!Array.isArray(value.lesson_ids)||!value.lesson_ids.every(uuid)||!Array.isArray(value.activity_ids)||!value.activity_ids.every(uuid)||!object(value.created_counts)||value.created_counts.modules!==1||value.created_counts.lessons!==value.lesson_ids.length||value.created_counts.activities!==value.activity_ids.length||!Array.isArray(value.unresolved_review_statuses)||!value.unresolved_review_statuses.every(item=>typeof item==='string'))return null;return value as unknown as SaveDraftRpcResponse}
