import{createServerSupabase}from'./integration.js';

export async function requireCurriculumAdmin(req){
  const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)throw Object.assign(new Error('Authentication required'),{status:401});
  const supabase=createServerSupabase();const{data,error}=await supabase.auth.getUser(token);if(error||!data.user)throw Object.assign(new Error('Invalid session'),{status:401});
  const profile=await supabase.from('profiles').select('id,role').eq('id',data.user.id).single();if(profile.error||!['admin','developer'].includes(profile.data?.role))throw Object.assign(new Error('Administrator access required'),{status:403});
  return{supabase,user:data.user,profile:profile.data};
}

const stopWords=new Set(['about','after','again','against','approved','aria','beginner','course','curriculum','from','into','jpac','lesson','module','preserve','source','student','that','their','this','using','while','with']);
const tokens=value=>String(value||'').toLowerCase().match(/[a-z0-9]{4,}/g)||[];
const uniqueTerms=value=>[...new Set(tokens(value).filter(token=>!stopWords.has(token)))].slice(0,18);
const one=value=>Array.isArray(value)?value[0]:value;
const termHits=(value,terms)=>{const normalized=String(value||'').toLowerCase();return terms.filter(term=>normalized.includes(term))};
const sourceSelect='id,source_id,course_id,level_number,topic,section_key,heading,content,content_hash,classification,keywords,sort_order,metadata,source:curriculum_sources!inner(id,title,source_type,version,approval_status,processing_status,discipline)';

async function retrieveSourceSections(supabase,{courseId,activeLevel,terms,focusText}){
  const query=()=>{let request=supabase.from('curriculum_source_sections').select(sourceSelect).eq('source.approval_status','approved').eq('source.processing_status','ready').or(`course_id.eq.${courseId},course_id.is.null`);if(activeLevel)request=request.or(`level_number.eq.${activeLevel},level_number.is.null`);return request};
  const scopedPromise=query().order('sort_order',{ascending:true}).limit(60);
  const searchExpression=terms.slice(0,12).join(' OR ');const searchedPromise=searchExpression?query().textSearch('search_vector',searchExpression,{type:'websearch',config:'english'}).limit(30):Promise.resolve({data:[],error:null});
  const[scoped,searched]=await Promise.all([scopedPromise,searchedPromise]);if(scoped.error)throw scoped.error;if(searched.error)throw searched.error;
  const candidates=new Map();for(const section of[...(searched.data||[]),...(scoped.data||[])])candidates.set(section.id,section);
  const focus=String(focusText||'').toLowerCase().trim();return[...candidates.values()].map(section=>{
    const source=one(section.source);const headingHits=termHits(section.heading,terms),topicHits=termHits(section.topic,terms),keywordHits=termHits((section.keywords||[]).join(' '),terms),contentHits=termHits(section.content,terms);
    const courseScope=section.course_id===courseId?'course-specific':section.course_id===null?'academy-wide':'other-course';const levelScope=activeLevel&&section.level_number===activeLevel?'level-specific':section.level_number===null?'all-levels':'other-level';
    const exactFocus=focus.length>=12&&String(section.content||'').toLowerCase().includes(focus);const score=headingHits.length*7+topicHits.length*6+keywordHits.length*5+contentHits.length*2+(courseScope==='course-specific'?5:1)+(levelScope==='level-specific'?4:1)+(exactFocus?8:0);
    const matchedTerms=[...new Set([...headingHits,...topicHits,...keywordHits,...contentHits])].slice(0,12);const reasons=[];if(headingHits.length)reasons.push(`heading matches ${headingHits.join(', ')}`);if(topicHits.length||keywordHits.length)reasons.push(`topic metadata matches ${[...topicHits,...keywordHits].join(', ')}`);if(contentHits.length)reasons.push(`${contentHits.length} relevant curriculum term${contentHits.length===1?'':'s'} in the excerpt`);reasons.push(`${courseScope}, ${levelScope}`);
    return{id:section.id,sourceSectionId:section.id,sourceId:section.source_id,sourceTitle:source?.title,sourceType:source?.source_type,version:source?.version,sectionKey:section.section_key,heading:section.heading,topic:section.topic,classification:section.classification||source?.source_type,keywords:section.keywords||[],excerpt:String(section.content||'').slice(0,1800),contentHash:section.content_hash,relevance:{score,matchedTerms,courseScope,levelScope,method:searchExpression?'PostgreSQL full-text prefilter plus bounded metadata/content ranking':'bounded metadata/content ranking'},reasonUsed:reasons.join('; '),sortOrder:section.sort_order};
  }).filter(section=>section.relevance.score>2).sort((a,b)=>b.relevance.score-a.relevance.score||a.sortOrder-b.sortOrder).slice(0,8);
}

export async function assembleCurriculumContext(supabase,{courseId,moduleId,lessonId,activityId,administratorInstruction='',levelNumbers=[]}){
  const courseResult=await supabase.from('courses').select('id,title,slug,description,status').eq('id',courseId).single();if(courseResult.error)throw courseResult.error;
  const modulesResult=await supabase.from('course_modules').select('id,course_id,course_level_id,level_module_number,title,description,status,short_intro,career_connection,primary_video_url,video_brief,core_xp,core_unlock_threshold,lab_tool_id,aria_coaching_targets,portfolio_moment,portfolio_ready_threshold,course_level:course_levels(level_number,title)').eq('course_id',courseId).order('sort_order').limit(80);if(modulesResult.error)throw modulesResult.error;
  const modules=modulesResult.data||[];const selectedModule=modules.find(item=>item.id===moduleId)||null;const activeLevel=one(selectedModule?.course_level)?.level_number||null;
  const moduleIds=(moduleId?[moduleId]:modules.filter(item=>!levelNumbers.length||levelNumbers.includes(one(item.course_level)?.level_number)).map(item=>item.id)).slice(0,40);
  const[lessonsResult,activitiesResult,toolsResult]=await Promise.all([
    moduleIds.length?supabase.from('lessons').select('id,module_id,title,status,sort_order,short_summary,learning_objective,content_blocks,technique_cues,common_mistakes,self_check').in('module_id',moduleIds).order('sort_order').limit(160):Promise.resolve({data:[],error:null}),
    moduleIds.length?supabase.from('activities').select('id,module_id,title,description,instructions,activity_type,submission_type,xp_reward,xp_type,required,status,passing_score,rubric,portfolio_candidate').in('module_id',moduleIds).limit(160):Promise.resolve({data:[],error:null}),
    supabase.from('lab_tools').select('id,name,description,status,launch_url,tool_type').eq('status','ready').limit(30)
  ]);const error=lessonsResult.error||activitiesResult.error||toolsResult.error;if(error)throw error;
  const lessons=lessonsResult.data||[];const activities=activitiesResult.data||[];const lesson=lessons.find(item=>item.id===lessonId)||null;const activity=activities.find(item=>item.id===activityId)||null;
  if(moduleId&&!selectedModule)throw new Error('Module is outside selected course');if(lessonId&&!lesson)throw new Error('Lesson is outside selected module');if(activityId&&!activity)throw new Error('Activity is outside selected module');
  const administratorGoal=String(administratorInstruction||'').slice(0,2000);const focusText=[administratorGoal,courseResult.data.title,selectedModule?.title,selectedModule?.description,lesson?.title,lesson?.learning_objective,lesson?.short_summary,JSON.stringify(lesson?.technique_cues||[]),activity?.title,activity?.description].join(' ');const terms=uniqueTerms(focusText);
  const sourceSections=await retrieveSourceSections(supabase,{courseId,activeLevel,terms,focusText:lesson?.title||activity?.title||selectedModule?.title});
  const publishedLessons=lessons.filter(item=>item.status==='published'),publishedActivities=activities.filter(item=>item.status==='published');const stagedLessons=lessons.filter(item=>item.status!=='published'),stagedActivities=activities.filter(item=>item.status!=='published');
  const sourceConflicts=[];for(let index=0;index<sourceSections.length;index++)for(let other=index+1;other<sourceSections.length;other++){const a=sourceSections[index],b=sourceSections[other];if(a.sourceId!==b.sourceId&&String(a.heading).toLowerCase()===String(b.heading).toLowerCase()&&a.excerpt!==b.excerpt)sourceConflicts.push({conflictType:'TRUSTED_SOURCE_CONFLICT',sourceA:`${a.sourceTitle} v${a.version}: ${a.heading}`,sourceB:`${b.sourceTitle} v${b.version}: ${b.heading}`,recommendedInterpretation:'Compare source authority and version before accepting the recommendation. Canonical curriculum remains unchanged.'})}
  const canonicalSnapshot={course:courseResult.data,module:selectedModule,lesson,activity,publishedModules:modules.filter(item=>item.status==='published').slice(0,40),publishedLessons:publishedLessons.slice(0,40),publishedActivities:publishedActivities.slice(0,40)};const stagedCurriculum={modules:modules.filter(item=>item.status!=='published').slice(0,40),lessons:stagedLessons.slice(0,40),activities:stagedActivities.slice(0,40)};
  return{course:courseResult.data,modules:moduleId?[selectedModule]:modules.filter(Boolean).slice(0,40),module:selectedModule,lesson,activity,lessons:lessons.slice(0,120),activities:activities.slice(0,120),tools:toolsResult.data||[],canonicalSnapshot,stagedCurriculum,sourceSections,sourceConflicts:sourceConflicts.slice(0,5),administratorInstruction:administratorGoal,retrieval:{activeCourseId:courseId,activeLevel,moduleId:moduleId||null,lessonId:lessonId||null,activityId:activityId||null,queryTerms:terms,maxSections:8,maxExcerptCharacters:1800},authorityLayers:['CANONICAL_CURRICULUM','TRUSTED_SOURCE','STAGED_CURRICULUM','ADMINISTRATOR_INSTRUCTION','AI_PROPOSAL'],constraints:{proposalOnly:true,publishedMutationForbidden:true,automaticPublicationForbidden:true,studentEvidenceProtected:true,coreActivityXp:350,unlockThreshold:438,allowedDecisions:['KEEP','IMPROVE','ADD','REPLACE_IN_FUTURE_VERSION'],knownIssues:['Singing Beginner Module 1 reviewed E3 Core Challenge is missing; preserve the published legacy challenge and do not manufacture a canonical record.']}};
}
