import{createClient}from'@supabase/supabase-js';

export function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
export const text=value=>typeof value==='string'?value.trim():'';
export function dateOrNull(value){if(!value)return null;const date=new Date(value);return Number.isNaN(date.getTime())?null:date.toISOString()}
export function parseBody(req){if(!req.body)return{};if(typeof req.body==='object')return req.body;try{return JSON.parse(req.body)}catch{return{}}}
export function getSharedSecret(req){return req.headers['x-jpac-wix-secret']||req.headers.authorization?.replace(/^Bearer\s+/i,'')||''}
export function requireIntegrationSecret(req){const configured=process.env.JPAC_WIX_SYNC_SECRET;return Boolean(configured&&getSharedSecret(req)===configured)}
export function configuration(){return{SUPABASE_URL:Boolean(process.env.SUPABASE_URL),SUPABASE_SERVICE_ROLE_KEY:Boolean(process.env.SUPABASE_SERVICE_ROLE_KEY),JPAC_WIX_SYNC_SECRET:Boolean(process.env.JPAC_WIX_SYNC_SECRET),WIX_PROGRESS_WEBHOOK_URL:Boolean(process.env.WIX_PROGRESS_WEBHOOK_URL),JPAC_NOTIFICATION_WEBHOOK_URL:Boolean(process.env.JPAC_NOTIFICATION_WEBHOOK_URL),JPAC_NOTIFICATION_WEBHOOK_SECRET:Boolean(process.env.JPAC_NOTIFICATION_WEBHOOK_SECRET)}}
export function createServerSupabase(){if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)throw new Error('Supabase server configuration is incomplete');return createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})}
export async function recordIntegrationEvent(supabase,{provider='wix',eventId,eventType,payload,status='received',profileId=null,errorMessage=null}){const row={provider,external_event_id:eventId,event_type:eventType,processing_status:status,payload,error_message:errorMessage,profile_id:profileId,processed_at:['processed','ignored','error'].includes(status)?new Date().toISOString():null};const{error}=await supabase.from('integration_events').upsert(row,{onConflict:'provider,external_event_id'});if(error)throw error}
export async function markIntegrationEvent(supabase,{provider='wix',eventId,status,profileId=null,errorMessage=null}){const patch={processing_status:status,error_message:errorMessage,processed_at:new Date().toISOString()};if(profileId)patch.profile_id=profileId;const{error}=await supabase.from('integration_events').update(patch).eq('provider',provider).eq('external_event_id',eventId);if(error)throw error}
export async function findJpacProfile(supabase,{email,wixMemberId}){if(email){const result=await supabase.from('profiles').select('id,display_name,email,role').ilike('email',email).maybeSingle();if(result.error)throw result.error;if(result.data)return result.data}if(wixMemberId){const result=await supabase.from('wix_member_links').select('profile:profiles(id,display_name,email,role)').eq('wix_member_id',wixMemberId).maybeSingle();if(result.error)throw result.error;return Array.isArray(result.data?.profile)?result.data.profile[0]:result.data?.profile||null}return null}
export async function postToWix(payload){if(!process.env.WIX_PROGRESS_WEBHOOK_URL)return{configured:false,delivered:false,status:null,responseText:'',errorText:'WIX_PROGRESS_WEBHOOK_URL is not configured'};try{const response=await fetch(process.env.WIX_PROGRESS_WEBHOOK_URL,{method:'POST',headers:{'Content-Type':'application/json','x-jpac-wix-secret':process.env.JPAC_WIX_SYNC_SECRET||''},body:JSON.stringify(payload)});const responseText=await response.text();return{configured:true,delivered:response.ok,status:response.status,responseText,errorText:response.ok?'':`Wix endpoint returned ${response.status}`}}catch(error){return{configured:true,delivered:false,status:null,responseText:'',errorText:error instanceof Error?error.message:'Unknown Wix delivery error'}}}
