-- REVIEW SEED ONLY. Do not run through automatic migration deployment.
-- Apply only after leadership approval and after migration 202608090003.
begin;

do $$ begin
  if (select count(*) from public.course_levels cl join public.courses c on c.id=cl.course_id where c.slug='singing')<>4 then raise exception 'Canonical Singing levels are not ready'; end if;
  if (select count(*) from public.course_modules m join public.courses c on c.id=m.course_id where c.slug='singing')<>40 then raise exception 'Canonical Singing modules are not ready'; end if;
end $$;

-- Transaction-local preservation baseline. The final assertion proves that this
-- authoring seed did not alter student evidence, XP, or enrollment.
create temporary table phase_e3_preservation_baseline on commit drop as
select
  m.id as original_module_2_id,
  (select count(*) from public.lesson_progress) as progress_rows,
  (select count(*) from public.submissions) as submission_rows,
  (select count(*) from public.xp_ledger) as xp_rows,
  (select count(*) from public.enrollments) as enrollment_rows,
  (select md5(coalesce(string_agg(to_jsonb(p)::text,'|' order by p.id::text),'')) from public.lesson_progress p) as progress_hash,
  (select md5(coalesce(string_agg(to_jsonb(s)::text,'|' order by s.id::text),'')) from public.submissions s) as submission_hash,
  (select md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id::text),'')) from public.xp_ledger x) as xp_hash,
  (select md5(coalesce(string_agg(to_jsonb(e)::text,'|' order by e.id::text),'')) from public.enrollments e) as enrollment_hash
from public.course_modules m
join public.course_levels cl on cl.id=m.course_level_id
join public.courses c on c.id=m.course_id
where c.slug='singing' and cl.level_number=1 and m.level_module_number=2
  and m.title in ('Pitch, Tone & First Performance','Find Your Natural Voice');

do $$ begin
  if (select count(*) from phase_e3_preservation_baseline)<>1 then
    raise exception 'Expected exactly one canonical Beginner Module 2';
  end if;
end $$;

-- New structured authoring metadata is safe on every canonical module. Rendered
-- student-facing module fields remain unchanged on every published module.
with authored(n,title,mission,brief,career,video,aria,career_ideas,portfolio_threshold) as(values
(1,'Breath, Alignment & Vocal Health','Build a healthy physical foundation for singing.','Coordinate balanced alignment, low-release breathing, controlled exhale, and sustainable vocal-health habits. Create a short performance that demonstrates supported phrases and healthy tone.','Alignment, breath coordination, and healthy vocal production support reliable work for live performers, recording artists, voice actors, and other vocal creators.','5–8 minute instructor demonstration of balanced singer alignment, quiet low-release inhalation, controlled exhalation, a gentle warm-up, and visible examples of common jaw, shoulder, and neck tension.',jsonb_build_object('strength_signals',array['balanced alignment','quiet coordinated inhalation','controlled phrase support','healthy tone'],'risk_signals',array['raised shoulders','collapsed posture','audible gasping','pressed tone'],'rules',array['If breath coordination is weakest, recommend short inhale/exhale cycles before another take.','Prioritize no more than three evidence-based corrections.']),jsonb_build_array(jsonb_build_object('title','Before-and-after breath comparison','bonus_xp',50,'idea','Record the same chorus before and after three focused breath cycles and compare phrase ease.')),null),
(2,'Find Your Natural Voice','Discover a comfortable, authentic vocal sound without forcing or imitation.','Connect speaking and singing, notice tension, explore healthy onset and resonance, then compare three versions of one song section to choose the healthiest authentic sound.','A sustainable natural sound helps creators deliver repeatable performances without copying another artist or forcing a style that does not fit.','6–8 minute demonstration moving from speech to sung tone, exploring lighter and stronger choices without force, identifying tension, and comparing healthy versus pressed onset.',jsonb_build_object('strength_signals',array['comfortable range','authentic tone','easy onset','low visible tension'],'risk_signals',array['imitation','throat pressure','breathy collapse','range forcing'],'rules',array['Recommend speech-to-song practice when onset or authenticity is weakest.','Do not treat personal tone preference as a technical defect.']),jsonb_build_array(jsonb_build_object('title','Authentic sound reel','bonus_xp',50,'idea','Share three tone choices with a trusted listener and document which sounds most natural.')),null),
(3,'Pitch Control','Strengthen the ability to hear and reproduce notes accurately.','Train focused listening, pitch matching, sustained notes, simple intervals, and self-correction. Create a before-and-after melody recording that demonstrates measurable improvement.','Pitch accuracy matters in auditions, ensembles, studio sessions, songwriting demos, background vocals, and live performance.','6–9 minute instructor demonstration of listening before singing, matching a reference note, sustaining pitch, correcting sharp/flat tendencies, and comparing a first and final melody take.',jsonb_build_object('strength_signals',array['accurate note starts','stable sustained pitch','melodic accuracy','effective self-correction'],'risk_signals',array['guessing before listening','consistent sharpness','consistent flatness','unstable sustain'],'rules',array['Recommend isolated pitch matching when note starts are weakest.','Recommend slow phrase loops when accuracy drops across a melody.']),jsonb_build_array(jsonb_build_object('title','Pitch progress comparison','bonus_xp',50,'idea','Create a short first-take/final-take comparison clip.')),null),
(4,'Rhythm, Timing & Groove','Sing confidently in time with music.','Develop steady pulse, accurate entrances, note duration, rhythmic phrasing, and introductory groove awareness. Create a performance with clear timing and confident entrances.','Reliable timing helps singers work with bands, producers, dancers, click tracks, backing tracks, and other collaborators.','6–8 minute instructor demonstration of finding pulse, counting an entrance, sustaining correct duration, clapping a phrase, and singing simple straight and syncopated examples.',jsonb_build_object('strength_signals',array['steady pulse','clean entrances','accurate releases','rhythmic phrasing'],'risk_signals',array['rushing','dragging','late entrances','inconsistent note length'],'rules',array['Recommend clap-and-count practice when entrances are weakest.','Recommend reduced-tempo loops when rushing or dragging is observed.']),jsonb_build_array(jsonb_build_object('title','One-take groove clip','bonus_xp',50,'idea','Record a clean one-take chorus with a backing track or metronome.')),null),
(5,'Tone & Resonance','Explore how placement and resonance influence vocal tone.','Notice chest and head sensations, experiment with forward resonance and bright/dark color, reduce unnecessary tension, and choose a tone that serves the lyric.','Tone flexibility helps vocalists adapt to songs, characters, sessions, live rooms, and creative direction while protecting a recognizable voice.','6–9 minute demonstration of safe humming-to-vowel resonance, chest/head sensation, bright/dark experiments, consistent tone, and tension warnings.',jsonb_build_object('strength_signals',array['consistent tone','intentional color','balanced resonance','low tension'],'risk_signals',array['nasal forcing','pressed volume','swallowed tone','jaw tension'],'rules',array['Recommend hum-to-vowel transitions when resonance is inconsistent.','Coach artistic fit without declaring one tone color universally correct.']),jsonb_build_array(jsonb_build_object('title','Three-tone comparison','bonus_xp',50,'idea','Create a labeled comparison of three tone colors.')),null),
(6,'Diction & Storytelling','Make lyrics clear and meaningful.','Coordinate consonants, vowels, phrasing, lyric intention, and emotional communication. Create a verse or chorus that makes the listener understand both the words and the story.','Clear storytelling supports recording artists, musical theatre performers, worship singers, voice actors, content creators, and live vocalists.','6–8 minute demonstration of clear consonants without overworking, sustained vowels, phrase intention, text emphasis, and one lyric performed with contrasting meanings.',jsonb_build_object('strength_signals',array['clear words','consistent vowels','intentional phrasing','believable story'],'risk_signals',array['swallowed consonants','over-articulation','unclear vowels','emotion disconnected from lyric'],'rules',array['Recommend spoken-text rehearsal when clarity is weakest.','Use the student’s stated listener intention when evaluating storytelling.']),jsonb_build_array(jsonb_build_object('title','Story performance reel','bonus_xp',50,'idea','Record a 15-second lyric moment designed to communicate one clear feeling.')),85),
(7,'Dynamics & Expression','Shape emotion through intentional vocal contrast.','Use soft/loud control, introductory crescendo and decrescendo, emphasis, breath planning, and contrasting interpretations. Create three versions and choose the strongest artistic reading.','Dynamic control helps performers hold audience attention, respond to creative direction, and shape recordings beyond correct notes.','6–9 minute demonstration of healthy soft and strong singing, gradual dynamic changes, phrase emphasis, breath planning, and three interpretations of one chorus.',jsonb_build_object('strength_signals',array['controlled contrast','intentional emphasis','supported soft singing','expressive phrasing'],'risk_signals',array['volume without support','breathy soft tone','single dynamic level','random emphasis'],'rules',array['Recommend marked lyric dynamics when contrast is missing.','Separate emotional taste from measurable control.']),jsonb_build_array(jsonb_build_object('title','Three-way interpretation poll','bonus_xp',50,'idea','Share three interpretations with a trusted listener and compare the response.')),null),
(8,'Microphone & Recording Basics','Learn how singers work with microphones and simple recording spaces.','Practice mic distance, plosive control, steady positioning, basic headphone awareness, room noise checks, multiple takes, and constructive playback review using available equipment.','Microphone awareness supports demos, content creation, auditions, live sound, home recording, and professional studio preparation.','7–10 minute demonstration using a phone and microphone, showing distance changes, plosives, angle, level consistency, room-noise checks, headphones, and take review.',jsonb_build_object('strength_signals',array['consistent distance','controlled plosives','clean level','prepared recording space'],'risk_signals',array['distance drift','clipping','excess room noise','poor playback review'],'rules',array['Recommend a placement test when level consistency is weakest.','Never penalize a student for using a phone instead of paid equipment.']),jsonb_build_array(jsonb_build_object('title','Clean studio-style reel','bonus_xp',50,'idea','Create a clean 15-second audition or performance clip using available equipment.')),85),
(9,'Performance Confidence','Develop presence and recovery while performing.','Prepare physically and mentally, use purposeful focus and body language, continue through small mistakes, and connect with an audience or camera in one continuous take.','Presence, recovery, and connection matter in auditions, performances, livestreams, rehearsals, studio video, and creator content.','6–8 minute demonstration of a short pre-performance routine, grounded stance, eye focus, expressive face, purposeful movement, mistake recovery, and a continuous take.',jsonb_build_object('strength_signals',array['committed presence','continued performance','clear focus','audience connection'],'risk_signals',array['stopping after mistakes','closed body language','wandering focus','unprepared start'],'rules',array['Recommend low-stakes one-take practice when recovery is weakest.','Distinguish quiet confidence from lack of engagement.']),jsonb_build_array(jsonb_build_object('title','Perform for one person','bonus_xp',50,'idea','Give one live or recorded performance and collect one specific response.')),null),
(10,'Beginner Showcase','Combine Beginner-level skills into one complete performance.','Prepare, warm up, record, review, and refine a polished 60–120 second performance demonstrating healthy technique, musicianship, expression, recording awareness, and presence.','A polished showcase gives creators evidence for auditions, portfolios, collaborators, applications, and the next stage of artistic development.','8–12 minute instructor walkthrough of song selection, preparation plan, warm-up, recording setup, full-take performance, self-review, revision priorities, and portfolio-quality checks.',jsonb_build_object('strength_signals',array['integrated technique','complete preparation','artistic intention','clean capture','constructive self-review'],'risk_signals',array['unsafe strain','incomplete performance','unprepared recording','no evidence of review'],'rules',array['Prioritize one to three improvements with the greatest performance impact.','Portfolio readiness requires evidence at or above 85 and is separate from the 70 passing score.']),jsonb_build_array(jsonb_build_object('title','Beginner showcase premiere','bonus_xp',50,'idea','Present the approved showcase to a trusted audience and collect specific feedback.')),85)
), targets as(select m.*,a.* from authored a join public.courses c on c.slug='singing' join public.course_levels cl on cl.course_id=c.id and cl.level_number=1 join public.course_modules m on m.course_level_id=cl.id and m.level_module_number=a.n)
update public.course_modules m set video_brief=t.video,aria_coaching_targets=t.aria,career_mission_ideas=t.career_ideas,portfolio_ready_threshold=t.portfolio_threshold,portfolio_moment=(t.n=10),updated_at=now() from targets t where m.id=t.id;

-- Evidence definitions are future coaching inputs, not claims that automated
-- audio/video analysis already exists or authority to mutate academic records.
with aria_evidence(n,evidence,priority_rule) as(values
(1,jsonb_build_array('front/side alignment observation','shoulder movement during inhalation','four-count exhale consistency','student-reported pain or strain'),'Address any pain/strain signal first; otherwise prioritize the least consistent breath or alignment observation.'),
(2,jsonb_build_array('speech-to-song comparison','comfortable-range repetitions','visible jaw/neck/shoulder tension','student-selected authentic take and reason'),'Prioritize unhealthy effort before stylistic preference; recommend the easiest repeatable speech-to-song drill supported by the evidence.'),
(3,jsonb_build_array('reference note and response pairs','sustained-note stability','sharp/flat tendency noted by student or reviewer','first/final melodic pattern comparison'),'Identify the earliest recurring pitch error and recommend one small reference-response or interval loop.'),
(4,jsonb_build_array('eight-count pulse continuity','counted entrance timing','held-note duration and release','backing-track phrase continuity'),'Prioritize the first observable timing break: pulse, entrance, duration, or release, then recommend the matching clap/count drill.'),
(5,jsonb_build_array('hum-to-vowel comparison','three labeled tone-color takes','pitch/word stability across colors','student effort and lyric-fit reflection'),'Reject any choice linked to strain; otherwise coach the clearest repeatable color that supports the stated lyric intention.'),
(6,jsonb_build_array('spoken lyric clarity','sung consonant/vowel clarity','marked emphasis and breath plan','listener intention and recorded response'),'Prioritize lost words before expressive nuance, then recommend a spoken, vowel-only, or emphasis rehearsal based on the weakest evidence.'),
(7,jsonb_build_array('soft/strong coordination comparison','marked dynamic arc','timing stability during changes','three-interpretation artistic rationale'),'Prioritize loss of healthy coordination or timing before increasing contrast; recommend one repeatable dynamic shape.'),
(8,jsonb_build_array('distance/angle test takes','plosive and clipping observations','room-noise before/after sample','take-selection criteria'),'Prioritize unusable capture problems first, then recommend one equipment-neutral placement, room, or level adjustment.'),
(9,jsonb_build_array('pre-performance routine completion','opening eye focus and body language','continuous-take recovery moment','student reflection on nerves and connection'),'Prioritize the behavior that most disrupts continuity or connection and recommend one low-stakes rehearsal cue.'),
(10,jsonb_build_array('showcase plan','complete dress-rehearsal take','one-to-three documented corrections','final integrated performance and self-reflection'),'Use rubric evidence to identify the highest-impact Beginner competency; never infer portfolio approval or award completion automatically.')
), targets as(
  select m.id,a.evidence,a.priority_rule from aria_evidence a join public.courses c on c.slug='singing'
  join public.course_levels cl on cl.course_id=c.id and cl.level_number=1
  join public.course_modules m on m.course_level_id=cl.id and m.level_module_number=a.n
)
update public.course_modules m set aria_coaching_targets=m.aria_coaching_targets||jsonb_build_object('evidence_targets',t.evidence,'priority_rule',t.priority_rule),updated_at=now()
from targets t where m.id=t.id;

with authored(n,title,mission,brief,career) as(values
(1,'Breath, Alignment & Vocal Health','Build a healthy physical foundation for singing.','Coordinate alignment, breathing, controlled exhale, and healthy warm-up habits, then demonstrate them in a short performance.','Healthy coordination supports reliable live and recorded vocal work.'),(2,'Find Your Natural Voice','Discover a comfortable, authentic vocal sound without forcing or imitation.','Connect speaking and singing, explore healthy onset and tone, and select an authentic sound from three creative takes.','A sustainable natural sound helps creators deliver repeatable performances.'),(3,'Pitch Control','Strengthen the ability to hear and reproduce notes accurately.','Listen, match, sustain, correct, and improve a short melody from first take to final take.','Pitch accuracy matters in auditions, ensembles, sessions, and live performance.'),(4,'Rhythm, Timing & Groove','Sing confidently in time with music.','Build steady pulse, clean entrances, accurate duration, and rhythmic phrasing in a groove-focused performance.','Reliable timing supports work with musicians, producers, dancers, and tracks.'),(5,'Tone & Resonance','Explore how placement and resonance influence vocal tone.','Experiment with resonance and three intentional tone colors, then choose the color that best serves the lyric.','Tone flexibility helps vocalists respond to songs and creative direction.'),(6,'Diction & Storytelling','Make lyrics clear and meaningful.','Coordinate words, vowels, phrasing, and intention to make a listener understand the story.','Clear storytelling supports many live, recorded, stage, and voice careers.'),(7,'Dynamics & Expression','Shape emotion through intentional vocal contrast.','Use dynamics, emphasis, breath planning, and three interpretations to make an artistic choice.','Dynamic control helps performers shape recordings and audience attention.'),(8,'Microphone & Recording Basics','Work confidently with microphones, phones, and simple recording spaces.','Prepare a space, control distance and plosives, record multiple takes, and deliver a clean studio-ready take.','Recording awareness supports demos, auditions, content, and studio preparation.'),(9,'Performance Confidence','Develop presence and recovery while performing.','Prepare, connect, continue through small mistakes, and finish one committed continuous performance.','Presence and recovery matter in auditions, shows, video, and rehearsals.'),(10,'Beginner Showcase','Combine Beginner skills into one complete performance.','Prepare, record, review, and refine a polished capstone performance suitable for quality-based portfolio review.','A showcase provides evidence for auditions, portfolios, collaborators, and future study.')), targets as(select m.id,m.status,a.* from authored a join public.courses c on c.slug='singing' join public.course_levels cl on cl.course_id=c.id and cl.level_number=1 join public.course_modules m on m.course_level_id=cl.id and m.level_module_number=a.n)
update public.course_modules m set title=t.title,description=t.brief,short_intro=t.mission,career_connection=t.career,jpac_tool_activity=jsonb_build_object('title',case t.n when 1 then 'Breath Cycle Comparison' when 2 then 'Natural Tone Comparison' when 3 then 'Pitch Match Lab' when 4 then 'Rhythm Match Lab' when 5 then 'Tone Color Lab' when 6 then 'Lyric Clarity Lab' when 7 then 'Dynamics Comparison Lab' when 8 then 'Recording Setup Lab' when 9 then 'Performance Review Lab' else 'Showcase Review Lab' end,'instructions','Record or compare focused takes using the module skill. Identify one measurable difference and one next adjustment.','intended_capability',case when t.n=3 then 'pitch comparison' when t.n=4 then 'rhythm matching' else 'recording comparison' end),real_world_activity=jsonb_build_object('title',case t.n when 1 then 'Before-and-After Breath Challenge' when 2 then 'Three Versions, One Authentic Voice' when 3 then 'First Take / Final Take Melody' when 4 then 'Lock Into the Backing Track' when 5 then 'Three Colors of One Phrase' when 6 then 'Tell the Lyric Story' when 7 then 'Three Dynamic Interpretations' when 8 then 'Phone or Microphone Placement Test' when 9 then 'No-Stop Performance Run' else 'Showcase Dress Rehearsal' end,'instructions','Complete a specific before/after, comparison, or continuous-take practice and identify the improvement you can hear or see.'),updated_at=now() from targets t where m.id=t.id and t.status<>'published';

-- Thirty concise, structured lessons. Matching existing Module 1 titles keep
-- their UUID/status/description and receive additive E3 metadata only.
with lesson_data(module_n,lesson_n,title,summary,minutes,objective,blocks,cues,mistakes,self_check) as(values
(1,1,'Singer Alignment and Breath','Coordinate body alignment with an efficient singer breath.',20,'Demonstrate balanced alignment and a quiet low-release breath.',jsonb_build_array('Stack feet, knees, hips, ribs, shoulders, and head without stiffness.','Let the lower ribs and abdomen respond during a quiet inhalation.','Release air steadily instead of pushing at the start of a phrase.'),array['Flexible knees','Released shoulders','Quiet inhale','Steady exhale'],array['Locked knees','Raised shoulders','Noisy gasp','Forcing the abdomen inward'],'Can you inhale quietly and release an even stream without lifting your shoulders?'),
(1,2,'Healthy Warm-Up Routine','Prepare the voice gradually and recognize healthy effort.',15,'Complete a short safe warm-up in a comfortable range.',jsonb_build_array('Begin with gentle body and breath release.','Use lip trills, hums, or easy slides at moderate volume.','Move from simple sounds toward song material without chasing extreme notes.'),array['Easy volume','Comfortable range','Hydrate','Stop with pain'],array['Starting too loud','Skipping body release','Forcing high notes','Singing through pain'],'Does your voice feel easier after the warm-up rather than tired or scratchy?'),
(1,3,'Vocal Health for Real Creators','Make practical choices that support repeatable singing.',15,'Identify healthy practice, recovery, and warning signs.',jsonb_build_array('Plan shorter focused practice with breaks instead of one exhausting session.','Notice environmental factors including hydration, sleep, noise, and monitoring level.','Pain, sudden voice loss, or persistent hoarseness requires rest and qualified support.'),array['Warm up gradually','Use breaks','Monitor volume','Notice warning signs'],array['Whispering through fatigue','Competing with loud speakers','Ignoring pain','Treating internet advice as diagnosis'],'What one habit will you use before your next recording or rehearsal?'),
(2,1,'Speaking Into Song','Connect a natural speaking voice to a comfortable sung phrase.',15,'Move from spoken lyric to healthy sung onset.',jsonb_build_array('Speak the lyric with clear intention.','Repeat it on one easy pitch without changing your natural communication.','Expand into the melody while keeping the jaw, tongue, and neck responsive.'),array['Conversational intent','Easy first note','Responsive jaw'],array['Imitating another singer','Breathy collapse','Hard glottal attack'],'Does the sung phrase still sound and feel connected to how you naturally communicate?'),
(2,2,'Comfortable Range and Tension Awareness','Choose notes and keys that allow healthy coordination.',20,'Recognize comfortable range and visible or felt tension.',jsonb_build_array('Explore a small group of easy notes before extending range.','Scan the jaw, tongue, neck, shoulders, and breath for unnecessary work.','Transpose or choose different material when a song demands unhealthy forcing.'),array['Comfort before volume','Release the tongue','Adjust the key'],array['Chin lifting','Neck reaching','Forcing low or high notes'],'Which notes feel reliable enough to repeat three times with the same healthy tone?'),
(2,3,'Natural Tone and Healthy Onset','Compare tone choices without ranking personal style.',20,'Create lighter, stronger, and conversational versions with healthy onset.',jsonb_build_array('Begin each phrase with coordinated breath and tone.','Explore lighter and stronger energy without squeezing.','Choose the version that feels repeatable and communicates the lyric authentically.'),array['Coordinated onset','Repeatable effort','Authentic choice'],array['Breathy start','Pressed attack','Choosing only by loudness'],'Which version could you repeat tomorrow without strain, and why?'),
(3,1,'Listen Before You Sing','Build a repeatable pitch-matching process.',15,'Match a reference pitch after focused listening.',jsonb_build_array('Listen through the full reference note before responding.','Imagine the pitch internally, then sing it at an easy volume.','Compare, adjust once, and repeat without turning correction into punishment.'),array['Listen first','Hear internally','Adjust calmly'],array['Singing before listening','Sliding randomly','Increasing volume to find pitch'],'Can you match three comfortable reference notes without guessing?'),
(3,2,'Stable Notes and Simple Intervals','Hold pitch and move cleanly between nearby notes.',20,'Sustain a stable note and sing simple melodic movement.',jsonb_build_array('Sustain one note with steady breath and vowel.','Practice two-note patterns slowly before adding rhythm.','Keep the destination note in mind while moving between pitches.'),array['Steady vowel','Supported sustain','Clear destination'],array['Vowel changing','Pitch sagging','Rushing intervals'],'Which note or interval needs a slower repetition before recording?'),
(3,3,'Correct Your Own Melody','Use playback to improve melodic accuracy.',20,'Identify and correct one pitch pattern in a short melody.',jsonb_build_array('Record a first take without stopping.','Mark one or two inaccurate moments rather than judging the whole performance.','Loop the smallest phrase, then record a final take and compare.'),array['Specific listening','Small phrase loops','Compare evidence'],array['Repeating the whole song','Vague self-criticism','Editing instead of learning'],'What exact note or phrase improved between your first and final take?'),
(4,1,'Find the Pulse','Feel and maintain a steady musical beat.',15,'Keep a steady pulse while speaking and singing a phrase.',jsonb_build_array('Tap or move with the underlying pulse.','Speak the lyric in rhythm before singing it.','Continue the pulse during rests so the next entrance stays prepared.'),array['Physical pulse','Count rests','Relaxed movement'],array['Following every syllable','Stopping during rests','Speeding up'],'Can you keep the pulse for eight counts before and after the phrase?'),
(4,2,'Entrances, Durations and Releases','Start and end notes at intentional times.',20,'Coordinate clean entrances, note lengths, and releases.',jsonb_build_array('Count into the phrase before making sound.','Hold notes for their complete duration.','Plan consonants and releases so they do not arrive late.'),array['Prepared breath','Count-in','Intentional release'],array['Late breath','Cutting notes short','Unplanned final consonants'],'Are your first entrance and final release aligned with the track?'),
(4,3,'Build the Groove','Place vocal phrasing confidently against accompaniment.',20,'Perform a rhythmic section without rushing or dragging.',jsonb_build_array('Identify where the vocal sits directly on or around the beat.','Practice difficult rhythm with claps or neutral syllables.','Return to the lyric while preserving the rhythmic shape.'),array['Feel subdivision','Loop slowly','Keep lyric flow'],array['Rushing syncopation','Dragging long notes','Overcounting during performance'],'Where does the groove feel most secure, and where does it move?'),
(5,1,'Where Tone Resonates','Notice vibration and resonance without forcing placement.',15,'Explore easy chest and head sensations through gentle sounds.',jsonb_build_array('Use hums and comfortable vowels to notice vibration.','Allow sensation to change across pitch without pushing it into one location.','Treat resonance language as a useful sensation, not a rigid physical target.'),array['Gentle hum','Easy vowel','Curious listening'],array['Forcing vibration','Pinching the nose','Driving volume'],'Which sound feels clearest with the least unnecessary effort?'),
(5,2,'Bright, Dark and Balanced Color','Create intentional tone-color contrast.',20,'Perform one phrase with three safe tone colors.',jsonb_build_array('Change vowel shape, resonance balance, and energy subtly.','Keep breath and pitch stable while color changes.','Avoid turning bright into nasal force or dark into swallowed tone.'),array['Small adjustments','Stable pitch','Lyric fit'],array['Exaggerated tension','Losing words','Changing every variable'],'Can a listener hear three choices while still recognizing your natural voice?'),
(5,3,'Choose Tone for the Lyric','Make an artistic tone choice based on meaning.',15,'Select and explain a tone color that serves the lyric.',jsonb_build_array('Name what the lyric communicates.','Compare the emotional effect of each tone color.','Choose the version that supports both healthy production and artistic intention.'),array['Lyric first','Healthy repeatability','Intentional choice'],array['Choosing by volume','Copying an artist exactly','Ignoring word meaning'],'What does your chosen tone help the listener understand?'),
(6,1,'Clear Words Without Overworking','Coordinate consonants and vowels for clarity.',20,'Sing intelligible lyrics while keeping musical flow.',jsonb_build_array('Speak the lyric at performance pace.','Let vowels carry sustained sound while consonants define words.','Adjust unclear sounds without exaggerating every syllable.'),array['Vowels carry','Consonants clarify','Natural jaw'],array['Chewing words','Dropping endings','Over-articulation'],'Can someone understand the lyric without reading it?'),
(6,2,'Phrase the Story','Use breath, emphasis, and timing to shape meaning.',20,'Plan phrasing around lyric intention.',jsonb_build_array('Identify the most important word in each phrase.','Plan breaths where they support meaning and vocal coordination.','Use timing and emphasis to guide the listener through the thought.'),array['Important words','Meaningful breaths','Complete thoughts'],array['Random breathing','Equal emphasis','Breaking a thought'],'Which word should the listener remember after this phrase?'),
(6,3,'Make Them Believe You','Commit to one listener feeling.',20,'Perform a verse or chorus with believable intention.',jsonb_build_array('Choose what you want the listener to feel.','Connect facial expression and vocal choices to that intention.','Review whether clarity and emotion support each other.'),array['Specific intention','Honest expression','Clear lyric'],array['Generic emotion','Acting without words','Sacrificing clarity'],'What evidence in your recording communicates the feeling you chose?'),
(7,1,'Control Soft and Strong Singing','Create volume contrast without losing coordination.',20,'Sing softly and strongly with stable breath and tone.',jsonb_build_array('Reduce volume without allowing the tone to disappear.','Increase energy without shouting or locking the body.','Compare how breath preparation changes for each choice.'),array['Supported soft tone','Strong not forced','Prepared breath'],array['Whispery collapse','Shouting','Raised shoulders'],'Can you repeat both versions with consistent pitch and healthy effort?'),
(7,2,'Shape a Phrase With Dynamics','Use gradual and sudden contrast intentionally.',20,'Plan and perform a dynamic arc.',jsonb_build_array('Mark where intensity grows, releases, or changes.','Use crescendo and decrescendo without changing tempo.','Coordinate the dynamic plan with lyric meaning.'),array['Plan the arc','Maintain timing','Support the change'],array['Getting faster when louder','Dropping pitch when softer','Random dynamics'],'Where is the emotional high point, and how does the dynamic shape lead there?'),
(7,3,'Interpret One Chorus Three Ways','Compare intimate, powerful, and emotional readings.',20,'Select an interpretation using audible evidence.',jsonb_build_array('Keep melody and rhythm stable across all versions.','Change dynamics, emphasis, and tone to create contrast.','Choose the version that communicates most clearly rather than simply sounding loudest.'),array['Stable foundation','Clear contrast','Artistic reason'],array['Changing the melody','Equating power with shouting','No stated intention'],'Which version best serves the lyric, and what evidence supports your choice?'),
(8,1,'Microphone and Phone Placement','Use available equipment at an effective distance and angle.',20,'Maintain consistent vocal level and reduce plosives.',jsonb_build_array('Test distance using speech before singing.','Angle slightly away when plosives overload the recording.','Keep placement consistent as performance energy changes.'),array['Test first','Consistent distance','Manage plosives'],array['Holding too close','Distance drift','Covering a phone microphone'],'Does the recorded level stay consistent from the first phrase to the last?'),
(8,2,'Prepare a Clean Recording Space','Reduce avoidable noise and monitoring problems.',15,'Complete a practical room, device, and headphone check.',jsonb_build_array('Listen for fans, traffic, reflections, notifications, and handling noise.','Set a level that avoids clipping while preserving detail.','Use headphones safely when they help monitor the track or recording.'),array['Quiet the room','Check level','Test playback'],array['Skipping test take','Recording too loud','Monitoring at unsafe volume'],'What one environmental change makes the recording clearer?'),
(8,3,'Record, Review and Choose a Take','Use multiple takes and specific playback criteria.',20,'Select a clean take using technique and delivery evidence.',jsonb_build_array('Record complete takes instead of stopping at every small issue.','Review mic consistency, noise, words, pitch, rhythm, and intention.','Choose or redo a take based on the most important improvement.'),array['Complete takes','Specific review','Purposeful redo'],array['Deleting every imperfect take','Listening only for mistakes','Choosing by volume'],'Why is your selected take stronger than the others?'),
(9,1,'Prepare to Perform','Build a short repeatable pre-performance routine.',15,'Use physical, vocal, and mental preparation before a take.',jsonb_build_array('Choose a brief warm-up connected to the song.','Set stance, breath, focus, and first intention before starting.','Use one grounding cue instead of trying to control everything.'),array['Warm up','Set focus','Know the first moment'],array['Starting unprepared','Over-rehearsing immediately before','Negative self-talk'],'What single cue helps you begin with commitment?'),
(9,2,'Presence, Focus and Connection','Use body and attention to support communication.',20,'Demonstrate purposeful focus, expression, and movement.',jsonb_build_array('Choose where your eyes and attention belong.','Let movement support the phrase instead of distracting from it.','Use facial expression that grows from lyric intention.'),array['Purposeful eyes','Grounded body','Connected expression'],array['Random movement','Closed posture','Performing only inward'],'Where does the recording show the clearest audience connection?'),
(9,3,'Recover and Keep Going','Continue through small mistakes without losing the performance.',20,'Complete a continuous take with confident recovery.',jsonb_build_array('Decide in advance that small mistakes will not stop the take.','Stay in pulse and reconnect at the next phrase.','Review recovery as a performance skill, not proof of failure.'),array['Keep the pulse','Breathe and rejoin','Finish the story'],array['Stopping immediately','Showing frustration','Rushing after a mistake'],'Did the recovery protect the listener’s experience?'),
(10,1,'Plan Your Beginner Showcase','Choose material and create a realistic preparation plan.',20,'Prepare a 60–120 second performance that demonstrates Beginner skills.',jsonb_build_array('Choose a song section in a healthy range.','Identify breath, pitch, rhythm, diction, expression, and recording priorities.','Schedule warm-up, practice, recording, review, and final take.'),array['Healthy song choice','Specific priorities','Realistic plan'],array['Choosing material for difficulty alone','No recording plan','Trying to fix everything at once'],'Which three Beginner skills should be easiest to observe in your showcase?'),
(10,2,'Dress Rehearsal and Self-Review','Run the complete performance and choose focused revisions.',25,'Evaluate a full take constructively.',jsonb_build_array('Complete a full dress-rehearsal take without stopping.','Review once for the overall creative impact, then again for specific evidence.','Select one to three high-value adjustments before the final recording.'),array['Complete take','Evidence first','Focused revision'],array['Endless retakes','Only negative feedback','Changing too many things'],'What is already working, and which adjustment will most improve the final?'),
(10,3,'Record the JPAC Beginner Showcase','Deliver and evaluate a polished capstone performance.',25,'Create a complete audio or video showcase for assessment and possible portfolio review.',jsonb_build_array('Warm up and prepare the recording environment.','Perform with integrated technique, musicianship, expression, and presence.','Review the final evidence honestly before submitting it for instructor assessment.'),array['Prepared start','Complete delivery','Clean capture','Honest review'],array['Submitting a test take','Ignoring technical noise','Assuming passing equals portfolio-ready'],'Does this performance represent your current best work, and what growth does it show?')
), modules as(select m.id module_id,m.course_id,m.level_module_number from public.course_modules m join public.course_levels cl on cl.id=m.course_level_id join public.courses c on c.id=m.course_id where c.slug='singing' and cl.level_number=1), rows as(select md.*,d.* from modules md join lesson_data d on d.module_n=md.level_module_number)
insert into public.lessons(module_id,title,description,lesson_type,duration_minutes,sort_order,xp_value,status,short_summary,learning_objective,content_blocks,technique_cues,common_mistakes,self_check)
select r.module_id,r.title,r.summary,'interactive',r.minutes,case when r.module_n=2 then 100+r.lesson_n else r.lesson_n end,0,'draft',r.summary,r.objective,r.blocks,r.cues,r.mistakes,r.self_check from rows r
where not exists(select 1 from public.lessons l where l.module_id=r.module_id and l.title=r.title);

with lesson_data(module_n,title,summary,objective,blocks,cues,mistakes,self_check) as(values
(1,'Singer Alignment and Breath','Coordinate body alignment with an efficient singer breath.','Demonstrate balanced alignment and a quiet low-release breath.',jsonb_build_array('Stack the body without stiffness.','Allow a quiet low-release inhalation.','Release air steadily through a phrase.'),array['Flexible knees','Released shoulders','Quiet inhale'],array['Locked knees','Raised shoulders','Noisy gasp'],'Can you release an even stream without lifting your shoulders?'),
(1,'Healthy Warm-Up Routine','Prepare the voice gradually and recognize healthy effort.','Complete a short safe warm-up in a comfortable range.',jsonb_build_array('Release body and breath.','Use easy trills, hums, or slides.','Move gradually toward song material.'),array['Easy volume','Comfortable range','Stop with pain'],array['Starting loud','Forcing range','Ignoring pain'],'Does your voice feel easier after the warm-up?')),
rows as(select l.id,d.* from lesson_data d join public.courses c on c.slug='singing' join public.course_levels cl on cl.course_id=c.id and cl.level_number=1 join public.course_modules m on m.course_level_id=cl.id and m.level_module_number=d.module_n join public.lessons l on l.module_id=m.id and l.title=d.title)
update public.lessons l set short_summary=r.summary,learning_objective=r.objective,content_blocks=r.blocks,technique_cues=r.cues,common_mistakes=r.mistakes,self_check=r.self_check from rows r where l.id=r.id;

-- A distinct in-lesson action keeps every lesson embodied and substantial
-- without creating XP, progress, or activity records for a small practice cue.
with quick_try(module_n,title,prompt) as(values
(1,'Singer Alignment and Breath','Try this now: stand with flexible knees, reset shoulders and jaw, then complete four quiet inhale-and-steady-exhale cycles while watching for shoulder lift.'),
(1,'Healthy Warm-Up Routine','Try this now: complete one gentle hum, one lip trill or easy slide, and one comfortable song phrase; stop if anything feels painful or scratchy.'),
(1,'Vocal Health for Real Creators','Try this now: design a 10-minute practice plan with a warm-up, one focused skill, one song application, and a short vocal break.'),
(2,'Speaking Into Song','Try this now: speak one lyric to an imaginary listener, repeat it on one easy pitch, then sing the melody without losing the conversational intention.'),
(2,'Comfortable Range and Tension Awareness','Try this now: sing a five-note pattern in three nearby starting keys and mark which version feels repeatable without chin, neck, or jaw effort.'),
(2,'Natural Tone and Healthy Onset','Try this now: sing one phrase conversationally, lightly, and with stronger energy; choose the version that feels healthiest and most like you.'),
(3,'Listen Before You Sing','Try this now: play or ask for three comfortable reference notes; for each, listen fully, imagine it silently, sing once, and make only one calm correction.'),
(3,'Stable Notes and Simple Intervals','Try this now: sustain one easy note for four counts, then sing two-note up/down patterns; notice whether either destination consistently lands sharp or flat.'),
(3,'Correct Your Own Melody','Try this now: sing a four-note pattern once, identify only the first missed note, practice that two-note connection three times, then retry the full pattern.'),
(4,'Find the Pulse','Try this now: tap eight steady beats, speak a lyric over the beat, continue tapping through a silent rest, and enter again without losing time.'),
(4,'Entrances, Durations and Releases','Try this now: count in, sing one held phrase, and release on a chosen count; repeat until the entrance and ending happen without guessing.'),
(4,'Build the Groove','Try this now: clap a difficult rhythm, speak it on a neutral syllable, then sing it with the lyric over a backing track at a manageable speed.'),
(5,'Where Tone Resonates','Try this now: hum gently and open to three comfortable vowels; compare where vibration is noticed without trying to push it into place.'),
(5,'Bright, Dark and Balanced Color','Try this now: sing one phrase with small bright, dark, and balanced choices while keeping the same pitch, words, and comfortable volume.'),
(5,'Choose Tone for the Lyric','Try this now: name the lyric intention, perform two contrasting tone choices, and ask which choice communicates the meaning with less effort.'),
(6,'Clear Words Without Overworking','Try this now: speak one lyric at tempo, sing it on vowels only, then restore consonants while keeping the same flowing line.'),
(6,'Phrase the Story','Try this now: underline one important word, mark one meaningful breath, and sing the phrase twice with that word clearly guiding the thought.'),
(6,'Make Them Believe You','Try this now: choose one specific listener and one intended feeling, then perform the section directly to that listener or the camera.'),
(7,'Control Soft and Strong Singing','Try this now: sing one short phrase at a healthy soft level and again with stronger energy; keep pitch, breath, and body freedom consistent.'),
(7,'Shape a Phrase With Dynamics','Try this now: draw an intensity line above one phrase, then sing the line without speeding up as it grows or losing support as it releases.'),
(7,'Interpret One Chorus Three Ways','Try this now: perform 20 seconds as intimate, powerful, and reflective while keeping melody and rhythm stable; choose using audible evidence.'),
(8,'Microphone and Phone Placement','Try this now: test the same phrase at three practical distances or angles and identify the cleanest level with the fewest plosives.'),
(8,'Prepare a Clean Recording Space','Try this now: record ten seconds of room sound, remove one avoidable noise source, set a safe monitoring level, and repeat the test.'),
(8,'Record, Review and Choose a Take','Try this now: record two uninterrupted takes, review each against three named criteria, and choose a take before deciding whether another is needed.'),
(9,'Prepare to Perform','Try this now: rehearse a 60-second routine—ground your stance, release one breath, set eye focus, name the first intention, and begin.'),
(9,'Presence, Focus and Connection','Try this now: perform one verse to the camera with one eye-focus plan and only purposeful movement, then review the opening and ending.'),
(9,'Recover and Keep Going','Try this now: deliberately restart one word late during rehearsal, stay in pulse, reconnect at the next phrase, and finish without apologizing.'),
(10,'Plan Your Beginner Showcase','Try this now: choose an appropriate 60–120 second section and write a short plan covering interpretation, warm-up, rehearsal, recording, and review.'),
(10,'Dress Rehearsal and Self-Review','Try this now: complete one no-stop dress rehearsal, review once for overall impact and once for evidence, then select no more than three corrections.'),
(10,'Record the JPAC Beginner Showcase','Try this now: complete the final sequence—warm up, prepare the space, perform one full take, self-check the evidence, and submit only when it represents your current best work.')
), targets as(
  select l.id,q.prompt from quick_try q join public.courses c on c.slug='singing'
  join public.course_levels cl on cl.course_id=c.id and cl.level_number=1
  join public.course_modules m on m.course_level_id=cl.id and m.level_module_number=q.module_n
  join public.lessons l on l.module_id=m.id and l.title=q.title
)
update public.lessons l set content_blocks=l.content_blocks||jsonb_build_array(t.prompt),updated_at=now()
from targets t where l.id=t.id and not (l.content_blocks ? t.prompt);

-- Draft practices and challenges. Existing published pilot activities are not
-- overwritten. Rubric weights total 100 and passing remains 70.
with activity_data(module_n,kind,title,description,instructions,submission_type,xp,required,rubric,portfolio_candidate) as(values
(1,'real','Before-and-After Breath Challenge','Compare one chorus before and after focused breathing practice.','Record the chorus once. Complete three controlled breath cycles. Record it again and identify one phrase that feels easier.','none',50,false,'{}'::jsonb,false),(1,'lab','Breath Cycle Comparison Lab','Compare three controlled breath cycles.','Use an available recording/comparison tool if one is assigned; otherwise record three cycles and note consistency.','none',50,false,'{}'::jsonb,false),(1,'core','Breath Control Studio Challenge','Demonstrate balanced alignment, coordinated inhalation, phrase support, and healthy tone.','Record 30–60 seconds of a song you choose. Use audio or video and submit your strongest complete take.','audio',350,true,jsonb_build_object('criteria',jsonb_build_array(jsonb_build_object('name','Alignment and posture','weight',20),jsonb_build_object('name','Breath coordination','weight',25),jsonb_build_object('name','Phrase control','weight',20),jsonb_build_object('name','Healthy vocal production','weight',20),jsonb_build_object('name','Preparation and completion','weight',15))),false),
(2,'real','Three Versions, One Authentic Voice','Compare conversational, lighter, and stronger versions.','Record the same short section three ways. Choose the healthiest authentic version and state one reason.','none',50,false,'{}',false),(2,'lab','Natural Tone Comparison Lab','Compare tone and tension across three short takes.','Use a real assigned comparison tool when available; otherwise label and compare three recordings.','none',50,false,'{}',false),(2,'core','Find Your Sound Challenge','Choose a healthy and authentic vocal approach.','Record one section conversationally, lighter, and stronger. Submit the healthiest authentic version with a short spoken or written reason.','audio',350,true,jsonb_build_object('criteria',jsonb_build_array(jsonb_build_object('name','Comfortable range','weight',20),jsonb_build_object('name','Healthy onset','weight',20),jsonb_build_object('name','Low tension','weight',20),jsonb_build_object('name','Natural tone','weight',25),jsonb_build_object('name','Artistic choice','weight',15))),false),
(3,'real','First Take / Final Take Melody','Create evidence of pitch improvement.','Record a first take, isolate one inaccurate phrase, practice slowly, then record a final take and compare.','none',50,false,'{}',false),(3,'lab','Pitch Match Lab','Compare reference notes and sung responses.','Use a real pitch-comparison tool if assigned; otherwise record reference/response pairs without a fake route.','none',50,false,'{}',false),(3,'core','Nail the Melody','Demonstrate improved pitch accuracy.','Submit a short melody or song section showing your strongest final pitch-accurate take.','audio',350,true,jsonb_build_object('criteria',jsonb_build_array(jsonb_build_object('name','Pitch matching','weight',25),jsonb_build_object('name','Sustained pitch','weight',20),jsonb_build_object('name','Melodic accuracy','weight',25),jsonb_build_object('name','Self-correction','weight',15),jsonb_build_object('name','Complete prepared take','weight',15))),false),
(4,'real','Lock Into the Backing Track','Practice clean timing against music.','Clap and count the section, rehearse difficult entrances slowly, then record a full rhythmic take.','none',50,false,'{}',false),(4,'lab','Rhythm Match Lab','Compare pulse and entrance accuracy.','Use an assigned rhythm tool if available; otherwise record clapped and sung versions for comparison.','none',50,false,'{}',false),(4,'core','Lock Into the Groove','Perform a rhythmic song section with confident timing.','Submit a complete section emphasizing steady pulse, clean entrances, accurate duration, and phrasing.','audio',350,true,jsonb_build_object('criteria',jsonb_build_array(jsonb_build_object('name','Steady pulse','weight',25),jsonb_build_object('name','Entrances and releases','weight',20),jsonb_build_object('name','Note duration','weight',20),jsonb_build_object('name','Rhythmic phrasing','weight',20),jsonb_build_object('name','Prepared complete take','weight',15))),false),
(5,'real','Three Colors of One Phrase','Explore intentional tone color.','Record one phrase bright, dark, and balanced while keeping pitch and words stable.','none',50,false,'{}',false),(5,'lab','Tone Color Lab','Compare resonance and tone across takes.','Use an assigned tone-comparison tool if available; otherwise compare labeled recordings.','none',50,false,'{}',false),(5,'core','Three Colors of Your Voice','Choose a tone color that serves the lyric.','Perform one phrase three ways, then submit the version that best fits the lyric with a short reason.','audio',350,true,jsonb_build_object('criteria',jsonb_build_array(jsonb_build_object('name','Tone consistency','weight',20),jsonb_build_object('name','Intentional color','weight',25),jsonb_build_object('name','Healthy resonance','weight',20),jsonb_build_object('name','Low tension','weight',20),jsonb_build_object('name','Lyric fit','weight',15))),false),
(6,'real','Tell the Lyric Story','Practice clarity and intention.','Speak the lyric, mark important words, plan breaths, then record the sung version for one intended listener feeling.','none',50,false,'{}',false),(6,'lab','Lyric Clarity Lab','Compare spoken and sung lyric clarity.','Use an assigned recording comparison tool if available; otherwise compare a spoken and sung take.','none',50,false,'{}',false),(6,'core','Make Them Believe You','Communicate clear lyrics and believable intention.','Submit a verse or chorus with clear diction, purposeful phrasing, and one stated listener feeling.','video',350,true,jsonb_build_object('criteria',jsonb_build_array(jsonb_build_object('name','Word clarity','weight',20),jsonb_build_object('name','Vowel and consonant coordination','weight',20),jsonb_build_object('name','Phrasing','weight',20),jsonb_build_object('name','Story intention','weight',25),jsonb_build_object('name','Complete performance','weight',15))),true),
(7,'real','Three Dynamic Interpretations','Compare intimate, powerful, and emotional choices.','Record the same chorus three ways while preserving melody and rhythm. Choose the strongest interpretation.','none',50,false,'{}',false),(7,'lab','Dynamics Comparison Lab','Compare dynamic shape across takes.','Use an assigned comparison tool if available; otherwise label three recordings and note audible contrast.','none',50,false,'{}',false),(7,'core','Sing It Three Ways','Demonstrate controlled expressive contrast.','Submit the strongest intimate, powerful, or emotional version and briefly identify the artistic choice.','audio',350,true,jsonb_build_object('criteria',jsonb_build_array(jsonb_build_object('name','Dynamic control','weight',25),jsonb_build_object('name','Healthy soft and strong tone','weight',20),jsonb_build_object('name','Phrasing and emphasis','weight',20),jsonb_build_object('name','Emotional contrast','weight',20),jsonb_build_object('name','Artistic choice','weight',15))),false),
(8,'real','Phone or Microphone Placement Test','Find a clean, consistent recording position.','Record the same phrase at three distances or angles. Choose the cleanest position and use it for one full take.','none',50,false,'{}',false),(8,'lab','Recording Setup Lab','Compare placement, level, and room noise.','Use a real recording analysis tool if assigned; otherwise compare test recordings without a fake destination.','none',50,false,'{}',false),(8,'core','Studio Ready Take','Create a clean vocal recording using available equipment.','Submit a 45–60 second take using a microphone or phone with consistent distance, controlled plosives, clean level, and complete delivery.','video',350,true,jsonb_build_object('criteria',jsonb_build_array(jsonb_build_object('name','Mic or phone positioning','weight',20),jsonb_build_object('name','Plosive control','weight',15),jsonb_build_object('name','Level consistency','weight',20),jsonb_build_object('name','Recording cleanliness','weight',20),jsonb_build_object('name','Vocal delivery','weight',25))),true),
(9,'real','No-Stop Performance Run','Practice recovery and presence.','Choose a section, prepare, and complete one continuous take without stopping for small mistakes.','none',50,false,'{}',false),(9,'lab','Performance Review Lab','Review presence and recovery evidence.','Use an assigned video review tool if available; otherwise watch one complete take and mark one strength and one adjustment.','none',50,false,'{}',false),(9,'core','One Take Performance','Demonstrate committed presence and recovery.','Submit one continuous performance emphasizing focus, body language, expression, recovery, and audience or camera connection.','video',350,true,jsonb_build_object('criteria',jsonb_build_array(jsonb_build_object('name','Preparation and start','weight',15),jsonb_build_object('name','Presence and focus','weight',25),jsonb_build_object('name','Expression and movement','weight',20),jsonb_build_object('name','Recovery and continuity','weight',25),jsonb_build_object('name','Audience connection','weight',15))),false),
(10,'real','Showcase Dress Rehearsal','Complete and review a full rehearsal take.','Record the entire showcase, identify what already works, then choose no more than three final adjustments.','none',50,false,'{}',false),(10,'lab','Showcase Review Lab','Compare rehearsal and final evidence.','Use an assigned performance review tool if available; otherwise compare complete recordings without a fake route.','none',50,false,'{}',false),(10,'core','JPAC Beginner Showcase','Create a polished Beginner capstone performance.','Submit a complete 60–120 second audio or video performance demonstrating integrated Beginner skills. Video is encouraged when practical.','video',350,true,jsonb_build_object('criteria',jsonb_build_array(jsonb_build_object('name','Healthy technique and breath','weight',20),jsonb_build_object('name','Pitch and rhythm','weight',20),jsonb_build_object('name','Tone, diction, and expression','weight',20),jsonb_build_object('name','Recording or microphone awareness','weight',15),jsonb_build_object('name','Presence and complete delivery','weight',15),jsonb_build_object('name','Preparation and self-review','weight',10))),true)
), modules as(select m.id module_id,m.course_id,m.level_module_number from public.course_modules m join public.course_levels cl on cl.id=m.course_level_id join public.courses c on c.id=m.course_id where c.slug='singing' and cl.level_number=1), rows as(select md.*,d.* from modules md join activity_data d on d.module_n=md.level_module_number)
insert into public.activities(course_id,module_id,title,description,activity_type,instructions,submission_type,xp_reward,required,status,rubric,xp_type,passing_score,allows_resubmission,portfolio_candidate)
select r.course_id,r.module_id,r.title,r.description,case when r.kind='core' then 'performance' else 'practice' end,r.instructions,r.submission_type,r.xp,r.required,'draft',r.rubric,case when r.required then 'core' else 'bonus' end,70,true,r.portfolio_candidate from rows r
where not exists(select 1 from public.activities a where a.module_id=r.module_id and a.title=r.title);

do $$ begin
  if exists(select 1 from public.course_modules m join public.course_levels cl on cl.id=m.course_level_id join public.courses c on c.id=m.course_id where c.slug='singing' and cl.level_number=1 and (m.core_xp<>625 or m.core_unlock_threshold<>438)) then raise exception 'E3 seed cannot alter canonical XP'; end if;
  if exists(select 1 from public.course_modules m join public.course_levels cl on cl.id=m.course_level_id join public.courses c on c.id=m.course_id where c.slug='singing' and cl.level_number>1 and (m.video_brief<>'' or m.aria_coaching_targets<>'{}'::jsonb)) then raise exception 'E3 authored outside Beginner'; end if;
  if exists(
    select 1 from phase_e3_preservation_baseline b
    where b.original_module_2_id<>(select m.id from public.course_modules m join public.course_levels cl on cl.id=m.course_level_id join public.courses c on c.id=m.course_id where c.slug='singing' and cl.level_number=1 and m.level_module_number=2)
       or b.progress_rows<>(select count(*) from public.lesson_progress)
       or b.submission_rows<>(select count(*) from public.submissions)
       or b.xp_rows<>(select count(*) from public.xp_ledger)
       or b.enrollment_rows<>(select count(*) from public.enrollments)
       or b.progress_hash<>(select md5(coalesce(string_agg(to_jsonb(p)::text,'|' order by p.id::text),'')) from public.lesson_progress p)
       or b.submission_hash<>(select md5(coalesce(string_agg(to_jsonb(s)::text,'|' order by s.id::text),'')) from public.submissions s)
       or b.xp_hash<>(select md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id::text),'')) from public.xp_ledger x)
       or b.enrollment_hash<>(select md5(coalesce(string_agg(to_jsonb(e)::text,'|' order by e.id::text),'')) from public.enrollments e)
  ) then raise exception 'E3 preservation assertion failed'; end if;
end $$;

commit;
