import type { ComponentType } from 'react';
import { HarmonyBuilderTool } from './harmony/HarmonyBuilderTool';
import { SmartMetronomeTool } from './metronome/SmartMetronomeTool';
import { NotationTrainerTool } from './notation/NotationTrainerTool';
import { LoopBuilderTool } from './loop/LoopBuilderTool';
import { SmartTunerTool } from './tuner/SmartTunerTool';
import { VirtualGuitarTool } from './guitar/VirtualGuitarTool';
import { ChoreoMirrorTool } from './choreo/ChoreoMirrorTool';
import { VirtualPianoTool } from './piano/VirtualPianoTool';

export type ToolActivity = { id: string; title: string; prompt: string };
const activitySets: Record<string, string[]> = {
  'harmony-builder': ['Try a two-chord welcome','Build a hopeful progression','Write a tension-and-release loop','Explore a minor mood','Create a sunrise progression','Add a surprise chord','Make a soundtrack for rain','Build a chorus lift','Compare major and minor','Compose a four-chord signature','Try a gospel-inspired movement','Create a calm bedtime loop','Write a question-and-answer progression','Find a progression for dancing','Make a cinematic ending','Limit yourself to three chords','Create a progression for your current mood','Transpose your favorite idea','Build an intro and an outro','Name the feeling your chords create'],
  'virtual-piano': ['Play a five-note pattern','Find middle C','Create a three-note melody','Try a left-hand drone','Play a major triad','Play a minor triad','Copy a rhythm from a song','Compose a musical greeting','Explore high and low registers','Build a call-and-response','Play softly then strongly','Create a five-minute warm-up','Improvise with only black keys','Make a melody for a character','Practice steady quarter notes','Invent a three-note motif','Play and describe a mood','Create an ending cadence','Repeat a pattern with one change','Share your favorite sound'],
  'smart-metronome': ['Tap along at 60 BPM','Practice a four-count entrance','Try accents on beat one','Switch between subdivisions','Increase tempo by five','Decrease tempo by five','Practice a silent count-in','Clap a syncopated rhythm','Hold steady through a pause','Create a two-bar groove','Practice walking in time','Try the same rhythm slowly','Record your best steady minute','Move accents to beat three','Practice an imaginary pickup','Count a verse and chorus','Challenge yourself at 100 BPM','Return to a comfortable tempo','Describe your timing goal','Celebrate one improvement'],
  'notation-trainer': ['Identify five treble notes','Identify five bass notes','Read a two-bar rhythm','Clap a dotted rhythm','Write a four-note melody','Name a key signature','Find a repeated pattern','Practice ledger lines','Translate notes to solfege','Create a rhythm with rests','Read from left to right','Circle the downbeats','Compare two rhythms','Sketch a musical question','Write a simple cadence','Challenge your note speed','Read a melody aloud','Invent a practice mnemonic','Correct one imagined error','Reflect on what feels easier'],
  'loop-builder': ['Build a four-on-the-floor beat','Create a halftime groove','Add a contrasting bass line','Make a loop for a chase scene','Try three kick patterns','Mute one layer and listen','Build a verse groove','Build a chorus groove','Create a drum fill','Use silence as a feature','Make a loop for your career path','Try a syncopated hi-hat','Keep only two sounds','Create a loop at a new tempo','Build a groove that feels joyful','Build a groove that feels tense','Arrange intro, loop, outro','Name your groove','Change one step at a time','Save your favorite pattern locally'],
  'smart-tuner': ['Find a comfortable reference note','Hum and observe your pitch','Glide slowly between two notes','Hold one note steadily','Compare two short takes','Practice a gentle siren','Tune a sustained vowel','Notice your starting pitch','Try a quiet and strong take','Warm up for two minutes','Match a piano reference','Listen before correcting','Practice descending five notes','Practice ascending five notes','Describe your vocal sensation','Take a relaxed breath','Repeat with less tension','Find your clearest tone','Celebrate improved consistency','Write a pitch-awareness goal'],
  'virtual-guitar': ['Find an open-string pattern','Play a two-chord loop','Try a simple downstroke','Build a four-beat strum','Create a riff with three notes','Practice changing chords','Play a quiet accompaniment','Make a melody over a chord','Explore a high-register idea','Try a bluesy phrase','Create an intro riff','Create an ending riff','Play with a steady pulse','Invent a call-and-response','Use one string only','Build a song section','Transpose your idea','Name the mood of your riff','Repeat with one variation','Plan a five-minute guitar session'],
  'choreo-mirror': ['Practice a four-count entrance','Create a two-step motif','Mirror a simple shape','Explore high and low levels','Try slow-motion movement','Make a joyful eight-count','Make a powerful eight-count','Practice stillness and release','Travel across your space safely','Create a character walk','Repeat with a direction change','Add a gesture to a lyric','Practice facial expression','Freestyle for thirty seconds','Mark a chorus pathway','Try a canon with yourself','Notice one strong choice','Build confidence with repetition','Create a beginning and ending pose','Reflect on how movement felt'],
};
const makeActivities = (slug: string) => activitySets[slug].map((title, index) => ({ id: `${slug}-${index + 1}`, title, prompt: `${title}. Explore this idea locally, then write one observation about what you discovered.` }));
export type PremiumToolDefinition = { slug: string; title: string; icon: string; description: string; component: ComponentType; activities: ToolActivity[] };
export const premiumCreatorTools: PremiumToolDefinition[] = [
  { slug: 'harmony-builder', title: 'Harmony Builder', icon: '🎼', description: 'Build chord progressions for Pop, R&B, Gospel, Blues, Country, and cinematic ideas.', component: HarmonyBuilderTool, activities: makeActivities('harmony-builder') },
  { slug: 'virtual-piano', title: 'Virtual Piano', icon: '🎹', description: 'Play two octaves, explore chord pads, and practice locally with Web Audio.', component: VirtualPianoTool, activities: makeActivities('virtual-piano') },
  { slug: 'smart-metronome', title: 'Smart Metronome', icon: '⏱️', description: 'Strengthen your timing with accents, subdivisions, tap tempo, and visual beats.', component: SmartMetronomeTool, activities: makeActivities('smart-metronome') },
  { slug: 'notation-trainer', title: 'Notation Trainer Pro', icon: '🎵', description: 'Practice treble and bass clef notes, rhythm values, and sketch a 64-bar score.', component: NotationTrainerTool, activities: makeActivities('notation-trainer') },
  { slug: 'loop-builder', title: 'Loop Builder / Beat Lab', icon: '🥁', description: 'Create a 16-step groove with synthesized drums, bass, presets, and a live playhead.', component: LoopBuilderTool, activities: makeActivities('loop-builder') },
  { slug: 'smart-tuner', title: 'Smart Tuner', icon: '🎙️', description: 'Practice pitch with opt-in, browser-local microphone feedback and reference notes.', component: SmartTunerTool, activities: makeActivities('smart-tuner') },
  { slug: 'virtual-guitar', title: 'Virtual Guitar / Instrument Studio', icon: '🎸', description: 'Play six strings and twelve frets, explore chord shapes, and try guitar-style effects.', component: VirtualGuitarTool, activities: makeActivities('virtual-guitar') },
  { slug: 'choreo-mirror', title: 'Choreo Mirror', icon: '🕺', description: 'Practice with an opt-in local camera mirror and simple motion-energy feedback.', component: ChoreoMirrorTool, activities: makeActivities('choreo-mirror') },
];
const aliases: Record<string, string> = { 'harmony-stack-pad': 'harmony-builder', 'jpac-virtual-piano': 'virtual-piano', metronome: 'smart-metronome', 'notation-trainer-pro': 'notation-trainer', 'music-reading-tool': 'notation-trainer', 'rhythm-reading': 'notation-trainer', 'beat-lab': 'loop-builder', 'loop-builder-songwriter': 'loop-builder', 'jpac-loop-builder': 'loop-builder', 'drum-sequencer': 'loop-builder', 'voice-instrument-tuner': 'smart-tuner', 'jpac-smart-tuner': 'smart-tuner', tuner: 'smart-tuner', 'pitch-trainer': 'smart-tuner', 'jpac-virtual-guitar': 'virtual-guitar', 'instrument-studio': 'virtual-guitar', 'jpac-instrument-studio': 'virtual-guitar', 'guitar-lab': 'virtual-guitar', 'jpac-choreo-mirror': 'choreo-mirror', 'choreo-studio': 'choreo-mirror', 'jpac-choreo-studio': 'choreo-mirror', 'dance-motion-lab': 'choreo-mirror' };
export function getPremiumCreatorTool(slug?: string) { const canonical = slug ? aliases[slug] || slug : ''; return premiumCreatorTools.find((tool) => tool.slug === canonical); }
export function getToolActivities(title: string) { return premiumCreatorTools.find((tool) => tool.title === title)?.activities || []; }
