import{useEffect,useMemo,useState}from'react';
import{supabase}from'../lib/supabase';
import{useAuth,type AppRole}from'../context/AuthContext';
type Profile={id:string;display_name:string;email:string|null;role:AppRole;total_xp:number};
type Course={id:string;title:string;status:string;total_xp:number};
const roleLabels:{[K in AppRole]:string}={student:'Student',teacher:'Teacher',admin:'Admin',developer:'Developer Admin'};
export function AdminPage(){const{profile}=useAuth();const[users,setUsers]=useState<Profile[]>([]);const[courses,setCourses]=useState<Course[]>([]);const[selectedUser,setSelectedUser]=useState('');const[selectedCourse,setSelectedCourse]=useState('');const[xp,setXp]=useState('500');const[reason,setReason]=useState('Creative practice achievement');const[message,setMessage]=useState('');const[loading,setLoading]=useState(true);
const students=useMemo(()=>users.filter(x=>x.role==='student'),[users]);const teachers=useMemo(()=>users.filter(x=>['teacher','admin','developer'].includes(x.role)),[users]);
async function load(){if(!supabase)return;setLoading(true);const[{data:u,error:ue},{data:c,error:ce}]=await Promise.all([supabase.from('profiles').select('id,display_name,email,role,total_xp').order('display_name'),supabase.from('courses').select('id,title,status,total_xp').order('title')]);if(ue||ce)setMessage(ue?.message||ce?.message||'Unable to load Academy data.');setUsers((u as Profile[])||[]);setCourses((c as Course[])||[]);setLoading(false)}
useEffect(()=>{void load()},[]);
async function changeRole(userId:string,role:AppRole){if(!supabase)return;setMessage('Saving role…');const{error}=await supabase.rpc('admin_set_user_role',{target_user:userId,new_role:role});setMessage(error?.message||'Role updated.');if(!error)await load()}
async function awardXp(){if(!supabase||!selectedUser)return;const amount=Number(xp);const{error}=await supabase.rpc('admin_award_xp',{target_student:selectedUser,xp_amount:amount,xp_reason:reason});setMessage(error?.message||`${amount.toLocaleString()} XP awarded.`);if(!error)await load()}
async function enroll(){if(!supabase||!selectedUser||!selectedCourse)return;const teacher=teachers[0]?.id||null;const{error}=await supabase.rpc('admin_enroll_student',{target_student:selectedUser,target_course:selectedCourse,assigned_teacher:teacher});setMessage(error?.message||'Student enrolled successfully.')}
async function issueCertificate(){if(!supabase||!selectedUser||!selectedCourse)return;const course=courses.find(x=>x.id===selectedCourse);const instructor=teachers[0]?.display_name||profile?.display_name||'JPAC Academy Instructor';const{error}=await supabase.rpc('admin_issue_completion_certificate',{target_student:selectedUser,target_course:selectedCourse,completion_on:new Date().toISOString().slice(0,10),grade_value:'A',score_value:95,hours_value:40,level_value:'Level 1',instructor_value:instructor});setMessage(error?.message||`Certificate queued for ${course?.title||'course'}.`)}
if(!profile||!['admin','developer'].includes(profile.role))return <div className="card card-pad"><h2>Administrator access required</h2></div>;
return <><div className="page-hero"><div><div className="eyebrow">Academy operations</div><h1 className="page-title">Admin Command Center</h1><p className="muted">Manage people, roles, enrollment, XP and credentials through visual workflows.</p></div><div className="studio-signal">● Live Supabase data</div></div><div className="admin-metrics"><div><strong>{users.length}</strong><span>Total accounts</span></div><div><strong>{students.length}</strong><span>Students</span></div><div><strong>{teachers.length}</strong><span>Staff</span></div><div><strong>{courses.length}</strong><span>Courses</span></div></div>{message&&<div className="admin-message">{message}</div>}<div className="admin-grid"><section className="card admin-panel"><div className="section-head"><h2>People & access</h2><button className="button button-secondary" onClick={()=>void load()}>Refresh</button></div>{loading?<p className="muted">Loading accounts…</p>:<div className="user-list">{users.map(user=><article className="user-row" key={user.id}><div className="avatar">{user.display_name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div><div className="user-details"><strong>{user.display_name||'Unnamed user'}</strong><small>{user.email}</small><span>{user.total_xp.toLocaleString()} XP</span></div><select value={user.role} onChange={e=>void changeRole(user.id,e.target.value as AppRole)} disabled={user.id===profile.id}><option value="student">Student</option><option value="teacher">Teacher</option><option value="admin">Admin</option><option value="developer">Developer Admin</option></select></article>)}</div>}</section><aside className="card admin-panel quick-actions"><h2>Quick academy actions</h2><label>Student<select value={selectedUser} onChange={e=>setSelectedUser(e.target.value)}><option value="">Select a student</option>{students.map(s=><option value={s.id} key={s.id}>{s.display_name}</option>)}</select></label><label>Course<select value={selectedCourse} onChange={e=>setSelectedCourse(e.target.value)}><option value="">Select a course</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><div className="action-box"><h3>Award XP</h3><input type="number" value={xp} onChange={e=>setXp(e.target.value)}/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason"/><button className="button button-primary" disabled={!selectedUser} onClick={()=>void awardXp()}>Award XP</button></div><button className="button button-secondary wide" disabled={!selectedUser||!selectedCourse} onClick={()=>void enroll()}>Enroll in selected course</button><button className="button button-secondary wide" disabled={!selectedUser||!selectedCourse} onClick={()=>void issueCertificate()}>Issue completion certificate</button></aside></div></>}
