import{useEffect,useMemo,useState}from'react';
import{Link}from'react-router-dom';
import{JPACCoachPanel}from'../features/ai-instructor/components/JPACCoachPanel';
import{buildDashboardCoachContext}from'../features/ai-instructor/contextBuilder';
import{continueDestination,loadMyCourses,type AcademyCourse}from'../lib/studentAccess';

export function AIInstructorHubPage(){
  const[courses,setCourses]=useState<AcademyCourse[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  useEffect(()=>{let active=true;void loadMyCourses().then(result=>{if(!active)return;setCourses(result.data);setError(result.error);setLoading(false)});return()=>{active=false}},[]);
  const destination=useMemo(()=>continueDestination(courses),[courses]);const context=useMemo(()=>buildDashboardCoachContext(courses,destination),[courses,destination]);
  const pending=courses.filter(course=>Number(course.progress||0)<100);
  return <div className="ai-instructor-page"><header className="ai-instructor-hero"><div><span>Deterministic instructor layer · Phase 1</span><h1>JPAC AI Instructor Hub</h1><p>One safe place to reconnect with learning, practice, assignment preparation, extra credit, and teacher feedback.</p></div><Link className="button button-primary" to={destination.to}>{loading?'Loading your next step…':destination.label}</Link></header>{error&&<div className="admin-message" role="alert">{error}</div>}<JPACCoachPanel context={context}/><section className="coach-hub-grid"><article><span>Continue learning</span><h2>{courses[0]?.title||'My Academy'}</h2><p>{loading?'Checking your authorized learning scope…':courses.length?'Continue from the next published lesson available to your enrollment.':'No active course is available yet.'}</p><Link to={destination.to}>Open next step →</Link></article><article><span>Pending work</span><h2>{pending.length} active {pending.length===1?'program':'programs'}</h2><p>Only published, authorized learning appears here. JPAC Coach does not change completion status.</p><Link to="/courses">Review My Academy →</Link></article><article><span>Practice connection</span><h2>Creator Tools</h2><p>Use local practice tools when they support your authored lesson or module goal.</p><Link to="/studio">Open Creative Studio →</Link></article><article><span>Extra credit and revisions</span><h2>Teacher review required</h2><p>Submission status and teacher feedback remain inside each Creator Tool project. Needs Revision feedback becomes a step-by-step plan there.</p><Link to="/studio">Check Creator Tool projects →</Link></article></section><section className="coach-hub-boundary"><strong>What JPAC Coach can do</strong><p>Explain, organize, recommend, navigate, and check completeness. It cannot submit, grade, approve, award XP or mastery, update progress, issue certificates, or change enrollment.</p></section></div>;
}
