import{Card}from'../components/ui';
const credentialTypes=[
 ['🏆','Certificate of Completion','Automatically issued at 100% course completion.','Auto'],
 ['⭐','Certificate of Excellence','Recognizes exceptional scores, performance and dedication.','Approval'],
 ['🚀','Level Up Certificate','Celebrates advancement through the JPAC career journey.','Auto'],
 ['✅','Perfect Attendance Award','Issued for 100% attendance in a course or program.','Auto'],
 ['🎭','Artist Achievement Award','Teacher-selected recognition for artistic growth.','Approval'],
 ['🎤','Performance Certificate','Documents showcases, recitals and live performances.','Approval'],
 ['🧭','Career Path Certification','Issued when a student completes a career specialization.','Auto'],
 ['🎵','Skill Badge Certificate','Recognizes mastery of an individual creative skill.','Auto']
];
export function CertificateCenterPage(){return <><div className="page-hero"><div><div className="eyebrow">Official JPAC credentials</div><h1 className="page-title">Certificate Center</h1><p className="muted">Every qualifying achievement can produce a formal print certificate and a mobile-ready digital achievement card with a unique verification record.</p></div><div className="credential-status">● Verification Ready</div></div><section className="certificate-showcase card"><div className="certificate-ribbon">JPAC Academy · Greatness Starts Now</div><div className="certificate-preview"><img className="certificate-logo" src="/assets/jpac-official-logo.png" alt="J. Moné's Performing Arts Center official logo"/><div className="eyebrow">Certificate of Completion</div><h2>Aaliyah Johnson</h2><p>has successfully completed</p><h3>Piano Level 2</h3><p className="certificate-system-name">JPAC Academy Learning System</p><div className="certificate-meta"><span><b>98%</b> Final Score</span><span><b>A+</b> Grade</span><span><b>40</b> Hours</span><span><b>Level 2</b> Level</span></div><div className="certificate-footer"><span>JPAC-2026-000001</span><strong>Official Gold Seal</strong><span>jmonespac.org</span></div></div></section><div className="certificate-actions"><button className="button button-primary">View earned certificates</button><button className="button button-secondary">Open verification center</button></div><div className="grid grid-4 credential-grid">{credentialTypes.map(x=><Card key={x[1]} className="credential-card"><div className="icon-tile">{x[0]}</div><div><h3>{x[1]}</h3><p className="muted">{x[2]}</p></div><span className={`credential-mode ${x[3]==='Auto'?'auto':''}`}>{x[3]}</span></Card>)}</div><Card className="card-pad credential-automation"><div><div className="eyebrow">System automation variables</div><h2>One student record. Two polished outputs.</h2><p className="muted">The credential engine uses the student name, course, completion date, grade, final score, hours, level, instructor, certificate ID, signatures and verification QR target to generate both the official print certificate and the social-ready digital achievement card.</p></div><div className="credential-output"><span>🖨️ 1920×1080 print</span><span>📱 1080×1350 digital</span><span>🔐 Unique verification token</span></div></Card></>}
