import { useState } from 'react';
import { supabase } from '../lib/supabase';
import { getStaffConsentLedger, updateConsentReview, type ConsentRecord } from '../lib/consentLedger';
import type { StudentLookup } from '../lib/singleCourseEnrollment';
import '../styles/legal-consent.css';

const yesNo = (value: boolean) => value ? 'Yes' : 'No';
export function ConsentLedgerPage() {
  const [email, setEmail] = useState(''); const [student, setStudent] = useState<StudentLookup | null>(null); const [record, setRecord] = useState<ConsentRecord | null>(null);
  const [note, setNote] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function lookup() { setError(''); setMessage(''); setStudent(null); setRecord(null); setNote(''); const value = email.trim().toLowerCase(); if (!value) return setError('Enter a student email before looking up consent.'); if (!supabase) return setError('Supabase is not configured.'); setBusy(true); try { const { data, error: lookupError } = await supabase.from('profiles').select('id,display_name,email,role').ilike('email', value).eq('role', 'student').maybeSingle(); if (lookupError) throw lookupError; if (!data) return setError('student_missing: No existing student profile was found for that email.'); const found = data as StudentLookup; const entries = await getStaffConsentLedger(found.id); setStudent(found); setRecord(entries[0] || null); setNote(entries[0]?.internal_note || ''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load consent.'); } finally { setBusy(false); } }
  async function review(status: 'needs_review' | 'revoked') { if (!record) return; setBusy(true); setError(''); setMessage(''); try { await updateConsentReview(record.id, status, note); const entries = await getStaffConsentLedger(record.student_id); setRecord(entries[0] || null); setMessage(`Consent marked ${status.replace('_', ' ')}. Course access was not changed.`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update consent review.'); } finally { setBusy(false); } }
  return <div className="consent-page"><header className="page-hero"><div><div className="eyebrow">Staff operations</div><h1 className="page-title">Student Consent Ledger</h1><p className="muted">Consent review does not grant or remove course access. Review with legal counsel before public launch and finalize all policy placeholders.</p></div></header>{(error || message) && <div className={error ? 'admin-message error' : 'admin-message'} role="status">{error || message}</div>}
    <section className="card card-pad consent-lookup"><label>Student email<div className="email-lookup"><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="student@example.com"/><button type="button" className="button button-secondary" disabled={busy} onClick={() => void lookup()}>{busy ? 'Loading…' : 'Look up'}</button></div></label>{student && <p>Student: <strong>{student.display_name || 'No display name'}</strong> · {student.email}</p>}</section>
    {student && !record && <section className="card card-pad"><h2>No consent record</h2><p className="muted">This student has not submitted the JPAC launch consent form.</p></section>}
    {record && <div className="consent-ledger-grid"><section className="card card-pad"><div className="consent-record-heading"><div><div className="eyebrow">{record.consent_version}</div><h2>{record.student_name || student?.display_name}</h2></div><span className={`consent-status status-${record.consent_status}`}>{record.consent_status.replace('_', ' ')}</span></div><dl className="consent-details"><ConsentFact label="Under 13" value={yesNo(record.under_13)}/><ConsentFact label="Age confirmed" value={yesNo(record.student_age_confirmed)}/><ConsentFact label="Terms" value={yesNo(record.terms_accepted)}/><ConsentFact label="Privacy" value={yesNo(record.privacy_acknowledged)}/><ConsentFact label="Children’s privacy" value={yesNo(record.children_privacy_acknowledged)}/><ConsentFact label="Acceptable use" value={yesNo(record.acceptable_use_accepted)}/><ConsentFact label="Refund policy" value={yesNo(record.refund_policy_acknowledged)}/><ConsentFact label="AI policy" value={yesNo(record.ai_usage_acknowledged)}/><ConsentFact label="Internal learning media" value={yesNo(record.internal_learning_media_consent)}/><ConsentFact label="Promotional media (optional)" value={yesNo(record.promotional_media_consent)}/><ConsentFact label="Parent/guardian consent" value={yesNo(record.parent_guardian_consent)}/><ConsentFact label="Signed" value={record.signed_at ? new Date(record.signed_at).toLocaleString() : 'Not complete'}/></dl><p><strong>Signer:</strong> {record.signed_by_name || 'Not provided'} · {record.signed_by_relationship || 'Relationship not provided'}</p><p><strong>Guardian:</strong> {record.guardian_name || 'Not provided'} · {record.guardian_email || 'No email'}</p></section>
      <aside className="card card-pad consent-review"><h2>Staff review</h2><p className="muted">Use only for compliance review. These actions do not change enrollment or payment records.</p><label>Internal note<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Visible to staff only"/></label><div className="review-actions"><button className="button button-secondary" type="button" disabled={busy} onClick={() => void review('needs_review')}>Mark needs review</button><button className="button button-secondary danger" type="button" disabled={busy} onClick={() => void review('revoked')}>Mark revoked</button></div></aside></div>}
  </div>;
}
function ConsentFact({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
