import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';
import { enrollmentAction, grantSingleCourseEnrollment, type PublishedCourse, type PurchaseType, type StudentLookup } from '../lib/singleCourseEnrollment';
import '../styles/course-enrollment-manager.css';

type Admission = { first:string; last:string; phone:string; type:'adult'|'minor'; experience:string; source:string; course:string; guardianName:string; guardianEmail:string; guardianPhone:string; relationship:string; notes:string };
type Payment = { method:string; status:string; amount:string; date:string; purchase:string; course:string; reference:string; visible:string; internal:string };
const methods=['wix_online','cash','in_person_card','check','scholarship','comped','manual_approval','other']; const statuses=['verified','pending','waived','refunded','cancelled','failed'];
const emptyAdmission:Admission={first:'',last:'',phone:'',type:'adult',experience:'online',source:'admin',course:'',guardianName:'',guardianEmail:'',guardianPhone:'',relationship:'guardian',notes:''};
const emptyPayment:Payment={method:'wix_online',status:'verified',amount:'',date:new Date().toISOString().slice(0,10),purchase:'first_course_purchase',course:'',reference:'',visible:'',internal:''};
const Field=({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean})=><label className={wide?'wide':''}>{label}{children}</label>;

export function CourseEnrollmentManagerPage(){
 const [email,setEmail]=useState(''),[student,setStudent]=useState<StudentLookup|null>(null),[missing,setMissing]=useState(false),[courses,setCourses]=useState<PublishedCourse[]>([]),[courseId,setCourseId]=useState('');
 const [purchase,setPurchase]=useState<PurchaseType>('first_course_purchase'),[verified,setVerified]=useState(false),[notes,setNotes]=useState(''),[admission,setAdmission]=useState(emptyAdmission),[payment,setPayment]=useState(emptyPayment); const [message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ledger,setLedger]=useState<'not recorded'|'recorded'|'unavailable'>('not recorded'),[copied,setCopied]=useState({welcome:false,consent:false});
 useEffect(()=>{void (async()=>{if(!supabase)return;const {data,error:e}=await supabase.from('courses').select('id,title,status').eq('status','published').order('title');if(e)setError(e.message);else setCourses((data as PublishedCourse[])||[])})()},[]);
 const setA=(key:keyof Admission,value:string)=>setAdmission(v=>({...v,[key]:value})); const setP=(key:keyof Payment,value:string)=>setPayment(v=>({...v,[key]:value}));
 async function lookup(){setError('');setMessage('');setStudent(null);setMissing(false);const value=email.trim().toLowerCase();if(!value)return setError('Enter a student email address.');if(!supabase)return setError('Supabase is not configured.');const {data,error:e}=await supabase.from('profiles').select('id,display_name,email,role,created_at').eq('email',value).eq('role','student').maybeSingle();if(e)setError(e.message);else if(data)setStudent(data as StudentLookup);else{setMissing(true);setA('first','');}}
 async function createAdmission(){if(!supabase)return;if(!admission.first.trim()||!admission.last.trim())return setError('First name and last name are required.');if(admission.type==='minor'&&!admission.guardianName.trim())return setError('Guardian name is required for a minor.');setBusy(true);try{const {data,error:e}=await supabase.rpc('manual_student_create',{student_first_name:admission.first,student_last_name:admission.last,student_email:email.trim().toLowerCase(),student_phone:admission.phone||null,target_course:admission.course||null,enrollment_notes:`Student type: ${admission.type}; experience: ${admission.experience}; source: ${admission.source}. ${admission.notes}`,guardian_full_name:admission.type==='minor'?admission.guardianName:null,guardian_email_address:admission.type==='minor'?admission.guardianEmail:null,guardian_phone_number:admission.type==='minor'?admission.guardianPhone:null,guardian_relationship_type:admission.relationship});if(e)throw e;setMessage(`Admissions record created. Login activation is still required before the student can access the app. (${String(data).slice(0,8)})`)}catch(e){setError(e instanceof Error?e.message:'Unable to create admissions record.')}finally{setBusy(false)}}
 async function savePayment(){if(!supabase||!student)return;setBusy(true);try{const {error:e}=await supabase.rpc('jpac_staff_upsert_payment_ledger_entry_v1',{student_id:student.id,payment_method:payment.method,payment_status:payment.status,amount:payment.amount?Number(payment.amount):null,payment_date:payment.date||null,purchase_type:payment.purchase,course_id:payment.course||courseId||null,reference_number:payment.reference||null,student_visible_note:payment.visible||null,internal_note:payment.internal||null});if(e)throw e;setLedger('recorded');setMessage('Payment ledger recorded. Course access was not granted automatically.')}catch(e){setLedger('unavailable');setError(`Payment ledger capability unavailable: ${e instanceof Error?e.message:'RPC not available'}`)}finally{setBusy(false)}}
 async function grant(){setError('');if(!student)return setError('Look up an existing student profile first.');if(!courseId)return setError('Select exactly one published course.');if(!verified)return setError('Payment verification is required before submission.');setBusy(true);try{const r=await grantSingleCourseEnrollment({learnerEmail:email,courseId,paymentVerified:verified,purchaseType:purchase,notes});setMessage(`${enrollmentAction(r.status)}${r.message?` — ${r.message}`:''}.`)}catch(e){setError(e instanceof Error?e.message:'Unable to grant enrollment.')}finally{setBusy(false)}}
 async function copy(kind:'welcome'|'consent'){const text=kind==='welcome'?`Welcome to JPAC Academy. Please log in at https://jpac-academy.vercel.app, complete Policies & Parent Consent, then open My Academy to begin your assigned course. Contact JPAC staff if you need help accessing your course.${admission.type==='minor'?' A parent or guardian should review and complete the consent information before the student begins coursework.':''}`:'Please log in at https://jpac-academy.vercel.app and complete Policies & Parent Consent before beginning coursework.';await navigator.clipboard?.writeText(text);setCopied(v=>({...v,[kind]:true}))}
 const checks=useMemo(()=>[{x:'Student account/profile confirmed',d:!!student},{x:'Parent/guardian info captured, if minor',d:admission.type==='adult'||!!admission.guardianName},{x:'Consent completed or pending',d:!!student},{x:'Payment verified',d:verified},{x:'Course access granted',d:false},{x:'Payment ledger recorded',d:ledger==='recorded'},{x:'Welcome instructions copied',d:copied.welcome}], [student,admission,verified,ledger,copied.welcome]); const status=!student?'Needs login activation':!verified?'Needs payment verification':ledger!=='recorded'?'Needs payment ledger record':'Needs course access';
 return <div className="course-enrollment-page"><header className="page-hero"><div><div className="eyebrow">Staff operations · guided workspace</div><h1 className="page-title">Enrollment Manager</h1><p className="muted">Complete the operational enrollment path in one place. Wix may support website and payment verification; JPAC Academy is the learning platform.</p></div><div className="status-card"><span>Current status</span><strong>{status}</strong></div></header>{(error||message)&&<div className={error?'admin-message error':'admin-message'} role="status">{error||message}</div>}<div className="workspace-grid"><main className="workspace-main">
 <section className="card card-pad"><div className="eyebrow">1 · Student setup</div><h2>Find or set up a student</h2><div className="email-lookup"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="student@example.com"/><button className="button button-secondary" onClick={()=>void lookup()}>Look up</button></div>{student&&<div className="lookup-result success"><strong>Profile confirmed</strong><span>{student.display_name||'Name unavailable'} · {student.email} · role: {student.role}</span><small>Enrollment history is managed below.</small></div>}{missing&&<div className="lookup-result warning"><strong>Student account/profile not found</strong><span>Account activation required. No login-ready account exists.</span></div>}</section>
 {missing&&<section className="card card-pad"><div className="eyebrow">Admissions intake</div><h2>Create admissions record</h2><p className="muted">Uses <code>manual_student_create</code>. No auth user, password, or invitation is created.</p><div className="form-grid"><Field label="First name"><input value={admission.first} onChange={e=>setA('first',e.target.value)}/></Field><Field label="Last name"><input value={admission.last} onChange={e=>setA('last',e.target.value)}/></Field><Field label="Phone"><input value={admission.phone} onChange={e=>setA('phone',e.target.value)}/></Field><Field label="Student type"><select value={admission.type} onChange={e=>setA('type',e.target.value)}><option value="adult">Adult</option><option value="minor">Minor</option></select></Field><Field label="Academy experience"><select value={admission.experience} onChange={e=>setA('experience',e.target.value)}><option>online</option><option>campus</option><option>hybrid</option></select></Field><Field label="Enrollment source"><select value={admission.source} onChange={e=>setA('source',e.target.value)}><option>admin</option><option>wix</option><option>campus</option><option>import</option><option>cash/in-person</option></select></Field><Field label="Intended course"><select value={admission.course} onChange={e=>setA('course',e.target.value)}><option value="">Assign later</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></Field>{admission.type==='minor'&&<><Field label="Guardian name"><input value={admission.guardianName} onChange={e=>setA('guardianName',e.target.value)}/></Field><Field label="Guardian email"><input value={admission.guardianEmail} onChange={e=>setA('guardianEmail',e.target.value)}/></Field><Field label="Guardian phone"><input value={admission.guardianPhone} onChange={e=>setA('guardianPhone',e.target.value)}/></Field><Field label="Relationship"><input value={admission.relationship} onChange={e=>setA('relationship',e.target.value)}/></Field></>}<Field label="Notes" wide><textarea value={admission.notes} onChange={e=>setA('notes',e.target.value)}/></Field></div><button className="button button-primary" disabled={busy} onClick={()=>void createAdmission()}>Create admissions record</button></section>}
 {student&&<><section className="card card-pad"><div className="eyebrow">2 · Consent</div><h2>Student/parent consent</h2><div className="inline-status warning"><strong>Pending / unavailable</strong><span>Consent should be completed before the student begins coursework. Staff completion is not enabled.</span></div><button className="button button-secondary" onClick={()=>void copy('consent')}>{copied.consent?'Copied':'Copy consent instruction'}</button></section>
 <section className="card card-pad"><div className="eyebrow">3 · Payment ledger</div><h2>Record payment</h2><p className="muted">Explicit save only; this never grants course access automatically.</p><div className="form-grid"><Field label="Payment method"><select value={payment.method} onChange={e=>setP('method',e.target.value)}>{methods.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Payment status"><select value={payment.status} onChange={e=>setP('status',e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Amount"><input type="number" min="0" step=".01" value={payment.amount} onChange={e=>setP('amount',e.target.value)}/></Field><Field label="Payment date"><input type="date" value={payment.date} onChange={e=>setP('date',e.target.value)}/></Field><Field label="Course"><select value={payment.course} onChange={e=>setP('course',e.target.value)}><option value="">Same as access selection</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></Field><Field label="Purchase type"><select value={payment.purchase} onChange={e=>setP('purchase',e.target.value)}><option>first_course_purchase</option><option>additional_course_purchase</option></select></Field><Field label="Reference number"><input value={payment.reference} onChange={e=>setP('reference',e.target.value)}/></Field><Field label="Student-visible note"><input value={payment.visible} onChange={e=>setP('visible',e.target.value)}/></Field><Field label="Internal note" wide><textarea value={payment.internal} onChange={e=>setP('internal',e.target.value)}/></Field></div><button className="button button-primary" disabled={busy} onClick={()=>void savePayment()}>Save payment ledger</button></section>
 <section className="card card-pad"><div className="eyebrow">4 · Course access</div><h2>Grant one course</h2><Field label="Published course"><select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Select one course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></Field><fieldset><legend>Purchase type</legend><label className="radio"><input type="radio" checked={purchase==='first_course_purchase'} onChange={()=>setPurchase('first_course_purchase')}/> First course purchase</label><label className="radio"><input type="radio" checked={purchase==='additional_course_purchase'} onChange={()=>setPurchase('additional_course_purchase')}/> Additional course purchase</label></fieldset><label className="payment-confirm"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/> Payment verified <small>Required</small></label><Field label="Staff note"><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></Field><button className="button button-primary" disabled={busy||!courseId||!verified} onClick={()=>void grant()}>Grant course access</button><p className="muted">Uses the unchanged single-course enrollment RPC with duplicate active-enrollment protection.</p></section>
 <section className="card card-pad"><div className="eyebrow">5 · Welcome</div><h2>Welcome instructions</h2><p>Copy the student/guardian-aware message after the operational steps are complete.</p><button className="button button-secondary" onClick={()=>void copy('welcome')}>{copied.welcome?'Welcome message copied':'Copy welcome instructions'}</button></section></>}
 </main><aside className="card card-pad checklist"><div className="eyebrow">Enrollment workspace</div><h2>Launch checklist</h2>{checks.map(c=><div className={c.d?'check done':'check'} key={c.x}><span>{c.d?'✓':'○'}</span>{c.x}</div>)}<div className="checklist-note"><strong>{status}</strong><span>{student?'Consent follow-up may still be needed.':'Look up a student to begin.'}</span></div><p className="muted">Standalone staff invitation endpoint: not found. No password or direct auth.users write is performed.</p></aside></div></div>;
}
