import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';

type PricingRow={family_id:string;household_name:string|null;guardian_name:string|null;guardian_email:string;guardian_phone:string|null;student_id:string;student_name:string|null;student_email:string|null;billing_order:number;course_title:string;base_amount:number;discount_amount:number;final_amount:number;pricing_source:string;override_reason:string|null};
type Config={base_monthly_amount:number;discount_type:'percent'|'fixed';second_child_discount:number;additional_child_discount:number;active:boolean;notes:string|null};
const monthStart=(value:string)=>`${value}-01`;
const currentMonth=()=>new Date().toISOString().slice(0,7);
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value||0));

export function FamilyBillingPage(){
 const[month,setMonth]=useState(currentMonth());const[rows,setRows]=useState<PricingRow[]>([]);const[config,setConfig]=useState<Config>({base_monthly_amount:29.99,discount_type:'percent',second_child_discount:10,additional_child_discount:15,active:true,notes:''});const[message,setMessage]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[overrideDrafts,setOverrideDrafts]=useState<Record<string,{amount:string;reason:string}>>({});
 async function load(){if(!supabase)return;setLoading(true);setError('');const target=monthStart(month);const[{data:cfg,error:cfgError},{data:overview,error:overviewError}]=await Promise.all([supabase.from('family_discount_months').select('base_monthly_amount,discount_type,second_child_discount,additional_child_discount,active,notes').eq('month_start',target).maybeSingle(),supabase.rpc('jpac_family_billing_overview',{target_month:target})]);if(cfgError)setError(cfgError.message);else if(cfg)setConfig(cfg as Config);else setConfig({base_monthly_amount:29.99,discount_type:'percent',second_child_discount:10,additional_child_discount:15,active:true,notes:''});if(overviewError)setError(current=>current||overviewError.message);setRows((overview as PricingRow[]|null)||[]);setLoading(false)}
 useEffect(()=>{void load()},[month]);
 const families=useMemo(()=>{const map=new Map<string,PricingRow[]>();rows.forEach(row=>map.set(row.family_id,[...(map.get(row.family_id)||[]),row]));return[...map.entries()].map(([id,students])=>({id,students:students.sort((a,b)=>a.billing_order-b.billing_order)}))},[rows]);
 async function saveConfig(){if(!supabase)return;setBusy(true);setError('');setMessage('');const{error:e}=await supabase.rpc('jpac_upsert_family_discount_month',{target_month:monthStart(month),base_amount:Number(config.base_monthly_amount),target_discount_type:config.discount_type,second_discount:Number(config.second_child_discount),additional_discount:Number(config.additional_child_discount),target_notes:config.notes||null,target_active:config.active});setBusy(false);if(e)setError(e.message);else{setMessage('Monthly family pricing saved. Existing families have been recalculated for this month.');await load()}}
 async function changeOrder(row:PricingRow,value:number){if(!supabase)return;const{error:e}=await supabase.rpc('jpac_set_family_billing_order',{target_family:row.family_id,target_student:row.student_id,target_order:value});if(e)setError(e.message);else await load()}
 async function saveOverride(row:PricingRow){if(!supabase)return;const draft=overrideDrafts[row.student_id];const amount=Number(draft?.amount);if(!draft?.amount||!Number.isFinite(amount)||amount<0){setError('Enter a valid final monthly price for the override.');return}setBusy(true);const{error:e}=await supabase.rpc('jpac_set_family_pricing_override',{target_month:monthStart(month),target_family:row.family_id,target_student:row.student_id,target_amount:amount,target_reason:draft.reason||null});setBusy(false);if(e)setError(e.message);else{setMessage(`Pricing override saved for ${row.student_name||'student'}.`);await load()}}
 async function clearOverride(row:PricingRow){if(!supabase)return;setBusy(true);const{error:e}=await supabase.rpc('jpac_clear_family_pricing_override',{target_month:monthStart(month),target_student:row.student_id});setBusy(false);if(e)setError(e.message);else{setMessage(`Pricing override cleared for ${row.student_name||'student'}.`);await load()}}
 return <div><header className="page-hero"><div><div className="eyebrow">Admin billing controls</div><h1 className="page-title">Family & Sibling Pricing</h1><p className="muted">Families can enroll multiple children in different JPAC programs while administrators control sibling pricing month by month.</p></div></header>{(message||error)&&<div className={error?'admin-message error':'admin-message'}>{error||message}</div>}
 <section className="card ops-panel" style={{marginBottom:22}}><div className="section-head"><div><div className="eyebrow">Monthly pricing policy</div><h2>Set {new Date(`${month}-01T12:00:00`).toLocaleDateString(undefined,{month:'long',year:'numeric'})} rates</h2><p className="muted">Child 1 pays the base tuition. Child 2 and each additional child receive the configured sibling discount unless an admin override is applied.</p></div><label>Billing month<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div><div className="wizard-form"><label>Base monthly tuition<input type="number" min="0" step="0.01" value={config.base_monthly_amount} onChange={e=>setConfig(v=>({...v,base_monthly_amount:Number(e.target.value)}))}/></label><label>Discount method<select value={config.discount_type} onChange={e=>setConfig(v=>({...v,discount_type:e.target.value as Config['discount_type']}))}><option value="percent">Percentage off</option><option value="fixed">Fixed dollar amount off</option></select></label><label>Second child discount<input type="number" min="0" step="0.01" value={config.second_child_discount} onChange={e=>setConfig(v=>({...v,second_child_discount:Number(e.target.value)}))}/><small>{config.discount_type==='percent'?'Percent off':'Dollars off'}</small></label><label>Additional child discount<input type="number" min="0" step="0.01" value={config.additional_child_discount} onChange={e=>setConfig(v=>({...v,additional_child_discount:Number(e.target.value)}))}/><small>Applies to child 3 and beyond.</small></label><label className="wide">Admin notes<textarea value={config.notes||''} onChange={e=>setConfig(v=>({...v,notes:e.target.value}))} placeholder="Optional reason for this month's pricing"/></label></div><button className="button button-primary" disabled={busy} onClick={()=>void saveConfig()}>{busy?'Saving…':'Save monthly pricing'}</button></section>
 <section><div className="section-head"><div><div className="eyebrow">Family accounts</div><h2>Household pricing preview</h2><p className="muted">Children are grouped automatically by guardian email. Each child keeps a separate course enrollment and student profile.</p></div></div>{loading?<p className="muted">Loading family pricing…</p>:families.length===0?<div className="card card-pad"><p className="muted">No multi-student family records have been created yet. Families will be grouped automatically when students share the same guardian email.</p></div>:families.map(family=>{const first=family.students[0];return <article className="card ops-panel" key={family.id} style={{marginBottom:18}}><div className="section-head"><div><div className="eyebrow">Family account</div><h2>{first.household_name||first.guardian_name||first.guardian_email}</h2><p className="muted">{first.guardian_email}{first.guardian_phone?` · ${first.guardian_phone}`:''}</p></div><strong>{family.students.length} child{family.students.length===1?'':'ren'}</strong></div><div className="ops-feed">{family.students.map(row=>{const draft=overrideDrafts[row.student_id]||{amount:'',reason:''};return <article key={row.student_id} style={{alignItems:'flex-start'}}><span>🎓</span><div style={{flex:1}}><strong>{row.student_name||row.student_email||'Student'} · {row.course_title}</strong><small>Base {money(row.base_amount)} · Discount {money(row.discount_amount)} · <b>Final {money(row.final_amount)}</b> · {row.pricing_source}</small>{row.override_reason&&<small>Override reason: {row.override_reason}</small>}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10,alignItems:'end'}}><label>Family billing order<select value={row.billing_order} onChange={e=>void changeOrder(row,Number(e.target.value))}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>Child {n}</option>)}</select></label><label>Override final price<input type="number" min="0" step="0.01" value={draft.amount} onChange={e=>setOverrideDrafts(v=>({...v,[row.student_id]:{...draft,amount:e.target.value}}))} placeholder={String(row.final_amount)}/></label><label>Reason<input value={draft.reason} onChange={e=>setOverrideDrafts(v=>({...v,[row.student_id]:{...draft,reason:e.target.value}}))} placeholder="Optional"/></label><button className="button button-secondary" disabled={busy} onClick={()=>void saveOverride(row)}>Apply override</button>{row.pricing_source==='Admin override'&&<button className="button button-secondary" disabled={busy} onClick={()=>void clearOverride(row)}>Clear override</button>}</div></div></article>})}</div></article>})}</section>
 </div>
}
