import{useEffect,useMemo,useRef,useState}from'react';
import{Link,useLocation,useParams}from'react-router-dom';
import{loadCourseContent,type CourseModule}from'../lib/studentAccess';
import{supabase}from'../lib/supabase';
import{useAuth}from'../context/AuthContext';
import{AriaFeedback,LearnSection,LevelUpCard,MasteryChecklist,MissionBrief,MissionProgress,PracticeChallenge,SubmissionHistory,WatchSection,type MissionActivity,type MissionAttempt,type MissionCompletion}from'../components/MissionExperience';
import'../styles/student-assignment-flow.css';

type CourseRecord={id:string;title:string};
type BonusAward={source_id:string|null;amount:number};
type VideoProgress={watched_seconds:number;duration_seconds:number;percent_watched:number;completed_at:string|null};
const MEGABYTE=1024*1024;
const evidenceRules={audio:{accept:'audio/*',label:'audio',maximumBytes:50*MEGABYTE,maximumLabel:'50 MB',mimeTypes:['audio/mpeg','audio/mp4','audio/x-m4a','audio/wav','audio/wave'] as readonly string[]},video:{accept:'video/*',label:'video',maximumBytes:250*MEGABYTE,maximumLabel:'250 MB',mimeTypes:['video/mp4','video/quicktime','video/webm'] as readonly string[]}} as const;
const matchesDataTitle=(activity:MissionActivity,data?:Record<string,string>)=>Boolean(data?.title&&activity.title.toLowerCase().includes(data.title.toLowerCase()));
const evidenceRule=(activity:MissionActivity)=>activity.submission_type==='video'?evidenceRules.video:evidenceRules.audio;
const validateEvidence=(activity:MissionActivity,selected:File)=>{const rule=evidenceRule(activity);if(!rule.mimeTypes.includes(selected.type))return`Choose a supported ${rule.label} recording. This challenge accepts ${rule.label} evidence only.`;if(selected.size>rule.maximumBytes)return`This recording is too large. The maximum ${rule.label} file size is ${rule.maximumLabel}. Please use a shorter or compressed recording.`;return''};

export function ModulePage(){
  const{courseId='',moduleId=''}=useParams();const location=useLocation();const{user}=useAuth();
  const[course,setCourse]=useState<CourseRecord|null>(null);const[module,setModule]=useState<CourseModule|null>(null);const[courseModules,setCourseModules]=useState<CourseModule[]>([]);const[lessons,setLessons]=useState<Awaited<ReturnType<typeof loadCourseContent>>['lessons']>([]);const[progress,setProgress]=useState<Awaited<ReturnType<typeof loadCourseContent>>['progress']>([]);const[activities,setActivities]=useState<MissionActivity[]>([]);const[completion,setCompletion]=useState<MissionCompletion|null>(null);const[videoProgress,setVideoProgress]=useState<VideoProgress|null>(null);const[attempts,setAttempts]=useState<MissionAttempt[]>([]);const[bonusAwards,setBonusAwards]=useState<BonusAward[]>([]);const[file,setFile]=useState<File|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const lastVideoSecond=useRef(-10);

  async function load(){
    setLoading(true);const result=await loadCourseContent(courseId);const selected=result.modules.find(item=>item.id===moduleId)||null;
    setCourse(result.course as CourseRecord|null);setModule(selected);setCourseModules(result.modules);setLessons(selected?result.lessons.filter(item=>item.module_id===selected.id):[]);setProgress(result.progress);setActivities([]);setCompletion(null);setVideoProgress(null);setAttempts([]);setBonusAwards([]);
    if(result.error||!selected||!supabase||!user){setMessage(result.error||(!selected?'This mission is locked, unavailable, or outside your enrolled course.':''));setLoading(false);return}
    const[activityResult,completionResult,bonusResult,videoProgressResult]=await Promise.all([
      supabase.from('activities').select('id,title,description,instructions,activity_type,submission_type,xp_reward,xp_type,required,passing_score,rubric').eq('module_id',selected.id).eq('status','published'),
      supabase.rpc('jpac_module_completion',{target_student:user.id,target_module:selected.id}),
      supabase.from('xp_ledger').select('source_id,amount').eq('student_id',user.id).eq('module_id',selected.id).eq('xp_type','bonus'),
      supabase.from('module_video_progress').select('watched_seconds,duration_seconds,percent_watched,completed_at').eq('student_id',user.id).eq('module_id',selected.id).maybeSingle(),
    ]);
    const activityRows=(activityResult.data as MissionActivity[]|null)||[];setActivities(activityRows);setCompletion(Array.isArray(completionResult.data)?(completionResult.data[0]as MissionCompletion||null):null);setBonusAwards((bonusResult.data as BonusAward[]|null)||[]);setVideoProgress((videoProgressResult.data as VideoProgress|null)||null);
    let historyError='';if(activityRows.length){const historyResult=await supabase.from('submissions').select('id,activity_id,attempt_number,status,score,teacher_feedback,submitted_at,reviewed_at,xp_awarded,rubric_assessment').eq('student_id',user.id).in('activity_id',activityRows.map(item=>item.id)).order('attempt_number',{ascending:false});setAttempts((historyResult.data as MissionAttempt[]|null)||[]);historyError=historyResult.error?.message||''}
    setMessage(activityResult.error?.message||completionResult.error?.message||bonusResult.error?.message||videoProgressResult.error?.message||historyError);setLoading(false);
  }
  useEffect(()=>{void load()},[courseId,moduleId,user?.id]);

  const requiredActivity=activities.find(activity=>activity.required)||null;
  const optionalActivities=activities.filter(activity=>!activity.required&&activity.xp_type==='bonus');
  const labActivity=optionalActivities.find(activity=>/^jpac\b/i.test(activity.title)||matchesDataTitle(activity,module?.jpac_tool_activity))||null;
  const realWorldActivity=optionalActivities.find(activity=>activity.id!==labActivity?.id&&(/^real[- ]world\b/i.test(activity.title)||matchesDataTitle(activity,module?.real_world_activity)))||optionalActivities.find(activity=>activity.id!==labActivity?.id)||null;
  const otherPractice=optionalActivities.filter(activity=>activity.id!==labActivity?.id&&activity.id!==realWorldActivity?.id);
  const bonusEarned=bonusAwards.reduce((sum,row)=>sum+Number(row.amount||0),0);const awardedSources=new Set(bonusAwards.map(row=>row.source_id).filter(Boolean));
  const bonusAvailable=optionalActivities.length?optionalActivities.reduce((sum,item)=>sum+Number(item.xp_reward||0),0):Number(module?.bonus_xp_available||0);
  const requiredAttempts=requiredActivity?attempts.filter(item=>item.activity_id===requiredActivity.id):[];const latestAttempt=requiredAttempts[0]||null;const latestAssessed=requiredAttempts.find(item=>item.score!==null)||null;const hasRevision=latestAttempt?.status==='revision_requested';
  useEffect(()=>{if(!loading&&location.hash==='#core-challenge'&&requiredActivity){requestAnimationFrame(()=>{const target=document.getElementById('core-challenge');target?.focus({preventScroll:true});target?.scrollIntoView({behavior:'smooth',block:'start'})})}},[loading,location.hash,requiredActivity?.id]);
  const nextModule=useMemo(()=>{if(!module)return null;return courseModules.filter(item=>item.sort_order>module.sort_order).sort((a,b)=>a.sort_order-b.sort_order)[0]||null},[courseModules,module]);

  async function completeIntro(){if(!supabase)return;setBusy(true);const{data,error}=await supabase.rpc('jpac_complete_module_intro',{target_module:moduleId});setBusy(false);setMessage(error?.message||(Number(data)>0?'Mission started. 50 Core XP earned.':'Mission intro was already complete; no duplicate Core XP was awarded.'));if(!error)await load()}
  async function trackVideo(event:React.SyntheticEvent<HTMLVideoElement>){if(!supabase)return;const video=event.currentTarget;if(video.paused||document.visibilityState!=='visible'||!Number.isFinite(video.duration)||video.duration<=0)return;const watched=Math.floor(video.currentTime);if(watched<lastVideoSecond.current)lastVideoSecond.current=watched-5;if(watched-lastVideoSecond.current<5)return;lastVideoSecond.current=watched;const{data,error}=await supabase.rpc('jpac_record_module_video_progress',{target_module:moduleId,watched,duration:Math.floor(video.duration)});if(error){setMessage(error.message);return}const creditedPercent=Number(data||0);setCompletion(current=>current?{...current,video_percent:creditedPercent}:current);setVideoProgress(current=>({watched_seconds:Math.floor((Number(module?.video_duration_seconds||video.duration)*creditedPercent)/100),duration_seconds:Number(module?.video_duration_seconds||video.duration),percent_watched:creditedPercent,completed_at:creditedPercent>=90?(current?.completed_at||new Date().toISOString()):null}));if(creditedPercent>=90&&Number(completion?.video_percent||0)<90)await load()}
  function chooseEvidence(activity:MissionActivity,selected:File|null,input:HTMLInputElement){setMessage('');if(!selected){setFile(null);return}const validationError=validateEvidence(activity,selected);if(validationError){setFile(null);input.value='';setMessage(validationError);return}setFile(selected)}
  async function submit(activity:MissionActivity){if(!supabase||!user||!file)return;const validationError=validateEvidence(activity,file);if(validationError){setFile(null);setMessage(validationError);return}setBusy(true);setMessage('Uploading your private creative submission…');const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${user.id}/${crypto.randomUUID()}-${safe}`;const{error:uploadError}=await supabase.storage.from('performance-submissions').upload(path,file,{contentType:file.type,upsert:false});if(uploadError){setBusy(false);setMessage(uploadError.message);return}const{error}=await supabase.rpc('jpac_submit_module_activity',{target_activity:activity.id,file_name:file.name,file_type:file.type,storage_path:path});if(error){const{error:cleanupError}=await supabase.storage.from('performance-submissions').remove([path]);setBusy(false);setMessage(cleanupError?`${error.message} The unused upload could not be removed; contact JPAC support.`:error.message);return}setBusy(false);setMessage('Creative submission received for assessment.');setFile(null);await load()}
  async function completePractice(activity:MissionActivity){if(!supabase)return;setBusy(true);const{data,error}=await supabase.rpc('jpac_complete_bonus_activity',{target_activity:activity.id});setBusy(false);setMessage(error?.message||(Number(data)>0?`Practice complete. ${data} Bonus XP awarded.`:'Practice was already recorded; no duplicate Bonus XP was awarded.'));if(!error)await load()}

  if(loading)return <div className="card card-pad">Loading mission…</div>;
  if(!course||!module)return <section className="card card-pad locked-course"><span>🔒</span><h1>Mission locked</h1><p>{message||'Complete the previous mission requirements to unlock this creative session.'}</p><Link className="button button-secondary" to={`/courses/${courseId}`}>Return to course</Link></section>;
  return <div className="creator-mission"><Link className="text-link" to={`/courses/${course.id}`}>← {course.title}</Link>
    <div className="eyebrow">Level {module.level_number||1} · Mission {module.level_module_number||module.sort_order}</div>
    <MissionProgress completion={completion} lessons={lessons} progress={progress} bonusEarned={bonusEarned} bonusAvailable={bonusAvailable} hasRevision={hasRevision}/>
    <MissionBrief module={module} requiredActivity={requiredActivity} bonusAvailable={bonusAvailable} onStart={()=>void completeIntro()} busy={busy} started={Boolean(completion?.intro_complete)}/>
    <LearnSection courseId={course.id} lessons={lessons} progress={progress}/>
    <WatchSection videoUrl={module.primary_video_url} title={module.video_title} provider={module.video_provider} durationSeconds={module.video_duration_seconds} watchedSeconds={Number(videoProgress?.watched_seconds||0)} percent={Number(videoProgress?.percent_watched??completion?.video_percent??0)} onTimeUpdate={trackVideo}/>
    <div className="mission-practice-grid"><PracticeChallenge kind="practice" activity={realWorldActivity} moduleData={module.real_world_activity} busy={busy} earned={Boolean(realWorldActivity&&awardedSources.has(realWorldActivity.id))} onComplete={activity=>void completePractice(activity)}/><PracticeChallenge kind="lab" activity={labActivity} moduleData={module.jpac_tool_activity} busy={busy} earned={Boolean(labActivity&&awardedSources.has(labActivity.id))} onComplete={activity=>void completePractice(activity)}/>{otherPractice.map(activity=><PracticeChallenge key={activity.id} kind="practice" activity={activity} busy={busy} earned={awardedSources.has(activity.id)} onComplete={item=>void completePractice(item)}/>)}</div>
    {requiredActivity&&<section className="mission-card creative-challenge" id="core-challenge" tabIndex={-1}><div className="creative-challenge-head"><div><div className="mission-section-label">Core Challenge · Assignment</div><h2>{requiredActivity.title}</h2></div><strong>{requiredActivity.xp_reward} Core XP</strong></div><div className="challenge-policy"><span><small>Submission type</small><strong>{evidenceRule(requiredActivity).label}</strong></span><span><small>Maximum file size</small><strong>{evidenceRule(requiredActivity).maximumLabel}</strong></span><span><small>Passing score</small><strong>{requiredActivity.passing_score}%</strong></span><span><small>Previous attempts</small><strong>{requiredAttempts.length}</strong></span><span><small>Current status</small><strong>{latestAttempt?latestAttempt.status.replaceAll('_',' '):'Not submitted'}</strong></span></div><p>{requiredActivity.description}</p><div className="challenge-instructions"><strong>Assignment instructions</strong><p>{requiredActivity.instructions}</p></div>{requiredAttempts.length?<SubmissionHistory attempts={requiredAttempts}/>:<p className="submission-status">No previous attempts. Your first submission will be preserved as attempt 1.</p>}<label className="practice-drop"><input type="file" accept={evidenceRule(requiredActivity).accept} onChange={event=>chooseEvidence(requiredActivity,event.target.files?.[0]||null,event.currentTarget)}/><strong>{file?.name||`Choose a ${evidenceRule(requiredActivity).label} take`}</strong><small>{file?`${Math.max(.01,file.size/MEGABYTE).toFixed(2)} MB · selected and ready to upload`:`Maximum ${evidenceRule(requiredActivity).maximumLabel}. Your file remains private and previous attempts are never overwritten.`}</small></label><button className="button button-primary" disabled={!file||busy} onClick={()=>void submit(requiredActivity)}>{busy?'Uploading…':requiredAttempts.length?`Submit attempt ${Math.max(...requiredAttempts.map(item=>item.attempt_number))+1}`:'Submit creative challenge'}</button></section>}
    {!requiredActivity&&!message&&<section className="mission-card"><div className="mission-section-label">Core Challenge</div><h2>Assignment unavailable</h2><p className="muted">No published Core Challenge is currently available for this unlocked module. Please contact JPAC Academy support.</p></section>}
    <AriaFeedback attempt={latestAssessed}/>
    <MasteryChecklist completion={completion}/>
    <LevelUpCard completion={completion} bonusEarned={bonusEarned} nextModule={nextModule} courseId={course.id} currentLevel={module.level_number}/>
    {message&&<div className="auth-message" role="status">{message}</div>}
  </div>
}
