import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { getMyConsentStatus, submitStudentConsent, type ConsentForm, type ConsentRecord } from '../lib/consentLedger';
import '../styles/legal-consent.css';

const emptyForm = (): ConsentForm => ({ guardianName: '', guardianEmail: '', birthdate: '', ageConfirmed: false, termsAccepted: false, privacyAcknowledged: false, childrenPrivacyAcknowledged: false, acceptableUseAccepted: false, refundPolicyAcknowledged: false, internalLearningMediaConsent: false, promotionalMediaConsent: false, aiUsageAcknowledged: false, parentGuardianConsent: false, signedByName: '', signedByRelationship: 'parent', studentVisibleNote: '' });
function formFromRecord(record: ConsentRecord): ConsentForm { return { guardianName: record.guardian_name || '', guardianEmail: record.guardian_email || '', birthdate: record.student_birthdate || '', ageConfirmed: record.student_age_confirmed, termsAccepted: record.terms_accepted, privacyAcknowledged: record.privacy_acknowledged, childrenPrivacyAcknowledged: record.children_privacy_acknowledged, acceptableUseAccepted: record.acceptable_use_accepted, refundPolicyAcknowledged: record.refund_policy_acknowledged, internalLearningMediaConsent: record.internal_learning_media_consent, promotionalMediaConsent: record.promotional_media_consent, aiUsageAcknowledged: record.ai_usage_acknowledged, parentGuardianConsent: record.parent_guardian_consent, signedByName: record.signed_by_name || '', signedByRelationship: record.signed_by_relationship || 'parent', studentVisibleNote: record.student_visible_note || '' }; }

export function StudentConsentPage() {
  const [form, setForm] = useState<ConsentForm>(emptyForm); const [record, setRecord] = useState<ConsentRecord | null>(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const age = useMemo(() => { if (!form.birthdate) return null; const birth = new Date(`${form.birthdate}T12:00:00`); const now = new Date(); let years = now.getFullYear() - birth.getFullYear(); if (now < new Date(now.getFullYear(), birth.getMonth(), birth.getDate())) years -= 1; return years; }, [form.birthdate]);
  const minor = age !== null && age < 18; const under13 = age !== null && age < 13;
  const update = <K extends keyof ConsentForm>(key: K, value: ConsentForm[K]) => setForm((current) => ({ ...current, [key]: value }));
  useEffect(() => { void getMyConsentStatus().then((found) => { setRecord(found); if (found) setForm(formFromRecord(found)); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load consent status.')).finally(() => setLoading(false)); }, []);

  async function submit() { setError(''); setMessage(''); if (!form.birthdate) return setError('Enter the student birthdate.'); if (!form.ageConfirmed) return setError('Confirm that the student birthdate is accurate.'); if (minor && (!form.guardianName.trim() || !form.guardianEmail.trim())) return setError('Guardian name and email are required for a minor.'); if (minor && !form.parentGuardianConsent) return setError('Parent or guardian consent is required for a minor.'); if (!form.signedByName.trim()) return setError('Enter the signer’s full name.'); setBusy(true); try { const result = await submitStudentConsent(form); setMessage(result?.consent_status === 'complete' ? 'Consent complete. Thank you.' : 'Consent saved as incomplete. Review all required acknowledgments.'); const latest = await getMyConsentStatus(); setRecord(latest); if (latest) setForm(formFromRecord(latest)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save consent.'); } finally { setBusy(false); } }

  if (loading) return <section className="card card-pad"><p className="muted">Loading consent status…</p></section>;
  return <div className="consent-page"><header className="page-hero"><div><div className="eyebrow">Account</div><h1 className="page-title">Policies &amp; Parent Consent</h1><p className="muted">Before using JPAC Academy, students and parents/guardians must review and acknowledge required policies. Promotional media permission is optional and separate from course participation.</p></div><span className={`consent-status status-${record?.consent_status || 'incomplete'}`}>{(record?.consent_status || 'incomplete').replace('_', ' ')}</span></header>{(error || message) && <div className={error ? 'admin-message error' : 'admin-message'} role="status">{error || message}</div>}
    <section className="card card-pad consent-form"><h2>Student and signer information</h2><div className="consent-fields"><label>Student birthdate<input type="date" required value={form.birthdate} onChange={(event) => update('birthdate', event.target.value)}/></label><label>Signed by full name<input required value={form.signedByName} onChange={(event) => update('signedByName', event.target.value)}/></label><label>Signer relationship<select value={form.signedByRelationship} onChange={(event) => update('signedByRelationship', event.target.value)}><option value="parent">Parent</option><option value="guardian">Guardian</option><option value="self">Self (adult student)</option></select></label><label>Guardian name<input required={minor} value={form.guardianName} onChange={(event) => update('guardianName', event.target.value)}/></label><label>Guardian email<input type="email" required={minor} value={form.guardianEmail} onChange={(event) => update('guardianEmail', event.target.value)}/></label></div><label className="consent-check"><input type="checkbox" checked={form.ageConfirmed} onChange={(event) => update('ageConfirmed', event.target.checked)}/><span>I confirm the student birthdate is accurate.{age !== null ? ` Current age: ${age}.` : ''}</span></label></section>
    <section className="card card-pad consent-form"><h2>Required acknowledgments</h2><ConsentCheck checked={form.termsAccepted} onChange={(value) => update('termsAccepted', value)} label="I accept the Terms of Service." to="/legal/terms"/><ConsentCheck checked={form.privacyAcknowledged} onChange={(value) => update('privacyAcknowledged', value)} label="I acknowledge the Privacy Policy." to="/legal/privacy"/><ConsentCheck checked={form.acceptableUseAccepted} onChange={(value) => update('acceptableUseAccepted', value)} label="I accept the Acceptable Use Policy." to="/legal/acceptable-use"/><ConsentCheck checked={form.refundPolicyAcknowledged} onChange={(value) => update('refundPolicyAcknowledged', value)} label="I acknowledge the Refund & Course Access Policy." to="/legal/refund-policy"/><ConsentCheck checked={form.aiUsageAcknowledged} onChange={(value) => update('aiUsageAcknowledged', value)} label="I acknowledge the AI Usage Policy." to="/legal/ai-policy"/><ConsentCheck checked={form.internalLearningMediaConsent} onChange={(value) => update('internalLearningMediaConsent', value)} label="I consent to internal learning use of student media when needed for assignments, feedback, portfolios, reviews, and showcase preparation." to="/legal/media-release"/>{under13 && <ConsentCheck checked={form.childrenPrivacyAcknowledged} onChange={(value) => update('childrenPrivacyAcknowledged', value)} label="I acknowledge the Children’s Privacy / COPPA Notice for this under-13 student." to="/legal/children-privacy"/>}{minor && <ConsentCheck checked={form.parentGuardianConsent} onChange={(value) => update('parentGuardianConsent', value)} label="I am the student’s parent or legal guardian and consent to the required participation and information practices."/>}</section>
    <section className="card card-pad consent-form optional-consent"><h2>Optional promotional media permission</h2><p className="muted">This is not required for course participation.</p><ConsentCheck checked={form.promotionalMediaConsent} onChange={(value) => update('promotionalMediaConsent', value)} label="I give optional permission for approved student media or testimonials to be used in JPAC websites, flyers, social media, ads, showcases, and promotional materials." to="/legal/media-release"/><label>Note for JPAC staff<textarea value={form.studentVisibleNote} onChange={(event) => update('studentVisibleNote', event.target.value)} placeholder="Optional question or context"/></label></section>
    <button className="button button-primary consent-submit" type="button" disabled={busy} onClick={() => void submit()}>{busy ? 'Saving…' : record ? 'Update consent' : 'Submit consent'}</button>
  </div>;
}

function ConsentCheck({ checked, onChange, label, to }: { checked: boolean; onChange: (value: boolean) => void; label: string; to?: string }) { return <label className="consent-check"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)}/><span>{label} {to && <Link to={to} target="_blank" rel="noreferrer">Read policy</Link>}</span></label>; }
