import{useEffect,useMemo,useState}from'react';
import{Link}from'react-router-dom';
import{supabase}from'../lib/supabase';
import{useAuth}from'../context/AuthContext';
import{WorkspaceHero}from'../components/WorkspaceHero';
import{MetricCard,AriaInsightCard,EmptyState,QuickActionGrid,SkeletonCards}from'../components/CreativeComponents';

type Student={id:string;display_name:string;email:string|null;total_xp:number};
type Enrollment={id:string;student_id:string;course_id:string;progress:number;status:string;courses:{title:string}|{title:string}[]|null;profiles:{display_name:string}|{display_name:string}[]|null};
type RubricCriterion={name:string;weight:number};
type RubricAssessment={schema_version:number;rubric:{criteria?:unknown};criterion_scores:Array<RubricCriterion&{score:number;weighted_contribution:number}>;calculated_score:number;passing_score:number;result:'approved'|'revision_requested'};
type RelatedLabel={id:string;title:string};
type ActivityContext={id:string;title:string;xp_reward:number;submission_type:string;passing_score:number;rubric:{criteria?:unknown};course:RelatedLabel|RelatedLabel[]|null;module:RelatedLabel|RelatedLabel[]|null};
type Submission={id:string;student_id:string;status:string;score:number|null;teacher_feedback:string|null;submitted_at:string;reviewed_at:string|null;attempt_number:number;media_type:string|null;rubric_assessment:RubricAssessment|null;activity:ActivityContext|ActivityContext[]|null;profiles:{display_name:string}|{display_name:string}[]|null};
type MediaAccess={submissionId:string;mediaType:'audio'|'video';signedUrl:string;expiresIn:number};

const one=<T,>(value:T|T[]|null|undefined):T|null=>Array.isArray(value)?value[0]||null:value||null;
const normalizeCriteria=(rubric:ActivityContext['rubric']|null|undefined):RubricCriterion[]=>{
  const source=rubric&&typeof rubric==='object'&&Array.isArray(rubric.criteria)?rubric.criteria:[];
  return source.flatMap(item=>{
    if(!item||typeof item!=='object')return[];
    const row=item as Record<string,unknown>;const name=String(row.name||'').trim();const weight=Number(row.weight);
    return name&&Number.isFinite(weight)&&weight>0?[{name,weight}]:[];
  });
};

export function TeacherPage(){
  const{profile}=useAuth();
  const[students,setStudents]=useState<Student[]>([]);const[enrollments,setEnrollments]=useState<Enrollment[]>([]);const[submissions,setSubmissions]=useState<Submission[]>([]);
  const[selectedCourse,setSelectedCourse]=useState('all');const[selected,setSelected]=useState('');const[selectedReview,setSelectedReview]=useState('');
  const[criterionScores,setCriterionScores]=useState<Record<string,string>>({});const[feedback,setFeedback]=useState('');const[media,setMedia]=useState<MediaAccess|null>(null);
  const[mediaBusy,setMediaBusy]=useState(false);const[reviewBusy,setReviewBusy]=useState(false);const[message,setMessage]=useState('');const[loading,setLoading]=useState(true);const[guardianLinked,setGuardianLinked]=useState(false);

  async function load(){
    if(!supabase)return;setLoading(true);
    const[{data:studentData,error:studentError},{data:enrollmentData,error:enrollmentError},{data:submissionData,error:submissionError}]=await Promise.all([
      supabase.from('profiles').select('id,display_name,email,total_xp').eq('role','student').order('display_name'),
      supabase.from('enrollments').select('id,student_id,course_id,progress,status,courses(title),profiles!enrollments_student_id_fkey(display_name)').order('created_at',{ascending:false}),
      supabase.from('submissions').select('id,student_id,status,score,teacher_feedback,submitted_at,reviewed_at,attempt_number,media_type,rubric_assessment,activity:activities(id,title,xp_reward,submission_type,passing_score,rubric,course:courses(id,title),module:course_modules(id,title)),profiles!submissions_student_id_fkey(display_name)').order('submitted_at',{ascending:false})
    ]);
    setMessage((studentError||enrollmentError||submissionError)?.message||'');
    const studentRows=(studentData as Student[])||[];setStudents(studentRows);setEnrollments((enrollmentData as unknown as Enrollment[])||[]);setSubmissions((submissionData as unknown as Submission[])||[]);
    if(!selected&&studentRows[0])setSelected(studentRows[0].id);setLoading(false);
  }
  useEffect(()=>{void load()},[]);
  useEffect(()=>{async function loadGuardian(){if(!supabase||!selected){setGuardianLinked(false);return}const{count,error}=await supabase.from('parent_relationships').select('id',{count:'exact',head:true}).eq('student_id',selected).in('invite_status',['invited','accepted']);setGuardianLinked(!error&&Boolean(count))}void loadGuardian()},[selected]);

  const classes=useMemo(()=>{const map=new Map<string,string>();enrollments.forEach(item=>map.set(item.course_id,one(item.courses)?.title||'JPAC Course'));return[...map.entries()].map(([id,title])=>({id,title}))},[enrollments]);
  const classEnrollments=useMemo(()=>selectedCourse==='all'?enrollments:enrollments.filter(item=>item.course_id===selectedCourse),[enrollments,selectedCourse]);
  const classStudentIds=useMemo(()=>new Set(classEnrollments.map(item=>item.student_id)),[classEnrollments]);
  const classStudents=useMemo(()=>selectedCourse==='all'?students:students.filter(item=>classStudentIds.has(item.id)),[students,selectedCourse,classStudentIds]);
  const selectedStudent=students.find(item=>item.id===selected)||null;
  const studentEnrollments=classEnrollments.filter(item=>item.student_id===selected);
  const studentSubmissions=submissions.filter(item=>item.student_id===selected&&(selectedCourse==='all'||one(one(item.activity)?.course)?.id===selectedCourse));
  const pending=submissions.filter(item=>['submitted','under_review'].includes(item.status)&&classStudentIds.has(item.student_id));
  const average=Math.round(classEnrollments.reduce((sum,item)=>sum+Number(item.progress||0),0)/Math.max(classEnrollments.length,1));
  const needsAttention=classEnrollments.filter(item=>Number(item.progress||0)<40).length;const readyToAdvance=classEnrollments.filter(item=>Number(item.progress||0)>=80).length;
  const inactiveStudents=classStudents.filter(student=>!submissions.some(item=>item.student_id===student.id)).length;
  const reviewedScores=submissions.filter(item=>typeof item.score==='number').map(item=>Number(item.score));const averageScore=reviewedScores.length?Math.round(reviewedScores.reduce((sum,value)=>sum+value,0)/reviewedScores.length):0;
  const selectedProgress=studentEnrollments.length?Math.round(studentEnrollments.reduce((sum,item)=>sum+Number(item.progress||0),0)/studentEnrollments.length):0;
  const selectedReviews=studentSubmissions.filter(item=>item.status==='approved').length;
  const attentionSignals=useMemo(()=>classStudents.map(student=>{const rows=classEnrollments.filter(item=>item.student_id===student.id);const progress=rows.length?Math.round(rows.reduce((sum,item)=>sum+Number(item.progress||0),0)/rows.length):0;const work=submissions.filter(item=>item.student_id===student.id);const pendingCount=work.filter(item=>['submitted','under_review'].includes(item.status)).length;const status=progress<40?'Needs encouragement':progress>=80?'Ready to advance':pendingCount?'Review waiting':'Steady progress';const icon=progress<40?'💜':progress>=80?'🚀':pendingCount?'📝':'✨';return{student,progress,pendingCount,status,icon}}).sort((a,b)=>{const rank=(item:{status:string})=>item.status==='Needs encouragement'?0:item.status==='Ready to advance'?1:item.status==='Review waiting'?2:3;return rank(a)-rank(b)}).slice(0,6),[classStudents,classEnrollments,submissions]);

  const reviewSubmission=studentSubmissions.find(item=>item.id===selectedReview)||null;
  const reviewActivity=one(reviewSubmission?.activity);const rubricCriteria=normalizeCriteria(reviewSubmission?.rubric_assessment?.rubric||reviewActivity?.rubric);
  const assessmentLocked=Boolean(reviewSubmission?.rubric_assessment||reviewSubmission?.reviewed_at);
  const rubricValid=rubricCriteria.length>0&&Math.abs(rubricCriteria.reduce((sum,item)=>sum+item.weight,0)-100)<.001;
  const allScoresPresent=rubricValid&&rubricCriteria.every(item=>criterionScores[item.name]!==''&&Number.isFinite(Number(criterionScores[item.name]))&&Number(criterionScores[item.name])>=0&&Number(criterionScores[item.name])<=100);
  const calculatedScore=allScoresPresent?Math.round(rubricCriteria.reduce((sum,item)=>sum+Number(criterionScores[item.name])*item.weight/100,0)*100)/100:null;
  const expectedResult=calculatedScore===null?null:calculatedScore>=Number(reviewActivity?.passing_score||0)?'Pass':'Needs Revision';

  function chooseCourse(id:string){setSelectedCourse(id);const first=id==='all'?students[0]:students.find(student=>enrollments.some(item=>item.course_id===id&&item.student_id===student.id));setSelected(first?.id||'');closeReview()}
  function chooseStudent(id:string){setSelected(id);closeReview()}
  function closeReview(){setSelectedReview('');setCriterionScores({});setFeedback('');setMedia(null)}
  function openReview(submission:Submission){
    setSelectedReview(submission.id);setMedia(null);setFeedback(submission.teacher_feedback||'');
    const stored=submission.rubric_assessment?.criterion_scores||[];const initial:Record<string,string>={};normalizeCriteria(submission.rubric_assessment?.rubric||one(submission.activity)?.rubric).forEach(item=>{initial[item.name]=String(stored.find(score=>score.name===item.name)?.score??'')});setCriterionScores(initial);
  }
  async function loadMedia(submissionId:string){
    if(!supabase)return;setMediaBusy(true);setMessage('');const{data}=await supabase.auth.getSession();
    const response=await fetch('/api/submission-media',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session?.access_token||''}`},body:JSON.stringify({submissionId})});
    const result=await response.json();setMediaBusy(false);if(!response.ok){setMessage(result.error||'Unable to open private submission evidence.');return}setMedia(result as MediaAccess);
  }
  async function assess(){
    if(!supabase||!reviewSubmission||!allScoresPresent)return;setReviewBusy(true);setMessage('');
    const criterion_scores=rubricCriteria.map(item=>({name:item.name,score:Number(criterionScores[item.name])}));
    const{error}=await supabase.rpc('jpac_assess_module_submission',{submission_target:reviewSubmission.id,criterion_scores,review_feedback:feedback});
    setReviewBusy(false);setMessage(error?.message||`Assessment complete: ${expectedResult}.`);if(!error){closeReview();await load()}
  }
  async function awardPracticeXp(){if(!supabase||!selected||!profile||!['admin','developer'].includes(profile.role))return;const{error}=await supabase.rpc('admin_award_xp',{target_student:selected,xp_amount:250,xp_reason:'Administrative practice recognition'});setMessage(error?.message||'250 XP awarded for practice.');if(!error)await load()}

  if(!profile||!['teacher','admin','developer'].includes(profile.role))return <div className="card card-pad"><h2>Teacher access required</h2></div>;
  if(loading)return <SkeletonCards count={5}/>;
  return <div className="teacher-experience">
    <WorkspaceHero eyebrow="Pilot assessment · Teacher Intelligence" title="Teacher Studio" description="Review private student evidence against the canonical activity rubric, then let the Academy apply approval, XP, and mastery rules." environment="classroom" ariaLabel="ARIA teaching intelligence" ariaMessage={needsAttention?`${needsAttention} enrollment${needsAttention===1?' needs':'s need'} encouragement.`:pending.length?`${pending.length} submission${pending.length===1?' is':'s are'} ready for evidence review.`:'Your current class view is stable.'} actions={<><button className="button button-primary" onClick={()=>void load()}>Refresh classroom</button><Link className="button button-secondary" to="/curriculum">Open curriculum</Link></>} stats={[{icon:'🎓',value:classStudents.length,label:'Students'},{icon:'💜',value:needsAttention,label:'Need encouragement'},{icon:'📝',value:pending.length,label:'Reviews waiting'}]}/>
    {message&&<div className="admin-message" role="status">{message}</div>}
    <section><div className="eyebrow">Same dashboard for every class</div><div className="teacher-class-switcher"><button className={selectedCourse==='all'?'active':''} onClick={()=>chooseCourse('all')}><strong>All Classes</strong><small>{students.length} students</small></button>{classes.map(course=><button key={course.id} className={selectedCourse===course.id?'active':''} onClick={()=>chooseCourse(course.id)}><strong>{course.title}</strong><small>{enrollments.filter(item=>item.course_id===course.id).length} students</small></button>)}</div></section>
    <div className="teacher-intelligence-strip"><article className="teacher-intelligence-card"><span>💜</span><strong>{needsAttention}</strong><small>Need encouragement</small></article><article className="teacher-intelligence-card"><span>🚀</span><strong>{readyToAdvance}</strong><small>Ready to advance</small></article><article className="teacher-intelligence-card"><span>📝</span><strong>{pending.length}</strong><small>Reviews waiting</small></article><article className="teacher-intelligence-card"><span>⭐</span><strong>{averageScore||'—'}</strong><small>Average reviewed score</small></article></div>
    <div className="teacher-intelligence-grid"><section className="card teacher-dashboard-card"><div className="section-head"><div><div className="eyebrow">ARIA student signals</div><h2>Who needs your attention now</h2></div></div>{attentionSignals.length?<div className="teacher-signal-list">{attentionSignals.map(item=><button key={item.student.id} className="teacher-signal" onClick={()=>chooseStudent(item.student.id)}><span>{item.icon}</span><div><strong>{item.student.display_name}</strong><small>{item.progress}% progress · {item.pendingCount} pending review{item.pendingCount===1?'':'s'}</small></div><b>{item.status}</b></button>)}</div>:<EmptyState icon="✨" title="No student signals yet." detail="Student enrollments and submissions will populate teaching priorities."/>}</section><aside className="card teacher-dashboard-card"><div className="eyebrow">Teaching recommendations</div><h2>Next best actions</h2><div className="teacher-recommendations"><article><span>Encouragement priority</span><p>{needsAttention?`Choose one of the ${needsAttention} low-progress enrollments and assign a short, confidence-building practice step.`:'No low-progress enrollments are visible in this class.'}</p></article><article><span>Assessment priority</span><p>{pending.length?`Inspect the evidence and complete ${pending.length} canonical rubric review${pending.length===1?'':'s'}.`:'No submissions are currently awaiting review.'}</p></article><article><span>Engagement priority</span><p>{inactiveStudents?`${inactiveStudents} student${inactiveStudents===1?' has':'s have'} no submission history.`:'Every visible student has submission activity.'}</p></article></div></aside></div>
    <div className="grid grid-4"><MetricCard icon="👩🏽‍🎓" value={classStudents.length} label="Class roster" detail="Students in this view"/><MetricCard icon="📝" value={pending.length} label="Awaiting review" detail="Newest work first" tone="warning"/><MetricCard icon="📈" value={`${average}%`} label="Average progress" detail="Across active enrollments" tone="gold"/><MetricCard icon="💜" value={needsAttention} label="Need attention" detail="Below 40% progress" tone="purple"/></div>
    <div className="teacher-dashboard-grid"><section className="card teacher-dashboard-card"><div className="section-head"><div><div className="eyebrow">Class roster</div><h2>Select a student</h2></div></div>{classStudents.length?<div className="teacher-student-list">{classStudents.map(student=>{const enrollment=classEnrollments.find(item=>item.student_id===student.id);return <button className={`teacher-student-row ${selected===student.id?'active':''}`} key={student.id} onClick={()=>chooseStudent(student.id)}><span className="avatar">{student.display_name.split(' ').map(part=>part[0]).join('').slice(0,2)}</span><span><strong>{student.display_name}</strong><small>{student.total_xp.toLocaleString()} XP · {one(enrollment?.courses)?.title||'No course selected'}</small></span><b>{Math.round(Number(enrollment?.progress||0))}%</b></button>})}</div>:<EmptyState icon="🎓" title="No students in this class yet." detail="Wix-linked enrollments will populate this reusable class dashboard."/>}</section><aside className="card teacher-dashboard-card"><div className="eyebrow">Fast teaching flow</div><h2>What needs attention</h2><div className="teacher-focus"><article><strong>{pending.length} reviews waiting</strong><span>Open evidence and complete the canonical rubric.</span></article><article><strong>{needsAttention} students below 40%</strong><span>Open My Growth for intervention guidance.</span></article><article><strong>{readyToAdvance} nearing completion</strong><span>Review performance evidence and remaining mastery requirements.</span></article></div><AriaInsightCard compact message="Choose a class, select a student, inspect evidence, then assess the exact attempt."/></aside></div>
    {selectedStudent&&<section className="card teacher-dashboard-card"><div className="teacher-selected-header"><div><div className="eyebrow">Selected student</div><h2>{selectedStudent.display_name}</h2><p className="muted">{selectedStudent.email||'No email'} · {selectedStudent.total_xp.toLocaleString()} XP</p></div>{['admin','developer'].includes(profile.role)&&<button className="button button-secondary" onClick={()=>void awardPracticeXp()}>Award administrative practice XP</button>}</div><div className="progress-list">{studentEnrollments.length?studentEnrollments.map(item=><article key={item.id}><div><strong>{one(item.courses)?.title||'JPAC Course'}</strong><span>{item.status}</span></div><div className="progress-track"><i style={{width:`${Math.min(100,Number(item.progress||0))}%`}}/></div><b>{Math.round(Number(item.progress||0))}%</b></article>):<p className="muted">No enrollment in this class view.</p>}</div>
      <div className="teacher-submission-list">{studentSubmissions.length?studentSubmissions.map(item=>{const activity=one(item.activity);const assessment=item.rubric_assessment;return <article className={`teacher-review-card ${selectedReview===item.id?'active':''}`} key={item.id}><div><div className="teacher-review-meta"><span>{item.status.replaceAll('_',' ')}</span><span>Attempt {item.attempt_number}</span><span>{activity?.submission_type||item.media_type||'performance'}</span></div><h3>{activity?.title||'Creative submission'}</h3><p className="muted">{one(activity?.course)?.title||'Academy course'} · {one(activity?.module)?.title||'Course module'}</p><p className="muted">Submitted {new Date(item.submitted_at).toLocaleString()}</p>{assessment&&<p><strong>{assessment.calculated_score}% · {assessment.result==='approved'?'Pass':'Needs Revision'}</strong></p>}{item.teacher_feedback&&<p>Previous feedback: {item.teacher_feedback}</p>}</div><div className="teacher-review-actions"><button className="button button-secondary" onClick={()=>openReview(item)}>{assessment||item.reviewed_at?'View assessment':'Review evidence'}</button></div></article>}) : <div className="teacher-empty">No submissions for this student yet.</div>}</div>
      {reviewSubmission&&reviewActivity&&<section className="teacher-assessment"><header><div><div className="eyebrow">Canonical attempt assessment</div><h2>{reviewActivity.title}</h2><p>{selectedStudent.display_name} · Attempt {reviewSubmission.attempt_number} · {new Date(reviewSubmission.submitted_at).toLocaleString()}</p></div><button className="button button-secondary" onClick={closeReview}>Close</button></header><div className="teacher-assessment-context"><span><small>Course</small>{one(reviewActivity.course)?.title||'Academy course'}</span><span><small>Module</small>{one(reviewActivity.module)?.title||'Course module'}</span><span><small>Submission</small>{reviewActivity.submission_type}</span><span><small>Status</small>{reviewSubmission.status.replaceAll('_',' ')}</span></div>
        <section className="teacher-media-review"><div className="section-head"><div><h3>Private submission evidence</h3><p>Signed access expires after five minutes.</p></div>{!media&&<button className="button button-primary" disabled={mediaBusy} onClick={()=>void loadMedia(reviewSubmission.id)}>{mediaBusy?'Opening evidence…':'Open evidence'}</button>}</div>{media?.submissionId===reviewSubmission.id&&(media.mediaType==='audio'?<audio controls src={media.signedUrl}/>:<video controls playsInline src={media.signedUrl}/>)}</section>
        {!rubricValid?<div className="admin-message">This activity does not have a valid weighted canonical rubric. Assessment is blocked.</div>:<section className="teacher-rubric"><div className="teacher-rubric-head"><div><h3>Canonical rubric</h3><p>Score every criterion from 0 to 100. Weights and the passing threshold come from the activity.</p></div><strong>{rubricCriteria.reduce((sum,item)=>sum+item.weight,0)} total weight</strong></div><div className="teacher-rubric-labels"><span>Criterion</span><span>Weight</span><span>Teacher score (0–100)</span><span>Contribution</span></div>{rubricCriteria.map(criterion=>{const score=Number(criterionScores[criterion.name]);const contribution=criterionScores[criterion.name]!==''&&Number.isFinite(score)?Math.round(score*criterion.weight)/100:null;return <label className="teacher-rubric-row" key={criterion.name}><strong>{criterion.name}</strong><span>{criterion.weight}%</span><input aria-label={`${criterion.name} score from 0 to 100`} type="number" min="0" max="100" step="1" disabled={assessmentLocked} value={criterionScores[criterion.name]??''} onChange={event=>setCriterionScores(current=>({...current,[criterion.name]:event.target.value}))}/><b>{contribution===null?'—':contribution.toFixed(2)}</b></label>})}<div className="teacher-score-summary"><span><small>Calculated final score</small><strong>{calculatedScore===null?'—':`${calculatedScore.toFixed(2)}%`}</strong></span><span><small>Passing threshold</small><strong>{reviewSubmission.rubric_assessment?.passing_score??reviewActivity.passing_score}%</strong></span><span className={expectedResult==='Pass'?'pass':expectedResult?'revision':''}><small>Expected result</small><strong>{reviewSubmission.rubric_assessment?(reviewSubmission.rubric_assessment.result==='approved'?'Pass':'Needs Revision'):(expectedResult||'Complete rubric')}</strong></span></div><label className="teacher-assessment-feedback">Teacher feedback<textarea disabled={assessmentLocked} value={feedback} onChange={event=>setFeedback(event.target.value)} placeholder="Associate feedback with this exact attempt."/></label>{assessmentLocked?<p className="teacher-assessment-locked">{reviewSubmission.rubric_assessment?'Assessment history is locked for this attempt. A revision requires a new student submission.':'This historical attempt already has an aggregate review and cannot be overwritten. Criterion evidence was not fabricated.'}</p>:<button className="button button-primary" disabled={!allScoresPresent||reviewBusy} onClick={()=>void assess()}>{reviewBusy?'Saving authoritative assessment…':`Complete assessment · ${expectedResult||'score every criterion'}`}</button>}</section>}
      </section>}
      {guardianLinked&&<section className="guardian-summary"><div className="eyebrow">Linked guardian summary</div><h3>Family progress view is available</h3><p>This summary appears only when the student has an active guardian relationship.</p><div className="guardian-summary-grid"><span><b>{selectedProgress}%</b><small>Course progress</small></span><span><b>{selectedReviews}</b><small>Approved submissions</small></span><span><b>{selectedStudent.total_xp.toLocaleString()}</b><small>Creative XP</small></span></div></section>}
    </section>}
    <section className="card teacher-dashboard-card"><div className="eyebrow">Quick actions</div><h2>One-click teacher tools</h2><QuickActionGrid items={[{icon:'🧬',label:'Student Growth',detail:'Open Digital Twin insights',to:'/student-intelligence',tone:'purple'},{icon:'📚',label:'Curriculum Studio',detail:'Prepare the next lesson',to:'/curriculum',tone:'gold'},{icon:'📜',label:'Certificates',detail:'Review student credentials',to:'/certificates',tone:'cyan'},{icon:'🎨',label:'JPAC LAB',detail:'Open creative practice tools',to:'/studio',tone:'success'}]}/></section>
  </div>
}
