import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ToolShell } from '../shared/ToolShell';
import { ExtraCreditPanel } from '../shared/ExtraCreditPanel';
import { LocalProjectPanel } from '../shared/LocalProjectPanel';
import { projectAsText, type LocalToolProject } from '../shared/projectStorage';
import { chordShapes, fretNumbers, guitarGoals, guitarHelpers, guitarSounds, guitarStrings, midiFrequency, midiLabel, type ChordName, type GuitarGoal, type GuitarSound } from './guitarTheory';

type ActiveVoice = { oscillator: OscillatorNode; modulators: OscillatorNode[]; gain: GainNode };
type GuitarSnapshot = { goal: GuitarGoal; sound: GuitarSound; selected_chord: ChordName; effects: string[]; recent_notes: string[]; notes_played: number; chords_strummed: number; chord_history: ChordName[] };

export function VirtualGuitarTool() {
  const [goal, setGoal] = useState<GuitarGoal>('Learn strings');
  const [sound, setSound] = useState<GuitarSound>('Clean Guitar'); const [selectedChord, setSelectedChord] = useState<ChordName>('G'); const [lastPlayed, setLastPlayed] = useState('Ready to play'); const [audioError, setAudioError] = useState('');
  const [effects, setEffects] = useState({ drive: false, chorus: false, delay: false }); const contextRef = useRef<AudioContext | null>(null); const voicesRef = useRef<ActiveVoice[]>([]); const strumTimersRef = useRef<number[]>([]);
  const [recentNotes, setRecentNotes] = useState<string[]>([]); const [notesPlayed, setNotesPlayed] = useState(0); const [chordsStrummed, setChordsStrummed] = useState(0); const [chordHistory, setChordHistory] = useState<ChordName[]>([]); const [soundChosen, setSoundChosen] = useState(false); const [chordChosen, setChordChosen] = useState(false); const [saved, setSaved] = useState(false);

  const stopAudio = useCallback(() => {
    strumTimersRef.current.forEach((timer) => window.clearTimeout(timer)); strumTimersRef.current = []; const now = contextRef.current?.currentTime || 0;
    voicesRef.current.forEach(({ oscillator, modulators, gain }) => { try { gain.gain.cancelScheduledValues(now); gain.gain.setTargetAtTime(0, now, .01); oscillator.stop(now + .08); modulators.forEach((item) => item.stop(now + .08)); } catch { /* voice already ended */ } }); voicesRef.current = []; setLastPlayed('Audio stopped');
  }, []);

  const playMidi = useCallback(async (midi: number, label = midiLabel(midi), trackNote = true) => {
    try {
      const AudioCtor = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioCtor) throw new Error('Web Audio is not supported by this browser.');
      const context = contextRef.current || new AudioCtor(); contextRef.current = context; if (context.state === 'suspended') await context.resume(); const now = context.currentTime;
      const oscillator = context.createOscillator(); const filter = context.createBiquadFilter(); const gain = context.createGain(); const modulators: OscillatorNode[] = [];
      oscillator.type = sound === 'Warm Acoustic' ? 'triangle' : sound === 'Bright Lead' ? 'sawtooth' : 'triangle'; oscillator.frequency.value = midiFrequency(midi); filter.type = 'lowpass'; filter.frequency.setValueAtTime(sound === 'Bright Lead' ? 4200 : sound === 'Warm Acoustic' ? 1700 : 2800, now); filter.frequency.exponentialRampToValueAtTime(650, now + 1.25); gain.gain.setValueAtTime(.0001, now); gain.gain.exponentialRampToValueAtTime(.2, now + .012); gain.gain.exponentialRampToValueAtTime(.0001, now + 1.45);
      oscillator.connect(filter).connect(gain); let output: AudioNode = gain;
      if (effects.drive) { const drive = context.createWaveShaper(); const curve = new Float32Array(256); for (let index = 0; index < curve.length; index += 1) { const x = index * 2 / 255 - 1; curve[index] = Math.tanh(2.8 * x); } drive.curve = curve; drive.oversample = '2x'; output.connect(drive); output = drive; }
      if (effects.chorus) { const chorus = context.createDelay(.05); chorus.delayTime.value = .018; const lfo = context.createOscillator(); const depth = context.createGain(); lfo.frequency.value = 1.7; depth.gain.value = .004; lfo.connect(depth).connect(chorus.delayTime); lfo.start(now); lfo.stop(now + 1.55); modulators.push(lfo); output.connect(chorus); output = chorus; }
      if (effects.delay) { const delay = context.createDelay(.5); const feedback = context.createGain(); delay.delayTime.value = .22; feedback.gain.value = .24; output.connect(delay); delay.connect(feedback).connect(delay); delay.connect(context.destination); }
      output.connect(context.destination); oscillator.start(now); oscillator.stop(now + 1.5); const voice = { oscillator, modulators, gain }; voicesRef.current.push(voice); oscillator.onended = () => { voicesRef.current = voicesRef.current.filter((item) => item !== voice); }; setLastPlayed(label); if (trackNote) { setRecentNotes((current) => [...current.slice(-9), label]); setNotesPlayed((value) => value + 1); } setAudioError('');
    } catch (error) { setAudioError(error instanceof Error ? error.message : 'Audio could not start. Tap a fret to try again.'); }
  }, [effects, sound]);

  function strumChord() { setChordsStrummed((value) => value + 1); setChordHistory((current) => [...current.slice(-5), selectedChord]); const shape = chordShapes[selectedChord]; shape.forEach((fret, stringIndex) => { if (fret === null) return; const timer = window.setTimeout(() => void playMidi(guitarStrings[stringIndex].midi + fret, `${selectedChord} chord`, false), stringIndex * 55); strumTimersRef.current.push(timer); }); }
  function reset() { stopAudio(); setSound('Clean Guitar'); setSelectedChord('G'); setEffects({ drive: false, chorus: false, delay: false }); setRecentNotes([]); setNotesPlayed(0); setChordsStrummed(0); setChordHistory([]); setSoundChosen(false); setChordChosen(false); setSaved(false); setAudioError(''); }
  useEffect(() => () => { strumTimersRef.current.forEach((timer) => window.clearTimeout(timer)); const context = contextRef.current; voicesRef.current.forEach(({ oscillator, modulators }) => { try { oscillator.stop(); modulators.forEach((item) => item.stop()); } catch { /* already stopped */ } }); if (context) void context.close(); contextRef.current = null; }, []);

  const activeEffects = useMemo(() => (Object.keys(effects) as (keyof typeof effects)[]).filter((effect) => effects[effect]), [effects]);
  const snapshot = useMemo<GuitarSnapshot>(() => ({ goal, sound, selected_chord: selectedChord, effects: activeEffects, recent_notes: recentNotes, notes_played: notesPlayed, chords_strummed: chordsStrummed, chord_history: chordHistory }), [activeEffects, chordHistory, chordsStrummed, goal, notesPlayed, recentNotes, selectedChord, sound]);
  const mission = [soundChosen, chordChosen, chordsStrummed >= 1, notesPlayed >= 2, new Set(chordHistory).size >= 2, saved];
  const missionLabels = ['Choose a guitar sound', 'Pick a chord', 'Strum the chord', 'Try two fret notes', 'Practice switching chords', 'Save your project locally'];
  const summary = projectAsText({ title: `${goal} guitar practice`, notes: 'Prepared from the current local session.', savedAt: new Date().toISOString(), data: snapshot }, 'Virtual Guitar');
  function loadProject(project: LocalToolProject<GuitarSnapshot>) { const data = project.data; if (guitarGoals.includes(data.goal)) setGoal(data.goal); if (guitarSounds.includes(data.sound)) setSound(data.sound); if (Object.hasOwn(chordShapes, data.selected_chord)) setSelectedChord(data.selected_chord); setEffects({ drive: data.effects.includes('drive'), chorus: data.effects.includes('chorus'), delay: data.effects.includes('delay') }); setRecentNotes(Array.isArray(data.recent_notes) ? data.recent_notes.slice(-10) : []); setNotesPlayed(Number(data.notes_played) || 0); setChordsStrummed(Number(data.chords_strummed) || 0); setChordHistory(Array.isArray(data.chord_history) ? data.chord_history.filter((item): item is ChordName => Object.hasOwn(chordShapes, item)).slice(-6) : []); setSoundChosen(true); setChordChosen(true); setSaved(true); setLastPlayed('Local project loaded'); }

  return <ToolShell title="Virtual Guitar / Instrument Studio" eyebrow="JPAC Creator Tool" description="Choose a sound, shape chords, build a riff, and save your practice idea locally.">
    <section className="premium-tool-panel virtual-guitar-tool instrument-lab guitar-lab">
      <div className="instrument-lab-intro"><div><span className="premium-kicker">Choose your creative goal</span><h2>What do you want to practice?</h2></div><div className="practice-goal-grid">{guitarGoals.map((item) => <button type="button" key={item} className={goal === item ? 'active' : ''} aria-pressed={goal === item} onClick={() => setGoal(item)}>{item}</button>)}</div></div>
      <section className="practice-mission"><header><div><span className="premium-kicker">Practice Mission</span><h2>{mission.filter(Boolean).length} of {mission.length} steps complete</h2></div><strong>{mission.every(Boolean) ? 'Mission complete! 🎸' : 'Build your sound'}</strong></header><ol>{missionLabels.map((label, index) => <li className={mission[index] ? 'complete' : ''} key={label}><span>{mission[index] ? '✓' : index + 1}</span>{label}</li>)}</ol></section>
      <div className="premium-control-grid guitar-controls"><label>Sound<select value={sound} onChange={(event) => { setSound(event.target.value as GuitarSound); setSoundChosen(true); }}>{guitarSounds.map((item) => <option key={item}>{item}</option>)}</select></label><div className="guitar-effect-group" role="group" aria-label="Guitar effects">{(['drive', 'chorus', 'delay'] as const).map((effect) => <button type="button" className={effects[effect] ? 'active' : ''} aria-pressed={effects[effect]} key={effect} onClick={() => setEffects((current) => ({ ...current, [effect]: !current[effect] }))}>{effect[0].toUpperCase() + effect.slice(1)}</button>)}</div><button type="button" className="button button-secondary" onClick={reset}>Stop / Reset audio</button></div>
      <div className="instrument-session-strip" aria-live="polite"><div><small>Last played</small><strong>{lastPlayed}</strong></div><div><small>Fret notes</small><strong>{notesPlayed}</strong></div><div><small>Chords</small><strong>{chordsStrummed}</strong></div><div><small>Sound</small><strong>{sound}</strong></div></div>{audioError ? <div className="premium-audio-error" role="alert">{audioError}</div> : null}
      <div className="guitar-fretboard-scroll"><div className="guitar-fretboard" role="group" aria-label="Six string, twelve fret virtual guitar"><div className="guitar-fret-header"><span>String</span>{fretNumbers.map((fret) => <b key={fret}>{fret === 0 ? 'Open' : fret}</b>)}</div>{guitarStrings.map((string, stringIndex) => <div className="guitar-string-row" key={`${string.name}-${stringIndex}`}><strong>{string.short}<small>{string.name}</small></strong>{fretNumbers.map((fret) => { const midi = string.midi + fret; return <button type="button" key={fret} aria-label={`${string.name} string, ${fret === 0 ? 'open' : `fret ${fret}`}, note ${midiLabel(midi)}`} onClick={() => void playMidi(midi)}><span /><i>{midiLabel(midi).replace(/\d/g, '')}</i></button>; })}</div>)}</div></div>
      <section className="guitar-chords"><div><span className="premium-kicker">Chord workshop</span><h2>Common chord shapes</h2><p>Select a chord, then strum all of its playable strings.</p></div><div className="guitar-chord-buttons" role="group" aria-label="Select a guitar chord">{(Object.keys(chordShapes) as ChordName[]).map((chord) => <button type="button" className={selectedChord === chord ? 'active' : ''} aria-pressed={selectedChord === chord} key={chord} onClick={() => { setSelectedChord(chord); setChordChosen(true); }}>{chord}</button>)}</div><button type="button" className="button button-primary" onClick={strumChord}>Strum {selectedChord}</button></section>
      <section className="session-pattern"><div><span className="premium-kicker">Session tracker</span><h2>{recentNotes.length ? recentNotes.join(' · ') : 'Tap fret notes to build a riff.'}</h2><p>{chordHistory.length ? `Chord switches: ${chordHistory.join(' → ')}` : 'Strum two different chords to practice switching.'}</p></div><button type="button" onClick={() => { setRecentNotes([]); setChordHistory([]); }}>Clear tracker</button></section>
      <div className="beginner-helper-grid">{guitarHelpers.map(([title, copy]) => <article key={title}><strong>{title}</strong><span>{copy}</span></article>)}</div>
      <div className="premium-learning-grid"><article><h2>How the fretboard works</h2><p>Each string starts on a different open note. Moving one fret toward the guitar body raises the pitch by one musical half step. The 12th fret repeats the open-string note one octave higher.</p></article><article><h2>Try this next</h2><p>Choose G, strum slowly, then play each highlighted chord tone one string at a time. Switch to C and listen for which notes move and which stay close.</p></article></div>
      <LocalProjectPanel toolType="virtual-guitar" toolLabel="Virtual Guitar" snapshot={snapshot} onLoad={loadProject} onSaved={() => setSaved(true)} />
      <ExtraCreditPanel summary={summary} />
    </section>
  </ToolShell>;
}
