import{useEffect,useState}from'react';import{supabase}from'../lib/supabase';
type Source={id:string;title:string;source_type:string;discipline:string|null;version:string;approval_status:string;file_format:string|null;file_size:number|null;processing_status:string;processing_error:string|null;created_at:string};
const types=['curriculum','teaching_standard','aria_standard','rubric_standard','practice_method','performance_standard','career_pathway','certificate_requirement','instructor_guidance','terminology','reference_material'];
async function token(){return(await supabase!.auth.getSession()).data.session?.access_token||''}
export function AriaKnowledgeLibrary({courseId,discipline}:{courseId?:string;discipline?:string}){
 const[sources,setSources]=useState<Source[]>([]);const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[file,setFile]=useState<File|null>(null);const[title,setTitle]=useState('');const[type,setType]=useState('curriculum');const[version,setVersion]=useState('1.0');const[level,setLevel]=useState('');
 async function load(){const response=await fetch('/api/curriculum-sources',{headers:{Authorization:`Bearer ${await token()}`}});const body=await response.json();if(response.ok)setSources(body.sources||[]);else setMessage(body.error||'Unable to load source library.')}
 useEffect(()=>{void load()},[]);
 async function upload(){if(!file||!title.trim())return;setBusy(true);setMessage('');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let index=0;index<bytes.length;index+=0x8000)binary+=String.fromCharCode(...bytes.subarray(index,index+0x8000));const format=(file.name.split('.').pop()||'').toLowerCase();const response=await fetch('/api/curriculum-sources',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({title,sourceType:type,version,format,fileName:file.name,contentBase64:btoa(binary),courseId,discipline,levelNumber:level||null})});const body=await response.json();setBusy(false);setMessage(response.ok?`Source processed into ${body.sectionCount} grounded sections.`:body.error||'Upload failed.');if(response.ok){setFile(null);setTitle('');await load()}}
 async function approve(id:string){setBusy(true);const response=await fetch('/api/curriculum-sources',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({id,approvalStatus:'approved'})});const body=await response.json();setBusy(false);setMessage(response.ok?'Source approved for ARIA retrieval.':body.error||'Approval failed.');if(response.ok)await load()}
 return <section className="ci-library"><button className="ci-library-toggle" onClick={()=>setOpen(value=>!value)}><span><b>ARIA Knowledge Library</b><small>{sources.filter(item=>item.approval_status==='approved'&&item.processing_status==='ready').length} approved sources ready</small></span><strong>{open?'Close':'Manage sources'}</strong></button>{open&&<div className="ci-library-body"><div className="ci-upload"><h3>Import trusted source</h3><p>PDF, DOCX, TXT, or Markdown · 10 MB maximum · administrator approval required before ARIA retrieval.</p><div><label>Source title<input value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Category<select value={type} onChange={event=>setType(event.target.value)}>{types.map(item=><option key={item} value={item}>{item.replaceAll('_',' ')}</option>)}</select></label><label>Version<input value={version} onChange={event=>setVersion(event.target.value)}/></label><label>Level<select value={level} onChange={event=>setLevel(event.target.value)}><option value="">All levels</option>{[1,2,3,4].map(item=><option key={item}>{item}</option>)}</select></label><label className="wide">Document<input type="file" accept=".pdf,.docx,.txt,.md,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,text/markdown" onChange={event=>setFile(event.target.files?.[0]||null)}/></label></div><button className="button button-primary" disabled={busy||!file||!title.trim()} onClick={()=>void upload()}>{busy?'Processing…':'Upload and process'}</button></div>{message&&<div className="admin-message">{message}</div>}<div className="ci-source-list">{sources.map(source=><article key={source.id}><div><span>{source.source_type.replaceAll('_',' ')}</span><b>{source.title}</b><small>v{source.version} · {source.file_format?.toUpperCase()||'Reference'} · {source.processing_status}</small>{source.processing_error&&<em>{source.processing_error}</em>}</div><aside><strong className={source.approval_status}>{source.approval_status}</strong>{source.processing_status==='ready'&&source.approval_status==='draft'&&<button disabled={busy} onClick={()=>void approve(source.id)}>Approve source</button>}</aside></article>)}</div></div>}</section>
}
