import{Link}from'react-router-dom';
import type{CareerMilestone,CareerMilestoneStatus,CareerPath,CareerPathStatus}from'../data/careerPaths';
const statusIcon:Record<CareerPathStatus|CareerMilestoneStatus,string>={'AVAILABLE NOW':'✦','PARTIAL PATH':'◐','COMING LATER':'◇','TEMPORARILY UNAVAILABLE':'!','UNDER REVIEW':'◌','COMPLETED':'✓','AVAILABLE':'✦'};
const classToken=(value:string)=>value.toLowerCase().replaceAll(' ','-');
export function CareerAvailabilityBadge({status}:{status:CareerPathStatus|CareerMilestoneStatus}){return <span className={`career-status career-status-${classToken(status)}`}><span aria-hidden="true">{statusIcon[status]}</span>{status}</span>}
export function CareerMilestoneMiniPath({milestones}:{milestones:CareerMilestone[]}){return <ol className="career-mini-path" aria-label="Five milestone preview">{milestones.map((item,index)=><li key={item.id} className={`career-mini-node is-${classToken(item.status)}`}><span aria-hidden="true">{index+1}</span><span className="career-sr-only">Milestone {index+1}: {item.title}, {item.status}</span></li>)}</ol>}
export function CareerPathCard({path}:{path:CareerPath}){return <article className={`career-path-card career-card-${classToken(path.status)}`}><div className="career-card-top"><span className="career-path-icon" aria-hidden="true">{path.icon}</span><CareerAvailabilityBadge status={path.status}/></div><div><p className="career-card-kicker">{path.category.replaceAll('-',' ')}</p><h2>{path.name}</h2><p>{path.outcome}</p></div><div className="career-program-chips" aria-label="Related JPAC programs">{path.relatedPrograms.map(program=><span key={program}>{program}</span>)}</div><CareerMilestoneMiniPath milestones={path.milestones}/><Link className="career-card-link" to={`/career-paths/${path.slug}`} aria-label={`Explore ${path.name}`}>{path.status==='COMING LATER'?'Preview journey':'Explore path'} <span aria-hidden="true">→</span></Link></article>}
export function CareerMilestoneRoute({milestones,selected,onSelect}:{milestones:CareerMilestone[];selected:string;onSelect:(milestone:CareerMilestone)=>void}){return <ol className="career-milestone-route" aria-label="Career milestones">{milestones.map((item,index)=><li key={item.id} className={`career-route-step is-${classToken(item.status)}`}><button type="button" className="career-milestone-node" aria-current={selected===item.id?'step':undefined} aria-expanded={selected===item.id} onClick={()=>onSelect(item)}><span className="career-node-number" aria-hidden="true">{index+1}</span><span className="career-node-copy"><small>Milestone {index+1}</small><strong>{item.title}</strong><CareerAvailabilityBadge status={item.status}/></span></button></li>)}</ol>}
export function CareerMilestonePanel({milestone}:{milestone:CareerMilestone}){return <section className="career-evidence-panel" aria-live="polite" aria-labelledby="career-evidence-title"><div><p className="career-card-kicker">Milestone evidence preview</p><h2 id="career-evidence-title">{milestone.title}</h2></div><CareerAvailabilityBadge status={milestone.status}/><p>{milestone.description}</p><dl><div><dt>Required evidence</dt><dd>{milestone.evidence}</dd></div><div><dt>Current availability</dt><dd>{milestone.status==='COMING LATER'?'The required JPAC curriculum is visible in the catalog but is not yet available for verified completion.':'Final read-only evidence verification is required before student progress can be shown.'}</dd></div></dl></section>}
export function CareerAriaGuide({path,milestone}:{path:CareerPath;milestone?:CareerMilestone}){return <aside className="career-aria-guide" aria-label="ARIA path guidance"><div className="career-aria-glyph" aria-hidden="true">A</div><div><span>ARIA path note</span><h2>{milestone?`About ${milestone.title}`:`Explore ${path.name}`}</h2><p>{milestone?.status==='COMING LATER'?`This milestone is part of your creative journey, but ${milestone.evidence} is not available for career completion yet. It does not count against student progress.`:path.ariaNote}</p><strong>Catalog guidance only · no academic decision</strong></div></aside>}
