import type{ReactNode,CSSProperties}from'react';import{Link}from'react-router-dom';

type Tone='purple'|'gold'|'cyan'|'success'|'warning';
export function MetricCard({icon,label,value,detail,tone='purple'}:{icon:ReactNode;label:string;value:ReactNode;detail?:string;tone?:Tone}){return <article className={`ces-metric ces-tone-${tone}`}><span className="ces-metric-icon">{icon}</span><div><strong>{value}</strong><h3>{label}</h3>{detail&&<p>{detail}</p>}</div></article>}
export function AriaInsightCard({title='ARIA says',message,actionLabel,actionTo,compact=false}:{title?:string;message:string;actionLabel?:string;actionTo?:string;compact?:boolean}){return <article className={`ces-aria-card ${compact?'compact':''}`}><div className="ces-aria-mark">A</div><div><span>{title}</span><p>{message}</p>{actionLabel&&actionTo&&<Link className="ces-inline-action" to={actionTo}>{actionLabel} →</Link>}</div></article>}
export function ProgressRing({value,label,size=112,tone='gold'}:{value:number;label:string;size?:number;tone?:Tone}){const safe=Math.max(0,Math.min(100,Number(value)||0));return <div className={`ces-progress-ring ces-tone-${tone}`} style={{'--value':`${safe*3.6}deg`,'--size':`${size}px`} as CSSProperties}><div><strong>{Math.round(safe)}%</strong><span>{label}</span></div></div>}
export function AchievementCard({icon,title,subtitle,progress,badge='Achievement'}:{icon:ReactNode;title:string;subtitle?:string;progress?:number;badge?:string}){return <article className="ces-achievement-card"><div className="ces-achievement-glow"/><span className="ces-achievement-icon">{icon}</span><small>{badge}</small><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}{typeof progress==='number'&&<div className="ces-mini-progress"><i style={{width:`${Math.max(0,Math.min(100,progress))}%`}}/></div>}</article>}
export function Timeline({items}:{items:{icon?:ReactNode;title:string;detail?:string;time?:string;status?:'complete'|'current'|'future'}[]}){return <div className="ces-timeline">{items.map((item,index)=><article className={item.status||'future'} key={`${item.title}-${index}`}><span className="ces-timeline-node">{item.icon||index+1}</span><div><strong>{item.title}</strong>{item.detail&&<p>{item.detail}</p>}</div>{item.time&&<time>{item.time}</time>}</article>)}</div>}
export function QuickActionGrid({items}:{items:{icon:ReactNode;label:string;detail?:string;to:string;tone?:Tone}[]}){return <div className="ces-quick-actions">{items.map(item=><Link to={item.to} key={item.label} className={`ces-quick-action ces-tone-${item.tone||'purple'}`}><span>{item.icon}</span><div><strong>{item.label}</strong>{item.detail&&<small>{item.detail}</small>}</div><b>›</b></Link>)}</div>}
export function EmptyState({icon='✨',title,detail,actionLabel,actionTo}:{icon?:ReactNode;title:string;detail:string;actionLabel?:string;actionTo?:string}){return <div className="ces-empty"><span>{icon}</span><h3>{title}</h3><p>{detail}</p>{actionLabel&&actionTo&&<Link className="button button-primary" to={actionTo}>{actionLabel}</Link>}</div>}
export function SkeletonCards({count=3}:{count?:number}){return <div className="ces-skeleton-grid" aria-label="Loading content">{Array.from({length:count}).map((_,i)=><div className="ces-skeleton-card" key={i}><i/><b/><span/></div>)}</div>}
