import{useEffect,useRef,useState}from'react';
import{parseCurriculumImportPreview,validateCurriculumImportFile}from'../lib/curriculumImportPreview';
import{CURRICULUM_IMPORT_MAX_BYTES}from'../types/curriculumImportPreview';
import type{CurriculumImportPreviewResult,ImportPreviewContext}from'../types/curriculumImportPreview';

export function CurriculumImportPreviewDialog({context,onClose}:{context:ImportPreviewContext;onClose:()=>void}){
  const[mode,setMode]=useState<'paste'|'upload'>('paste');const[source,setSource]=useState('');const[fileName,setFileName]=useState('');const[result,setResult]=useState<CurriculumImportPreviewResult|null>(null);const heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;heading.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);previous?.focus()}},[onClose]);
  function close(){setSource('');setResult(null);setFileName('');onClose()}
  function parse(){setResult(parseCurriculumImportPreview(source,context))}
  async function upload(file:File|undefined){setResult(null);setSource('');setFileName(file?.name||'');if(!file)return;const validation=validateCurriculumImportFile(file.name,file.size);if(validation){setResult({ok:false,findings:[validation]});return}try{setSource(await file.text())}catch{setResult({ok:false,findings:[{severity:'ERROR',code:'FILE_READ_FAILED',message:'The selected file could not be read.'}]})}}
  const preview=result?.ok?result.preview:null;const findings=result?result.ok?result.preview.findings:result.findings:[];
  return <div className="e4-export-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="card e4-export-dialog e4-import-dialog" role="dialog" aria-modal="true" aria-labelledby="curriculum-import-title">
    <div className="section-head"><div><div className="eyebrow">Local validation • No database writes</div><h2 id="curriculum-import-title" ref={heading} tabIndex={-1}>Curriculum Import Preview</h2></div><button type="button" className="button button-secondary" onClick={close}>Close</button></div>
    <div className="e4-import-notice"><strong>Import Preview Only</strong><span>Nothing will be saved, published, or sent to Supabase.</span></div>
    <div className="e4-import-tabs" role="tablist" aria-label="Curriculum input method"><button type="button" role="tab" aria-selected={mode==='paste'} className={mode==='paste'?'active':''} onClick={()=>setMode('paste')}>Paste JSON</button><button type="button" role="tab" aria-selected={mode==='upload'} className={mode==='upload'?'active':''} onClick={()=>setMode('upload')}>Upload JSON</button></div>
    {mode==='paste'?<label className="e4-export-preview">JPAC curriculum export JSON<textarea value={source} onChange={event=>{setSource(event.target.value);setResult(null)}} spellCheck={false} maxLength={CURRICULUM_IMPORT_MAX_BYTES} placeholder="Paste jpac-curriculum-export v1.2.0 JSON"/></label>:<label className="e4-import-file">Choose a JSON export<input type="file" accept=".json,application/json" onChange={event=>void upload(event.target.files?.[0])}/><span>{fileName||'No file selected'} · 10 MB maximum</span></label>}
    <div className="e4-actions"><button type="button" className="button button-primary" disabled={!source} onClick={parse}>Parse and Preview</button></div>
    {result&&<div className={result.ok?'admin-message':'e4-warning'} role={result.ok?'status':'alert'}>{result.ok?'Preview parsed successfully. No records were changed.':result.findings.map(item=>`${item.code}: ${item.message}`).join(' ')}</div>}
    {findings.length>0&&<section className="e4-import-findings"><h3>Validation results</h3><ul>{findings.map((item,index)=><li key={`${item.code}-${index}`}><b>{item.severity} · {item.code}</b><span>{item.message}</span></li>)}</ul></section>}
    {preview&&<div className="e4-import-preview"><section><div className="section-head"><h3>Curriculum summary</h3><b>{preview.scope.type} scope</b></div><div className="e4-import-counts"><span><b>{preview.counts.levels}</b> levels</span><span><b>{preview.counts.modules}</b> modules</span><span><b>{preview.counts.lessons}</b> lessons</span><span><b>{preview.counts.activities}</b> activities</span><span><b>{preview.counts.warnings}</b> warnings</span></div><p><b>{preview.course.title||preview.scope.course_slug}</b> · {preview.scope.course_slug}{preview.scope.level_number?` · Level ${preview.scope.level_number}`:''}{preview.scope.module_number?` · Module ${preview.scope.module_number}`:''}</p></section>
      {preview.source_warnings.length>0&&<details><summary>Source warnings ({preview.source_warnings.length})</summary><pre>{JSON.stringify(preview.source_warnings,null,2)}</pre></details>}
      <section><h3>Basic local comparison only</h3><p>Identity and title checks use only selected-course data already loaded in Curriculum Studio. They do not authorize creation or reuse.</p>{preview.levels.map(level=><details key={level.level_number} open={preview.levels.length===1}><summary>Level {level.level_number}: {level.title||'Untitled'} · {level.modules.length} modules</summary><div className="e4-import-modules">{level.modules.map(module=><article key={`${level.level_number}-${module.module_number}`}><div><b>Module {module.module_number}: {module.title||'Untitled'}</b><span className="e4-import-status">{module.comparison_status}</span></div><p>{module.comparison_reason}</p><dl><div><dt>Lessons</dt><dd>{module.lessons.length}</dd></div><div><dt>Activities/Core Challenges</dt><dd>{module.activities.length}</dd></div><div><dt>Media</dt><dd>{module.media_review_status}</dd></div><div><dt>Tool</dt><dd>{module.tool_review_status}</dd></div><div><dt>Career Paths</dt><dd>{module.career_path_status}</dd></div></dl>{module.lessons.length>0&&<details><summary>Lessons</summary><ul>{module.lessons.map((lesson,index)=><li key={`${lesson.sort_order}-${index}`}>{lesson.sort_order??'–'}. {lesson.title} — {lesson.objective}</li>)}</ul></details>}{module.activities.length>0&&<details><summary>Activities and Core Challenges</summary><ul>{module.activities.map((activity,index)=><li key={`${activity.role}-${index}`}><b>{activity.role}</b>: {activity.title} ({activity.status||'status not supplied'})</li>)}</ul></details>}</article>)}</div></details>)}</section></div>}
    <div className="e4-actions"><button type="button" className="button button-primary" disabled title="Database persistence is not part of Import Preview v1">Save as Draft — Coming Later</button></div>
  </section></div>
}
