import{useEffect,useRef,useState}from'react';
import{parseCurriculumImportPreview,summarizeImportPreviewDecisions,validateCurriculumImportFile}from'../lib/curriculumImportPreview';
import{buildSaveDraftRpcPayload,evaluateSaveDraftEligibility,extractSourceWarningCodes,sanitizeSaveDraftError,validateSaveDraftRpcResponse}from'../lib/curriculumSaveDraft';
import{supabase}from'../lib/supabase';
import{CURRICULUM_IMPORT_MAX_BYTES}from'../types/curriculumImportPreview';
import type{CurriculumImportPreviewResult,ImportPreviewContext,SaveDraftRpcResponse}from'../types/curriculumImportPreview';

type Props={context:ImportPreviewContext;selectedCourseId:string|null;canSaveDraft:boolean;onSaved:(result:SaveDraftRpcResponse)=>Promise<void>;onClose:()=>void};
export function CurriculumImportPreviewDialog({context,selectedCourseId,canSaveDraft,onSaved,onClose}:Props){
  const[mode,setMode]=useState<'paste'|'upload'>('paste');const[source,setSource]=useState('');const[fileName,setFileName]=useState('');const[result,setResult]=useState<CurriculumImportPreviewResult|null>(null);const[acknowledged,setAcknowledged]=useState<string[]>([]);const[confirmed,setConfirmed]=useState(false);const[pending,setPending]=useState(false);const[saveResult,setSaveResult]=useState<SaveDraftRpcResponse|null>(null);const[saveError,setSaveError]=useState('');const heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;heading.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!pending)close()};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);previous?.focus()}},[onClose,pending]);
  function resetSave(){setAcknowledged([]);setConfirmed(false);setSaveResult(null);setSaveError('')}
  function close(){if(pending)return;setSource('');setResult(null);setFileName('');resetSave();onClose()}
  function parse(){resetSave();setResult(parseCurriculumImportPreview(source,context))}
  async function upload(file:File|undefined){setResult(null);setSource('');setFileName(file?.name||'');resetSave();if(!file)return;const validation=validateCurriculumImportFile(file.name,file.size);if(validation){setResult({ok:false,findings:[validation]});return}try{setSource(await file.text())}catch{setResult({ok:false,findings:[{severity:'ERROR',code:'FILE_READ_FAILED',message:'The selected file could not be read.'}]})}}
  const preview=result?.ok?result.preview:null,findings=result?result.ok?result.preview.findings:result.findings:[],decisions=preview?summarizeImportPreviewDecisions(preview):null,warningState=extractSourceWarningCodes(source);
  const saveContext={selected_course_id:selectedCourseId,selected_course_slug:context.selected_course_slug,can_save_draft:canSaveDraft,acknowledged_warning_codes:acknowledged,confirmed,pending};const eligibility=evaluateSaveDraftEligibility(source,preview,saveContext);
  const interpretation=decisions?(decisions.course_mismatch?'Select the matching course before continuing.':decisions.possible_conflicts?'Resolve possible conflicts before any future Save as Draft workflow.':decisions.not_checked?'Some modules could not be compared using currently loaded data.':decisions.would_create?'Preview includes a new module identity. Review all curriculum before saving a draft.':'No local identity conflicts detected. Full compatibility has not been validated.'):'';
  const saveLabel=decisions?(decisions.course_mismatch?'Save as Draft unavailable - Select matching course':decisions.possible_conflicts?'Save as Draft unavailable - Resolve conflicts first':decisions.not_checked||!decisions.complete?'Save as Draft unavailable - Comparison incomplete':'Save as Draft'):'Save as Draft unavailable - Parse preview first';
  async function saveDraft(){if(!supabase||!preview||!eligibility.eligible||pending)return;setPending(true);setSaveError('');try{const payload=buildSaveDraftRpcPayload(source,preview,{...saveContext,pending:false});const{data,error}=await supabase.rpc('curriculum_save_module_as_draft_v1',{import_payload:payload});if(error)throw error;const validated=validateSaveDraftRpcResponse(data);if(!validated)throw new Error('Invalid Save as Draft response');setSaveResult(validated);await onSaved(validated)}catch(error){setSaveError(sanitizeSaveDraftError(error))}finally{setPending(false)}}
  return <div className="e4-export-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="card e4-export-dialog e4-import-dialog" role="dialog" aria-modal="true" aria-labelledby="curriculum-import-title">
    <div className="section-head"><div><div className="eyebrow">Local preview · Controlled draft RPC</div><h2 id="curriculum-import-title" ref={heading} tabIndex={-1}>Curriculum Import Preview</h2></div><button type="button" className="button button-secondary" disabled={pending} onClick={close}>Close</button></div>
    <div className="e4-import-notice"><strong>Import Preview</strong><span>Nothing is sent to Supabase unless an eligible administrator explicitly confirms Save as Draft.</span></div>
    <div className="e4-import-tabs" role="tablist" aria-label="Curriculum input method"><button type="button" role="tab" aria-selected={mode==='paste'} className={mode==='paste'?'active':''} onClick={()=>setMode('paste')}>Paste JSON</button><button type="button" role="tab" aria-selected={mode==='upload'} className={mode==='upload'?'active':''} onClick={()=>setMode('upload')}>Upload JSON</button></div>
    {mode==='paste'?<label className="e4-export-preview">JPAC curriculum export JSON<textarea value={source} onChange={event=>{setSource(event.target.value);setResult(null);resetSave()}} spellCheck={false} maxLength={CURRICULUM_IMPORT_MAX_BYTES} placeholder="Paste jpac-curriculum-export v1.2.0 JSON"/></label>:<label className="e4-import-file">Choose a JSON export<input type="file" accept=".json,application/json" onChange={event=>void upload(event.target.files?.[0])}/><span>{fileName||'No file selected'} · 10 MB maximum</span></label>}
    <div className="e4-actions"><button type="button" className="button button-primary" disabled={!source||pending} onClick={parse}>Parse and Preview</button></div>
    {result&&<div className={result.ok?'admin-message':'e4-warning'} role={result.ok?'status':'alert'}>{result.ok?'Preview parsed successfully. No records were changed.':result.findings.map(item=>`${item.code}: ${item.message}`).join(' ')}</div>}
    {findings.length>0&&<section className="e4-import-findings"><h3>Validation results</h3><ul>{findings.map((item,index)=><li key={`${item.code}-${index}`}><b>{item.severity} · {item.code}</b><span>{item.message}</span></li>)}</ul></section>}
    {preview&&<div className="e4-import-preview"><section><div className="section-head"><h3>Curriculum summary</h3><b>{preview.scope.type} scope</b></div><div className="e4-import-counts"><span><b>{preview.counts.levels}</b> levels</span><span><b>{preview.counts.modules}</b> modules</span><span><b>{preview.counts.lessons}</b> lessons</span><span><b>{preview.counts.activities}</b> activities</span><span><b>{preview.counts.warnings}</b> warnings</span></div><p><b>{preview.course.title||preview.scope.course_slug}</b> · {preview.scope.course_slug}{preview.scope.level_number?` · Level ${preview.scope.level_number}`:''}{preview.scope.module_number?` · Module ${preview.scope.module_number}`:''}</p></section>
      {decisions&&<section className="e4-import-decision"><h3>Local Comparison Decision Summary</h3><p>This compares semantic module identity and title against selected-course data already loaded in Curriculum Studio. It does not prove full compatibility.</p><div className="e4-import-decision-grid">{([['Would reuse',decisions.would_reuse,'Existing identity and title match'],['Would create',decisions.would_create,'No loaded semantic match'],['Possible conflicts',decisions.possible_conflicts,'Review identity or title'],['Course mismatch',decisions.course_mismatch,'Selected course differs'],['Not checked',decisions.not_checked,'Comparison unavailable']]as const).map(([label,count,help])=><article key={label}><b>{count}</b><strong>{label}</strong><small>{help}</small></article>)}</div><p className="e4-import-interpretation"><b>{interpretation}</b></p></section>}
      {preview.source_warnings.length>0&&<details><summary>Source warnings ({preview.source_warnings.length})</summary><pre>{JSON.stringify(preview.source_warnings,null,2)}</pre></details>}
      <section><h3>Basic local comparison only</h3>{preview.levels.map(level=><details key={level.level_number} open={preview.levels.length===1}><summary>Level {level.level_number}: {level.title||'Untitled'} · {level.modules.length} modules</summary><div className="e4-import-modules">{level.modules.map(module=><article key={`${level.level_number}-${module.module_number}`}><div><b>Module {module.module_number}: {module.title||'Untitled'}</b><span className="e4-import-status">{module.comparison_status}</span></div><p>{module.comparison_reason}</p><dl><div><dt>Lessons</dt><dd>{module.lessons.length}</dd></div><div><dt>Activities/Core Challenges</dt><dd>{module.activities.length}</dd></div><div><dt>Media</dt><dd>{module.media_review_status}</dd></div><div><dt>Tool</dt><dd>{module.tool_review_status}</dd></div><div><dt>Career Paths</dt><dd>{module.career_path_status}</dd></div></dl></article>)}</div></details>)}</section>
      <section className="e4-save-eligibility"><h3>Save Eligibility</h3><p>Save as Draft v1 creates one new draft module only, with no overwrite, publication, or student-progress change.</p>{eligibility.blockers.length?<ul>{eligibility.blockers.map(item=><li key={item.code}><b>{item.code}</b><span>{item.message}</span></li>)}</ul>:<p className="eligible"><b>Eligibility checks passed.</b> The server will independently validate the request.</p>}{!canSaveDraft&&<p>Save as Draft requires an administrator or developer account.</p>}
        {!warningState.malformed&&warningState.codes.length>0&&<fieldset><legend>Source warning acknowledgement</legend>{warningState.codes.map(code=><label key={code}><input type="checkbox" checked={acknowledged.includes(code)} disabled={pending||Boolean(saveResult)} onChange={event=>setAcknowledged(current=>event.target.checked?[...current,code]:current.filter(item=>item!==code))}/><span><b>{code}</b> - reviewed, not resolved or approved</span></label>)}</fieldset>}
        <label className="e4-save-confirm"><input type="checkbox" checked={confirmed} disabled={pending||Boolean(saveResult)} onChange={event=>setConfirmed(event.target.checked)}/><span>I understand this will create one new draft module only, with no overwrite, no publish, and no student progress changes.</span></label>
      </section>{saveError&&<div className="e4-warning" role="alert">{saveError}</div>}{saveResult&&<section className="e4-save-result" role="status"><h3>Draft module created</h3><p>Operation ID: <code>{saveResult.operation_id}</code></p><p>Status: <b>{saveResult.status}</b> · {saveResult.created_counts.modules} module · {saveResult.created_counts.lessons} lessons · {saveResult.created_counts.activities} activities</p><p>Still unresolved: {saveResult.unresolved_review_statuses.join(', ')||'None reported'}</p></section>}</div>}
    <div className="e4-actions"><button type="button" className="button button-primary e4-save-draft-action" disabled={!eligibility.eligible||pending||Boolean(saveResult)} onClick={()=>void saveDraft()}>{pending?'Saving one draft module…':saveResult?'Draft module created':eligibility.eligible?'Save as Draft':saveLabel}</button></div>
  </section></div>
}
