import{useEffect,useMemo,useState}from'react';
import{supabase}from'../lib/supabase';
import{formatInstructionalDuration,normalizeInstructionalMediaUrl,type InstructionalMedia}from'../lib/instructionalMedia';
import{InstructionalMediaPlayer}from'./InstructionalMediaPlayer';

export function InstructionalMediaManager({moduleId,canManage,media,onChanged,onMessage}:{moduleId:string;canManage:boolean;media:InstructionalMedia[];onChanged:()=>Promise<void>;onMessage:(message:string)=>void}){
  const active=media.find(item=>item.status==='active')||null;const history=media.filter(item=>item.id!==active?.id).sort((a,b)=>b.version_number-a.version_number);
  const[url,setUrl]=useState('');const[title,setTitle]=useState('');const[duration,setDuration]=useState('');const[confirm,setConfirm]=useState(false);const[busy,setBusy]=useState(false);const[editing,setEditing]=useState(false);const[draftId,setDraftId]=useState('');const normalized=useMemo(()=>normalizeInstructionalMediaUrl(url),[url]);
  useEffect(()=>{setUrl('');setTitle('');setDuration('');setConfirm(false);setEditing(false);setDraftId('')},[moduleId]);
  const preview:InstructionalMedia|null=normalized?{id:`preview-${normalized.providerMediaId}`,module_id:moduleId,version_number:(media[0]?.version_number||0)+1,provider:normalized.provider,provider_media_id:normalized.providerMediaId,source_url:url,normalized_url:normalized.normalizedUrl,title:title||'Video preview',duration_seconds:Number(duration)||null,status:'draft',created_at:'',activated_at:null,retired_at:null,replaces_media_id:active?.id||null}:null;

  async function activate(){if(!supabase||!preview||!canManage)return;const seconds=Number(duration);if(!title.trim()||!Number.isInteger(seconds)||seconds<1){onMessage('A video title and valid detected or entered duration are required before activation.');return}setBusy(true);const result=draftId?await supabase.rpc('curriculum_activate_instructional_media',{target_media:draftId,media_title:title.trim(),media_duration_seconds:seconds}):await supabase.rpc('curriculum_set_instructional_media',{target_module:moduleId,media_url:url,media_title:title.trim(),media_duration_seconds:seconds});setBusy(false);setConfirm(false);onMessage(result.error?.message||(active?'Instructional video replaced. Historical viewing evidence remains preserved.':'Instructional video activated.'));if(!result.error){setUrl('');setTitle('');setDuration('');setDraftId('');await onChanged()}}
  async function saveActiveMetadata(){if(!supabase||!active||!canManage)return;const seconds=Number(duration);setBusy(true);const{error}=await supabase.rpc('curriculum_update_instructional_media_metadata',{target_media:active.id,media_title:title.trim(),media_duration_seconds:seconds});setBusy(false);onMessage(error?.message||'Instructional video metadata updated.');if(!error){setEditing(false);await onChanged()}}

  return <section className="e4-instructional-media"><div className="section-head"><div><div className="eyebrow">Instructional Media</div><h3>{active?'Active instructional video':'Add instructional video'}</h3></div><span>{active?`VERSION ${active.version_number}`:'NOT CONFIGURED'}</span></div>
    {active&&<div className="media-active"><InstructionalMediaPlayer media={active}/><dl><div><dt>Title</dt><dd>{active.title}</dd></div><div><dt>Provider</dt><dd>{active.provider}</dd></div><div><dt>Identity</dt><dd>{active.provider_media_id}</dd></div><div><dt>Duration</dt><dd>{formatInstructionalDuration(active.duration_seconds)}</dd></div></dl>{canManage&&!editing&&<div className="e4-actions"><button className="button button-secondary" onClick={()=>{setEditing(true);setTitle(active.title);setDuration(String(active.duration_seconds||''))}}>Edit metadata</button><button className="button button-primary" onClick={()=>{setUrl('');setTitle('');setDuration('');setConfirm(false);document.getElementById('replacement-media-url')?.focus()}}>Replace video</button></div>}{editing&&<div className="e4-form"><label>Video title<input value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Duration (seconds)<input type="number" min="1" max="7200" value={duration} onChange={event=>setDuration(event.target.value)}/></label><div className="e4-actions wide"><button className="button button-secondary" onClick={()=>setEditing(false)}>Cancel</button><button className="button button-primary" disabled={busy} onClick={()=>void saveActiveMetadata()}>Save metadata</button></div></div>}</div>}
    {canManage&&<div className="media-add"><h4>{draftId?'Finalize draft media':active?'Replace instructional video':'Add video'}</h4><p>Paste a normal YouTube link or an approved HTTPS MP4, WebM, or M4V link. JPAC normalizes the provider and identity automatically.</p><div className="e4-form"><label className="wide">Video URL<input id="replacement-media-url" type="url" value={url} disabled={Boolean(draftId)} onChange={event=>{setUrl(event.target.value);setDraftId('');setConfirm(false)}} placeholder="https://www.youtube.com/watch?v=..."/></label><label>Video title<input value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Duration (seconds)<input type="number" min="1" max="7200" value={duration} onChange={event=>setDuration(event.target.value)}/></label></div>{url&&!normalized&&<p className="media-error">Enter a supported YouTube or direct HTTPS video URL. Raw iframe HTML is not accepted.</p>}{preview&&<div className="media-preview"><div className="media-detection"><span>Provider <b>{preview.provider}</b></span><span>Normalized identity <b>{preview.provider_media_id}</b></span></div><InstructionalMediaPlayer media={preview} onDuration={seconds=>setDuration(current=>current||String(seconds))} onTitle={value=>setTitle(current=>current||value)} onError={onMessage}/></div>}{preview&&!confirm&&<button className="button button-primary" disabled={busy||!title.trim()||Number(duration)<1} onClick={()=>setConfirm(true)}>{draftId?'Activate draft':active?'Replace video':'Add video'}</button>}{confirm&&<div className="e4-media-confirm" role="alert"><strong>{active?'Replace instructional video?':'Activate instructional video?'}</strong><p>{active?'Existing historical viewing evidence will be preserved and the new video will become the active instructional media.':'The reviewed video will become the module’s active instructional media.'}</p><div><button className="button button-secondary" disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button><button className="button button-primary" disabled={busy} onClick={()=>void activate()}>{busy?'Activating...':active?'Confirm replacement':'Confirm activation'}</button></div></div>}</div>}
    <div className="media-history"><h4>Previous-version history</h4>{history.length?history.map(item=><article key={item.id}><div><strong>Version {item.version_number} · {item.title||'Untitled video'}</strong><small>{item.provider} · {item.provider_media_id}</small></div><span>{item.status}</span><small>{formatInstructionalDuration(item.duration_seconds)}</small>{canManage&&item.status==='draft'&&item.source_url&&<button className="button button-secondary" onClick={()=>{setDraftId(item.id);setUrl(item.source_url||'');setTitle(item.title);setDuration(String(item.duration_seconds||''));setConfirm(false)}}>Preview and activate</button>}</article>):<p>No previous versions.</p>}</div>
  </section>
}
