import{Link}from'react-router-dom';
import type{CourseLesson,CourseModule,LessonProgress}from'../lib/studentAccess';

export type MissionActivity={id:string;title:string;description:string;instructions:string;activity_type:string;submission_type:string;xp_reward:number;xp_type:'core'|'bonus';required:boolean;passing_score:number;rubric:Record<string,unknown>};
export type MissionAttempt={id:string;activity_id:string;attempt_number:number;status:string;score:number|null;teacher_feedback:string|null;submitted_at:string};
export type MissionCompletion={video_percent:number;assignment_score:number;core_xp_earned:number;core_xp_available:number;core_xp_threshold:number;intro_complete:boolean;assignment_submitted:boolean;assessment_passed:boolean;mastery_awarded:boolean;is_complete:boolean};
type StageState='locked'|'available'|'active'|'complete'|'revision';

const stageLabel:Record<StageState,string>={locked:'Locked',available:'Ready',active:'Next',complete:'Complete',revision:'Revise'};
function statusLabel(value:string){return value.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())}

export function MissionProgress({completion,lessons,progress,bonusEarned,bonusAvailable,hasRevision}:{completion:MissionCompletion|null;lessons:CourseLesson[];progress:LessonProgress[];bonusEarned:number;bonusAvailable:number;hasRevision:boolean}){
  const lessonsComplete=lessons.length>0&&lessons.every(lesson=>progress.find(item=>item.lesson_id===lesson.id)?.status==='completed');
  const stages:Array<{label:string;detail:string;state:StageState}>=[
    {label:'Start',detail:'Mission brief',state:completion?.intro_complete?'complete':'active'},
    {label:'Learn',detail:lessons.length?`${progress.filter(item=>item.status==='completed'&&lessons.some(lesson=>lesson.id===item.lesson_id)).length}/${lessons.length} lessons`:'No lessons yet',state:lessonsComplete?'complete':completion?.intro_complete?'active':'available'},
    {label:'Watch',detail:`${Math.round(completion?.video_percent||0)}% watched`,state:(completion?.video_percent||0)>=90?'complete':'available'},
    {label:'Practice',detail:bonusAvailable?`${bonusEarned}/${bonusAvailable} Bonus XP`:'Optional',state:bonusEarned>0?'complete':'available'},
    {label:'Core Challenge',detail:hasRevision?'Another take':completion?.assignment_submitted?'Awaiting review':'Submit your evidence',state:hasRevision?'revision':completion?.assessment_passed?'complete':completion?.assignment_submitted?'active':'available'},
    {label:'Master',detail:completion?.is_complete?'Mission mastered':'Complete every Core step',state:completion?.is_complete?'complete':hasRevision?'revision':'available'},
  ];
  return <section className="mission-progress" aria-label="Mission progress"><div className="mission-progress-head"><div><span>Mission progress</span><h2>Keep your creative momentum</h2></div><div className="mission-xp-summary"><strong>{completion?.core_xp_earned||0} / {completion?.core_xp_available||625}</strong><small>Core XP</small><b>{bonusEarned} / {bonusAvailable}</b><small>Bonus XP</small></div></div><ol>{stages.map((stage,index)=><li className={`mission-stage state-${stage.state}`} key={stage.label}><span>{stage.state==='complete'?'✓':index+1}</span><div><strong>{stage.label}</strong><small>{stage.detail}</small></div><em>{stageLabel[stage.state]}</em></li>)}</ol></section>
}

export function MissionBrief({module,requiredActivity,bonusAvailable,onStart,busy,started}:{module:CourseModule;requiredActivity:MissionActivity|null;bonusAvailable:number;onStart:()=>void;busy:boolean;started:boolean}){
  return <section className="mission-card mission-brief"><div className="mission-section-label">Mission brief</div><div className="mission-brief-grid"><div><h1>{module.title}</h1><p>{module.short_intro||module.description}</p><button className="button button-primary" disabled={busy||started} onClick={onStart}>{started?'Mission started':busy?'Starting…':'Start mission'}</button></div><dl><div><dt>What you are learning</dt><dd>{module.description||module.short_intro}</dd></div><div><dt>Why it matters</dt><dd>{module.career_connection||'Build a practical creative skill you can use in future projects and performances.'}</dd></div><div><dt>What you will create</dt><dd>{requiredActivity?.title||'A creative challenge connected to this mission.'}</dd></div><div><dt>What you can earn</dt><dd>{module.core_xp||625} Core XP + {bonusAvailable} optional Bonus XP</dd></div></dl></div></section>
}

export function LearnSection({courseId,lessons,progress}:{courseId:string;lessons:CourseLesson[];progress:LessonProgress[]}){
  return <section className="mission-card"><div className="mission-section-head"><div><div className="mission-section-label">Learn it</div><h2>Build the skill</h2></div><span>{lessons.length} lesson{lessons.length===1?'':'s'}</span></div>{lessons.length?<div className="mission-lessons">{lessons.map((lesson,index)=>{const state=progress.find(item=>item.lesson_id===lesson.id);const complete=state?.status==='completed';const started=Boolean(state);return <article key={lesson.id}><span>{complete?'✓':index+1}</span><div><small>Lesson {index+1}{lesson.duration_minutes?` · ${lesson.duration_minutes} min`:''}</small><h3>{lesson.title}</h3><p>{lesson.description||'Open this lesson to continue the mission.'}</p></div><Link className="button button-secondary" to={`/courses/${courseId}/lessons/${lesson.id}`}>{complete?'Review':started?'Continue':'Open'}</Link><em className={complete?'complete':''}>{complete?'Completed':started?statusLabel(state?.status||'in progress'):'Ready'}</em></article>})}</div>:<p className="mission-empty">Published lessons will appear here when the curriculum team adds them.</p>}</section>
}

export function WatchSection({videoUrl,percent,onTimeUpdate}:{videoUrl?:string|null;percent:number;onTimeUpdate:(event:React.SyntheticEvent<HTMLVideoElement>)=>void}){
  return <section className="mission-card"><div className="mission-section-head"><div><div className="mission-section-label">Watch it</div><h2>Instructional video</h2></div><strong>{Math.round(percent)}% watched</strong></div><div className="watch-progress"><i style={{width:`${Math.min(100,percent)}%`}}/></div><p className="muted">Watch at least 90% to complete this Core step.</p>{videoUrl?<video className="module-video" controls preload="metadata" src={videoUrl} onTimeUpdate={onTimeUpdate}/>:<div className="video-configuration"><span>Video preparation in progress</span><strong>This mission’s instructional video has not been configured yet.</strong><p>You can explore the mission brief, lessons, and practice activities now. Video completion will become available when authorized curriculum staff add the approved source.</p></div>}</section>
}

export function PracticeChallenge({kind,activity,moduleData,busy,earned,onComplete}:{kind:'practice'|'lab';activity:MissionActivity|null;moduleData?:Record<string,string>;busy:boolean;earned:boolean;onComplete:(activity:MissionActivity)=>void}){
  if(!activity&&!moduleData?.title)return null;const title=activity?.title||moduleData?.title||'Creative practice';const detail=activity?.description||moduleData?.instructions||'';const instructions=activity?.instructions||moduleData?.instructions||'';const route=[moduleData?.route,moduleData?.tool_route,moduleData?.launch_url].find(value=>value?.startsWith('/'));
  return <section className={`mission-card practice-challenge ${kind==='lab'?'jpac-lab':''}`}><div className="mission-section-label">{kind==='lab'?'JPAC Lab':'Try it'}</div><div className="practice-title"><div><h2>{title}</h2><p>{detail}</p></div><strong>+{activity?.xp_reward||0} Bonus XP</strong></div>{instructions&&instructions!==detail&&<p className="practice-instructions">{instructions}</p>}<div className="mission-actions">{route&&<Link className="button button-secondary" to={route}>Open JPAC tool</Link>}{activity&&<button className="button button-secondary" disabled={busy||earned} onClick={()=>onComplete(activity)}>{earned?'Practice recorded':busy?'Saving…':kind==='lab'?'Complete lab practice':'Complete practice'}</button>}</div><small>Optional practice builds skill and Bonus XP. It does not replace Core mission requirements.</small></section>
}

export function SubmissionHistory({attempts}:{attempts:MissionAttempt[]}){
  if(!attempts.length)return null;return <div className="attempt-timeline"><div className="mission-section-label">Submission history</div>{attempts.map(attempt=><article key={attempt.id}><span>{attempt.attempt_number}</span><div><strong>Attempt {attempt.attempt_number}</strong><small>{new Date(attempt.submitted_at).toLocaleDateString()} · {statusLabel(attempt.status)}</small>{attempt.teacher_feedback&&<p>{attempt.teacher_feedback}</p>}</div><b>{attempt.score===null?'Awaiting review':`${attempt.score}%`}</b></article>)}</div>
}

export function AriaFeedback({attempt}:{attempt:MissionAttempt|null}){
  if(!attempt||attempt.score===null)return <section className="mission-card aria-feedback"><div className="mission-section-label">ARIA feedback</div><h2>Feedback arrives after assessment</h2><p className="muted">Your instructor’s verified review will appear here. ARIA will not invent feedback before evidence exists.</p></section>;
  const passing=attempt.status==='approved';return <section className={`mission-card aria-feedback ${passing?'passing':'revision'}`}><div className="mission-section-head"><div><div className="mission-section-label">ARIA feedback</div><h2>{passing?'Creative strengths confirmed':'Revision mission'}</h2></div><strong>{attempt.score}%</strong></div><div className="feedback-grid"><div><span>What you did well</span><p>{passing?(attempt.teacher_feedback||'Your assessed submission met the configured mastery standard.'):'You completed a real creative attempt and created evidence your instructor could assess.'}</p></div><div><span>What to improve</span><p>{passing?'Keep the strongest choices consistent in your next mission.':attempt.teacher_feedback||'Review the rubric and instructor assessment before recording another take.'}</p></div><div><span>Try this next</span><p>{passing?'Carry this skill into the next creative mission.':'Focus on one correction, practice it deliberately, then submit a new attempt.'}</p></div><div><span>Mastery status</span><p>{passing?'Assessment passed. Complete any remaining Core steps to master the mission.':'Revision recommended. Your previous attempt remains part of your creative journey.'}</p></div></div></section>
}

export function MasteryChecklist({completion}:{completion:MissionCompletion|null}){
  const rows=[['Mission intro',Boolean(completion?.intro_complete)],['Instructional video 90%+',Number(completion?.video_percent||0)>=90],['Creative challenge submitted',Boolean(completion?.assignment_submitted)],['Assessment meets the configured standard',Boolean(completion?.assessment_passed)],['Core XP threshold',Number(completion?.core_xp_earned||0)>=Number(completion?.core_xp_threshold||438)],['Mastery award',Boolean(completion?.mastery_awarded)]];return <section className="mission-card mastery-card"><div className="mission-section-label">Master it</div><h2>What completes this mission?</h2><div>{rows.map(([label,done])=><p className={done?'complete':''} key={String(label)}><span>{done?'✓':'○'}</span><strong>{label}</strong></p>)}</div><small>These results come from the Academy learning engine. Bonus XP never replaces a Core requirement.</small></section>
}

export function LevelUpCard({completion,bonusEarned,nextModule,courseId,currentLevel}:{completion:MissionCompletion|null;bonusEarned:number;nextModule:CourseModule|null;courseId:string;currentLevel:number|null}){
  if(!completion?.is_complete)return null;const levelComplete=Boolean(nextModule&&nextModule.level_number!==currentLevel);return <section className="level-up-card"><span>{levelComplete?'Level complete':'Module mastered'}</span><h2>{levelComplete?'A new creative level is ready.':'Next mission unlocked.'}</h2><div><strong>{completion.core_xp_earned} / {completion.core_xp_available} Core XP</strong><b>{bonusEarned} Bonus XP earned</b></div>{nextModule?<><p>Continue with <strong>{nextModule.title}</strong>.</p><Link className="button button-primary" to={`/courses/${courseId}/modules/${nextModule.id}`}>Continue to next mission</Link></>:<p>You have completed every currently published mission in this pathway.</p>}</section>
}
