-- JPAC Video Production 49-module rollout preflight. READ ONLY.
begin transaction read only;
with manifest(level,num,sort,title) as (values
 (1,1,1,'CapCut Basics & Your First Edit'),(1,2,2,'Planning Your First Video'),(1,3,3,'Light Makes Everything Better'),(1,4,4,'Recording Audio for Video'),(1,5,5,'Understanding Frame Rates and Resolution'),(1,6,6,'Basic Editing: Cuts and Transitions'),(1,7,7,'Storyboarding Your Ideas'),(1,8,8,'Basic Interview Techniques'),(1,9,9,'Shooting Your First Short Video'),(1,10,10,'Exporting for Social Media'),
 (2,1,11,'Camera Movement: Sliders, Gimbals'),(2,2,12,'Advanced Lighting Techniques'),(2,3,13,'Color Correction and Grading'),(2,4,14,'Storyboarding and Shot Listing'),(2,5,15,'Color Grading'),(2,6,16,'Directing Talent'),(2,7,17,'Pre-Production and Planning'),(2,8,18,'Shooting a Music Performance'),(2,9,19,'Intro to Motion Graphics'),(2,10,20,'Creating a Short Documentary'),(2,11,21,'Color Correction & Grading'),(2,12,22,'Creating Your First Music Video'),
 (3,1,23,'Advanced Cinematography'),(3,2,24,'Working with Green Screen'),(3,3,25,'Color Correction & Grading'),(3,4,26,'Sound Design for Video'),(3,5,27,'Directing a Short Film'),(3,6,28,'Producing and Budgeting'),(3,7,29,'Drone Cinematography'),(3,8,30,'Visual Effects Fundamentals (After Effects)'),(3,9,31,'Budgeting and Scheduling'),(3,10,32,'Gimbal and Stabilizer Techniques'),(3,11,33,'Advanced Color Grading'),(3,12,34,'Advanced Social Media Video Production: Mastering Platform Optimization'),(3,13,35,'Advanced Camera Control: Manual Mode'),(3,14,36,'Cinematic Lighting Techniques'),(3,15,37,'Advanced Editing: J-Cuts, L-Cuts & Match Cuts'),
 (4,1,38,'Developing a Director''s Vision'),(4,2,39,'Feature Film Pre-Production'),(4,3,40,'VFX: Green Screen and Compositing'),(4,4,41,'Director Study: Spike Jonze'),(4,5,42,'Film Festival Strategy'),(4,6,43,'Mentoring Emerging Filmmakers'),(4,7,44,'The Future of Filmmaking'),(4,8,45,'Film Financing and Distribution'),(4,9,46,'Developing a Signature Style'),(4,10,47,'Capstone: Short Film Production'),(4,20,48,'Visual Effects (VFX) Basics'),(4,24,49,'Festival Submission & Digital Distribution')
), course_identity as (
 select count(*)::int n,(array_agg(id order by id::text))[1] id from public.courses where slug='video-production'
), sdi as (
 select count(*) filter(where (select count(*) from regexp_matches(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m\.status=''published''','g'))=2 and strpos(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m.status<>''archived''')=0)::int n from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('jpac_sync_enrollment_progress','jpac_enforce_canonical_enrollment_progress')
), canonical_trigger as (
 select count(*)::int n from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='enrollments' and t.tgname='enrollments_enforce_canonical_progress' and not t.tgisinternal and t.tgenabled<>'D'
), level_conflicts as (
 select count(*)::int n from public.course_levels l join public.courses c on c.id=l.course_id where c.slug='video-production' and (l.level_number not between 1 and 4 or l.title is distinct from (array['Beginner','Intermediate','Advanced','Master'])[l.level_number] or l.status<>'draft' or l.approved_by is not null or l.approved_at is not null)
), module_conflicts as (
 select count(*)::int n from manifest e join public.courses c on c.slug='video-production' left join public.course_levels l on l.course_id=c.id and l.level_number=e.level join public.course_modules m on m.course_id=c.id and (m.sort_order=e.sort or (m.course_level_id=l.id and m.level_module_number=e.num))
 where m.course_level_id is distinct from l.id or m.level_module_number is distinct from e.num or m.sort_order is distinct from e.sort or m.title is distinct from e.title or m.description is distinct from 'Develop and demonstrate source-aligned Video Production skills for '||e.title||'.' or m.short_intro is distinct from 'Draft source-aligned Video Production module.' or m.status<>'draft' or m.xp_value<>625 or m.core_xp<>625 or m.intro_core_xp<>50 or m.video_core_xp<>100 or m.assignment_core_xp<>350 or m.mastery_core_xp<>125 or m.core_unlock_threshold<>438 or m.bonus_xp_available<>0 or m.jpac_tool_activity is distinct from '{}'::jsonb or m.real_world_activity is distinct from jsonb_build_object('title',e.title||' Guided Practice','instructions','Plan, capture, edit, or analyze source-aligned work using teacher-approved accessible equipment-free or supplied-media alternatives.') or m.career_connection is distinct from '' or m.portfolio_moment or m.video_brief is distinct from 'NEEDS REVIEW: no media is activated.' or m.lab_tool_id is not null or m.active_instructional_media_id is not null or m.primary_video_url is not null or m.approved_by is not null or m.approved_at is not null
), sort_conflicts as (
 select count(*)::int n from public.course_modules m join public.courses c on c.id=m.course_id left join manifest e on e.sort=m.sort_order where c.slug='video-production' and m.sort_order between 1 and 49 and (e.sort is null or m.title is distinct from e.title)
), child_conflicts as (
 select count(*)::int n from manifest e join public.courses c on c.slug='video-production' join public.course_levels l on l.course_id=c.id and l.level_number=e.level join public.course_modules m on m.course_level_id=l.id and m.level_module_number=e.num
 where (exists(select 1 from public.lessons where module_id=m.id) or exists(select 1 from public.activities where module_id=m.id)) and ((select count(*) from public.lessons where module_id=m.id)<>3 or (select count(*) from public.lessons where module_id=m.id and status='draft' and xp_value=0 and title in(e.title||': Story and Production Foundations',e.title||': Guided Technical Application',e.title||': Edit, Present, and Reflect'))<>3 or (select count(*) from public.activities where module_id=m.id)<>2 or (select count(*) from public.activities where module_id=m.id and title=e.title||' Guided Practice' and status='draft' and activity_type='practice' and not required and xp_reward=0 and xp_type='bonus')<>1 or (select count(*) from public.activities where module_id=m.id and title=e.title||' Core Challenge' and status='draft' and activity_type='performance' and required and xp_reward=350 and xp_type='core' and passing_score=70 and allows_resubmission and jsonb_array_length(rubric->'criteria')=5 and (select sum((x->>'weight')::int) from jsonb_array_elements(rubric->'criteria') x)=100)<>1)
), numbering_conflicts as (
 select count(*)::int n from public.course_modules m join public.course_levels l on l.id=m.course_level_id join public.courses c on c.id=m.course_id where c.slug='video-production' and l.level_number=4 and m.level_module_number in(11,12,13,14,15,16,17,18,19,21,22,23)
), assets as (
 select (select count(*) from public.module_instructional_media mi join public.course_modules m on m.id=mi.module_id where m.course_id=(select id from course_identity))::int media,(select count(*) from public.lab_tool_courses where course_id=(select id from course_identity))::int tools
), deps as (
 select (select count(*) from public.enrollments where course_id=(select id from course_identity))+(select count(*) from public.submissions s join public.activities a on a.id=s.activity_id where a.course_id=(select id from course_identity))+(select count(*) from public.lesson_progress p join public.lessons l on l.id=p.lesson_id join public.course_modules m on m.id=l.module_id where m.course_id=(select id from course_identity))+(select count(*) from public.activity_progress p join public.activities a on a.id=p.activity_id where a.course_id=(select id from course_identity))+(select count(*) from public.practice_logs p join public.activities a on a.id=p.activity_id where a.course_id=(select id from course_identity))+(select count(*) from public.xp_ledger where course_id=(select id from course_identity))+(select count(*) from public.certificates where course_id=(select id from course_identity))+(select count(*) from public.portfolio_projects p join public.activities a on a.id=p.activity_id where a.course_id=(select id from course_identity)) n
), baselines as (
 select upper(c.slug)||'_CURRICULUM_BASELINE' code,md5(coalesce(string_agg(v,E'\n' order by v),'')) details from public.courses c cross join lateral (select m.id||':'||m.status||':'||m.title v from public.course_modules m where m.course_id=c.id union all select l.id||':'||l.status||':'||l.title from public.lessons l join public.course_modules m on m.id=l.module_id where m.course_id=c.id union all select a.id||':'||a.status||':'||a.title from public.activities a where a.course_id=c.id) q where c.slug in('singing','piano','guitar','acting','dance') group by c.slug
 union all select 'STUDENT_STATE_BASELINE',jsonb_build_object('enrollments',(select count(*) from public.enrollments),'lesson_progress',(select count(*) from public.lesson_progress),'activity_progress',(select count(*) from public.activity_progress),'practice_logs',(select count(*) from public.practice_logs),'submissions',(select count(*) from public.submissions),'xp_ledger',(select count(*) from public.xp_ledger),'certificates',(select count(*) from public.certificates),'portfolio_projects',(select count(*) from public.portfolio_projects))::text
 union all select 'ASSIGNMENT_SWAP_BASELINE',jsonb_build_object('definition_hash',(select md5(coalesce(string_agg(p.proname||':'||pg_get_functiondef(p.oid),E'\n' order by p.proname),'')) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('curriculum_swap_module_assignment_v1','curriculum_rollback_assignment_swap_v1')),'audit_rows',(select count(*) from public.curriculum_assignment_swap_operations))::text
), findings as (
 select 'IDENTITY' section,'VIDEO_PRODUCTION_IDENTITY' code,case when n=1 then 'PASS' else 'BLOCK' end result,format('canonical Video Production course rows=%s; id=%s',n,coalesce(id::text,'NULL')) details from course_identity
 union all select 'DRAFT_ISOLATION','SAFE_DRAFT_ISOLATION',case when s.n=2 and t.n=1 then 'PASS' else 'BLOCK' end,format('published-only functions=%s/2; trigger=%s',s.n,t.n) from sdi s cross join canonical_trigger t
 union all select 'COMPATIBILITY','LEVEL_COMPATIBILITY',case when n=0 then 'PASS' else 'BLOCK' end,format('incompatible levels=%s',n) from level_conflicts
 union all select 'COMPATIBILITY','MODULE_COMPATIBILITY',case when n=0 then 'PASS' else 'BLOCK' end,format('incompatible modules=%s',n) from module_conflicts
 union all select 'COMPATIBILITY','GLOBAL_SORT_ORDER',case when n=0 then 'PASS' else 'BLOCK' end,format('incompatible global sort rows=%s',n) from sort_conflicts
 union all select 'COMPATIBILITY','CHILD_COMPATIBILITY',case when n=0 then 'PASS' else 'BLOCK' end,format('incompatible populated module children=%s',n) from child_conflicts
 union all select 'SOURCE_DECISIONS','MASTER_NUMBERING_GAPS',case when n=0 then 'PASS' else 'BLOCK' end,format('fabricated Master gap modules=%s',n) from numbering_conflicts
 union all select 'EVIDENCE','VIDEO_PRODUCTION_DEPENDENCIES',case when n=0 then 'PASS' else 'BLOCK' end,format('Video Production evidence/student dependencies=%s',n) from deps
 union all select 'ASSETS','MEDIA_TOOL_BINDINGS',case when media=0 and tools=0 then 'PASS' else 'BLOCK' end,format('instructional media rows=%s; Lab/tool course bindings=%s',media,tools) from assets
 union all select 'MANIFEST','MANIFEST_COUNTS',case when count(*)=49 and count(*) filter(where level=1)=10 and count(*) filter(where level=2)=12 and count(*) filter(where level=3)=15 and count(*) filter(where level=4)=12 and min(sort)=1 and max(sort)=49 and count(distinct sort)=49 and count(*) filter(where level=4 and num in(20,24))=2 then 'PASS' else 'BLOCK' end,format('modules=%s; L1=%s; L2=%s; L3=%s; L4=%s; sort=%s-%s',count(*),count(*) filter(where level=1),count(*) filter(where level=2),count(*) filter(where level=3),count(*) filter(where level=4),min(sort),max(sort)) from manifest
 union all select 'PRESERVATION',code,'INFO','Capture and compare after migration: '||details from baselines
), blockers as(select count(*) filter(where result='BLOCK')::int n from findings)
select section as report_section,code,result,details from findings
union all select 'READINESS','BLOCKERS',case when n=0 then 'PASS' else 'BLOCK' end,format('blocking findings=%s',n) from blockers
union all select 'READINESS','OVERALL',case when n=0 then 'PASS' else 'BLOCK' end,case when n=0 then 'PASS: READY FOR VIDEO PRODUCTION DRAFT ROLLOUT MIGRATION' else 'BLOCK: DO NOT RUN MIGRATION' end from blockers
order by report_section,code;
rollback;
