begin transaction read only;
with
required_tables(name) as(values('courses'),('course_levels'),('course_modules'),('lessons'),('activities'),('submissions'),('lesson_progress'),('xp_ledger'),('certificates'),('enrollments'),('practice_logs'),('activity_progress'),('portfolio_projects'),('module_video_progress'),('module_instructional_media'),('course_progress'),('curriculum_module_revisions'),('curriculum_change_requests'),('curriculum_proposals')),
missing_tables as(select name from required_tables where to_regclass('public.'||name) is null),
required_columns(table_name,column_name) as(values
 ('course_modules','course_level_id'),('course_modules','level_module_number'),('course_modules','sort_order'),('course_modules','core_xp'),('course_modules','core_unlock_threshold'),
 ('activities','module_id'),('activities','lesson_id'),('activities','activity_type'),('activities','xp_type'),('activities','required'),('activities','status'),('activities','rubric'),('activities','passing_score'),('activities','allows_resubmission'),('activities','portfolio_candidate'),('activities','certificate_eligible')),
missing_columns as(select r.* from required_columns r left join information_schema.columns c on c.table_schema='public' and c.table_name=r.table_name and c.column_name=r.column_name where c.column_name is null),
target_course as(select * from public.courses where slug='piano'),
target_level as(select l.* from public.course_levels l join target_course c on c.id=l.course_id where l.level_number=1),
target_module as(select m.* from public.course_modules m join target_course c on c.id=m.course_id join target_level l on l.id=m.course_level_id where m.level_module_number=13),
target_lessons as(select l.* from public.lessons l join target_module m on m.id=l.module_id),
target_activities as(select a.* from public.activities a join target_module m on m.id=a.module_id),
target_hash as(select md5(concat((select coalesce(string_agg(to_jsonb(m)::text,',' order by m.id),'') from target_module m),'|',(select coalesce(string_agg(to_jsonb(l)::text,',' order by l.id),'') from target_lessons l),'|',(select coalesce(string_agg(to_jsonb(a)::text,',' order by a.id),'') from target_activities a))) hash),
practice as(select * from target_activities where activity_type='practice' and not required and xp_type='bonus'),
core as(select * from target_activities where activity_type='performance' and required and xp_type='core'),
rubric_check as(select count(*) criterion_count,coalesce(sum((c->>'weight')::numeric),0) total_weight,count(distinct trim(c->>'name')) unique_names,
  bool_and(jsonb_typeof(c->'bands')='object' and (select count(*) from jsonb_object_keys(c->'bands'))=4 and ((c->'bands' ?& array['Exceeds','Meets','Developing','Not Yet']) or (c->'bands' ?& array['exceeds','meets','developing','not_yet'])) and not exists(select 1 from jsonb_each_text(c->'bands') b where nullif(trim(b.value),'') is null)) bands_ok
  from core a cross join lateral jsonb_array_elements(a.rubric->'criteria') c),
evidence as(select
 (select count(*) from public.submissions s join target_activities a on a.id=s.activity_id) submissions,
 (select count(*) from public.activity_progress p join target_activities a on a.id=p.activity_id) activity_progress,
 (select count(*) from public.practice_logs p join target_activities a on a.id=p.activity_id) practice_logs,
 (select count(*) from public.portfolio_projects p join target_activities a on a.id=p.activity_id) portfolio_projects,
 (select count(*) from public.lesson_progress p join target_lessons l on l.id=p.lesson_id) lesson_progress,
 (select count(*) from public.xp_ledger x join target_module m on x.module_id=m.id) xp_module,
 (select count(*) from public.xp_ledger x where x.source_id in(select id from target_activities) or x.source_id in(select id from target_lessons)) xp_source,
 (select count(*) from public.xp_ledger x join target_module m on m.id=x.module_id where x.xp_type='core' and x.metadata->>'component'='mastery') mastery,
 (select count(*) from public.module_video_progress p join target_module m on m.id=p.module_id) media_progress,
 (select count(*) from public.module_instructional_media p join target_module m on m.id=p.module_id) media_rows,
 (select count(*) from public.course_progress p where p.current_module_id in(select id from target_module) or p.current_lesson_id in(select id from target_lessons)) course_progress,
 (select count(*) from public.curriculum_module_revisions r where r.module_id in(select id from target_module)) module_revisions,
 (select count(*) from public.curriculum_change_requests r where r.module_id in(select id from target_module) or r.activity_id in(select id from target_activities) or r.lesson_id in(select id from target_lessons)) change_requests,
 (select count(*) from public.curriculum_proposals p join public.curriculum_change_requests r on r.id=p.request_id where r.module_id in(select id from target_module) or r.activity_id in(select id from target_activities) or r.lesson_id in(select id from target_lessons)) proposals),
safe_draft_defs as(select p.proname,regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g') definition from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('jpac_sync_enrollment_progress','jpac_enforce_canonical_enrollment_progress')),
safe_draft as(select count(*)=2 and bool_and((select count(*) from regexp_matches(definition,'m\.status=''published''','g'))=2 and definition not like '%m.status<>''archived''%') ok from safe_draft_defs),
activity_triggers as(select count(*) total,count(*) filter(where t.tgname='set_updated_at' and p.proname='set_updated_at' and t.tgenabled<>'D') expected,jsonb_agg(jsonb_build_object('trigger',t.tgname,'function',p.proname,'enabled',t.tgenabled) order by t.tgname) details from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid where n.nspname='public' and c.relname='activities' and not t.tgisinternal),
protected_functions as(select count(distinct p.proname) names,jsonb_agg(jsonb_build_object('name',p.proname,'args',pg_get_function_identity_arguments(p.oid),'hash',md5(pg_get_functiondef(p.oid))) order by p.proname,pg_get_function_identity_arguments(p.oid)) details from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('jpac_sync_enrollment_progress','jpac_enforce_canonical_enrollment_progress','jpac_award_module_core_component','jpac_finalize_module_mastery','jpac_module_completion','jpac_module_is_unlocked','jpac_submit_module_activity','jpac_review_module_submission','jpac_assess_module_submission','jpac_review_submission','jpac_issue_completion_certificate','jpac_student_has_course_access')),
singing as(select count(distinct c.id) course_count,md5(coalesce(string_agg(concat_ws('|',to_jsonb(c)::text,to_jsonb(m)::text,to_jsonb(l)::text,to_jsonb(a)::text),',' order by c.id,m.id,l.id,a.id),'')) hash from public.courses c left join public.course_modules m on m.course_id=c.id left join public.lessons l on l.module_id=m.id left join public.activities a on a.module_id=m.id where c.slug='singing'),
singing_evidence as(select jsonb_build_object('submissions',jsonb_build_object('count',(select count(*) from public.submissions s join public.activities a on a.id=s.activity_id join public.course_modules m on m.id=a.module_id join public.courses c on c.id=m.course_id where c.slug='singing'),'hash',(select md5(coalesce(string_agg(to_jsonb(s)::text,',' order by s.id),'')) from public.submissions s join public.activities a on a.id=s.activity_id join public.course_modules m on m.id=a.module_id join public.courses c on c.id=m.course_id where c.slug='singing')),'lesson_progress',jsonb_build_object('count',(select count(*) from public.lesson_progress p join public.lessons l on l.id=p.lesson_id join public.course_modules m on m.id=l.module_id join public.courses c on c.id=m.course_id where c.slug='singing'),'hash',(select md5(coalesce(string_agg(to_jsonb(p)::text,',' order by p.id),'')) from public.lesson_progress p join public.lessons l on l.id=p.lesson_id join public.course_modules m on m.id=l.module_id join public.courses c on c.id=m.course_id where c.slug='singing')),'xp_ledger',jsonb_build_object('count',(select count(*) from public.xp_ledger x join public.courses c on c.id=x.course_id where c.slug='singing'),'hash',(select md5(coalesce(string_agg(to_jsonb(x)::text,',' order by x.id),'')) from public.xp_ledger x join public.courses c on c.id=x.course_id where c.slug='singing')),'mastery',jsonb_build_object('count',(select count(*) from public.xp_ledger x join public.courses c on c.id=x.course_id where c.slug='singing' and x.xp_type='core' and x.metadata->>'component'='mastery'),'hash',(select md5(coalesce(string_agg(to_jsonb(x)::text,',' order by x.id),'')) from public.xp_ledger x join public.courses c on c.id=x.course_id where c.slug='singing' and x.xp_type='core' and x.metadata->>'component'='mastery'))) details),
student_state as(select jsonb_build_object('enrollments',jsonb_build_object('count',(select count(*) from public.enrollments),'hash',(select md5(coalesce(string_agg(concat_ws('|',id,student_id,course_id,status,progress),',' order by id),'')) from public.enrollments)),'submissions',jsonb_build_object('count',(select count(*) from public.submissions),'hash',(select md5(coalesce(string_agg(concat_ws('|',id,activity_id,student_id,status,score),',' order by id),'')) from public.submissions)),'lesson_progress',jsonb_build_object('count',(select count(*) from public.lesson_progress),'hash',(select md5(coalesce(string_agg(concat_ws('|',id,lesson_id,student_id,status,percent_complete),',' order by id),'')) from public.lesson_progress)),'xp_ledger',jsonb_build_object('count',(select count(*) from public.xp_ledger),'hash',(select md5(coalesce(string_agg(concat_ws('|',id,student_id,amount,module_id,source_id),',' order by id),'')) from public.xp_ledger)),'certificates',jsonb_build_object('count',(select count(*) from public.certificates),'hash',(select md5(coalesce(string_agg(concat_ws('|',id,student_id,course_id,status),',' order by id),'')) from public.certificates))) details),
fk_inventory as(select jsonb_agg(jsonb_build_object('constraint',con.conname,'from_table',src.relname,'definition',pg_get_constraintdef(con.oid)) order by src.relname,con.conname) details from pg_constraint con join pg_class src on src.oid=con.conrelid join pg_class dst on dst.oid=con.confrelid join pg_namespace n on n.oid=src.relnamespace where con.contype='f' and n.nspname='public' and dst.relname in('activities','course_modules','lessons','courses','course_levels')),
reports(ord,report_section,code,result,details) as(
 select 10,'REQUIRED_SCHEMA','ASV1-SCHEMA',case when not exists(select 1 from missing_tables) and not exists(select 1 from missing_columns) then 'PASS' else 'BLOCK' end,jsonb_build_object('missing_tables',coalesce((select jsonb_agg(name) from missing_tables),'[]'),'missing_columns',coalesce((select jsonb_agg(to_jsonb(m)) from missing_columns m),'[]'))::text
 union all select 12,'UUID_SUPPORT','ASV1-UUID',case when to_regprocedure('gen_random_uuid()') is not null and to_regprocedure('digest(bytea,text)') is not null then 'PASS' else 'BLOCK' end,jsonb_build_object('gen_random_uuid',to_regprocedure('gen_random_uuid()'),'digest',to_regprocedure('digest(bytea,text)'))::text
 union all select 14,'ADMIN_AUTHORIZATION','ASV1-AUTH',case when to_regprocedure('public.is_admin()') is not null and pg_get_functiondef(to_regprocedure('public.is_admin()')) like '%admin%' and pg_get_functiondef(to_regprocedure('public.is_admin()')) like '%developer%' then 'PASS' else 'BLOCK' end,case when to_regprocedure('public.is_admin()') is null then 'public.is_admin() missing' else jsonb_build_object('hash',md5(pg_get_functiondef(to_regprocedure('public.is_admin()'))))::text end
 union all select 20,'TARGET_COURSE','ASV1-COURSE',case when (select count(*) from target_course)=1 then 'PASS' else 'BLOCK' end,coalesce((select jsonb_build_object('id',id,'slug',slug,'status',status)::text from target_course),'Piano missing or ambiguous')
 union all select 30,'TARGET_LEVEL','ASV1-LEVEL',case when (select count(*) from target_level)=1 then 'PASS' else 'BLOCK' end,coalesce((select jsonb_build_object('id',id,'level_number',level_number,'title',title,'status',status)::text from target_level),'Level missing or ambiguous')
 union all select 40,'TARGET_MODULE','ASV1-MODULE',case when (select count(*) from target_module)=1 and (select bool_and(title='Save Draft Test Module' and sort_order=49 and status='draft' and core_xp=625 and intro_core_xp=50 and video_core_xp=100 and assignment_core_xp=350 and mastery_core_xp=125 and core_unlock_threshold=438) from target_module) and (select count(*) from target_lessons)=3 and (select count(*) from target_activities)=2 then 'PASS' else 'BLOCK' end,coalesce((select jsonb_build_object('id',id,'number',level_module_number,'sort_order',sort_order,'title',title,'status',status,'lesson_count',(select count(*) from target_lessons),'activity_count',(select count(*) from target_activities),'curriculum_hash',(select hash from target_hash))::text from target_module),'Module missing or ambiguous')
 union all select 50,'TARGET_PRACTICE','ASV1-PRACTICE',case when count(*)=1 and bool_and(status='draft' and activity_type='practice' and not required and xp_reward=0 and xp_type='bonus' and passing_score=70 and allows_resubmission and not portfolio_candidate and not coalesce(certificate_eligible,false) and lesson_id is null) then 'PASS' else 'BLOCK' end,coalesce(jsonb_agg(jsonb_build_object('id',id,'title',title,'status',status,'lesson_id',lesson_id))::text,'[]') from practice
 union all select 60,'TARGET_CORE','ASV1-CORE',case when count(*)=1 and bool_and(status='draft' and activity_type='performance' and required and xp_reward=350 and xp_type='core' and passing_score=70 and allows_resubmission and not portfolio_candidate and not coalesce(certificate_eligible,false) and lesson_id is null) and (select criterion_count=5 and total_weight=100 and unique_names=5 and bands_ok from rubric_check) then 'PASS' else 'BLOCK' end,coalesce(jsonb_agg(jsonb_build_object('id',id,'title',title,'status',status,'lesson_id',lesson_id,'rubric',(select to_jsonb(r) from rubric_check r)))::text,'[]') from core
 union all select 70,'EVIDENCE_DEPENDENCIES','ASV1-EVIDENCE',case when submissions+activity_progress+practice_logs+portfolio_projects+lesson_progress+xp_module+xp_source+mastery+media_progress+media_rows+course_progress+module_revisions+change_requests+proposals=0 then 'PASS' else 'BLOCK' end,to_jsonb(e)::text from evidence e
 union all select 80,'SAFE_DRAFT_ISOLATION','ASV1-DRAFT-ISOLATION',case when ok then 'PASS' else 'BLOCK' end,jsonb_build_object('published_only',ok)::text from safe_draft
 union all select 90,'ACTIVITY_TRIGGER_BASELINE','ASV1-TRIGGERS',case when total=1 and expected=1 then 'PASS' else 'BLOCK' end,jsonb_build_object('total',total,'expected',expected,'triggers',details)::text from activity_triggers
 union all select 100,'PROTECTED_FUNCTION_BASELINE','ASV1-FUNCTIONS',case when names>=10 then 'INFO' else 'BLOCK' end,jsonb_build_object('function_names',names,'functions',details)::text from protected_functions
 union all select 110,'SINGING_BASELINE','ASV1-SINGING',case when course_count=1 then 'INFO' else 'BLOCK' end,jsonb_build_object('course_count',course_count,'hash',hash)::text from singing
 union all select 115,'SINGING_EVIDENCE_BASELINE','ASV1-SINGING-EVIDENCE','INFO',details::text from singing_evidence
 union all select 120,'STUDENT_STATE_BASELINE','ASV1-STUDENT-STATE','INFO',details::text from student_state
 union all select 130,'FOREIGN_KEY_INVENTORY','ASV1-FKS','INFO',coalesce(details,'[]')::text from fk_inventory
 union all select 140,'OBJECTS_ABSENT','ASV1-ABSENT',case when to_regclass('public.curriculum_assignment_swap_operations') is null and to_regprocedure('public.curriculum_swap_module_assignment_v1(jsonb)') is null and to_regprocedure('public.curriculum_rollback_assignment_swap_v1(uuid)') is null then 'PASS' else 'BLOCK' end,jsonb_build_object('audit_table',to_regclass('public.curriculum_assignment_swap_operations'),'swap_rpc',to_regprocedure('public.curriculum_swap_module_assignment_v1(jsonb)'),'rollback_rpc',to_regprocedure('public.curriculum_rollback_assignment_swap_v1(uuid)'))::text),
blockers as(select code,details from reports where result='BLOCK'),
final as(select * from reports union all select 900,'BLOCKERS','ASV1-BLOCKERS',case when exists(select 1 from blockers) then 'BLOCK' else 'PASS' end,coalesce((select jsonb_agg(jsonb_build_object('code',code,'details',details))::text from blockers),'No blockers detected') union all select 999,'OVERALL','ASV1-OVERALL',case when exists(select 1 from blockers) then 'BLOCK' else 'PASS' end,case when exists(select 1 from blockers) then 'BLOCK: DO NOT RUN MIGRATION' else 'PASS: READY FOR ASSIGNMENT SWAP V1 MIGRATION REVIEW' end)
select report_section,code,result,details from final order by ord,code;
rollback;
