-- Review-only Piano full draft rollout artifact. Do not execute without approved preflight.
begin transaction read only;
with piano as(select id from public.courses where slug='piano'), level_counts as(select l.level_number,count(m.id) module_count from public.course_levels l left join public.course_modules m on m.course_level_id=l.id where l.course_id=(select id from piano) group by l.level_number), findings as(
 select 'LEVELS' code,case when (select count(*) from public.course_levels where course_id=(select id from piano))=4 and not exists(select 1 from public.course_levels where course_id=(select id from piano) and status<>'draft') then 'PASS' else 'FAIL' end result
 union all select 'MODULES',case when (select count(*) from public.course_modules where course_id=(select id from piano))=48 and not exists(select 1 from level_counts where module_count<>12) then 'PASS' else 'FAIL' end
 union all select 'LESSONS',case when (select count(*) from public.lessons l join public.course_modules m on m.id=l.module_id where m.course_id=(select id from piano))=144 and not exists(select 1 from public.lessons l join public.course_modules m on m.id=l.module_id where m.course_id=(select id from piano) and l.status<>'draft') and not exists(select 1 from public.course_modules m where m.course_id=(select id from piano) and (select count(*) from public.lessons l where l.module_id=m.id)<>3) then 'PASS' else 'FAIL' end
 union all select 'ACTIVITIES',case when (select count(*) from public.activities where course_id=(select id from piano))=96 and (select count(*) from public.activities where course_id=(select id from piano) and activity_type='practice' and xp_type='bonus' and xp_reward=0 and not required and status='draft')=48 and (select count(*) from public.activities where course_id=(select id from piano) and activity_type='performance' and xp_type='core' and xp_reward=350 and required and passing_score=70 and allows_resubmission and status='draft')=48 and not exists(select 1 from public.course_modules m where m.course_id=(select id from piano) and (select count(*) from public.activities a where a.module_id=m.id)<>2) then 'PASS' else 'FAIL' end
 union all select 'RUBRICS',case when not exists(select 1 from public.activities a where a.course_id=(select id from piano) and a.xp_type='core' and ((select count(*) from jsonb_array_elements(a.rubric->'criteria'))<>5 or (select sum((x->>'weight')::int) from jsonb_array_elements(a.rubric->'criteria') x)<>100)) then 'PASS' else 'FAIL' end
 union all select 'DRAFT_ISOLATION',case when not exists(select 1 from public.course_modules where course_id=(select id from piano) and status<>'draft') then 'PASS' else 'FAIL' end
 union all select 'MEDIA_LAB',case when not exists(select 1 from public.module_instructional_media im join public.course_modules m on m.id=im.module_id where m.course_id=(select id from piano)) and not exists(select 1 from public.course_modules where course_id=(select id from piano) and (lab_tool_id is not null or active_instructional_media_id is not null)) then 'PASS' else 'FAIL' end
 union all select 'MODULE1',case when (select count(*) from public.course_modules m join public.course_levels l on l.id=m.course_level_id where m.course_id=(select id from piano) and l.level_number=1 and m.level_module_number=1 and m.title='Piano Posture and Hand Position' and m.status='draft')=1 then 'PASS' else 'FAIL' end
)
select * from findings
union all select 'PRESERVE_SINGING_CURRICULUM',md5(coalesce((select string_agg(to_jsonb(m)::text,'|' order by m.id) from public.course_modules m join public.courses c on c.id=m.course_id where c.slug='singing'),'')||coalesce((select string_agg(to_jsonb(l)::text,'|' order by l.id) from public.lessons l join public.course_modules m on m.id=l.module_id join public.courses c on c.id=m.course_id where c.slug='singing'),'')||coalesce((select string_agg(to_jsonb(a)::text,'|' order by a.id) from public.activities a join public.courses c on c.id=a.course_id where c.slug='singing'),''))
union all select 'PRESERVE_STUDENT_STATE',md5(coalesce((select string_agg(to_jsonb(e)::text,'|' order by e.id) from public.enrollments e),'')||coalesce((select string_agg(to_jsonb(s)::text,'|' order by s.id) from public.submissions s),'')||coalesce((select string_agg(to_jsonb(x)::text,'|' order by x.id) from public.xp_ledger x),''))
union all select 'PRESERVE_SHARED_FUNCTIONS',md5(coalesce((select string_agg(pg_get_functiondef(p.oid),'|' order by p.proname,p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'jpac_%'),''))
union all select 'PRESERVE_CAREER_PATHS',md5(coalesce((select string_agg(to_jsonb(cp)::text,'|' order by cp.id) from public.career_paths cp),'')||coalesce((select string_agg(to_jsonb(cm)::text,'|' order by cm.id) from public.career_milestones cm),''))
union all select 'PRESERVE_PIANO_MODULE_1',md5(coalesce((select string_agg(to_jsonb(m)::text,'|' order by m.id) from public.course_modules m join public.course_levels l on l.id=m.course_level_id where m.course_id=(select id from piano) and l.level_number=1 and m.level_module_number=1),'')||coalesce((select string_agg(to_jsonb(ls)::text,'|' order by ls.id) from public.lessons ls join public.course_modules m on m.id=ls.module_id join public.course_levels l on l.id=m.course_level_id where m.course_id=(select id from piano) and l.level_number=1 and m.level_module_number=1),'')||coalesce((select string_agg(to_jsonb(a)::text,'|' order by a.id) from public.activities a join public.course_modules m on m.id=a.module_id join public.course_levels l on l.id=m.course_level_id where m.course_id=(select id from piano) and l.level_number=1 and m.level_module_number=1),''))
union all select 'OVERALL',case when exists(select 1 from findings where result='FAIL') then 'FAIL' else 'PASS: 48-MODULE DRAFT ROLLOUT VALID; COMPARE PRESERVATION HASHES TO PREFLIGHT' end;
rollback;
