-- READ ONLY. Compare student/Singing hashes and counts with retained preflight output.
begin transaction read only;

do $$ declare v_course uuid;v_level uuid;v_module uuid;v_total numeric;
 v_rubric jsonb:=jsonb_build_object('criteria',jsonb_build_array(
  jsonb_build_object('name','Technique and safe hand shape','weight',35,'bands',jsonb_build_object('exceeds','Consistently uses a natural, functional hand shape with flexible wrist and independently releases tension.','meets','Generally uses safe hand shape and wrist freedom with minor inconsistency.','developing','Shows partial technique; recurring tension or finger collapse affects control.','not_yet','Evidence is missing, substantially uncontrolled, or presents an unresolved safety concern.')),
  jsonb_build_object('name','Posture and body alignment','weight',25,'bands',jsonb_build_object('exceeds','Setup is balanced, supported, individualized, and consistently maintained.','meets','Setup is functional and generally balanced with minor alignment issues.','developing','Reaching, crowding, instability, or tension affects playing.','not_yet','Setup cannot be evaluated or does not yet support safe functional playing.')),
  jsonb_build_object('name','Finger control and five-finger pattern accuracy','weight',20,'bands',jsonb_build_object('exceeds','Pattern is accurate, clear, controlled, and reasonably even.','meets','Pattern is recognizable and mostly accurate with minor inconsistency.','developing','Repeated accuracy or control problems interrupt the pattern.','not_yet','Pattern evidence is absent or insufficient to evaluate.')),
  jsonb_build_object('name','Student reflection/self-awareness','weight',10,'bands',jsonb_build_object('exceeds','Specifically identifies a strength, adjustment, and useful next step.','meets','Identifies all required reflection elements with adequate understanding.','developing','Reflection is vague, incomplete, or weakly connected to the evidence.','not_yet','Reflection is absent or does not demonstrate meaningful self-awareness.')),
  jsonb_build_object('name','Preparation and submission completeness','weight',10,'bands',jsonb_build_object('exceeds','Evidence is complete, clear, and easy to review.','meets','Required evidence is present with minor clarity issues.','developing','One required component is incomplete or difficult to evaluate.','not_yet','Multiple components are absent or evidence cannot be reviewed reliably.'))
 ));
begin
 if (select count(*) from public.courses where slug='piano')<>1 then raise exception 'Expected exactly one canonical Piano course'; end if;
 select id into v_course from public.courses where slug='piano';
 select id into v_level from public.course_levels where course_id=v_course and level_number=1 and title='Beginner' and description='Beginner Piano foundations. Draft review only.' and learning_objectives=array['Build healthy setup and foundational keyboard control.']::text[] and status='draft' and core_xp_target=6250 and review_notes='Piano Module 1 pilot; AI-PROPOSED content requires leadership and piano-teacher review.' and approved_by is null and approved_at is null;
 if v_level is null then raise exception 'Compatible draft Piano Level 1 missing'; end if;
 select id into v_module from public.course_modules where course_id=v_course and course_level_id=v_level and level_module_number=1 and sort_order=1 and title='Piano Posture and Hand Position'
  and status='draft' and xp_value=625 and core_xp=625 and intro_core_xp=50 and video_core_xp=100 and assignment_core_xp=350 and mastery_core_xp=125 and core_unlock_threshold=438 and bonus_xp_available=0
  and description='Establish a balanced or adaptive setup, natural hand shape, relaxed wrists, and controlled five-finger movement.' and short_intro='Build a comfortable Piano setup before speed: align, relax, play slowly, observe, and adjust.'
  and primary_video_url is null and video_provider is null and video_title is null and video_duration_seconds is null and active_instructional_media_id is null
  and video_brief='NEEDS REVIEW: Validate source video accuracy, availability, licensing, captions, transcript quality, and alignment before creating media.'
  and aria_coaching_targets=jsonb_build_object('advisory_only',true,'targets',jsonb_build_array('posture','bench distance','curved fingers','relaxed wrists','finger independence','wrist tension','finger collapse','hand positioning','slow practice','confidence building'),'prohibited',jsonb_build_array('assess','approve evidence','award XP','grant mastery','unlock content','diagnose injury'))
  and lab_tool_id is null and jpac_tool_activity='{}' and real_world_activity='{}' and career_connection='' and career_mission_ideas='[]' and not portfolio_moment
  and review_notes='AI-PROPOSED — leadership and piano-teacher review required. Media NEEDS REVIEW; tools NEEDS CATALOG REVIEW.' and approved_by is null and approved_at is null;
 if v_module is null then raise exception 'Compatible draft Piano Module 1 missing'; end if;
 if (select count(*) from public.lessons where module_id=v_module)<>3 or (select count(*) from public.lessons where module_id=v_module and wix_lesson_id is null and wix_lesson_url is null and lesson_type='interactive' and xp_value=0 and status='draft' and (
  (sort_order=1 and duration_minutes=20 and title='Bench and Body Alignment' and description='Set up the bench or adaptive playing position so your body feels supported, flexible, and ready to move.' and short_summary='Build a stable and comfortable playing setup.' and learning_objective='Establish supported seating, appropriate keyboard distance, relaxed shoulders, and functional arm alignment.' and content_blocks=jsonb_build_array('Sit near the front of the bench or use an approved adaptive position.','Support both feet or use an appropriate foot support.','Adjust distance so elbows can move without reaching or crowding.','Keep the spine tall but flexible and release shoulders, neck, and jaw.','Make one intentional setup adjustment and explain why it helped.') and technique_cues=array['Shoulders away from ears','Elbows have room to move','Supported, not stiff','Stop and contact staff if playing causes pain']::text[] and common_mistakes=array['Reaching for the keyboard','Crowding the keyboard','Raised shoulders','Rigid posture']::text[] and self_check='Can you name one setup adjustment that improved comfort or balance?' and resource_brief='AI-PROPOSED. Alternatives: wheelchair or adaptive seating, foot support, photographs with narration, live teacher demonstration, or assistive communication.')
  or (sort_order=2 and duration_minutes=20 and title='Curved Fingers and Relaxed Wrists' and description='Practice a natural hand shape, flexible wrist, and gentle controlled key presses.' and short_summary='Use natural hand shape without unnecessary tension.' and learning_objective='Establish a functional finger curve, flexible wrist, relaxed thumb, and controlled press-and-release motion.' and content_blocks=jsonb_build_array('Observe the hand natural resting shape.','Place five fingers on neighboring white keys without pressing.','Press and release one key at a time.','Pause after each sequence and release the wrist.','Name one sign of tension and one reset strategy.') and technique_cues=array['Natural rather than forced curve','Flexible wrist','Release after each note','Slow down when joints collapse']::text[] and common_mistakes=array['Forced finger curve','Rigid or collapsed wrist','Tucked rigid thumb','Excessive finger lifting']::text[] and self_check='What tension sign did you notice, and how did you reset?' and resource_brief='AI-PROPOSED. Alternatives: approved individual hand position, one hand, fewer notes, adaptive keyboard, live or narrated evidence.')
  or (sort_order=3 and duration_minutes=25 and title='Five-Finger Technique Check' and description='Combine setup and hand technique in a slow five-note pattern with each hand separately.' and short_summary='Apply balanced setup to a controlled five-finger pattern.' and learning_objective='Play an approved five-note pattern with functional posture, hand shape, wrist freedom, note-order accuracy, and self-awareness.' and content_blocks=jsonb_build_array('Place one hand over an approved five-note pattern such as C-D-E-F-G.','Play upward and downward slowly.','Pause and release tension before repeating with the other hand.','Use about 60 BPM only when it supports relaxed control.','Identify one strength and one next improvement.') and technique_cues=array['Control before speed','Clear even notes','Pause and reset','Hands separate first']::text[] and common_mistakes=array['Rushing to match the metronome','Continuing through tension','Finger collapse','Unplanned restart']::text[] and self_check='What improved between your first and second controlled attempt?' and resource_brief='AI-PROPOSED. Alternatives: fewer notes, one hand, adapted controller, audio plus teacher-observed setup, or counted pulse without metronome.')
 ))<>3 then raise exception 'Exact lesson payload invariant failed'; end if;
 if (select count(*) from public.activities where module_id=v_module)<>2 then raise exception 'Unexpected Module 1 activity count'; end if;
 if (select count(*) from public.activities where module_id=v_module and course_id=v_course and lesson_id is null and title='Guided Piano Setup Practice' and description='Low-pressure preparation before the assessed challenge.' and activity_type='practice' and instructions='Check the bench or adaptive position, body alignment, natural hand shape, and wrist. Play the approved five-finger pattern with each hand separately. Identify one strength, make one adjustment, and repeat. No submission is required.' and submission_type='none' and xp_reward=0 and estimated_minutes=20 and xp_type='bonus' and not required and status='draft' and rubric='{}' and skill_tags=array['piano setup','posture','hand position','five-finger pattern']::text[] and ai_summary='AI-PROPOSED; optional, non-progressive, and non-assessed.' and passing_score=70 and allows_resubmission and not portfolio_candidate and not certificate_eligible)<>1 then raise exception 'Exact practice payload invariant failed'; end if;
 if (select count(*) from public.activities where module_id=v_module and course_id=v_course and lesson_id is null and title='Balanced Piano Setup Challenge' and description='Demonstrate a balanced or adaptive setup and controlled beginner five-finger technique.' and activity_type='performance' and instructions='Submit JPAC video evidence showing or explaining your playing position and keyboard distance, natural hand shape, flexible wrist, and two upward/downward repetitions of an approved five-finger pattern with each hand separately unless an accommodation is approved. Include one strength, one adjustment, and one next improvement. Allowed alternatives through existing teacher review include live demonstration, multiple short angles, photographs plus audio, audio plus teacher-observed setup, adapted keyboard, or one-hand evidence. Stop and contact staff if playing causes pain.' and submission_type='video' and xp_reward=350 and estimated_minutes=30 and xp_type='core' and required and status='draft' and passing_score=70 and allows_resubmission and rubric=v_rubric and skill_tags=array['piano setup','posture','hand position','wrist freedom','five-finger pattern','self-reflection']::text[] and ai_summary='AI-PROPOSED — teacher review required. ARIA cannot assess, approve, award XP, grant mastery, or unlock content.' and not portfolio_candidate and not certificate_eligible)<>1 then raise exception 'Exact Core Challenge payload invariant failed'; end if;
 select sum((x->>'weight')::numeric) into v_total from public.activities a cross join lateral jsonb_array_elements(a.rubric->'criteria') x where a.module_id=v_module and a.title='Balanced Piano Setup Challenge';
 if coalesce(v_total,-1)<>100 then raise exception 'Rubric total invalid'; end if;
 if (select count(*) from public.activities a cross join lateral jsonb_array_elements(a.rubric->'criteria') x where a.module_id=v_module and a.title='Balanced Piano Setup Challenge')<>5 then raise exception 'Rubric must contain exactly five criteria'; end if;
 if (select count(distinct x->>'name') from public.activities a cross join lateral jsonb_array_elements(a.rubric->'criteria') x where a.module_id=v_module and a.title='Balanced Piano Setup Challenge')<>5 then raise exception 'Rubric names must be unique'; end if;
 if (select count(*) from public.activities a cross join lateral jsonb_array_elements(a.rubric->'criteria') x where a.module_id=v_module and a.title='Balanced Piano Setup Challenge' and ((x->>'name'='Technique and safe hand shape' and (x->>'weight')::numeric=35) or (x->>'name'='Posture and body alignment' and (x->>'weight')::numeric=25) or (x->>'name'='Finger control and five-finger pattern accuracy' and (x->>'weight')::numeric=20) or (x->>'name'='Student reflection/self-awareness' and (x->>'weight')::numeric=10) or (x->>'name'='Preparation and submission completeness' and (x->>'weight')::numeric=10)))<>5 then raise exception 'Rubric names or weights differ from approval'; end if;
 if exists(select 1 from public.activities a cross join lateral jsonb_array_elements(a.rubric->'criteria') x where a.module_id=v_module and a.title='Balanced Piano Setup Challenge' and (jsonb_typeof(x->'weight')<>'number' or (x->>'weight')::numeric<=0 or jsonb_typeof(x->'bands')<>'object' or not(x->'bands' ?& array['exceeds','meets','developing','not_yet']) or (select count(*) from jsonb_object_keys(x->'bands'))<>4 or nullif(trim(x->'bands'->>'exceeds'),'') is null or nullif(trim(x->'bands'->>'meets'),'') is null or nullif(trim(x->'bands'->>'developing'),'') is null or nullif(trim(x->'bands'->>'not_yet'),'') is null)) then raise exception 'Rubric band structure invalid'; end if;
 if exists(select 1 from public.module_instructional_media where module_id=v_module) then raise exception 'No media row permitted'; end if;
end $$;

select 'COMPARE TO PREFLIGHT' instruction,
 'COUNT ONLY — supplemental; not proof of content preservation' evidence_scope,
 (select count(*) from public.enrollments e join public.courses c on c.id=e.course_id where c.slug='piano') piano_enrollments,
 (select count(*) from public.course_progress cp join public.courses c on c.id=cp.course_id where c.slug='piano') piano_course_progress,
 (select count(*) from public.xp_ledger x join public.courses c on c.id=x.course_id where c.slug='piano') piano_xp,
 (select count(*) from public.submissions s join public.activities a on a.id=s.activity_id join public.courses c on c.id=a.course_id where c.slug='piano') piano_submissions,
 (select count(*) from public.student_career_progress) career_progress_rows,
 (select count(*) from public.career_paths) career_path_rows,
 (select count(*) from public.career_milestones) career_milestone_rows,
 (select count(*) from public.lab_tool_courses ltc join public.courses c on c.id=ltc.course_id where c.slug='piano') piano_lab_bindings;

select c.id course_id,c.status,c.module_count,c.total_xp,c.core_xp_total,
 'COUNT ONLY — supplemental; not proof of content preservation' evidence_scope,
 (select count(*) from public.course_levels where course_id=c.id) levels,
 (select count(*) from public.course_modules where course_id=c.id) modules,
 (select count(*) from public.lessons l join public.course_modules m on m.id=l.module_id where m.course_id=c.id) lessons,
 (select count(*) from public.activities where course_id=c.id) activities,
 (select count(*) from public.enrollments where course_id=c.id) enrollments,
 (select count(*) from public.xp_ledger where course_id=c.id) xp_rows,
 md5(concat_ws('|',c.id::text,c.status,c.module_count::text,c.total_xp::text,c.core_xp_total::text,c.updated_at::text)) course_hash
from public.courses c where c.slug='singing';

-- Rerun-readiness: all deterministic batch identities either exist exactly once or were safely replaced by compatible reused identities.
with target as(select m.id from public.course_modules m join public.course_levels l on l.id=m.course_level_id join public.courses c on c.id=m.course_id where c.slug='piano' and l.level_number=1 and m.level_module_number=1)
select
  'COUNT ONLY — supplemental; not proof of content preservation' evidence_scope,
  3-(select count(*) from public.lessons where module_id in(select id from target) and title in('Bench and Body Alignment','Curved Fingers and Relaxed Wrists','Five-Finger Technique Check')) missing_lessons,
  2-(select count(*) from public.activities where module_id in(select id from target) and title in('Guided Piano Setup Practice','Balanced Piano Setup Challenge')) missing_activities,
  greatest((select count(*) from public.lessons where module_id in(select id from target))-3,0) unexpected_lesson_duplicates,
  greatest((select count(*) from public.activities where module_id in(select id from target))-2,0) unexpected_activity_duplicates,
  0 records_needing_correction,
  'PASS only when every value is zero and all preceding exact assertions pass' interpretation;

-- Must match the identically named preflight hashes exactly.
select 'piano_course_full' set_name,md5(coalesce(string_agg(to_jsonb(c)::text,'|' order by c.id),'')) set_hash,count(*) row_count from public.courses c where c.slug='piano'
union all select 'piano_level1_enrollments_full',md5(coalesce(string_agg(to_jsonb(e)::text,'|' order by e.id),'')),count(*) from public.enrollments e join public.courses c on c.id=e.course_id where c.slug='piano' and e.level=1
union all select 'piano_level1_course_progress_full',md5(coalesce(string_agg(to_jsonb(cp)::text,'|' order by cp.enrollment_id),'')),count(*) from public.course_progress cp join public.enrollments e on e.id=cp.enrollment_id join public.courses c on c.id=e.course_id where c.slug='piano' and e.level=1
union all select 'career_paths_full',md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id),'')),count(*) from public.career_paths x
union all select 'career_milestones_full',md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id),'')),count(*) from public.career_milestones x
union all select 'student_career_progress_full',md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.student_id,x.career_path_id),'')),count(*) from public.student_career_progress x;

select 'singing_course_full' set_name,md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id),'')) set_hash,count(*) row_count from public.courses x where x.slug='singing'
union all select 'singing_levels_full',md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id),'')),count(*) from public.course_levels x join public.courses c on c.id=x.course_id where c.slug='singing'
union all select 'singing_modules_full',md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id),'')),count(*) from public.course_modules x join public.courses c on c.id=x.course_id where c.slug='singing'
union all select 'singing_lessons_full',md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id),'')),count(*) from public.lessons x join public.course_modules m on m.id=x.module_id join public.courses c on c.id=m.course_id where c.slug='singing'
union all select 'singing_activities_full',md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id),'')),count(*) from public.activities x join public.courses c on c.id=x.course_id where c.slug='singing'
union all select 'singing_media_full',md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id),'')),count(*) from public.module_instructional_media x join public.course_modules m on m.id=x.module_id join public.courses c on c.id=m.course_id where c.slug='singing'
union all select 'singing_enrollments_full',md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id),'')),count(*) from public.enrollments x join public.courses c on c.id=x.course_id where c.slug='singing'
union all select 'singing_progress_full',md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.enrollment_id),'')),count(*) from public.course_progress x join public.courses c on c.id=x.course_id where c.slug='singing'
union all select 'singing_submissions_full',md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id),'')),count(*) from public.submissions x join public.activities a on a.id=x.activity_id join public.courses c on c.id=a.course_id where c.slug='singing'
union all select 'singing_xp_full',md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id),'')),count(*) from public.xp_ledger x join public.courses c on c.id=x.course_id where c.slug='singing';

select p.proname,md5(pg_get_functiondef(p.oid)) definition_hash
from pg_proc p join pg_namespace n on n.oid=p.pronamespace
where n.nspname='public' and p.proname in('jpac_module_completion','jpac_module_is_unlocked','jpac_finalize_module_mastery','jpac_sync_enrollment_progress','jpac_submit_module_activity','jpac_review_module_submission','jpac_assess_module_submission')
order by p.proname,p.oid;
rollback;
