begin transaction read only;
with
rpc_rows as(select p.oid,p.proname,p.prosecdef,p.proconfig,coalesce(array_to_string(p.proacl,','),'') acl,md5(pg_get_functiondef(p.oid)) definition_hash,pg_get_functiondef(p.oid) definition from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and (p.oid=to_regprocedure('public.curriculum_swap_module_assignment_v1(jsonb)') or p.oid=to_regprocedure('public.curriculum_rollback_assignment_swap_v1(uuid)'))),
rpc_check as(select count(*) rpc_count,bool_and(prosecdef and proconfig @> array['search_path=public'] and acl like '%authenticated%' and acl not like '%anon%' and acl not like '%=X/%') secure,bool_and(definition not like '%jpac_finalize_module_mastery%' and definition not like '%jpac_sync_enrollment_progress%' and definition not like '%jpac_review%' and definition not like '%jpac_issue%') workflow_safe,jsonb_agg(jsonb_build_object('name',proname,'hash',definition_hash,'security_definer',prosecdef,'config',proconfig,'acl',acl) order by proname) details from rpc_rows),
audit_check as(select to_regclass('public.curriculum_assignment_swap_operations') is not null exists_ok,(select relrowsecurity from pg_class where oid=to_regclass('public.curriculum_assignment_swap_operations')) rls,(select count(*) from public.curriculum_assignment_swap_operations) row_count,(select count(*) from pg_trigger where tgrelid=to_regclass('public.curriculum_assignment_swap_operations') and not tgisinternal and tgname='curriculum_assignment_swap_audit_immutable' and tgenabled<>'D') immutable_trigger,(select count(*) from pg_policies where schemaname='public' and tablename='curriculum_assignment_swap_operations' and policyname='curriculum_assignment_swap_admin_read') policy_count),
safe_defs as(select regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g') definition from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('jpac_sync_enrollment_progress','jpac_enforce_canonical_enrollment_progress')),
safe_draft as(select count(*)=2 and bool_and((select count(*) from regexp_matches(definition,'m\.status=''published''','g'))=2 and definition not like '%m.status<>''archived''%') ok from safe_defs),
activity_triggers as(select count(*) total,count(*) filter(where t.tgname='set_updated_at' and p.proname='set_updated_at' and t.tgenabled<>'D') expected,jsonb_agg(jsonb_build_object('trigger',t.tgname,'function',p.proname,'enabled',t.tgenabled)) details from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid where n.nspname='public' and c.relname='activities' and not t.tgisinternal),
protected_functions as(select count(distinct p.proname) names,jsonb_agg(jsonb_build_object('name',p.proname,'args',pg_get_function_identity_arguments(p.oid),'hash',md5(pg_get_functiondef(p.oid))) order by p.proname,pg_get_function_identity_arguments(p.oid)) details from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('jpac_sync_enrollment_progress','jpac_enforce_canonical_enrollment_progress','jpac_award_module_core_component','jpac_finalize_module_mastery','jpac_module_completion','jpac_module_is_unlocked','jpac_submit_module_activity','jpac_review_module_submission','jpac_assess_module_submission','jpac_review_submission','jpac_issue_completion_certificate','jpac_student_has_course_access')),
target as(select m.*,l.level_number,c.slug from public.course_modules m join public.course_levels l on l.id=m.course_level_id join public.courses c on c.id=m.course_id where c.slug='piano' and l.level_number=1 and m.level_module_number=13),
target_check as(select count(*) module_count,bool_and(sort_order=49 and title='Save Draft Test Module' and status='draft' and core_xp=625 and intro_core_xp=50 and video_core_xp=100 and assignment_core_xp=350 and mastery_core_xp=125 and core_unlock_threshold=438) exact,(select count(*) from public.lessons where module_id in(select id from target)) lessons,(select count(*) from public.activities where module_id in(select id from target)) activities,md5(concat(coalesce(string_agg(to_jsonb(t)::text,',' order by t.id),''),'|',(select coalesce(string_agg(to_jsonb(l)::text,',' order by l.id),'') from public.lessons l where l.module_id in(select id from target)),'|',(select coalesce(string_agg(to_jsonb(a)::text,',' order by a.id),'') from public.activities a where a.module_id in(select id from target)))) hash from target t),
singing as(select count(distinct c.id) course_count,md5(coalesce(string_agg(concat_ws('|',to_jsonb(c)::text,to_jsonb(m)::text,to_jsonb(l)::text,to_jsonb(a)::text),',' order by c.id,m.id,l.id,a.id),'')) hash from public.courses c left join public.course_modules m on m.course_id=c.id left join public.lessons l on l.module_id=m.id left join public.activities a on a.module_id=m.id where c.slug='singing'),
singing_evidence as(select jsonb_build_object('submissions',jsonb_build_object('count',(select count(*) from public.submissions s join public.activities a on a.id=s.activity_id join public.course_modules m on m.id=a.module_id join public.courses c on c.id=m.course_id where c.slug='singing'),'hash',(select md5(coalesce(string_agg(to_jsonb(s)::text,',' order by s.id),'')) from public.submissions s join public.activities a on a.id=s.activity_id join public.course_modules m on m.id=a.module_id join public.courses c on c.id=m.course_id where c.slug='singing')),'lesson_progress',jsonb_build_object('count',(select count(*) from public.lesson_progress p join public.lessons l on l.id=p.lesson_id join public.course_modules m on m.id=l.module_id join public.courses c on c.id=m.course_id where c.slug='singing'),'hash',(select md5(coalesce(string_agg(to_jsonb(p)::text,',' order by p.id),'')) from public.lesson_progress p join public.lessons l on l.id=p.lesson_id join public.course_modules m on m.id=l.module_id join public.courses c on c.id=m.course_id where c.slug='singing')),'xp_ledger',jsonb_build_object('count',(select count(*) from public.xp_ledger x join public.courses c on c.id=x.course_id where c.slug='singing'),'hash',(select md5(coalesce(string_agg(to_jsonb(x)::text,',' order by x.id),'')) from public.xp_ledger x join public.courses c on c.id=x.course_id where c.slug='singing')),'mastery',jsonb_build_object('count',(select count(*) from public.xp_ledger x join public.courses c on c.id=x.course_id where c.slug='singing' and x.xp_type='core' and x.metadata->>'component'='mastery'),'hash',(select md5(coalesce(string_agg(to_jsonb(x)::text,',' order by x.id),'')) from public.xp_ledger x join public.courses c on c.id=x.course_id where c.slug='singing' and x.xp_type='core' and x.metadata->>'component'='mastery'))) details),
student_state as(select jsonb_build_object('enrollments',jsonb_build_object('count',(select count(*) from public.enrollments),'hash',(select md5(coalesce(string_agg(concat_ws('|',id,student_id,course_id,status,progress),',' order by id),'')) from public.enrollments)),'submissions',jsonb_build_object('count',(select count(*) from public.submissions),'hash',(select md5(coalesce(string_agg(concat_ws('|',id,activity_id,student_id,status,score),',' order by id),'')) from public.submissions)),'lesson_progress',jsonb_build_object('count',(select count(*) from public.lesson_progress),'hash',(select md5(coalesce(string_agg(concat_ws('|',id,lesson_id,student_id,status,percent_complete),',' order by id),'')) from public.lesson_progress)),'xp_ledger',jsonb_build_object('count',(select count(*) from public.xp_ledger),'hash',(select md5(coalesce(string_agg(concat_ws('|',id,student_id,amount,module_id,source_id),',' order by id),'')) from public.xp_ledger)),'certificates',jsonb_build_object('count',(select count(*) from public.certificates),'hash',(select md5(coalesce(string_agg(concat_ws('|',id,student_id,course_id,status),',' order by id),'')) from public.certificates))) details),
reports(ord,report_section,code,result,details) as(
 select 10,'AUDIT_TABLE','ASV1P-AUDIT',case when exists_ok and rls and immutable_trigger=1 and policy_count=1 and row_count=0 then 'PASS' else 'BLOCK' end,jsonb_build_object('exists',exists_ok,'rls',rls,'immutable_trigger',immutable_trigger,'policy_count',policy_count,'row_count',row_count)::text from audit_check
 union all select 20,'RPC_EXISTS_SIGNATURE','ASV1P-RPCS',case when rpc_count=2 then 'PASS' else 'BLOCK' end,details::text from rpc_check
 union all select 30,'RPC_SECURITY_PRIVILEGES','ASV1P-SECURITY',case when secure then 'PASS' else 'BLOCK' end,details::text from rpc_check
 union all select 40,'RPC_DEFINITION_SAFETY','ASV1P-DEFINITION',case when workflow_safe then 'PASS' else 'BLOCK' end,'RPC definitions must not invoke protected academic workflows' from rpc_check
 union all select 50,'SAFE_DRAFT_ISOLATION','ASV1P-DRAFT',case when ok then 'PASS' else 'BLOCK' end,jsonb_build_object('published_only',ok)::text from safe_draft
 union all select 60,'ACTIVITY_TRIGGER_BASELINE','ASV1P-TRIGGERS',case when total=1 and expected=1 then 'PASS' else 'BLOCK' end,jsonb_build_object('total',total,'expected',expected,'details',details)::text from activity_triggers
 union all select 70,'PROTECTED_FUNCTION_HASHES','ASV1P-FUNCTIONS',case when names>=10 then 'INFO' else 'BLOCK' end,jsonb_build_object('instruction','Compare these hashes exactly with the preflight output','functions',details)::text from protected_functions
 union all select 80,'SINGING_BASELINE','ASV1P-SINGING',case when course_count=1 then 'INFO' else 'BLOCK' end,jsonb_build_object('instruction','Compare hash exactly with preflight','course_count',course_count,'hash',hash)::text from singing
 union all select 85,'SINGING_EVIDENCE_UNCHANGED','ASV1P-SINGING-EVIDENCE','INFO',jsonb_build_object('instruction','Compare exactly with preflight','baseline',details)::text from singing_evidence
 union all select 90,'PIANO_TEST_MODULE_UNCHANGED','ASV1P-PIANO',case when module_count=1 and exact and lessons=3 and activities=2 then 'PASS' else 'BLOCK' end,jsonb_build_object('module_count',module_count,'exact',exact,'lessons',lessons,'activities',activities,'hash',hash)::text from target_check
 union all select 100,'STUDENT_STATE_UNCHANGED','ASV1P-STUDENT','INFO',jsonb_build_object('instruction','Compare all counts and hashes exactly with preflight','baseline',details)::text from student_state),
blockers as(select code,details from reports where result='BLOCK'),
final as(select * from reports union all select 900,'BLOCKERS','ASV1P-BLOCKERS',case when exists(select 1 from blockers) then 'BLOCK' else 'PASS' end,coalesce((select jsonb_agg(jsonb_build_object('code',code,'details',details))::text from blockers),'No blockers detected') union all select 999,'OVERALL','ASV1P-OVERALL',case when exists(select 1 from blockers) then 'BLOCK' else 'PASS' end,case when exists(select 1 from blockers) then 'BLOCK: REVIEW BEFORE FRONTEND WIRING' else 'PASS: ASSIGNMENT SWAP V1 BACKEND INSTALL VALID' end)
select report_section,code,result,details from final order by ord,code;
rollback;
