-- JPAC Dance 47-module rollout preflight. READ ONLY.
begin transaction read only;
with manifest(level,num,sort,title) as (values
 (1,1,1,'Rhythm & Body Awareness'),(1,2,2,'Basic Steps & Patterns'),(1,3,3,'Simple Hip-Hop Grooves'),(1,4,4,'Rock Energy & Attitude'),(1,5,5,'Rock and Roll Footwork'),(1,6,6,'Classic Dance Moves Everyone Knows'),(1,7,7,'Stretching for Dancers'),(1,8,8,'Intro to Isolations'),(1,9,9,'Building Stamina'),(1,10,10,'Freestyle Your First 8-Count'),(1,11,11,'Performance & Presentation'),(1,12,12,'Beginner Showcase: Your Dance Journey'),
 (2,1,13,'Mastering Isolations'),(2,2,14,'Turns and Pirouettes'),(2,3,15,'Jumps and Leaps'),(2,4,16,'Musicality and Phrasing'),(2,5,17,'Contemporary Dance Basics'),(2,6,18,'Intermediate Choreography'),(2,7,19,'Freestyle and Improvisation Skills'),(2,8,20,'Dynamics and Textures'),(2,9,21,'Strength and Conditioning'),(2,10,22,'Audition and Performance Prep'),(2,11,23,'Teaching Dance Basics'),(2,12,24,'Intermediate Showcase: Artistic Growth'),
 (3,1,25,'Complex Rhythms and Syncopation'),(3,2,26,'Advanced Turns and Combinations'),(3,3,27,'Storytelling Through Movement'),(3,4,28,'Partnering and Lifts'),(3,5,29,'Ayo & Teo: Dance Revolution'),(3,6,30,'Jazz and Lyrical Fusion'),(3,7,31,'Advanced Improvisation Structures'),(3,8,32,'Floorwork and Transitions'),(3,9,33,'The Business of Dance'),(3,10,34,'Creating a Dance Concept Video'),(3,11,35,'Exploring Dance for Social Impact: Community Building and Activism'),(3,12,36,'Advanced Blues Dance Choreography: Mastering the Art of Expression'),
 (4,1,37,'Developing Your Signature Style'),(4,2,38,'Advanced Choreographic Principles'),(4,3,39,'Teaching and Leading a Class'),(4,4,40,'Artist Study: Michael Jackson'),(4,5,41,'Artist Study: Beyoncé'),(4,6,42,'Directing and Producing a Dance Show'),(4,7,43,'Dance for Camera'),(4,8,44,'Grant Writing and Funding'),(4,9,45,'Grant Writing and Project Funding'),(4,10,46,'Legacy and Mentorship'),(4,12,47,'Master''s Magnum Opus: Dance Legacy')
), dance as (
 select count(*)::int n,(array_agg(id order by id::text))[1] id from public.courses where slug='dance'
), sdi as (
 select count(*) filter(where (select count(*) from regexp_matches(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m\.status=''published''','g'))=2 and strpos(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m.status<>''archived''')=0)::int n from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('jpac_sync_enrollment_progress','jpac_enforce_canonical_enrollment_progress')
), canonical_trigger as (
 select count(*)::int n from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='enrollments' and t.tgname='enrollments_enforce_canonical_progress' and not t.tgisinternal and t.tgenabled<>'D'
), level_conflicts as (
 select count(*)::int n from public.course_levels l join public.courses c on c.id=l.course_id where c.slug='dance' and (l.level_number not between 1 and 4 or l.title is distinct from (array['Beginner','Intermediate','Advanced','Master'])[l.level_number] or l.status<>'draft' or l.approved_by is not null or l.approved_at is not null)
), module_conflicts as (
 select count(*)::int n from manifest e join public.courses c on c.slug='dance' left join public.course_levels l on l.course_id=c.id and l.level_number=e.level join public.course_modules m on m.course_id=c.id and (m.sort_order=e.sort or (m.course_level_id=l.id and m.level_module_number=e.num))
 where m.course_level_id is distinct from l.id or m.level_module_number is distinct from e.num or m.sort_order is distinct from e.sort or m.title is distinct from e.title or m.description is distinct from 'Develop and demonstrate source-aligned Dance skills for '||e.title||'.' or m.short_intro is distinct from 'Draft source-aligned Dance module.' or m.status<>'draft' or m.xp_value<>625 or m.core_xp<>625 or m.intro_core_xp<>50 or m.video_core_xp<>100 or m.assignment_core_xp<>350 or m.mastery_core_xp<>125 or m.core_unlock_threshold<>438 or m.bonus_xp_available<>0 or m.jpac_tool_activity is distinct from '{}'::jsonb or m.real_world_activity is distinct from jsonb_build_object('title',e.title||' Guided Practice','instructions','Rehearse in a clear safe space using a teacher-approved accessible adaptation.') or m.career_connection is distinct from '' or m.portfolio_moment or m.video_brief is distinct from 'NEEDS REVIEW: no media is activated.' or m.lab_tool_id is not null or m.active_instructional_media_id is not null or m.primary_video_url is not null or m.approved_by is not null or m.approved_at is not null
), inactive_assets as (
 select (select count(*) from public.module_instructional_media mi join public.course_modules m on m.id=mi.module_id where m.course_id=(select id from dance))::int media,(select count(*) from public.lab_tool_courses where course_id=(select id from dance))::int tools
), sort_conflicts as (
 select count(*)::int n from public.course_modules m join public.courses c on c.id=m.course_id left join manifest e on e.sort=m.sort_order where c.slug='dance' and m.sort_order between 1 and 47 and (e.sort is null or m.title is distinct from e.title)
), child_conflicts as (
 select count(*)::int n from manifest e join public.courses c on c.slug='dance' join public.course_levels l on l.course_id=c.id and l.level_number=e.level join public.course_modules m on m.course_level_id=l.id and m.level_module_number=e.num
 where (exists(select 1 from public.lessons where module_id=m.id) or exists(select 1 from public.activities where module_id=m.id)) and ((select count(*) from public.lessons where module_id=m.id)<>3 or (select count(*) from public.lessons where module_id=m.id and status='draft' and xp_value=0 and title in(e.title||': Foundations and Safety',e.title||': Guided Application',e.title||': Performance and Reflection'))<>3 or (select count(*) from public.activities where module_id=m.id)<>2 or (select count(*) from public.activities where module_id=m.id and title=e.title||' Guided Practice' and status='draft' and activity_type='practice' and not required and xp_reward=0 and xp_type='bonus')<>1 or (select count(*) from public.activities where module_id=m.id and title=e.title||' Core Challenge' and status='draft' and activity_type='performance' and required and xp_reward=350 and xp_type='core' and passing_score=70 and allows_resubmission and jsonb_array_length(rubric->'criteria')=5 and (select sum((x->>'weight')::int) from jsonb_array_elements(rubric->'criteria') x)=100)<>1)
), excluded_conflicts as (
 select count(*)::int n from public.course_modules m join public.course_levels l on l.id=m.course_level_id join public.courses c on c.id=m.course_id where c.slug='dance' and l.level_number=4 and m.level_module_number=11
), deps as (
 select (select count(*) from public.enrollments where course_id=(select id from dance))+(select count(*) from public.submissions s join public.activities a on a.id=s.activity_id where a.course_id=(select id from dance))+(select count(*) from public.lesson_progress p join public.lessons l on l.id=p.lesson_id join public.course_modules m on m.id=l.module_id where m.course_id=(select id from dance))+(select count(*) from public.activity_progress p join public.activities a on a.id=p.activity_id where a.course_id=(select id from dance))+(select count(*) from public.practice_logs p join public.activities a on a.id=p.activity_id where a.course_id=(select id from dance))+(select count(*) from public.xp_ledger where course_id=(select id from dance))+(select count(*) from public.certificates where course_id=(select id from dance))+(select count(*) from public.portfolio_projects p join public.activities a on a.id=p.activity_id where a.course_id=(select id from dance)) n
), baselines as (
 select upper(c.slug)||'_CURRICULUM_BASELINE' code,md5(coalesce(string_agg(v,E'\n' order by v),'')) details from public.courses c cross join lateral (select m.id||':'||m.status||':'||m.title v from public.course_modules m where m.course_id=c.id union all select l.id||':'||l.status||':'||l.title from public.lessons l join public.course_modules m on m.id=l.module_id where m.course_id=c.id union all select a.id||':'||a.status||':'||a.title from public.activities a where a.course_id=c.id) q where c.slug in('singing','piano','guitar','acting') group by c.slug
 union all select 'STUDENT_STATE_BASELINE',jsonb_build_object('enrollments',(select count(*) from public.enrollments),'lesson_progress',(select count(*) from public.lesson_progress),'activity_progress',(select count(*) from public.activity_progress),'practice_logs',(select count(*) from public.practice_logs),'submissions',(select count(*) from public.submissions),'xp_ledger',(select count(*) from public.xp_ledger),'certificates',(select count(*) from public.certificates),'portfolio_projects',(select count(*) from public.portfolio_projects))::text
 union all select 'ASSIGNMENT_SWAP_BASELINE',jsonb_build_object('definition_hash',(select md5(coalesce(string_agg(p.proname||':'||pg_get_functiondef(p.oid),E'\n' order by p.proname),'')) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('curriculum_swap_module_assignment_v1','curriculum_rollback_assignment_swap_v1')),'audit_rows',(select count(*) from public.curriculum_assignment_swap_operations))::text
), findings as (
 select 'IDENTITY' section,'DANCE_IDENTITY' code,case when n=1 then 'PASS' else 'BLOCK' end result,format('canonical Dance course rows=%s; id=%s',n,coalesce(id::text,'NULL')) details from dance
 union all select 'DRAFT_ISOLATION','SAFE_DRAFT_ISOLATION',case when s.n=2 and t.n=1 then 'PASS' else 'BLOCK' end,format('published-only functions=%s/2; trigger=%s',s.n,t.n) from sdi s cross join canonical_trigger t
 union all select 'COMPATIBILITY','LEVEL_COMPATIBILITY',case when n=0 then 'PASS' else 'BLOCK' end,format('incompatible levels=%s',n) from level_conflicts
 union all select 'COMPATIBILITY','MODULE_COMPATIBILITY',case when n=0 then 'PASS' else 'BLOCK' end,format('incompatible modules=%s',n) from module_conflicts
 union all select 'COMPATIBILITY','GLOBAL_SORT_ORDER',case when n=0 then 'PASS' else 'BLOCK' end,format('incompatible global sort rows=%s',n) from sort_conflicts
 union all select 'COMPATIBILITY','CHILD_COMPATIBILITY',case when n=0 then 'PASS' else 'BLOCK' end,format('incompatible populated module children=%s',n) from child_conflicts
 union all select 'EXCLUSIONS','MASTER_MODULE_11_ABSENT',case when n=0 then 'PASS' else 'BLOCK' end,format('fake Master Module 11 rows=%s',n) from excluded_conflicts
 union all select 'EVIDENCE','DANCE_DEPENDENCIES',case when n=0 then 'PASS' else 'BLOCK' end,format('Dance evidence/student dependencies=%s',n) from deps
 union all select 'ASSETS','MEDIA_TOOL_BINDINGS',case when media=0 and tools=0 then 'PASS' else 'BLOCK' end,format('instructional media rows=%s; Lab/tool course bindings=%s',media,tools) from inactive_assets
 union all select 'MANIFEST','MANIFEST_COUNTS',case when count(*)=47 and count(*) filter(where level=1)=12 and count(*) filter(where level=2)=12 and count(*) filter(where level=3)=12 and count(*) filter(where level=4)=11 and min(sort)=1 and max(sort)=47 and count(distinct sort)=47 then 'PASS' else 'BLOCK' end,format('modules=%s; L1=%s; L2=%s; L3=%s; L4=%s; sort=%s-%s',count(*),count(*) filter(where level=1),count(*) filter(where level=2),count(*) filter(where level=3),count(*) filter(where level=4),min(sort),max(sort)) from manifest
 union all select 'PRESERVATION',code,'INFO','Capture and compare after migration: '||details from baselines
), blockers as(select count(*) filter(where result='BLOCK')::int n from findings)
select section as report_section,code,result,details from findings
union all select 'READINESS','BLOCKERS',case when n=0 then 'PASS' else 'BLOCK' end,format('blocking findings=%s',n) from blockers
union all select 'READINESS','OVERALL',case when n=0 then 'PASS' else 'BLOCK' end,case when n=0 then 'PASS: READY FOR DANCE DRAFT ROLLOUT MIGRATION' else 'BLOCK: DO NOT RUN MIGRATION' end from blockers
order by report_section,code;
rollback;
