-- JPAC Audio Engineering 48-module rollout post-validation. READ ONLY.
begin transaction read only;
with manifest as (select * from jsonb_to_recordset('[
 {"level":1,"num":1,"sort":1,"title":"Sound Waves, Frequency & Critical Listening"},{"level":1,"num":2,"sort":2,"title":"DAW Fundamentals & First Session"},{"level":1,"num":3,"sort":3,"title":"Drum Programming & Timing Foundations"},{"level":1,"num":4,"sort":4,"title":"Microphone Types & Safe Setup"},{"level":1,"num":5,"sort":5,"title":"Recording Your First Audio"},{"level":1,"num":6,"sort":6,"title":"Intro to EQ"},{"level":1,"num":7,"sort":7,"title":"Synthesizer & Sound-Generation Basics"},{"level":1,"num":8,"sort":8,"title":"MIDI Fundamentals"},{"level":1,"num":9,"sort":9,"title":"Basic Mixing: Levels, Panning & Stereo Image"},{"level":1,"num":10,"sort":10,"title":"Basic Editing: Cuts, Fades & Comping"},{"level":1,"num":11,"sort":11,"title":"Intro to Compression"},{"level":1,"num":12,"sort":12,"title":"Beginner Mixdown Showcase"},
 {"level":2,"num":1,"sort":13,"title":"Advanced Drum Engineering"},{"level":2,"num":2,"sort":14,"title":"Intermediate Microphone Techniques"},{"level":2,"num":3,"sort":15,"title":"Signal Flow & Routing"},{"level":2,"num":4,"sort":16,"title":"EQ & Advanced Frequency Shaping"},{"level":2,"num":5,"sort":17,"title":"Compression & Advanced Dynamics"},{"level":2,"num":6,"sort":18,"title":"Sampling: Time, Pitch & Authorized Source Use"},{"level":2,"num":7,"sort":19,"title":"Reverb, Delay & Modulation"},{"level":2,"num":8,"sort":20,"title":"Vocal Recording Techniques"},{"level":2,"num":9,"sort":21,"title":"Saturation & Harmonic Character"},{"level":2,"num":10,"sort":22,"title":"Mixing Workflow & Strategy"},{"level":2,"num":11,"sort":23,"title":"Automation in Mixing"},{"level":2,"num":12,"sort":24,"title":"Acoustic Treatment & Studio Readiness"},
 {"level":3,"num":1,"sort":25,"title":"Advanced Microphone Techniques"},{"level":3,"num":2,"sort":26,"title":"Advanced Mixing: Parallel Processing, Bus Compression & Translation"},{"level":3,"num":3,"sort":27,"title":"Advanced Automation"},{"level":3,"num":4,"sort":28,"title":"Vocal Production & Processing"},{"level":3,"num":5,"sort":29,"title":"Mastering Techniques"},{"level":3,"num":6,"sort":30,"title":"Live Sound Engineering"},{"level":3,"num":7,"sort":31,"title":"Audio Post-Production"},{"level":3,"num":8,"sort":32,"title":"Stereo Imaging & Widening"},{"level":3,"num":9,"sort":33,"title":"Sound Design"},{"level":3,"num":10,"sort":34,"title":"Reference Mixing & Critical Translation"},{"level":3,"num":11,"sort":35,"title":"Analog vs. Digital Systems"},{"level":3,"num":12,"sort":36,"title":"Full Band Recording Showcase"},
 {"level":4,"num":1,"sort":37,"title":"Mastering: The Final Polish"},{"level":4,"num":2,"sort":38,"title":"Advanced Mixing Systems"},{"level":4,"num":3,"sort":39,"title":"Advanced Sound Design"},{"level":4,"num":4,"sort":40,"title":"Mastering for Streaming & LUFS"},{"level":4,"num":5,"sort":41,"title":"Studio Design & Acoustics"},{"level":4,"num":6,"sort":42,"title":"Client Sessions & Communication"},{"level":4,"num":7,"sort":43,"title":"Mentoring Junior Engineers"},{"level":4,"num":8,"sort":44,"title":"Future Audio Technology & Responsible AI"},{"level":4,"num":9,"sort":45,"title":"Professional Studio Workflow"},{"level":4,"num":10,"sort":46,"title":"Experimental & Innovative Engineering"},{"level":4,"num":11,"sort":47,"title":"Industry Professional Practices, Standards & Delivery"},{"level":4,"num":12,"sort":48,"title":"Master Capstone: Complete Album Production"}
 ]'::jsonb) as x(level int,num int,sort int,title text)), course_identity as(select id from public.courses where slug='audio-engineering'), counts as (
 select (select count(*) from public.course_levels where course_id=(select id from course_identity))::int levels,(select count(*) from public.course_modules where course_id=(select id from course_identity))::int modules,(select count(*) from public.lessons l join public.course_modules m on m.id=l.module_id where m.course_id=(select id from course_identity))::int lessons,(select count(*) from public.activities where course_id=(select id from course_identity) and activity_type='practice')::int practices,(select count(*) from public.activities where course_id=(select id from course_identity) and activity_type='performance' and required and xp_type='core')::int challenges
), level_counts as (
 select l.level_number,count(m.id)::int modules from public.course_levels l left join public.course_modules m on m.course_level_id=l.id where l.course_id=(select id from course_identity) group by l.level_number
), exact_manifest as (
 select count(*)::int exact from manifest e join public.course_levels l on l.course_id=(select id from course_identity) and l.level_number=e.level join public.course_modules m on m.course_level_id=l.id and m.level_module_number=e.num and m.sort_order=e.sort and m.title=e.title
), rubrics as (
 select count(*)::int challenges,coalesce(sum(jsonb_array_length(rubric->'criteria')),0)::int criteria,count(*) filter(where jsonb_array_length(rubric->'criteria')=5 and (select sum((x->>'weight')::int) from jsonb_array_elements(rubric->'criteria') x)=100 and (select array_agg(x->>'name' order by x->>'name') from jsonb_array_elements(rubric->'criteria') x)=array['Creative Sound Design / Production Choices','Mixing, Balance & Processing','Professional Delivery & Reflection','Recording / Sound Capture Quality','Technical Setup & Signal Flow'] and not exists(select 1 from jsonb_array_elements(rubric->'criteria') x where jsonb_typeof(x->'bands')<>'object' or (select count(*) from jsonb_object_keys(x->'bands'))<>4 or exists(select 1 from jsonb_each_text(x->'bands') b where b.value='')))::int valid from public.activities where course_id=(select id from course_identity) and activity_type='performance' and required and xp_type='core'
), safety as (
 select (select count(*) from public.course_levels where course_id=(select id from course_identity) and status<>'draft')+(select count(*) from public.course_modules where course_id=(select id from course_identity) and status<>'draft')+(select count(*) from public.lessons l join public.course_modules m on m.id=l.module_id where m.course_id=(select id from course_identity) and l.status<>'draft')+(select count(*) from public.activities where course_id=(select id from course_identity) and status<>'draft') nondraft,
 (select count(*) from public.course_modules where course_id=(select id from course_identity) and status='draft' and core_xp=625 and intro_core_xp=50 and video_core_xp=100 and assignment_core_xp=350 and mastery_core_xp=125 and core_unlock_threshold=438 and lab_tool_id is null and active_instructional_media_id is null and primary_video_url is null and video_brief='MEDIA NEEDS REVIEW: no media is activated.' and jpac_tool_activity='{}'::jsonb) payloads,
 (select count(*) from public.module_instructional_media mi join public.course_modules m on m.id=mi.module_id where m.course_id=(select id from course_identity)) media,
 (select count(*) from public.course_modules where course_id=(select id from course_identity) and lab_tool_id is not null)+(select count(*) from public.lab_tool_courses where course_id=(select id from course_identity)) tools
), capstones as (
 select (select count(*) from public.course_modules m join public.course_levels l on l.id=m.course_level_id where m.course_id=(select id from course_identity) and l.level_number=3 and m.level_module_number=12 and m.title='Full Band Recording Showcase')::int advanced,
 (select count(*) from public.course_modules m join public.course_levels l on l.id=m.course_level_id where m.course_id=(select id from course_identity) and l.level_number=4 and m.level_module_number=12 and m.title='Master Capstone: Complete Album Production' and m.review_notes like '%raw Mix and Master an Album assessment is merged as staged evidence%')::int master,
 (select count(*) from public.course_modules where course_id=(select id from course_identity) and title='Capstone: Mix and Master an Album')::int standalone_old
), review_flags as (
 select count(*) filter(where review_notes like '%MEDIA NEEDS REVIEW%' and review_notes like '%NEEDS CATALOG REVIEW%' and review_notes like '%TOOL/ACCESSIBILITY REVIEW%')::int base_flags,
 count(*) filter(where review_notes like '%SCOPE REVIEW%')::int scope_flags,
 count(*) filter(where review_notes like '%RIGHTS/DISTRIBUTION REVIEW%')::int rights_flags,
 count(*) filter(where review_notes like '%BUSINESS/LEGAL REVIEW%')::int business_flags,
 count(*) filter(where review_notes like '%AI/ETHICS REVIEW%')::int ai_flags
 from public.course_modules where course_id=(select id from course_identity)
), excluded as (
 select count(*)::int n from public.course_modules where course_id=(select id from course_identity) and title=any(array['Advanced Synthesis Techniques','Working with Artists: Collaboration','Running a Studio','Remixing Techniques','Immersive Audio and Atmos','Audio for Film and Games','Joe Carrell''s Production Masterclass: Recording Techniques Across Genres','Bass Design and 808s','Advanced Drum Layering Techniques for Hip-Hop Production','Your First Full Beat Production','Song Arrangement & Structure','Advanced Arrangement Techniques','Advanced Rhythm Programming','Advanced Harmony & Jazz Concepts','Blues Production & Vintage Techniques','Advanced DJ Techniques: Live Performance and Beat Juggling','Ayo & Teo: Dance Revolution','Developing Your Artistic Voice'])
), deps as (
 select (select count(*) from public.enrollments where course_id=(select id from course_identity))+(select count(*) from public.submissions s join public.activities a on a.id=s.activity_id where a.course_id=(select id from course_identity))+(select count(*) from public.lesson_progress p join public.lessons l on l.id=p.lesson_id join public.course_modules m on m.id=l.module_id where m.course_id=(select id from course_identity))+(select count(*) from public.activity_progress p join public.activities a on a.id=p.activity_id where a.course_id=(select id from course_identity))+(select count(*) from public.practice_logs p join public.activities a on a.id=p.activity_id where a.course_id=(select id from course_identity))+(select count(*) from public.xp_ledger where course_id=(select id from course_identity))+(select count(*) from public.certificates where course_id=(select id from course_identity))+(select count(*) from public.portfolio_projects p join public.activities a on a.id=p.activity_id where a.course_id=(select id from course_identity)) n
), draft_isolation as (
 select (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('jpac_sync_enrollment_progress','jpac_enforce_canonical_enrollment_progress') and (select count(*) from regexp_matches(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m\.status=''published''','g'))=2 and strpos(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m.status<>''archived''')=0)::int functions,(select count(*) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='enrollments' and t.tgname='enrollments_enforce_canonical_progress' and not t.tgisinternal and t.tgenabled<>'D')::int triggers
), baselines as (
 select upper(c.slug)||'_CURRICULUM_BASELINE' code,md5(coalesce(string_agg(v,E'\n' order by v),'')) details from public.courses c cross join lateral (select m.id||':'||m.status||':'||m.title v from public.course_modules m where m.course_id=c.id union all select l.id||':'||l.status||':'||l.title from public.lessons l join public.course_modules m on m.id=l.module_id where m.course_id=c.id union all select a.id||':'||a.status||':'||a.title from public.activities a where a.course_id=c.id) q where c.slug in('singing','piano','guitar','acting','dance','video-production') group by c.slug
 union all select 'STUDENT_STATE_BASELINE',jsonb_build_object('enrollments',(select count(*) from public.enrollments),'lesson_progress',(select count(*) from public.lesson_progress),'activity_progress',(select count(*) from public.activity_progress),'practice_logs',(select count(*) from public.practice_logs),'submissions',(select count(*) from public.submissions),'xp_ledger',(select count(*) from public.xp_ledger),'certificates',(select count(*) from public.certificates),'portfolio_projects',(select count(*) from public.portfolio_projects))::text
 union all select 'ASSIGNMENT_SWAP_BASELINE',jsonb_build_object('definition_hash',(select md5(coalesce(string_agg(p.proname||':'||pg_get_functiondef(p.oid),E'\n' order by p.proname),'')) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('curriculum_swap_module_assignment_v1','curriculum_rollback_assignment_swap_v1')),'audit_rows',(select count(*) from public.curriculum_assignment_swap_operations))::text
), findings as (
 select 'STRUCTURE' section,'LEVELS' code,case when levels=4 then 'PASS' else 'BLOCK' end result,format('levels=%s/4',levels) details from counts
 union all select 'STRUCTURE','MODULES',case when modules=48 then 'PASS' else 'BLOCK' end,format('modules=%s/48',modules) from counts
 union all select 'STRUCTURE','LEVEL_MODULE_COUNTS',case when coalesce((select modules from level_counts where level_number=1),0)=12 and coalesce((select modules from level_counts where level_number=2),0)=12 and coalesce((select modules from level_counts where level_number=3),0)=12 and coalesce((select modules from level_counts where level_number=4),0)=12 then 'PASS' else 'BLOCK' end,(select coalesce(jsonb_object_agg(level_number,modules order by level_number),'{}'::jsonb)::text from level_counts)
 union all select 'STRUCTURE','EXACT_MANIFEST',case when exact=48 then 'PASS' else 'BLOCK' end,format('exact canonical modules=%s/48',exact) from exact_manifest
 union all select 'STRUCTURE','LESSONS',case when lessons=144 then 'PASS' else 'BLOCK' end,format('lessons=%s/144',lessons) from counts
 union all select 'STRUCTURE','PRACTICES',case when practices=48 then 'PASS' else 'BLOCK' end,format('practices=%s/48',practices) from counts
 union all select 'STRUCTURE','CORE_CHALLENGES',case when challenges=48 then 'PASS' else 'BLOCK' end,format('Core Challenges=%s/48',challenges) from counts
 union all select 'ASSESSMENT','RUBRICS',case when challenges=48 and criteria=240 and valid=48 then 'PASS' else 'BLOCK' end,format('challenges=%s; criteria=%s/240; exact rubrics=%s/48',challenges,criteria,valid) from rubrics
 union all select 'SAFETY','DRAFT_ONLY',case when nondraft=0 then 'PASS' else 'BLOCK' end,format('non-draft records=%s',nondraft) from safety
 union all select 'SAFETY','CANONICAL_PAYLOAD',case when payloads=48 then 'PASS' else 'BLOCK' end,format('canonical draft modules=%s/48',payloads) from safety
 union all select 'SAFETY','MEDIA_TOOLS',case when media=0 and tools=0 then 'PASS' else 'BLOCK' end,format('media rows=%s; tool bindings=%s',media,tools) from safety
 union all select 'SAFETY','AUDIO_ENGINEERING_DEPENDENCIES',case when n=0 then 'PASS' else 'BLOCK' end,format('student/evidence dependencies=%s',n) from deps
 union all select 'CLASSIFICATION','EXCLUDED_ITEMS_ABSENT',case when n=0 then 'PASS' else 'BLOCK' end,format('HOLD/OUT-OF-SCOPE standalone modules=%s',n) from excluded
 union all select 'CAPSTONES','APPROVED_CAPSTONES',case when advanced=1 and master=1 and standalone_old=0 then 'PASS' else 'BLOCK' end,format('Advanced showcase=%s/1; Master final=%s/1; old standalone capstone=%s',advanced,master,standalone_old) from capstones
 union all select 'CLASSIFICATION','REVIEW_FLAGS',case when base_flags=48 and scope_flags=6 and rights_flags=7 and business_flags=7 and ai_flags=2 then 'PASS' else 'BLOCK' end,format('base=%s/48; scope=%s/6; rights=%s/7; business=%s/7; AI=%s/2',base_flags,scope_flags,rights_flags,business_flags,ai_flags) from review_flags
 union all select 'SAFETY','SAFE_DRAFT_ISOLATION',case when functions=2 and triggers=1 then 'PASS' else 'BLOCK' end,format('published-only functions=%s/2; canonical trigger=%s',functions,triggers) from draft_isolation
 union all select 'PRESERVATION',code,'INFO','Compare exactly with preflight: '||details from baselines
), blockers as(select count(*) filter(where result='BLOCK')::int n from findings)
select section as report_section,code,result,details from findings
union all select 'READINESS','BLOCKERS',case when n=0 then 'PASS' else 'BLOCK' end,format('blocking findings=%s',n) from blockers
union all select 'READINESS','OVERALL',case when n=0 then 'PASS' else 'BLOCK' end,case when n=0 then 'PASS: AUDIO ENGINEERING FULL DRAFT ROLLOUT VALID; COMPARE PRESERVATION BASELINES' else 'BLOCK: REVIEW AUDIO ENGINEERING ROLLOUT' end from blockers
order by report_section,code;
rollback;
