-- Read-only: inspects schema/access controls and performs no writes.
with findings(report_section,code,result,details) as (
select 'SCHEMA','TABLES',case when count(*)=2 then 'PASS' else 'BLOCK' end,format('tables=%s/2',count(*)) from information_schema.tables where table_schema='public' and table_name in ('creator_tool_extra_credit_submissions','creator_tool_extra_credit_submission_events')
union all select 'SCHEMA','COLUMNS',case when count(*)>=21 then 'PASS' else 'BLOCK' end,format('required columns=%s/21',count(*)) from information_schema.columns where table_schema='public' and table_name in ('creator_tool_extra_credit_submissions','creator_tool_extra_credit_submission_events')
union all select 'SCHEMA','FUNCTIONS',case when count(*)=3 then 'PASS' else 'BLOCK' end,format('functions=%s/3',count(*)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('creator_tool_extra_credit_log_submission','creator_tool_extra_credit_withdraw','creator_tool_extra_credit_review')
union all select 'ACCESS','RLS',case when count(*) filter(where relrowsecurity)=2 then 'PASS' else 'BLOCK' end,format('RLS enabled=%s/2',count(*) filter(where relrowsecurity)) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('creator_tool_extra_credit_submissions','creator_tool_extra_credit_submission_events')
union all select 'ACCESS','POLICIES',case when count(*)=3 then 'PASS' else 'BLOCK' end,format('policies=%s/3',count(*)) from pg_policies where schemaname='public' and tablename in ('creator_tool_extra_credit_submissions','creator_tool_extra_credit_submission_events')
union all select 'ACCESS','STUDENT_INSERT_GUARD',case when count(*)=1 then 'PASS' else 'BLOCK' end,format('fully guarded student insert policies=%s/1',count(*)) from pg_policies where schemaname='public' and tablename='creator_tool_extra_credit_submissions' and policyname='creator_tool_extra_credit_insert' and cmd='INSERT' and lower(coalesce(with_check,'')) like '%auth.uid()%student_id%' and lower(coalesce(with_check,'')) like '%status%pending_review%' and lower(coalesce(with_check,'')) like '%teacher_feedback%is null%' and lower(coalesce(with_check,'')) like '%reviewed_by%is null%' and lower(coalesce(with_check,'')) like '%reviewed_at%is null%'
union all select 'ACCESS','NO_ANON_PRIVILEGES',case when count(*)=0 then 'PASS' else 'BLOCK' end,format('anon table privileges=%s',count(*)) from information_schema.role_table_grants where table_schema='public' and table_name in ('creator_tool_extra_credit_submissions','creator_tool_extra_credit_submission_events') and grantee='anon'
union all select 'DATA SAFETY','NO_SEED_ROWS',case when (select count(*) from public.creator_tool_extra_credit_submissions)=0 and (select count(*) from public.creator_tool_extra_credit_submission_events)=0 then 'PASS' else 'BLOCK' end,format('submissions=%s; events=%s',(select count(*) from public.creator_tool_extra_credit_submissions),(select count(*) from public.creator_tool_extra_credit_submission_events))
union all select 'SAFETY','PROTECTED_TABLES',case when count(*)=7 then 'PASS' else 'BLOCK' end,format('protected tables present=%s/7',count(*)) from information_schema.tables where table_schema='public' and table_name in ('courses','course_modules','enrollments','submissions','xp_ledger','lesson_progress','certificates')),
overall as(select 'OVERALL','POST_VALIDATION',case when count(*) filter(where result='BLOCK')=0 then 'PASS' else 'BLOCK' end,format('blockers=%s',count(*) filter(where result='BLOCK')) from findings)
select * from findings union all select * from overall order by 1,2;
