import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { useAuth } from '../../../context/AuthContext';
import { getPremiumCreatorTool } from '../creativeToolRegistry';
import { createExtraCreditSubmission, listMyExtraCreditSubmissions, withdrawExtraCreditSubmission, type ExtraCreditSubmission } from './extraCreditSubmission';

export function ExtraCreditPanel({ summary }: { summary: string }) {
  const { user } = useAuth(); const { toolSlug } = useParams(); const tool = getPremiumCreatorTool(toolSlug);
  const [message, setMessage] = useState('');
  const [title,setTitle]=useState(''); const[notes,setNotes]=useState(''); const[confirmed,setConfirmed]=useState(false); const[submitting,setSubmitting]=useState(false); const[submissions,setSubmissions]=useState<ExtraCreditSubmission[]>([]);
  async function refresh(){if(!user||!tool)return;const result=await listMyExtraCreditSubmissions(user.id,tool.slug);if(!result.error)setSubmissions(result.data)}
  useEffect(()=>{void refresh()},[user?.id,tool?.slug]);
  async function copy() { try { await navigator.clipboard.writeText(summary); setMessage('Extra-credit summary copied.'); } catch { setMessage('Copy was blocked by this browser.'); } }
  async function submit(){if(!user||!tool){setMessage('Sign in and open a supported Creator Tool before submitting.');return}if(!title.trim()){setMessage('Add a project title first.');return}if(!confirmed){setMessage('Confirm that you understand this is teacher-reviewed and does not automatically award credit.');return}setSubmitting(true);const{error}=await createExtraCreditSubmission({studentId:user.id,toolSlug:tool.slug,toolName:tool.title,projectTitle:title,projectSummary:summary,studentNotes:notes});setSubmitting(false);if(error){setMessage(error.message);return}setTitle('');setNotes('');setConfirmed(false);setMessage('Submitted for teacher review');await refresh()}
  async function withdraw(id:string){const{error}=await withdrawExtraCreditSubmission(id);setMessage(error?.message||'Submission withdrawn.');if(!error)await refresh()}
  return <section className="extra-credit-panel"><div className="extra-credit-heading"><span className="premium-kicker">Teacher-reviewed pathway</span><h2>Prepare for Extra Credit</h2><p>Send a text-only project snapshot to your JPAC teacher for review.</p><small>This sends your project summary to your teacher for review. It does not automatically award XP, grades, mastery, or certificates.</small></div><div className="extra-credit-fields"><label>Project title<input maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Name this practice project"/></label><label>Student note (optional)<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What would you like your teacher to notice?"/></label><label className="extra-credit-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I understand this enters a teacher review queue and does not guarantee extra credit.</label></div><div className="premium-action-row"><button type="button" className="button button-primary" disabled={submitting} onClick={()=>void submit()}>{submitting?'Submitting…':'Submit for Extra Credit'}</button><button type="button" className="button button-secondary" onClick={()=>void copy()}>Copy project summary</button></div>{message?<span role="status">{message}</span>:null}{submissions.length?<div className="extra-credit-history"><h3>Your recent submissions</h3>{submissions.map(item=><article key={item.id}><div><strong>{item.project_title}</strong><small>{item.status.replace('_',' ')} · {new Date(item.submitted_at).toLocaleDateString()}</small>{item.teacher_feedback?<p>Teacher feedback: {item.teacher_feedback}</p>:null}</div>{['pending_review','needs_revision'].includes(item.status)?<button className="button button-secondary" type="button" onClick={()=>void withdraw(item.id)}>Withdraw</button>:null}</article>)}</div>:null}</section>;
}
