begin;

-- Deterministic IDs identify deletion candidates only; exact approved payload and dependency guards authorize deletion.
do $$
declare v_course uuid;v_level uuid;v_module uuid;
 v_rubric jsonb:=jsonb_build_object('criteria',jsonb_build_array(
  jsonb_build_object('name','Technique and safe hand shape','weight',35,'bands',jsonb_build_object('exceeds','Consistently uses a natural, functional hand shape with flexible wrist and independently releases tension.','meets','Generally uses safe hand shape and wrist freedom with minor inconsistency.','developing','Shows partial technique; recurring tension or finger collapse affects control.','not_yet','Evidence is missing, substantially uncontrolled, or presents an unresolved safety concern.')),
  jsonb_build_object('name','Posture and body alignment','weight',25,'bands',jsonb_build_object('exceeds','Setup is balanced, supported, individualized, and consistently maintained.','meets','Setup is functional and generally balanced with minor alignment issues.','developing','Reaching, crowding, instability, or tension affects playing.','not_yet','Setup cannot be evaluated or does not yet support safe functional playing.')),
  jsonb_build_object('name','Finger control and five-finger pattern accuracy','weight',20,'bands',jsonb_build_object('exceeds','Pattern is accurate, clear, controlled, and reasonably even.','meets','Pattern is recognizable and mostly accurate with minor inconsistency.','developing','Repeated accuracy or control problems interrupt the pattern.','not_yet','Pattern evidence is absent or insufficient to evaluate.')),
  jsonb_build_object('name','Student reflection/self-awareness','weight',10,'bands',jsonb_build_object('exceeds','Specifically identifies a strength, adjustment, and useful next step.','meets','Identifies all required reflection elements with adequate understanding.','developing','Reflection is vague, incomplete, or weakly connected to the evidence.','not_yet','Reflection is absent or does not demonstrate meaningful self-awareness.')),
  jsonb_build_object('name','Preparation and submission completeness','weight',10,'bands',jsonb_build_object('exceeds','Evidence is complete, clear, and easy to review.','meets','Required evidence is present with minor clarity issues.','developing','One required component is incomplete or difficult to evaluate.','not_yet','Multiple components are absent or evidence cannot be reviewed reliably.'))));
begin
 if (select count(*) from public.courses where slug='piano')<>1 then raise exception 'Rollback requires exactly one canonical Piano course'; end if;
 select id into v_course from public.courses where slug='piano' for share;
 select id into v_level from public.course_levels where course_id=v_course and level_number=1;
 if v_level is null then raise exception 'Rollback stopped: canonical Piano Level 1 is missing'; end if;
 select id into v_module from public.course_modules where course_id=v_course and course_level_id=v_level and level_module_number=1;
 if v_module is null then raise exception 'Rollback stopped: canonical Piano Module 1 is missing'; end if;
 if exists(select 1 from public.enrollments where course_id=v_course and level=1) then raise exception 'Rollback stopped: Piano Level 1 enrollment exists'; end if;
 if exists(select 1 from public.lesson_progress where lesson_id in('a2610001-0000-4000-8000-000000000011','a2610001-0000-4000-8000-000000000012','a2610001-0000-4000-8000-000000000013')) then raise exception 'Rollback stopped: lesson progress exists'; end if;
 if exists(select 1 from public.submissions where activity_id in('a2610001-0000-4000-8000-000000000021','a2610001-0000-4000-8000-000000000022')) then raise exception 'Rollback stopped: submissions/reviews exist'; end if;
 if exists(select 1 from public.practice_logs where activity_id in('a2610001-0000-4000-8000-000000000021','a2610001-0000-4000-8000-000000000022')) then raise exception 'Rollback stopped: practice logs exist'; end if;
 if exists(select 1 from public.activity_progress where activity_id in('a2610001-0000-4000-8000-000000000021','a2610001-0000-4000-8000-000000000022')) then raise exception 'Rollback stopped: activity progress exists'; end if;
 if exists(select 1 from public.portfolio_projects where activity_id in('a2610001-0000-4000-8000-000000000021','a2610001-0000-4000-8000-000000000022')) then raise exception 'Rollback stopped: portfolio evidence exists'; end if;
 if exists(select 1 from public.curriculum_change_requests where module_id=v_module or lesson_id in('a2610001-0000-4000-8000-000000000011','a2610001-0000-4000-8000-000000000012','a2610001-0000-4000-8000-000000000013') or activity_id in('a2610001-0000-4000-8000-000000000021','a2610001-0000-4000-8000-000000000022')) then raise exception 'Rollback stopped: curriculum change request exists'; end if;
 if exists(select 1 from public.curriculum_module_revisions where module_id=v_module) then raise exception 'Rollback stopped: module revision exists'; end if;
 if exists(select 1 from public.course_progress where current_module_id=v_module or current_lesson_id in('a2610001-0000-4000-8000-000000000011','a2610001-0000-4000-8000-000000000012','a2610001-0000-4000-8000-000000000013')) then raise exception 'Rollback stopped: current progress reference exists'; end if;
 if exists(select 1 from public.xp_ledger where module_id=v_module or source_id in('a2610001-0000-4000-8000-000000000021','a2610001-0000-4000-8000-000000000022')) then raise exception 'Rollback stopped: XP/mastery evidence exists'; end if;
 if exists(select 1 from public.module_video_progress where module_id=v_module) or exists(select 1 from public.module_instructional_media where module_id=v_module) then raise exception 'Rollback stopped: media dependency exists'; end if;
 if exists(select 1 from public.certificates where course_id=v_course) then raise exception 'Rollback stopped: Piano certificate dependency exists'; end if;
 if to_regclass('public.portfolio_projects') is not null and exists(select 1 from public.portfolio_projects where course_id=v_course) then raise exception 'Rollback stopped: Piano portfolio dependency exists'; end if;
 if exists(select 1 from public.activities where lesson_id in('a2610001-0000-4000-8000-000000000011','a2610001-0000-4000-8000-000000000012','a2610001-0000-4000-8000-000000000013')) then raise exception 'Rollback stopped: activity references batch lesson'; end if;

 if exists(select 1 from public.activities where id='a2610001-0000-4000-8000-000000000021') and not exists(select 1 from public.activities where id='a2610001-0000-4000-8000-000000000021' and module_id=v_module and course_id=v_course and lesson_id is null and title='Guided Piano Setup Practice' and description='Low-pressure preparation before the assessed challenge.' and activity_type='practice' and instructions='Check the bench or adaptive position, body alignment, natural hand shape, and wrist. Play the approved five-finger pattern with each hand separately. Identify one strength, make one adjustment, and repeat. No submission is required.' and submission_type='none' and xp_reward=0 and estimated_minutes=20 and xp_type='bonus' and not required and status='draft' and rubric='{}'::jsonb and skill_tags=array['piano setup','posture','hand position','five-finger pattern']::text[] and ai_summary='AI-PROPOSED; optional, non-progressive, and non-assessed.' and passing_score=70 and allows_resubmission and not portfolio_candidate and not certificate_eligible) then raise exception 'Rollback stopped: deterministic practice payload drifted'; end if;
 if exists(select 1 from public.activities where id='a2610001-0000-4000-8000-000000000022') and not exists(select 1 from public.activities where id='a2610001-0000-4000-8000-000000000022' and module_id=v_module and course_id=v_course and lesson_id is null and title='Balanced Piano Setup Challenge' and description='Demonstrate a balanced or adaptive setup and controlled beginner five-finger technique.' and activity_type='performance' and instructions='Submit JPAC video evidence showing or explaining your playing position and keyboard distance, natural hand shape, flexible wrist, and two upward/downward repetitions of an approved five-finger pattern with each hand separately unless an accommodation is approved. Include one strength, one adjustment, and one next improvement. Allowed alternatives through existing teacher review include live demonstration, multiple short angles, photographs plus audio, audio plus teacher-observed setup, adapted keyboard, or one-hand evidence. Stop and contact staff if playing causes pain.' and submission_type='video' and xp_reward=350 and estimated_minutes=30 and xp_type='core' and required and status='draft' and passing_score=70 and allows_resubmission and rubric=v_rubric and skill_tags=array['piano setup','posture','hand position','wrist freedom','five-finger pattern','self-reflection']::text[] and ai_summary='AI-PROPOSED — teacher review required. ARIA cannot assess, approve, award XP, grant mastery, or unlock content.' and not portfolio_candidate and not certificate_eligible) then raise exception 'Rollback stopped: deterministic Core Challenge payload drifted'; end if;
 if exists(select 1 from public.lessons where id='a2610001-0000-4000-8000-000000000011') and not exists(select 1 from public.lessons where id='a2610001-0000-4000-8000-000000000011' and module_id=v_module and title='Bench and Body Alignment' and description='Set up the bench or adaptive playing position so your body feels supported, flexible, and ready to move.' and short_summary='Build a stable and comfortable playing setup.' and learning_objective='Establish supported seating, appropriate keyboard distance, relaxed shoulders, and functional arm alignment.' and content_blocks=jsonb_build_array('Sit near the front of the bench or use an approved adaptive position.','Support both feet or use an appropriate foot support.','Adjust distance so elbows can move without reaching or crowding.','Keep the spine tall but flexible and release shoulders, neck, and jaw.','Make one intentional setup adjustment and explain why it helped.') and technique_cues=array['Shoulders away from ears','Elbows have room to move','Supported, not stiff','Stop and contact staff if playing causes pain']::text[] and common_mistakes=array['Reaching for the keyboard','Crowding the keyboard','Raised shoulders','Rigid posture']::text[] and self_check='Can you name one setup adjustment that improved comfort or balance?' and resource_brief='AI-PROPOSED. Alternatives: wheelchair or adaptive seating, foot support, photographs with narration, live teacher demonstration, or assistive communication.' and lesson_type='interactive' and duration_minutes=20 and sort_order=1 and xp_value=0 and status='draft' and wix_lesson_id is null and wix_lesson_url is null) then raise exception 'Rollback stopped: deterministic lesson 1 payload drifted'; end if;
 if exists(select 1 from public.lessons where id='a2610001-0000-4000-8000-000000000012') and not exists(select 1 from public.lessons where id='a2610001-0000-4000-8000-000000000012' and module_id=v_module and title='Curved Fingers and Relaxed Wrists' and description='Practice a natural hand shape, flexible wrist, and gentle controlled key presses.' and short_summary='Use natural hand shape without unnecessary tension.' and learning_objective='Establish a functional finger curve, flexible wrist, relaxed thumb, and controlled press-and-release motion.' and content_blocks=jsonb_build_array('Observe the hand natural resting shape.','Place five fingers on neighboring white keys without pressing.','Press and release one key at a time.','Pause after each sequence and release the wrist.','Name one sign of tension and one reset strategy.') and technique_cues=array['Natural rather than forced curve','Flexible wrist','Release after each note','Slow down when joints collapse']::text[] and common_mistakes=array['Forced finger curve','Rigid or collapsed wrist','Tucked rigid thumb','Excessive finger lifting']::text[] and self_check='What tension sign did you notice, and how did you reset?' and resource_brief='AI-PROPOSED. Alternatives: approved individual hand position, one hand, fewer notes, adaptive keyboard, live or narrated evidence.' and lesson_type='interactive' and duration_minutes=20 and sort_order=2 and xp_value=0 and status='draft' and wix_lesson_id is null and wix_lesson_url is null) then raise exception 'Rollback stopped: deterministic lesson 2 payload drifted'; end if;
 if exists(select 1 from public.lessons where id='a2610001-0000-4000-8000-000000000013') and not exists(select 1 from public.lessons where id='a2610001-0000-4000-8000-000000000013' and module_id=v_module and title='Five-Finger Technique Check' and description='Combine setup and hand technique in a slow five-note pattern with each hand separately.' and short_summary='Apply balanced setup to a controlled five-finger pattern.' and learning_objective='Play an approved five-note pattern with functional posture, hand shape, wrist freedom, note-order accuracy, and self-awareness.' and content_blocks=jsonb_build_array('Place one hand over an approved five-note pattern such as C-D-E-F-G.','Play upward and downward slowly.','Pause and release tension before repeating with the other hand.','Use about 60 BPM only when it supports relaxed control.','Identify one strength and one next improvement.') and technique_cues=array['Control before speed','Clear even notes','Pause and reset','Hands separate first']::text[] and common_mistakes=array['Rushing to match the metronome','Continuing through tension','Finger collapse','Unplanned restart']::text[] and self_check='What improved between your first and second controlled attempt?' and resource_brief='AI-PROPOSED. Alternatives: fewer notes, one hand, adapted controller, audio plus teacher-observed setup, or counted pulse without metronome.' and lesson_type='interactive' and duration_minutes=25 and sort_order=3 and xp_value=0 and status='draft' and wix_lesson_id is null and wix_lesson_url is null) then raise exception 'Rollback stopped: deterministic lesson 3 payload drifted'; end if;
 delete from public.activities where id in('a2610001-0000-4000-8000-000000000021','a2610001-0000-4000-8000-000000000022') and module_id=v_module and status='draft';
 delete from public.lessons where id in('a2610001-0000-4000-8000-000000000011','a2610001-0000-4000-8000-000000000012','a2610001-0000-4000-8000-000000000013') and module_id=v_module and status='draft';
 if v_module='a2610001-0000-4000-8000-000000000002' then
   if not exists(select 1 from public.course_modules where id=v_module and course_id=v_course and course_level_id=v_level and level_module_number=1 and sort_order=1 and title='Piano Posture and Hand Position' and description='Establish a balanced or adaptive setup, natural hand shape, relaxed wrists, and controlled five-finger movement.' and short_intro='Build a comfortable Piano setup before speed: align, relax, play slowly, observe, and adjust.' and status='draft' and xp_value=625 and core_xp=625 and intro_core_xp=50 and video_core_xp=100 and assignment_core_xp=350 and mastery_core_xp=125 and core_unlock_threshold=438 and bonus_xp_available=0 and primary_video_url is null and video_provider is null and video_title is null and video_duration_seconds is null and active_instructional_media_id is null and video_brief='NEEDS REVIEW: Validate source video accuracy, availability, licensing, captions, transcript quality, and alignment before creating media.' and aria_coaching_targets=jsonb_build_object('advisory_only',true,'targets',jsonb_build_array('posture','bench distance','curved fingers','relaxed wrists','finger independence','wrist tension','finger collapse','hand positioning','slow practice','confidence building'),'prohibited',jsonb_build_array('assess','approve evidence','award XP','grant mastery','unlock content','diagnose injury')) and lab_tool_id is null and jpac_tool_activity='{}'::jsonb and real_world_activity='{}'::jsonb and career_connection='' and career_mission_ideas='[]'::jsonb and not portfolio_moment and review_notes='AI-PROPOSED — leadership and piano-teacher review required. Media NEEDS REVIEW; tools NEEDS CATALOG REVIEW.' and approved_by is null and approved_at is null) then raise exception 'Rollback stopped: deterministic module payload is not batch-compatible'; end if;
   if exists(select 1 from public.lessons where module_id=v_module) or exists(select 1 from public.activities where module_id=v_module) then raise exception 'Rollback stopped: module has remaining children'; end if;
   delete from public.course_modules where id=v_module and course_id=v_course and status='draft' and level_module_number=1 and title='Piano Posture and Hand Position';
 end if;
 if v_level='a2610001-0000-4000-8000-000000000001' then
   if not exists(select 1 from public.course_levels where id=v_level and course_id=v_course and level_number=1 and title='Beginner' and description='Beginner Piano foundations. Draft review only.' and learning_objectives=array['Build healthy setup and foundational keyboard control.']::text[] and status='draft' and core_xp_target=6250 and review_notes='Piano Module 1 pilot; AI-PROPOSED content requires leadership and piano-teacher review.' and approved_by is null and approved_at is null) then raise exception 'Rollback stopped: deterministic level payload is not batch-compatible'; end if;
   if exists(select 1 from public.course_modules where course_level_id='a2610001-0000-4000-8000-000000000001') then raise exception 'Rollback stopped: batch level has remaining modules'; end if;
   delete from public.course_levels where id='a2610001-0000-4000-8000-000000000001' and course_id=v_course and level_number=1 and status='draft';
 end if;
 if not exists(select 1 from public.courses where id=v_course and slug='piano') then raise exception 'Canonical Piano course invariant failed'; end if;
 if (select count(*) from public.courses where slug='singing')<>1 then raise exception 'Protected Singing identity invariant failed'; end if;
end $$;

commit;
