-- PREPARED ONLY: destructive rollback for the matching import; separate approval required.
begin;

do $$ declare actual text; begin
  select md5(coalesce(string_agg(concat_ws('|',m.id::text,coalesce(m.primary_video_url,''),coalesce(m.video_title,''),coalesce(m.video_provider,''),coalesce(m.video_duration_seconds::text,''),coalesce(m.active_instructional_media_id::text,''),(select count(*) from public.module_instructional_media x where x.module_id=m.id)::text),E'\n' order by m.id),'')) into actual from public.course_modules m join public.courses c on c.id=m.course_id where c.slug='singing' and (m.primary_video_url is not null or m.video_title is not null or m.video_provider is not null or m.video_duration_seconds is not null or m.active_instructional_media_id is not null or exists(select 1 from public.module_instructional_media x where x.module_id=m.id)); if actual<>'e6e45328064ad2b26c8d7df6de4383ec' then raise exception 'Singing video/media-count baseline changed; rollback refused'; end if;
  if (select count(*) from public.lessons l join public.course_modules m on m.id=l.module_id join public.courses c on c.id=m.course_id join public.course_levels cl on cl.id=m.course_level_id where c.slug='singing' and cl.level_number between 2 and 4)<>90 then raise exception 'Expected imported 90 lessons'; end if;
  if (select count(*) from public.activities a join public.course_modules m on m.id=a.module_id join public.courses c on c.id=m.course_id join public.course_levels cl on cl.id=m.course_level_id where c.slug='singing' and cl.level_number between 2 and 4)<>30 then raise exception 'Expected imported 30 assignments'; end if;
end $$;

delete from public.activities a using public.course_modules m,public.courses c,public.course_levels cl
where a.module_id=m.id and c.id=m.course_id and cl.id=m.course_level_id and c.slug='singing' and cl.level_number between 2 and 4;
delete from public.lessons l using public.course_modules m,public.courses c,public.course_levels cl
where l.module_id=m.id and c.id=m.course_id and cl.id=m.course_level_id and c.slug='singing' and cl.level_number between 2 and 4;

with old(level_number,module_number,title,career) as(values
(2,1,'Breath Control Under Pressure','Reliable support helps performers stay consistent through demanding phrases.'),(2,2,'Extending Range and Registration','Flexible registration expands repertoire and professional versatility.'),(2,3,'Tone Colors and Style','Working singers adapt tone while maintaining healthy technique.'),(2,4,'Harmony and Ensemble Precision','Ensemble accuracy is essential for groups, sessions, and live productions.'),(2,5,'Runs, Riffs and Musical Choices','Agility becomes useful when musical choices remain intentional.'),(2,6,'Interpretation and Phrasing','Phrasing turns correct notes into a compelling performance.'),(2,7,'Studio Vocal Workflow','Recording workflows teach preparation, comping awareness, and repeatable takes.'),(2,8,'Live Performance Stamina','Performance stamina supports rehearsals, shows, and touring conditions.'),(2,9,'Collaboration Session','Professional creators communicate, revise, and deliver within a team.'),(2,10,'Intermediate Performance Project','A complete project demonstrates growing independence and artistic decision-making.'),
(3,1,'Advanced Vocal Coordination','Advanced coordination supports demanding repertoire safely.'),(3,2,'Genre Fluency','Genre awareness helps vocalists work across varied creative opportunities.'),(3,3,'Advanced Harmony and Arrangement','Arrangement skills expand ensemble, production, and directing opportunities.'),(3,4,'Improvisation With Intent','Improvisation supports responsive, original performance choices.'),(3,5,'Character, Emotion and Authenticity','Authentic interpretation connects technique to audience experience.'),(3,6,'Recording Session Leadership','Session leadership combines preparation, communication, and efficient delivery.'),(3,7,'Performance Production','Artists coordinate sound, staging, visuals, and collaborators.'),(3,8,'Audition Strategy','Audition readiness combines material choice, preparation, and adaptability.'),(3,9,'Original Vocal Project','Independent creation demonstrates advanced artistic ownership.'),(3,10,'Advanced Showcase','A polished showcase provides evidence for performance and portfolio review.'),
(4,1,'Professional Vocal Identity','Professionals define their sound, strengths, audience, and working direction.'),(4,2,'Signature Repertoire','Strategic repertoire communicates identity and employable range.'),(4,3,'High-Level Studio Delivery','Professional recording requires consistency, direction-taking, and efficient revision.'),(4,4,'Live Set Design','Set design balances pacing, audience experience, stamina, and artistic purpose.'),(4,5,'Creative Direction and Collaboration','Creative leaders align collaborators around a clear performance vision.'),(4,6,'Vocal Business Essentials','Working artists need practical knowledge of preparation, communication, rights, and delivery.'),(4,7,'Brand and Audience Connection','Clear presentation helps audiences and collaborators understand an artist’s work.'),(4,8,'Professional Audition Package','A strong package makes skills easy for decision-makers to evaluate.'),(4,9,'Portfolio-Ready Capstone','A capstone demonstrates independent professional creative practice.'),(4,10,'Career-Ready Showcase','The final showcase connects mastery evidence to next career actions.')
), targets as(select m.id,o.* from old o join public.courses c on c.slug='singing' join public.course_levels cl on cl.course_id=c.id and cl.level_number=o.level_number join public.course_modules m on m.course_level_id=cl.id and m.level_module_number=o.module_number)
update public.course_modules m set title=t.title,description='Draft creative module outline. Requires human-authored lessons, video, assignment, rubric, and two practice reviews before approval.',short_intro='Create, perform, compare, improve, and show a measurable skill through a concise studio challenge.',learning_objectives='{}',career_connection=t.career,portfolio_moment=false,updated_at=now() from targets t where m.id=t.id;

do $$ begin
  if exists(select 1 from public.lessons l join public.course_modules m on m.id=l.module_id join public.courses c on c.id=m.course_id join public.course_levels cl on cl.id=m.course_level_id where c.slug='singing' and cl.level_number between 2 and 4) or exists(select 1 from public.activities a join public.course_modules m on m.id=a.module_id join public.courses c on c.id=m.course_id join public.course_levels cl on cl.id=m.course_level_id where c.slug='singing' and cl.level_number between 2 and 4) then raise exception 'Rollback child cleanup failed'; end if;
end $$;

commit;
