import'./styles/auth-milestone.css';import'./styles/student-access.css';import{BrowserRouter,Navigate,Route,Routes,useLocation}from'react-router-dom';
import type{ReactNode}from'react';import{AppLayout}from'./layouts/AppLayout';import{StudioPage,CareerPage,AchievementsPage}from'./pages/pages';import{StudentDashboardPage}from'./pages/StudentDashboardPage';import{MyCoursesPage}from'./pages/MyCoursesPage';import{CoursePage}from'./pages/CoursePage';import{LessonPage}from'./pages/LessonPage';import{OperationsCenterPage}from'./pages/OperationsCenterPage';import{CurriculumStudioPage}from'./pages/CurriculumStudioPage';import{EnrollmentManagerPage}from'./pages/EnrollmentManagerPage';import{ManualStudentPage}from'./pages/ManualStudentPage';import{LabManagerPage}from'./pages/LabManagerPage';import{AriaCorePage}from'./pages/AriaCorePage';import{StudentIntelligencePage}from'./pages/StudentIntelligencePage';import{MentorIntelligencePage}from'./pages/MentorIntelligencePage';import{PracticeCoachPage}from'./pages/PracticeCoachPage';import{DreamBoardIntelligencePage}from'./pages/DreamBoardIntelligencePage';import{CreativeChallengesPage}from'./pages/CreativeChallengesPage';import{CertificateCenterPage}from'./pages/CertificateCenterPage';import{VerificationPage}from'./pages/VerificationPage';import{AdminPage}from'./pages/AdminPage';import{TeacherPage}from'./pages/TeacherPage';import{DeveloperStudioPage}from'./pages/DeveloperStudioPage';import{LoginPage}from'./pages/LoginPage';import{AuthCallbackPage}from'./pages/AuthCallbackPage';import{SetPasswordPage}from'./pages/SetPasswordPage';import{ForgotPasswordPage}from'./pages/ForgotPasswordPage';import{useAuth,type AppRole}from'./context/AuthContext';
import{AcademyDashboardPage}from'./pages/AcademyDashboardPage';
function Loading(){return <div className="auth-loading"><img src="/assets/jpac-official-logo.png.png" alt="J. Moné's Performing Arts Center"/><p>Preparing your creative workspace…</p></div>}
function RequireAuth(){const{user,loading}=useAuth();const location=useLocation();if(loading)return <Loading/>;if(!user)return <Navigate to="/login" replace state={{from:location.pathname}}/>;return <AppLayout/>}
function RequireRole({roles,children}:{roles:AppRole[];children:ReactNode}){const{profile,loading}=useAuth();if(loading||!profile)return <Loading/>;return roles.includes(profile.role)?children:<Navigate to="/" replace/>}
function HomeRoute(){const{profile}=useAuth();if(profile?.role==='student')return <StudentDashboardPage/>;return profile&&['admin','developer'].includes(profile.role)?<OperationsCenterPage/>:<AcademyDashboardPage/>}
const staff:AppRole[]=['teacher','admin','developer'];const admins:AppRole[]=['admin','developer'];
export default function App(){return <BrowserRouter><Routes><Route path="/verify/:token" element={<VerificationPage/>}/><Route path="/auth/callback" element={<AuthCallbackPage/>}/><Route path="/forgot-password" element={<ForgotPasswordPage/>}/><Route path="/set-password" element={<SetPasswordPage/>}/><Route path="/login" element={<LoginPage/>}/><Route element={<RequireAuth/>}><Route path="/" element={<HomeRoute/>}/><Route path="/courses" element={<MyCoursesPage/>}/><Route path="/courses/:courseId" element={<CoursePage/>}/><Route path="/courses/:courseId/lessons/:lessonId" element={<LessonPage/>}/><Route path="/mentor" element={<MentorIntelligencePage/>}/><Route path="/practice-coach" element={<PracticeCoachPage/>}/><Route path="/challenges" element={<CreativeChallengesPage/>}/><Route path="/student-intelligence" element={<StudentIntelligencePage/>}/><Route path="/studio" element={<StudioPage/>}/><Route path="/dream-board" element={<DreamBoardIntelligencePage/>}/><Route path="/career" element={<CareerPage/>}/><Route path="/achievements" element={<AchievementsPage/>}/><Route path="/certificates" element={<CertificateCenterPage/>}/><Route path="/curriculum" element={<RequireRole roles={staff}><CurriculumStudioPage/></RequireRole>}/><Route path="/teacher" element={<RequireRole roles={staff}><TeacherPage/></RequireRole>}/><Route path="/enrollment" element={<RequireRole roles={admins}><EnrollmentManagerPage/></RequireRole>}/><Route path="/manual-student" element={<RequireRole roles={admins}><ManualStudentPage/></RequireRole>}/><Route path="/lab-manager" element={<RequireRole roles={admins}><LabManagerPage/></RequireRole>}/><Route path="/aria-core" element={<RequireRole roles={admins}><AriaCorePage/></RequireRole>}/><Route path="/admin" element={<RequireRole roles={admins}><AdminPage/></RequireRole>}/><Route path="/developer" element={<RequireRole roles={['developer']}><DeveloperStudioPage/></RequireRole>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes></BrowserRouter>}
