-- JPAC Audio Engineering 48-module draft rollout. Run only after preflight PASS and explicit approval.
begin;
do $$
declare
 v_course uuid; v_level uuid; v_module uuid; v_lesson_title text; v_rubric jsonb; v_module_created boolean; r record; i int; v_review text;
 v_marker constant text := 'Audio Engineering full draft rollout 202608140005';
 v_levels constant text[] := array['Beginner','Intermediate','Advanced','Master'];
begin
 if (select count(*) from public.courses where slug='audio-engineering')<>1 then raise exception 'Expected exactly one canonical audio-engineering course'; end if;
 select id into v_course from public.courses where slug='audio-engineering' for share;
 if exists(select 1 from public.enrollments where course_id=v_course)
 or exists(select 1 from public.submissions s join public.activities a on a.id=s.activity_id where a.course_id=v_course)
 or exists(select 1 from public.lesson_progress p join public.lessons l on l.id=p.lesson_id join public.course_modules m on m.id=l.module_id where m.course_id=v_course)
 or exists(select 1 from public.activity_progress p join public.activities a on a.id=p.activity_id where a.course_id=v_course)
 or exists(select 1 from public.practice_logs p join public.activities a on a.id=p.activity_id where a.course_id=v_course)
 or exists(select 1 from public.xp_ledger where course_id=v_course)
 or exists(select 1 from public.certificates where course_id=v_course)
 or exists(select 1 from public.portfolio_projects p join public.activities a on a.id=p.activity_id where a.course_id=v_course)
 or exists(select 1 from public.module_instructional_media mi join public.course_modules m on m.id=mi.module_id where m.course_id=v_course)
 or exists(select 1 from public.lab_tool_courses where course_id=v_course)
 then raise exception 'Audio Engineering student/evidence dependencies block rollout'; end if;
 if (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('jpac_sync_enrollment_progress','jpac_enforce_canonical_enrollment_progress') and (select count(*) from regexp_matches(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m\.status=''published''','g'))=2 and strpos(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m.status<>''archived''')=0)<>2 then raise exception 'Safe Draft Isolation is not active'; end if;
 if (select count(*) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='enrollments' and t.tgname='enrollments_enforce_canonical_progress' and not t.tgisinternal and t.tgenabled<>'D')<>1 then raise exception 'Canonical enrollment progress trigger missing'; end if;

 v_rubric:=jsonb_build_object('criteria',jsonb_build_array(
  jsonb_build_object('name','Technical Setup & Signal Flow','weight',20,'bands',jsonb_build_object('Exceeds','Technical setup and signal flow consistently exceed the approved standard.','Meets','Technical setup and signal flow meet the approved standard.','Developing','Technical setup and signal flow partially meet the standard.','Not Yet','Technical setup and signal flow do not yet meet the standard.')),
  jsonb_build_object('name','Recording / Sound Capture Quality','weight',20,'bands',jsonb_build_object('Exceeds','Sound capture consistently exceeds the approved standard.','Meets','Sound capture meets the approved standard.','Developing','Sound capture partially meets the standard.','Not Yet','Sound capture does not yet meet the standard.')),
  jsonb_build_object('name','Mixing, Balance & Processing','weight',20,'bands',jsonb_build_object('Exceeds','Mixing and processing consistently exceed the approved standard.','Meets','Mixing and processing meet the approved standard.','Developing','Mixing and processing partially meet the standard.','Not Yet','Mixing and processing do not yet meet the standard.')),
  jsonb_build_object('name','Creative Sound Design / Production Choices','weight',20,'bands',jsonb_build_object('Exceeds','Creative choices consistently exceed the approved standard.','Meets','Creative choices meet the approved standard.','Developing','Creative choices partially meet the standard.','Not Yet','Creative choices do not yet meet the standard.')),
  jsonb_build_object('name','Professional Delivery & Reflection','weight',20,'bands',jsonb_build_object('Exceeds','Delivery and reflection consistently exceed the approved standard.','Meets','Delivery and reflection meet the approved standard.','Developing','Delivery and reflection partially meet the standard.','Not Yet','Delivery and reflection do not yet meet the standard.'))
 ));

 for r in select * from jsonb_to_recordset('[
 {"level":1,"num":1,"sort":1,"title":"Sound Waves, Frequency & Critical Listening"},{"level":1,"num":2,"sort":2,"title":"DAW Fundamentals & First Session"},{"level":1,"num":3,"sort":3,"title":"Drum Programming & Timing Foundations"},{"level":1,"num":4,"sort":4,"title":"Microphone Types & Safe Setup"},{"level":1,"num":5,"sort":5,"title":"Recording Your First Audio"},{"level":1,"num":6,"sort":6,"title":"Intro to EQ"},{"level":1,"num":7,"sort":7,"title":"Synthesizer & Sound-Generation Basics"},{"level":1,"num":8,"sort":8,"title":"MIDI Fundamentals"},{"level":1,"num":9,"sort":9,"title":"Basic Mixing: Levels, Panning & Stereo Image"},{"level":1,"num":10,"sort":10,"title":"Basic Editing: Cuts, Fades & Comping"},{"level":1,"num":11,"sort":11,"title":"Intro to Compression"},{"level":1,"num":12,"sort":12,"title":"Beginner Mixdown Showcase"},
 {"level":2,"num":1,"sort":13,"title":"Advanced Drum Engineering"},{"level":2,"num":2,"sort":14,"title":"Intermediate Microphone Techniques"},{"level":2,"num":3,"sort":15,"title":"Signal Flow & Routing"},{"level":2,"num":4,"sort":16,"title":"EQ & Advanced Frequency Shaping"},{"level":2,"num":5,"sort":17,"title":"Compression & Advanced Dynamics"},{"level":2,"num":6,"sort":18,"title":"Sampling: Time, Pitch & Authorized Source Use"},{"level":2,"num":7,"sort":19,"title":"Reverb, Delay & Modulation"},{"level":2,"num":8,"sort":20,"title":"Vocal Recording Techniques"},{"level":2,"num":9,"sort":21,"title":"Saturation & Harmonic Character"},{"level":2,"num":10,"sort":22,"title":"Mixing Workflow & Strategy"},{"level":2,"num":11,"sort":23,"title":"Automation in Mixing"},{"level":2,"num":12,"sort":24,"title":"Acoustic Treatment & Studio Readiness"},
 {"level":3,"num":1,"sort":25,"title":"Advanced Microphone Techniques"},{"level":3,"num":2,"sort":26,"title":"Advanced Mixing: Parallel Processing, Bus Compression & Translation"},{"level":3,"num":3,"sort":27,"title":"Advanced Automation"},{"level":3,"num":4,"sort":28,"title":"Vocal Production & Processing"},{"level":3,"num":5,"sort":29,"title":"Mastering Techniques"},{"level":3,"num":6,"sort":30,"title":"Live Sound Engineering"},{"level":3,"num":7,"sort":31,"title":"Audio Post-Production"},{"level":3,"num":8,"sort":32,"title":"Stereo Imaging & Widening"},{"level":3,"num":9,"sort":33,"title":"Sound Design"},{"level":3,"num":10,"sort":34,"title":"Reference Mixing & Critical Translation"},{"level":3,"num":11,"sort":35,"title":"Analog vs. Digital Systems"},{"level":3,"num":12,"sort":36,"title":"Full Band Recording Showcase"},
 {"level":4,"num":1,"sort":37,"title":"Mastering: The Final Polish"},{"level":4,"num":2,"sort":38,"title":"Advanced Mixing Systems"},{"level":4,"num":3,"sort":39,"title":"Advanced Sound Design"},{"level":4,"num":4,"sort":40,"title":"Mastering for Streaming & LUFS"},{"level":4,"num":5,"sort":41,"title":"Studio Design & Acoustics"},{"level":4,"num":6,"sort":42,"title":"Client Sessions & Communication"},{"level":4,"num":7,"sort":43,"title":"Mentoring Junior Engineers"},{"level":4,"num":8,"sort":44,"title":"Future Audio Technology & Responsible AI"},{"level":4,"num":9,"sort":45,"title":"Professional Studio Workflow"},{"level":4,"num":10,"sort":46,"title":"Experimental & Innovative Engineering"},{"level":4,"num":11,"sort":47,"title":"Industry Professional Practices, Standards & Delivery"},{"level":4,"num":12,"sort":48,"title":"Master Capstone: Complete Album Production"}
 ]'::jsonb) as x(level int,num int,sort int,title text) order by sort loop
  select id into v_level from public.course_levels where course_id=v_course and level_number=r.level;
  if v_level is null then
   insert into public.course_levels(id,course_id,level_number,title,description,learning_objectives,status,core_xp_target,review_notes)
   values(gen_random_uuid(),v_course,r.level,v_levels[r.level],'Draft Audio Engineering level; canonical source-classification review only.',array['Develop source-aligned recording, signal-flow, mixing, sound-design, mastering, and professional audio delivery skills safely.'],'draft',7500,v_marker||'; batch-created level; canonical 12-module level.') returning id into v_level;
  elsif not exists(select 1 from public.course_levels where id=v_level and title=v_levels[r.level] and description='Draft Audio Engineering level; canonical source-classification review only.' and learning_objectives=array['Develop source-aligned recording, signal-flow, mixing, sound-design, mastering, and professional audio delivery skills safely.'] and status='draft' and core_xp_target=7500 and approved_by is null and approved_at is null) then raise exception 'Incompatible Audio Engineering level %',r.level; end if;

  v_review:=v_marker||'; canonical KEEP module; MERGE content is incorporated only within approved targets. MEDIA NEEDS REVIEW; NEEDS CATALOG REVIEW; TOOL/ACCESSIBILITY REVIEW; no media or tool records are created.';
  if (r.level=1 and r.num in(3,7,8)) or (r.level=2 and r.num in(1,6)) or (r.level=3 and r.num=7) then v_review:=v_review||' SCOPE REVIEW.'; end if;
  if (r.level=2 and r.num=6) or (r.level=3 and r.num in(7,10)) or (r.level=4 and r.num in(1,4,11,12)) then v_review:=v_review||' RIGHTS/DISTRIBUTION REVIEW.'; end if;
  if (r.level=2 and r.num=12) or (r.level=3 and r.num=6) or (r.level=4 and r.num in(5,6,7,9,11)) then v_review:=v_review||' BUSINESS/LEGAL REVIEW.'; end if;
  if r.level=4 and r.num in(8,10) then v_review:=v_review||' AI/ETHICS REVIEW.'; end if;
  if r.level=4 and r.num=12 then v_review:=v_review||' Approved final capstone; raw Mix and Master an Album assessment is merged as staged evidence, not a standalone module.'; end if;

  select id into v_module from public.course_modules where course_id=v_course and (sort_order=r.sort or (course_level_id=v_level and level_module_number=r.num));
  if v_module is null then
   insert into public.course_modules(id,course_id,course_level_id,level_module_number,title,description,short_intro,sort_order,xp_value,core_xp,intro_core_xp,video_core_xp,assignment_core_xp,mastery_core_xp,core_unlock_threshold,bonus_xp_available,jpac_tool_activity,real_world_activity,career_connection,portfolio_moment,status,video_brief,aria_coaching_targets,career_mission_ideas,review_notes)
   values(gen_random_uuid(),v_course,v_level,r.num,r.title,'Develop and demonstrate canonical Audio Engineering skills for '||r.title||'.','Draft canonical Audio Engineering module.',r.sort,625,625,50,100,350,125,438,0,'{}'::jsonb,jsonb_build_object('title',r.title||' Guided Practice','instructions','Practice the approved engineering objective using safe listening levels and teacher-approved DAW-neutral, equipment-neutral, or supplied-material alternatives.'),'',false,'draft','MEDIA NEEDS REVIEW: no media is activated.',jsonb_build_object('advisory_only',true,'targets',jsonb_build_array('gain staging','clean recording setup','DAW workflow','EQ','compression','panning and stereo image','reverb, delay, and effects','MIDI and beat engineering','sound design','mastering and LUFS','client and studio workflow','safe listening and hearing protection'),'prohibited',jsonb_build_array('assess','approve','diagnose hearing conditions','award XP','grant mastery','unlock','publish')),'[]'::jsonb,v_review) returning id into v_module;
   v_module_created:=true;
  elsif not exists(select 1 from public.course_modules where id=v_module and course_level_id=v_level and level_module_number=r.num and sort_order=r.sort and title=r.title and description='Develop and demonstrate canonical Audio Engineering skills for '||r.title||'.' and short_intro='Draft canonical Audio Engineering module.' and status='draft' and xp_value=625 and core_xp=625 and intro_core_xp=50 and video_core_xp=100 and assignment_core_xp=350 and mastery_core_xp=125 and core_unlock_threshold=438 and bonus_xp_available=0 and jpac_tool_activity='{}'::jsonb and real_world_activity=jsonb_build_object('title',r.title||' Guided Practice','instructions','Practice the approved engineering objective using safe listening levels and teacher-approved DAW-neutral, equipment-neutral, or supplied-material alternatives.') and career_connection='' and not portfolio_moment and video_brief='MEDIA NEEDS REVIEW: no media is activated.' and review_notes=v_review and lab_tool_id is null and active_instructional_media_id is null and primary_video_url is null and approved_by is null and approved_at is null) then raise exception 'Incompatible Audio Engineering module L% M%',r.level,r.num; end if;

  if v_module_created is distinct from true then
   if (select count(*) from public.lessons where module_id=v_module)<>3
   or (select count(*) from public.lessons where module_id=v_module and status='draft' and xp_value=0 and title in(r.title||': Technical Foundations and Safety',r.title||': Guided Engineering Application',r.title||': Professional Delivery and Reflection'))<>3
   or (select count(*) from public.activities where module_id=v_module)<>2
   or (select count(*) from public.activities where module_id=v_module and title=r.title||' Guided Practice' and status='draft' and activity_type='practice' and not required and xp_reward=0 and xp_type='bonus')<>1
   or (select count(*) from public.activities where module_id=v_module and title=r.title||' Core Challenge' and status='draft' and activity_type='performance' and required and xp_reward=350 and xp_type='core' and passing_score=70 and allows_resubmission and rubric=v_rubric)<>1
   then raise exception 'Existing Audio Engineering module children are not exact-compatible L% M%',r.level,r.num; end if;
  else
   for i in 1..3 loop
    v_lesson_title:=case i when 1 then r.title||': Technical Foundations and Safety' when 2 then r.title||': Guided Engineering Application' else r.title||': Professional Delivery and Reflection' end;
    insert into public.lessons(id,module_id,title,description,lesson_type,duration_minutes,sort_order,xp_value,status,short_summary,learning_objective,content_blocks,technique_cues,common_mistakes,self_check,resource_brief)
    values(gen_random_uuid(),v_module,v_lesson_title,'Study and apply '||v_lesson_title||'.','interactive',25,i,0,'draft','Canonical Audio Engineering lesson; draft review only.','Study and apply '||v_lesson_title||'.',jsonb_build_array('Plan signal flow, monitoring level, source rights, and the engineering objective.','Apply the technique with teacher-approved DAW-neutral tools or supplied material.','Review technical quality, creative choices, safe listening, delivery, and one next step.'),array['Set conservative gain and monitoring levels','Confirm routing before processing','Take listening breaks and use authorized source material'],array['Clipping or unsafe monitoring','Treating optional software or hardware as mandatory','Using unlicensed material or publishing without approval'],'Can you demonstrate the objective and explain one engineering decision?','AI-PROPOSED lesson details and accessibility alternatives require Audio Engineering teacher review.');
   end loop;
   insert into public.activities(id,course_id,module_id,title,description,activity_type,instructions,submission_type,xp_reward,estimated_minutes,required,status,rubric,skill_tags,ai_summary,xp_type,passing_score,allows_resubmission,portfolio_candidate,certificate_eligible) values
   (gen_random_uuid(),v_course,v_module,r.title||' Guided Practice','Optional canonical Audio Engineering preparation.','practice','Practice at safe listening levels using a teacher-approved DAW-neutral, equipment-neutral, simulated, written, or supplied-audio alternative. Named products are optional examples only.','none',0,20,false,'draft','{}'::jsonb,'{}'::text[],'AI-PROPOSED; optional, non-progressive, non-assessed; teacher review required.','bonus',70,true,false,false),
   (gen_random_uuid(),v_course,v_module,r.title||' Core Challenge','Required canonical Audio Engineering Core Challenge.','performance','Submit an authorized recording, session export, mix, master, routing plan, analysis, or equivalent accessible evidence through the existing JPAC submission and teacher-review workflow. Use safe listening levels; do not publish or distribute externally.','file',350,30,true,'draft',v_rubric,'{}'::text[],'AI-PROPOSED; teacher review required; Aria advisory only.','core',70,true,false,false);
  end if;
  v_level:=null; v_module:=null; v_module_created:=false;
 end loop;
end $$;
commit;
