-- JPAC Acting 46-module draft rollout. Review and run only after preflight PASS.
begin;
do $$
declare
 v_course uuid; v_level uuid; v_module uuid; v_lesson_title text; v_rubric jsonb; v_module_created boolean; r record; i int;
 v_marker constant text := 'Acting full draft rollout 202608140002';
 v_levels constant text[] := array['Beginner','Intermediate','Advanced','Master'];
begin
 if (select count(*) from public.courses where slug='acting') <> 1 then raise exception 'Expected exactly one canonical acting course'; end if;
 select id into v_course from public.courses where slug='acting' for share;
 if exists(select 1 from public.enrollments where course_id=v_course)
 or exists(select 1 from public.submissions s join public.activities a on a.id=s.activity_id where a.course_id=v_course)
 or exists(select 1 from public.lesson_progress p join public.lessons l on l.id=p.lesson_id join public.course_modules m on m.id=l.module_id where m.course_id=v_course)
 or exists(select 1 from public.activity_progress p join public.activities a on a.id=p.activity_id where a.course_id=v_course)
 or exists(select 1 from public.practice_logs p join public.activities a on a.id=p.activity_id where a.course_id=v_course)
 or exists(select 1 from public.xp_ledger where course_id=v_course)
 or exists(select 1 from public.certificates where course_id=v_course)
 or exists(select 1 from public.portfolio_projects p join public.activities a on a.id=p.activity_id where a.course_id=v_course)
 then raise exception 'Acting student/evidence dependencies block rollout'; end if;
 if (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('jpac_sync_enrollment_progress','jpac_enforce_canonical_enrollment_progress') and (select count(*) from regexp_matches(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m\.status=''published''','g'))=2 and strpos(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m.status<>''archived''')=0)<>2 then raise exception 'Safe Draft Isolation is not active'; end if;
 if (select count(*) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='enrollments' and t.tgname='enrollments_enforce_canonical_progress' and not t.tgisinternal and t.tgenabled<>'D')<>1 then raise exception 'Canonical enrollment progress trigger missing'; end if;

 v_rubric:=jsonb_build_object('criteria',jsonb_build_array(
  jsonb_build_object('name','Character truth and objective','weight',25,'bands',jsonb_build_object('Exceeds','Consistently exceeds the approved standard.','Meets','Meets the approved standard.','Developing','Partially meets the standard.','Not Yet','Does not yet meet the standard.')),
  jsonb_build_object('name','Voice, speech, and textual clarity','weight',20,'bands',jsonb_build_object('Exceeds','Consistently exceeds the approved standard.','Meets','Meets the approved standard.','Developing','Partially meets the standard.','Not Yet','Does not yet meet the standard.')),
  jsonb_build_object('name','Physical expression and stage/screen technique','weight',20,'bands',jsonb_build_object('Exceeds','Consistently exceeds the approved standard.','Meets','Meets the approved standard.','Developing','Partially meets the standard.','Not Yet','Does not yet meet the standard.')),
  jsonb_build_object('name','Listening, responsiveness, and emotional safety','weight',20,'bands',jsonb_build_object('Exceeds','Consistently exceeds the approved standard.','Meets','Meets the approved standard.','Developing','Partially meets the standard.','Not Yet','Does not yet meet the standard.')),
  jsonb_build_object('name','Preparation, reflection, and submission completeness','weight',15,'bands',jsonb_build_object('Exceeds','Consistently exceeds the approved standard.','Meets','Meets the approved standard.','Developing','Partially meets the standard.','Not Yet','Does not yet meet the standard.'))
 ));

 for r in select * from jsonb_to_recordset('[
 {"level":1,"num":1,"sort":1,"title":"Stage Presence & First Impressions"},{"level":1,"num":2,"sort":2,"title":"Intro to Improvisation: Yes, And..."},{"level":1,"num":3,"sort":3,"title":"Voice & Character Voices"},{"level":1,"num":4,"sort":4,"title":"Facial Expressions & Emotions"},{"level":1,"num":5,"sort":5,"title":"Scene Study: First Read"},{"level":1,"num":6,"sort":6,"title":"Partner Scenes & Interaction"},{"level":1,"num":7,"sort":7,"title":"Comedy Basics & Timing"},{"level":1,"num":8,"sort":8,"title":"Basic Drama & Emotional Truth"},{"level":1,"num":9,"sort":9,"title":"Different Worlds & Time Periods"},{"level":1,"num":10,"sort":10,"title":"Costume and Props"},{"level":1,"num":11,"sort":11,"title":"Audition Basics & Presentation"},{"level":1,"num":12,"sort":12,"title":"Your First Scene Performance"},
 {"level":2,"num":1,"sort":13,"title":"Method Acting Basics"},{"level":2,"num":2,"sort":14,"title":"Advanced Character Development"},{"level":2,"num":3,"sort":15,"title":"Shakespeare & Classical Text"},{"level":2,"num":4,"sort":16,"title":"Contemporary Realism"},{"level":2,"num":5,"sort":17,"title":"Advanced Comedy Techniques"},{"level":2,"num":6,"sort":18,"title":"Advanced Drama & Emotional Depth"},{"level":2,"num":7,"sort":19,"title":"Advanced Camera Techniques"},{"level":2,"num":8,"sort":20,"title":"Period & Genre Acting"},{"level":2,"num":9,"sort":21,"title":"Cold Reading Skills"},{"level":2,"num":10,"sort":22,"title":"Professional Audition Mastery"},{"level":2,"num":11,"sort":23,"title":"Advanced Ensemble Acting Techniques for Intermediate Students"},{"level":2,"num":12,"sort":24,"title":"Intermediate Showcase: Professional Reel"},
 {"level":3,"num":1,"sort":25,"title":"Meisner Technique Mastery"},{"level":3,"num":2,"sort":26,"title":"Adler Technique & Imagination"},{"level":3,"num":3,"sort":27,"title":"Advanced Physical Acting"},{"level":3,"num":4,"sort":28,"title":"Classical Acting Mastery"},{"level":3,"num":5,"sort":29,"title":"Professional Film & TV Acting"},{"level":3,"num":6,"sort":30,"title":"Devised Theater & Creation"},{"level":3,"num":8,"sort":31,"title":"Professional Voice Acting"},{"level":3,"num":9,"sort":32,"title":"Advanced Scene Study"},{"level":3,"num":10,"sort":33,"title":"Industry & Career Development"},{"level":3,"num":11,"sort":34,"title":"Advanced Performance & Endurance"},{"level":3,"num":12,"sort":35,"title":"Advanced Capstone: Master Performance"},
 {"level":4,"num":1,"sort":36,"title":"Master''s Approach to Character"},{"level":4,"num":2,"sort":37,"title":"Integration of All Methods"},{"level":4,"num":3,"sort":38,"title":"Extreme Performance Challenges"},{"level":4,"num":4,"sort":39,"title":"Cross-Cultural Performance Mastery"},{"level":4,"num":5,"sort":40,"title":"Mastering Ensemble Acting: The Power of Collaborative Performance"},{"level":4,"num":6,"sort":41,"title":"Cross-Cultural and International Acting"},{"level":4,"num":7,"sort":42,"title":"Elite Screen Performance"},{"level":4,"num":8,"sort":43,"title":"Master Teacher & Mentor"},{"level":4,"num":9,"sort":44,"title":"Industry Leadership & Influence"},{"level":4,"num":10,"sort":45,"title":"Utilizing Drama Therapy for Social Change and Community Healing"},{"level":4,"num":12,"sort":46,"title":"Mastering the Art of Acting: Legacy, Leadership, and Inspiration"}
 ]'::jsonb) as x(level int,num int,sort int,title text) order by sort loop
  select id into v_level from public.course_levels where course_id=v_course and level_number=r.level;
  if v_level is null then
   insert into public.course_levels(id,course_id,level_number,title,description,learning_objectives,status,core_xp_target,review_notes)
   values(gen_random_uuid(),v_course,r.level,v_levels[r.level],'Draft Acting level; source-aligned review only.','Develop source-aligned Acting performance skills.','draft',case when r.level=1 then 7500 when r.level=2 then 7500 when r.level=3 then 6875 else 6875 end,v_marker||'; batch-created level; metadata target reconciliation deferred.') returning id into v_level;
  elsif not exists(select 1 from public.course_levels where id=v_level and title=v_levels[r.level] and status='draft' and approved_by is null and approved_at is null) then raise exception 'Incompatible Acting level %',r.level; end if;

  select id into v_module from public.course_modules where course_id=v_course and (sort_order=r.sort or (course_level_id=v_level and level_module_number=r.num));
  if v_module is null then
   insert into public.course_modules(id,course_id,course_level_id,level_module_number,title,description,short_intro,sort_order,xp_value,core_xp,intro_core_xp,video_core_xp,assignment_core_xp,mastery_core_xp,core_unlock_threshold,bonus_xp_available,jpac_tool_activity,real_world_activity,career_connection,portfolio_moment,status,video_brief,aria_coaching_targets,career_mission_ideas,review_notes)
   values(gen_random_uuid(),v_course,v_level,r.num,r.title,'Develop and demonstrate source-aligned Acting skills for '||r.title||'.','Draft source-aligned Acting module.',r.sort,625,625,50,100,350,125,438,0,jsonb_build_object('review_status','NEEDS CATALOG REVIEW'),jsonb_build_object('title',r.title||' Guided Practice','instructions','Rehearse the source-aligned objective using a teacher-approved, emotionally safe adaptation.'),'',false,'draft','NEEDS REVIEW: no media is activated.',jsonb_build_object('advisory_only',true,'targets',jsonb_build_array('character objective','listening and response','voice and physical choices','confidence-building feedback','emotional safety'),'prohibited',jsonb_build_array('assess','approve','award XP','grant mastery','unlock')),'[]'::jsonb,v_marker||'; source-aligned module; AI-PROPOSED lesson and assessment criteria require Acting teacher review.') returning id into v_module;
   v_module_created:=true;
  elsif not exists(select 1 from public.course_modules where id=v_module and course_level_id=v_level and level_module_number=r.num and sort_order=r.sort and title=r.title and description='Develop and demonstrate source-aligned Acting skills for '||r.title||'.' and short_intro='Draft source-aligned Acting module.' and status='draft' and xp_value=625 and core_xp=625 and intro_core_xp=50 and video_core_xp=100 and assignment_core_xp=350 and mastery_core_xp=125 and core_unlock_threshold=438 and bonus_xp_available=0 and jpac_tool_activity=jsonb_build_object('review_status','NEEDS CATALOG REVIEW') and real_world_activity=jsonb_build_object('title',r.title||' Guided Practice','instructions','Rehearse the source-aligned objective using a teacher-approved, emotionally safe adaptation.') and career_connection='' and not portfolio_moment and video_brief='NEEDS REVIEW: no media is activated.' and lab_tool_id is null and active_instructional_media_id is null and primary_video_url is null and approved_by is null and approved_at is null) then raise exception 'Incompatible Acting module L% M%',r.level,r.num; end if;

  if v_module_created is distinct from true then
   if (select count(*) from public.lessons where module_id=v_module)<>3
   or (select count(*) from public.lessons where module_id=v_module and status='draft' and xp_value=0)<>3
   or (select count(*) from public.lessons where module_id=v_module and title in(r.title||': Foundations',r.title||': Guided Application',r.title||': Performance and Reflection'))<>3
   or (select count(*) from public.activities where module_id=v_module)<>2
   or (select count(*) from public.activities where module_id=v_module and title=r.title||' Guided Practice' and status='draft' and activity_type='practice' and not required and xp_reward=0 and xp_type='bonus')<>1
   or (select count(*) from public.activities where module_id=v_module and title=r.title||' Core Challenge' and status='draft' and activity_type='performance' and required and xp_reward=350 and xp_type='core' and passing_score=70 and allows_resubmission and rubric=v_rubric)<>1
   then raise exception 'Existing Acting module children are not exact-compatible L% M%',r.level,r.num; end if;
  else
   for i in 1..3 loop
    v_lesson_title:=case i when 1 then r.title||': Foundations' when 2 then r.title||': Guided Application' else r.title||': Performance and Reflection' end;
    insert into public.lessons(id,module_id,title,description,lesson_type,duration_minutes,sort_order,xp_value,status,short_summary,learning_objective,content_blocks,technique_cues,common_mistakes,self_check,resource_brief)
    values(gen_random_uuid(),v_module,v_lesson_title,'Study and apply '||v_lesson_title||'.','interactive',25,i,0,'draft','Source-aligned Acting lesson; draft review only.','Study and apply '||v_lesson_title||'.',jsonb_build_array('Review the source-aligned acting concept.','Rehearse with a teacher-approved adaptation.','Reflect on one effective choice and one next step.'),array['Name the objective and playable action','Listen and respond truthfully','Protect vocal, physical, and emotional safety'],array['Forcing emotion','Ignoring scene partners or boundaries','Skipping reflection'],'Can you demonstrate the objective and explain one acting choice?','AI-PROPOSED accessibility and no-tool alternatives require Acting teacher review.');
   end loop;
   insert into public.activities(id,course_id,module_id,title,description,activity_type,instructions,submission_type,xp_reward,estimated_minutes,required,status,rubric,skill_tags,ai_summary,xp_type,passing_score,allows_resubmission,portfolio_candidate,certificate_eligible) values
   (gen_random_uuid(),v_course,v_module,r.title||' Guided Practice','Optional source-aligned Acting preparation.','practice','Rehearse safely using the JPAC workflow or a teacher-approved accessible alternative. CapCut and Cakewalk are optional examples only.','none',0,20,false,'draft','{}'::jsonb,'{}'::text[],'AI-PROPOSED; optional, non-progressive, non-assessed; teacher review required.','bonus',70,true,false,false),
   (gen_random_uuid(),v_course,v_module,r.title||' Core Challenge','Required source-aligned Acting Core Challenge.','performance','Submit a source-aligned performance and reflection through the existing JPAC submission and teacher-review workflow. Use a teacher-approved accessible alternative when needed.','video',350,30,true,'draft',v_rubric,'{}'::text[],'AI-PROPOSED; teacher review required; Aria advisory only.','core',70,true,false,false);
  end if;
  v_level:=null; v_module:=null; v_module_created:=false;
 end loop;
 if exists(select 1 from public.course_modules where course_id=v_course and course_level_id in(select id from public.course_levels where course_id=v_course and level_number=3) and level_module_number=7) then raise exception 'Held Advanced Module 7 must not exist'; end if;
 if exists(select 1 from public.course_modules where course_id=v_course and course_level_id in(select id from public.course_levels where course_id=v_course and level_number=4) and level_module_number=11) then raise exception 'Fake Master Module 11 must not exist'; end if;
end $$;
commit;
