-- JPAC Video Production 49-module draft rollout. Run only after preflight PASS and explicit approval.
begin;
do $$
declare
 v_course uuid; v_level uuid; v_module uuid; v_lesson_title text; v_rubric jsonb; v_module_created boolean; r record; i int;
 v_marker constant text := 'Video Production full draft rollout 202608140004';
 v_levels constant text[] := array['Beginner','Intermediate','Advanced','Master'];
 v_review text;
begin
 if (select count(*) from public.courses where slug='video-production')<>1 then raise exception 'Expected exactly one canonical video-production course'; end if;
 select id into v_course from public.courses where slug='video-production' for share;
 if exists(select 1 from public.enrollments where course_id=v_course)
 or exists(select 1 from public.submissions s join public.activities a on a.id=s.activity_id where a.course_id=v_course)
 or exists(select 1 from public.lesson_progress p join public.lessons l on l.id=p.lesson_id join public.course_modules m on m.id=l.module_id where m.course_id=v_course)
 or exists(select 1 from public.activity_progress p join public.activities a on a.id=p.activity_id where a.course_id=v_course)
 or exists(select 1 from public.practice_logs p join public.activities a on a.id=p.activity_id where a.course_id=v_course)
 or exists(select 1 from public.xp_ledger where course_id=v_course)
 or exists(select 1 from public.certificates where course_id=v_course)
 or exists(select 1 from public.portfolio_projects p join public.activities a on a.id=p.activity_id where a.course_id=v_course)
 or exists(select 1 from public.module_instructional_media mi join public.course_modules m on m.id=mi.module_id where m.course_id=v_course)
 or exists(select 1 from public.lab_tool_courses where course_id=v_course)
 then raise exception 'Video Production student/evidence dependencies block rollout'; end if;
 if (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('jpac_sync_enrollment_progress','jpac_enforce_canonical_enrollment_progress') and (select count(*) from regexp_matches(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m\.status=''published''','g'))=2 and strpos(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m.status<>''archived''')=0)<>2 then raise exception 'Safe Draft Isolation is not active'; end if;
 if (select count(*) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='enrollments' and t.tgname='enrollments_enforce_canonical_progress' and not t.tgisinternal and t.tgenabled<>'D')<>1 then raise exception 'Canonical enrollment progress trigger missing'; end if;

 v_rubric:=jsonb_build_object('criteria',jsonb_build_array(
  jsonb_build_object('name','Story & Concept Development','weight',20,'bands',jsonb_build_object('Exceeds','Story and concept choices consistently exceed the approved standard.','Meets','Story and concept choices meet the approved standard.','Developing','Story and concept choices partially meet the standard.','Not Yet','Story and concept choices do not yet meet the standard.')),
  jsonb_build_object('name','Camera / Visual Technique','weight',20,'bands',jsonb_build_object('Exceeds','Visual technique consistently exceeds the approved standard.','Meets','Visual technique meets the approved standard.','Developing','Visual technique partially meets the standard.','Not Yet','Visual technique does not yet meet the standard.')),
  jsonb_build_object('name','Editing & Pacing','weight',20,'bands',jsonb_build_object('Exceeds','Editing and pacing consistently exceed the approved standard.','Meets','Editing and pacing meet the approved standard.','Developing','Editing and pacing partially meet the standard.','Not Yet','Editing and pacing do not yet meet the standard.')),
  jsonb_build_object('name','Sound / Audio-Visual Integration','weight',20,'bands',jsonb_build_object('Exceeds','Audio-visual integration consistently exceeds the approved standard.','Meets','Audio-visual integration meets the approved standard.','Developing','Audio-visual integration partially meets the standard.','Not Yet','Audio-visual integration does not yet meet the standard.')),
  jsonb_build_object('name','Production Readiness & Professional Presentation','weight',20,'bands',jsonb_build_object('Exceeds','Production readiness consistently exceeds the approved standard.','Meets','Production readiness meets the approved standard.','Developing','Production readiness partially meets the standard.','Not Yet','Production readiness does not yet meet the standard.'))
 ));

 for r in select * from jsonb_to_recordset('[
 {"level":1,"num":1,"sort":1,"title":"CapCut Basics & Your First Edit"},{"level":1,"num":2,"sort":2,"title":"Planning Your First Video"},{"level":1,"num":3,"sort":3,"title":"Light Makes Everything Better"},{"level":1,"num":4,"sort":4,"title":"Recording Audio for Video"},{"level":1,"num":5,"sort":5,"title":"Understanding Frame Rates and Resolution"},{"level":1,"num":6,"sort":6,"title":"Basic Editing: Cuts and Transitions"},{"level":1,"num":7,"sort":7,"title":"Storyboarding Your Ideas"},{"level":1,"num":8,"sort":8,"title":"Basic Interview Techniques"},{"level":1,"num":9,"sort":9,"title":"Shooting Your First Short Video"},{"level":1,"num":10,"sort":10,"title":"Exporting for Social Media"},
 {"level":2,"num":1,"sort":11,"title":"Camera Movement: Sliders, Gimbals"},{"level":2,"num":2,"sort":12,"title":"Advanced Lighting Techniques"},{"level":2,"num":3,"sort":13,"title":"Color Correction and Grading"},{"level":2,"num":4,"sort":14,"title":"Storyboarding and Shot Listing"},{"level":2,"num":5,"sort":15,"title":"Color Grading"},{"level":2,"num":6,"sort":16,"title":"Directing Talent"},{"level":2,"num":7,"sort":17,"title":"Pre-Production and Planning"},{"level":2,"num":8,"sort":18,"title":"Shooting a Music Performance"},{"level":2,"num":9,"sort":19,"title":"Intro to Motion Graphics"},{"level":2,"num":10,"sort":20,"title":"Creating a Short Documentary"},{"level":2,"num":11,"sort":21,"title":"Color Correction & Grading"},{"level":2,"num":12,"sort":22,"title":"Creating Your First Music Video"},
 {"level":3,"num":1,"sort":23,"title":"Advanced Cinematography"},{"level":3,"num":2,"sort":24,"title":"Working with Green Screen"},{"level":3,"num":3,"sort":25,"title":"Color Correction & Grading"},{"level":3,"num":4,"sort":26,"title":"Sound Design for Video"},{"level":3,"num":5,"sort":27,"title":"Directing a Short Film"},{"level":3,"num":6,"sort":28,"title":"Producing and Budgeting"},{"level":3,"num":7,"sort":29,"title":"Drone Cinematography"},{"level":3,"num":8,"sort":30,"title":"Visual Effects Fundamentals (After Effects)"},{"level":3,"num":9,"sort":31,"title":"Budgeting and Scheduling"},{"level":3,"num":10,"sort":32,"title":"Gimbal and Stabilizer Techniques"},{"level":3,"num":11,"sort":33,"title":"Advanced Color Grading"},{"level":3,"num":12,"sort":34,"title":"Advanced Social Media Video Production: Mastering Platform Optimization"},{"level":3,"num":13,"sort":35,"title":"Advanced Camera Control: Manual Mode"},{"level":3,"num":14,"sort":36,"title":"Cinematic Lighting Techniques"},{"level":3,"num":15,"sort":37,"title":"Advanced Editing: J-Cuts, L-Cuts & Match Cuts"},
 {"level":4,"num":1,"sort":38,"title":"Developing a Director''s Vision"},{"level":4,"num":2,"sort":39,"title":"Feature Film Pre-Production"},{"level":4,"num":3,"sort":40,"title":"VFX: Green Screen and Compositing"},{"level":4,"num":4,"sort":41,"title":"Director Study: Spike Jonze"},{"level":4,"num":5,"sort":42,"title":"Film Festival Strategy"},{"level":4,"num":6,"sort":43,"title":"Mentoring Emerging Filmmakers"},{"level":4,"num":7,"sort":44,"title":"The Future of Filmmaking"},{"level":4,"num":8,"sort":45,"title":"Film Financing and Distribution"},{"level":4,"num":9,"sort":46,"title":"Developing a Signature Style"},{"level":4,"num":10,"sort":47,"title":"Capstone: Short Film Production"},{"level":4,"num":20,"sort":48,"title":"Visual Effects (VFX) Basics"},{"level":4,"num":24,"sort":49,"title":"Festival Submission & Digital Distribution"}
 ]'::jsonb) as x(level int,num int,sort int,title text) order by sort loop
  select id into v_level from public.course_levels where course_id=v_course and level_number=r.level;
  if v_level is null then
   insert into public.course_levels(id,course_id,level_number,title,description,learning_objectives,status,core_xp_target,review_notes)
   values(gen_random_uuid(),v_course,r.level,v_levels[r.level],'Draft Video Production level; source-aligned review only.',array['Develop source-aligned video storytelling, production, editing, and presentation skills safely and ethically.'],'draft',(array[6250,7500,9375,7500])[r.level],v_marker||'; batch-created level; metadata target reconciliation deferred.') returning id into v_level;
  elsif not exists(select 1 from public.course_levels where id=v_level and title=v_levels[r.level] and status='draft' and approved_by is null and approved_at is null) then raise exception 'Incompatible Video Production level %',r.level; end if;

  v_review:=v_marker||'; source-aligned module; AI-PROPOSED lesson and assessment details require Video Production teacher review. Media NEEDS REVIEW; Tools NEEDS CATALOG REVIEW; no media or tool records are created.';
  if (r.level=1 and r.num=3) or (r.level=2 and r.num in(2,3,5,11)) or (r.level=3 and r.num in(3,8,11,14)) or (r.level=4 and r.num in(3,5,8,20,24)) then v_review:=v_review||' NEEDS REVIEW: repeated topic retained pending possible future consolidation.'; end if;
  if r.level=3 and r.num=7 then v_review:=v_review||' SAFETY/LEGAL REVIEW: drone use is optional; simulator, supplied-footage, or storyboard alternatives required.'; end if;
  if r.level=4 and r.num=4 then v_review:=v_review||' RIGHTS/CULTURAL REVIEW: director study requires authorized, contextualized source use.'; end if;
  if r.level=4 and r.num in(5,8,24) then v_review:=v_review||' RIGHTS/DISTRIBUTION REVIEW: festival, financing, submission, and distribution guidance requires review.'; end if;
  if (r.level=3 and r.num=6) or (r.level=4 and r.num in(6,10)) then v_review:=v_review||' MEDIA NEEDS REVIEW: source says Overview Video: None while also supplying a URL or descriptor; do not activate.'; end if;

  select id into v_module from public.course_modules where course_id=v_course and (sort_order=r.sort or (course_level_id=v_level and level_module_number=r.num));
  if v_module is null then
   insert into public.course_modules(id,course_id,course_level_id,level_module_number,title,description,short_intro,sort_order,xp_value,core_xp,intro_core_xp,video_core_xp,assignment_core_xp,mastery_core_xp,core_unlock_threshold,bonus_xp_available,jpac_tool_activity,real_world_activity,career_connection,portfolio_moment,status,video_brief,aria_coaching_targets,career_mission_ideas,review_notes)
   values(gen_random_uuid(),v_course,v_level,r.num,r.title,'Develop and demonstrate source-aligned Video Production skills for '||r.title||'.','Draft source-aligned Video Production module.',r.sort,625,625,50,100,350,125,438,0,'{}'::jsonb,jsonb_build_object('title',r.title||' Guided Practice','instructions','Plan, capture, edit, or analyze source-aligned work using teacher-approved accessible equipment-free or supplied-media alternatives.'),'',false,'draft','NEEDS REVIEW: no media is activated.',jsonb_build_object('advisory_only',true,'targets',jsonb_build_array('story development','shot composition','camera movement','lighting','editing and pacing','sound design','color grading','production planning','portfolio and reel reflection','safety, legal, consent, and media rights reminders'),'prohibited',jsonb_build_array('assess','approve','award XP','grant mastery','unlock','publish')),'[]'::jsonb,v_review) returning id into v_module;
   v_module_created:=true;
  elsif not exists(select 1 from public.course_modules where id=v_module and course_level_id=v_level and level_module_number=r.num and sort_order=r.sort and title=r.title and description='Develop and demonstrate source-aligned Video Production skills for '||r.title||'.' and short_intro='Draft source-aligned Video Production module.' and status='draft' and xp_value=625 and core_xp=625 and intro_core_xp=50 and video_core_xp=100 and assignment_core_xp=350 and mastery_core_xp=125 and core_unlock_threshold=438 and bonus_xp_available=0 and jpac_tool_activity='{}'::jsonb and real_world_activity=jsonb_build_object('title',r.title||' Guided Practice','instructions','Plan, capture, edit, or analyze source-aligned work using teacher-approved accessible equipment-free or supplied-media alternatives.') and career_connection='' and not portfolio_moment and video_brief='NEEDS REVIEW: no media is activated.' and lab_tool_id is null and active_instructional_media_id is null and primary_video_url is null and approved_by is null and approved_at is null) then raise exception 'Incompatible Video Production module L% M%',r.level,r.num; end if;

  if v_module_created is distinct from true then
   if (select count(*) from public.lessons where module_id=v_module)<>3
   or (select count(*) from public.lessons where module_id=v_module and status='draft' and xp_value=0 and title in(r.title||': Story and Production Foundations',r.title||': Guided Technical Application',r.title||': Edit, Present, and Reflect'))<>3
   or (select count(*) from public.activities where module_id=v_module)<>2
   or (select count(*) from public.activities where module_id=v_module and title=r.title||' Guided Practice' and status='draft' and activity_type='practice' and not required and xp_reward=0 and xp_type='bonus')<>1
   or (select count(*) from public.activities where module_id=v_module and title=r.title||' Core Challenge' and status='draft' and activity_type='performance' and required and xp_reward=350 and xp_type='core' and passing_score=70 and allows_resubmission and rubric=v_rubric)<>1
   then raise exception 'Existing Video Production module children are not exact-compatible L% M%',r.level,r.num; end if;
  else
   for i in 1..3 loop
    v_lesson_title:=case i when 1 then r.title||': Story and Production Foundations' when 2 then r.title||': Guided Technical Application' else r.title||': Edit, Present, and Reflect' end;
    insert into public.lessons(id,module_id,title,description,lesson_type,duration_minutes,sort_order,xp_value,status,short_summary,learning_objective,content_blocks,technique_cues,common_mistakes,self_check,resource_brief)
    values(gen_random_uuid(),v_module,v_lesson_title,'Study and apply '||v_lesson_title||'.','interactive',25,i,0,'draft','Source-aligned Video Production lesson; draft review only.','Study and apply '||v_lesson_title||'.',jsonb_build_array('Plan the story, shot, edit, sound, or production purpose.','Apply the source-aligned technique with teacher-approved tools or accessible alternatives.','Review pacing, clarity, rights, safety, accessibility, and one next step.'),array['Prioritize story purpose and safe production','Use authorized media and obtain consent','Use supplied footage, storyboard, simulation, or analysis when equipment is unavailable'],array['Treating optional software as mandatory','Using unlicensed media or unsafe production methods','Publishing or distributing work without approval'],'Can you demonstrate the objective and explain one production choice?','AI-PROPOSED accessibility/no-tool alternatives require Video Production teacher review.');
   end loop;
   insert into public.activities(id,course_id,module_id,title,description,activity_type,instructions,submission_type,xp_reward,estimated_minutes,required,status,rubric,skill_tags,ai_summary,xp_type,passing_score,allows_resubmission,portfolio_candidate,certificate_eligible) values
   (gen_random_uuid(),v_course,v_module,r.title||' Guided Practice','Optional source-aligned Video Production preparation.','practice','Plan, rehearse, capture, edit, or analyze a short exercise using teacher-approved accessible or supplied-media alternatives. Named software and equipment are optional examples only.','none',0,20,false,'draft','{}'::jsonb,'{}'::text[],'AI-PROPOSED; optional, non-progressive, non-assessed; teacher review required.','bonus',70,true,false,false),
   (gen_random_uuid(),v_course,v_module,r.title||' Core Challenge','Required source-aligned Video Production Core Challenge.','performance','Submit source-aligned video, storyboard, edit, production plan, or equivalent accessible evidence through the existing JPAC submission and teacher-review workflow. Use only authorized media and obtain required consent. Do not publish or distribute externally.','video',350,30,true,'draft',v_rubric,'{}'::text[],'AI-PROPOSED; teacher review required; Aria advisory only.','core',70,true,false,false);
  end if;
  v_level:=null; v_module:=null; v_module_created:=false;
 end loop;
 if exists(select 1 from public.course_modules m join public.course_levels l on l.id=m.course_level_id where m.course_id=v_course and l.level_number=4 and m.level_module_number in(11,12,13,14,15,16,17,18,19,21,22,23)) then raise exception 'Fabricated Master module number detected'; end if;
end $$;
commit;
