-- PREPARED ONLY: do not apply without separate owner approval.
-- Completes draft Singing Levels 2-4 curriculum while preserving module IDs,
-- video projections, instructional media, XP, access, progress, and awards.
begin;

create temporary table singing_l24_baseline on commit drop as
select
  (select md5(coalesce(string_agg(concat_ws('|',m.id::text,coalesce(m.primary_video_url,''),coalesce(m.video_title,''),coalesce(m.video_provider,''),coalesce(m.video_duration_seconds::text,''),coalesce(m.active_instructional_media_id::text,''),(select count(*) from public.module_instructional_media x where x.module_id=m.id)::text),E'\n' order by m.id),'')) from public.course_modules m join public.courses c on c.id=m.course_id where c.slug='singing' and (m.primary_video_url is not null or m.video_title is not null or m.video_provider is not null or m.video_duration_seconds is not null or m.active_instructional_media_id is not null or exists(select 1 from public.module_instructional_media x where x.module_id=m.id))) video_hash,
  (select md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id::text),'')) from public.module_instructional_media x join public.course_modules m on m.id=x.module_id join public.courses c on c.id=m.course_id where c.slug='singing') media_hash,
  (select md5(coalesce(string_agg(concat_ws('|',m.id::text,m.core_xp::text,m.intro_core_xp::text,m.video_core_xp::text,m.assignment_core_xp::text,m.mastery_core_xp::text,m.core_unlock_threshold::text,m.jpac_tool_bonus_xp::text,m.real_world_bonus_xp::text,m.bonus_xp_available::text),E'\n' order by m.id),'')) from public.course_modules m join public.courses c on c.id=m.course_id where c.slug='singing') xp_hash,
  (select count(*) from public.enrollments) enrollment_rows,
  (select count(*) from public.lesson_progress) lesson_progress_rows,
  (select count(*) from public.activity_progress) activity_progress_rows,
  (select count(*) from public.xp_ledger) xp_rows,
  (select count(*) from public.student_xp_ledger) student_xp_rows,
  (select count(*) from public.student_skill_mastery) mastery_rows,
  (select count(*) from public.submissions) submission_rows,
  (select count(*) from public.certificates) certificate_rows;

do $$ begin
  if (select count(*) from public.course_modules m join public.courses c on c.id=m.course_id join public.course_levels cl on cl.id=m.course_level_id where c.slug='singing' and cl.level_number between 2 and 4) <> 30 then raise exception 'Expected 30 canonical Singing Level 2-4 modules'; end if;
  if exists(select 1 from public.course_modules m join public.courses c on c.id=m.course_id join public.course_levels cl on cl.id=m.course_level_id where c.slug='singing' and cl.level_number between 2 and 4 and (m.status<>'draft' or m.core_xp<>625 or m.core_unlock_threshold<>438)) then raise exception 'Singing target draft/XP baseline changed'; end if;
  if (select video_hash from singing_l24_baseline)<>'e6e45328064ad2b26c8d7df6de4383ec' then raise exception 'Singing video/media-count baseline changed'; end if;
end $$;

create temporary table singing_l24_content(
  level_number int, module_number int, title text, overview text, objective text,
  career text, lesson_titles text[], lesson_summaries text[], assignment_title text,
  assignment text, submission text, rubric_names text[], teacher_review text,
  primary key(level_number,module_number)
) on commit drop;

insert into singing_l24_content values
(2,1,'Strengthening Vocal Warm-Ups','Students expand their warm-up routine beyond basic breathing and humming. They learn how warm-ups prepare the voice for stronger singing, clearer tone, and safer vocal practice.','Students will demonstrate an intermediate vocal warm-up routine using breath support, pitch movement, and clear tone.','Professional singers, actors, recording artists, and performers use structured warm-ups before rehearsals, recording sessions, auditions, and live performances.',array['Why Intermediate Singers Warm Up Differently','Vocal Slides, Sirens, and Scale Patterns','Building a Personal Warm-Up Routine'],array['Learn that warm-ups are preparation for vocal strength and control.','Practice moving smoothly through higher and lower notes without pushing or straining.','Select warm-ups that help the voice feel ready, relaxed, and focused.'],'Strengthening Vocal Warm-Ups Assignment','Record a 90-second warm-up routine that includes breathing, humming or lip trills, vocal slides, and one short scale pattern.','Submit one .mp4 or .mp3 recording and introduce the routine before performing it.',array['Breath Preparation','Vocal Safety','Pitch Movement','Routine Structure','Confidence'],'Confirm safe warm-up, breath support, and readiness for intermediate vocal work.'),
(2,2,'Pitch Accuracy and Ear Training','Students improve their ability to hear, match, and adjust pitch, including recognizing notes that are high, low, or centered.','Students will match simple pitch patterns and make vocal adjustments based on what they hear.','Pitch accuracy is essential for solo singers, choir members, studio artists, background vocalists, and musical theater performers.',array['Listening Before Singing','Matching Pitch With Confidence','Correcting Pitch Without Fear'],array['Listen carefully before repeating a note or melody.','Practice matching single notes and short patterns.','Treat adjusting pitch as part of vocal growth.'],'Pitch Accuracy and Ear Training Assignment','Record five short pitch patterns; after each pattern, pause and repeat it with your voice.','Submit a .mp4 or .mp3 recording using a piano, keyboard app, teacher track, or vocal guide.',array['Listening Skills','Pitch Matching','Adjustment','Focus','Growth Mindset'],'Evaluate pitch awareness and the ability to hear and adjust notes.'),
(2,3,'Breath Support for Longer Phrases','Students learn to manage breath during longer vocal lines without running out of air or losing tone.','Students will sing longer phrases using controlled breath support and planned breathing points.','Breath support helps singers perform full songs, auditions, choir selections, studio vocals, and live performances consistently.',array['Planning Where to Breathe','Holding Tone Through a Phrase','Avoiding Breath Panic'],array['Mark natural breathing places in a song.','Keep the voice steady from the beginning to the end of a phrase.','Stay calm and controlled when singing longer lines.'],'Breath Support for Longer Phrases Assignment','Record a short song section with at least two long phrases using planned breathing points.','Submit a .mp4 recording and briefly explain the planned breathing points before singing.',array['Breath Planning','Breath Control','Tone Stability','Posture','Application'],'Confirm intentional breath management instead of random breaths or rushed phrases.'),
(2,4,'Head Voice and Chest Voice','Students learn the difference between chest voice and head voice and practice moving between registers with awareness and control.','Students will identify and demonstrate chest voice and head voice in simple vocal examples.','Register control supports flexible, confident performance in pop, R&B, gospel, musical theater, and classical-inspired music.',array['Understanding Chest Voice','Understanding Head Voice','Moving Between Registers'],array['Explore the stronger, lower, speech-like quality of chest voice.','Explore the lighter, higher, lifted quality of head voice.','Practice low-to-high patterns without forcing the voice.'],'Head Voice and Chest Voice Assignment','Record a short demonstration of chest voice, head voice, and one melody that uses both.','Submit a .mp4 recording and label each part of the demonstration.',array['Chest Voice Awareness','Head Voice Awareness','Transition','Vocal Safety','Explanation'],'Evaluate register awareness, safe practice, and developing control.'),
(2,5,'Tone, Diction, and Vocal Clarity','Students improve vocal sound and clarity by focusing on vowels, consonants, and shaping words for listeners.','Students will sing a short section with clear diction, shaped vowels, and consistent tone.','Clear diction and tone help singers communicate lyrics and perform professionally on stage or in the studio.',array['What Makes a Tone Sound Clear','Singing Words Clearly','Matching Tone to the Song'],array['Learn how breath, posture, and mouth shape affect tone.','Practice consonants and vowel shapes without over-pronouncing.','Explore tone choices that fit a song’s style and emotion.'],'Tone, Diction, and Vocal Clarity Assignment','Record 45-60 seconds of a song section focused on clear words, strong vowels, and consistent tone.','Submit a .mp4 recording while facing the camera.',array['Diction','Vowel Shape','Tone Quality','Expression','Presentation'],'Confirm improving clarity and effective shaping of words for the listener.'),
(2,6,'Rhythm and Timing for Singers','Students learn how rhythm affects vocal performance and practice singing in time with a beat, track, or count.','Students will perform a vocal section with steady timing and awareness of rhythm.','Timing is important for studio recording, live bands, choir, dance-based performance, and music production.',array['Feeling the Beat','Singing on Time','Using Rhythm for Style'],array['Count, clap, and move with a steady beat.','Practice intentional phrase entrances and endings.','Use timing to create groove, emotion, and personality.'],'Rhythm and Timing for Singers Assignment','Record 30-60 seconds of singing with a backing track, metronome, or steady beat.','Submit a .mp4 or .mp3 recording with the beat or track audible for review.',array['Beat Awareness','Phrase Timing','Rhythm Accuracy','Musical Feel','Confidence'],'Evaluate timing awareness and ability to sing with accompaniment.'),
(2,7,'Singing With Emotion','Students connect emotionally with lyrics through facial expression, tone, dynamics, and phrasing.','Students will perform a short song section using emotion, vocal expression, and intentional phrasing.','Emotional delivery helps artists connect with audiences and communicate a song’s meaning.',array['Understanding the Story of the Song','Using Dynamics and Phrasing','Performing With Honest Expression'],array['Identify the speaker, feeling, and message.','Use softness, strength, pace, and connection to express emotion.','Practice expression that feels honest rather than forced.'],'Singing With Emotion Assignment','Choose and record a song section with clear expression and storytelling.','Submit a .mp4 recording and briefly state the song’s emotion before performing.',array['Lyric Understanding','Emotional Tone','Facial Expression','Dynamics','Storytelling'],'Confirm connection to lyrics and purposeful emotional vocal choices.'),
(2,8,'Singing With Style','Students explore how genres affect vocal delivery while keeping healthy technique.','Students will perform a song section with style choices appropriate to the genre.','Artists use style to shape identity across pop, R&B, gospel, country, musical theater, and other genres.',array['What Is Vocal Style?','Adding Personality Without Overdoing It','Matching Style to Genre'],array['Study tone, rhythm, phrasing, runs, attitude, and musical choices.','Practice simple choices that support the song.','Compare genre-specific approaches to the same lyric.'],'Singing With Style Assignment','Record 45-60 seconds of a song section with at least two intentional style choices.','Submit a .mp4 recording and name the style or genre before performing.',array['Genre Awareness','Vocal Choices','Control','Musicality','Confidence'],'Evaluate controlled, age-appropriate, musically effective style choices.'),
(2,9,'Preparing a Full Song Section','Students combine breath, pitch, timing, tone, emotion, and style in a longer performance section.','Students will prepare and perform a longer song section using multiple intermediate vocal skills.','Singers prepare full songs for auditions, showcases, recording sessions, competitions, and performances.',array['Choosing the Right Song Section','Rehearsing With a Plan','Self-Reviewing a Performance'],array['Choose material suited to voice and skill level.','Plan practice for pitch, breath, words, timing, and expression.','Review a recording to identify progress and next work.'],'Preparing a Full Song Section Assignment','Record 60-90 seconds demonstrating pitch, breath support, timing, diction, and emotional expression.','Submit a .mp4 recording and introduce the section and one skill focus.',array['Preparation','Pitch and Timing','Breath and Tone','Expression','Self-Awareness'],'Confirm the student combines multiple skills in a longer performance.'),
(2,10,'Level 2 Vocal Growth Showcase','Students complete Level 2 with a showcase demonstrating intermediate vocal growth before advanced study.','Students will perform a complete vocal showcase selection using intermediate technique, expression, and stage confidence.','Showcases prepare students for auditions, recitals, competitions, studio demos, and live performance opportunities.',array['Selecting Your Showcase Song','Final Rehearsal and Performance Choices','Showcase Reflection'],array['Choose age-appropriate material suited to the voice.','Refine breathing, pitch, tone, diction, timing, emotion, and style.','Reflect on growth and set Level 3 goals.'],'Level 2 Vocal Growth Showcase Final Assignment','Perform a 90-second to 2-minute vocal showcase piece.','Submit a performance-ready .mp4 video.',array['Vocal Technique','Expression','Stage Presence','Preparation','Growth Reflection'],'Determine readiness for advanced vocal study based on growth, consistency, confidence, and application of feedback.'),
(3,1,'Advanced Vocal Warm-Ups','Students warm up with purpose for range, stamina, breath, tone, flexibility, and vocal health.','Students will perform an advanced routine that prepares the voice for longer and more demanding work.','Professional vocalists warm up before studio sessions, auditions, concerts, rehearsals, and stage performances.',array['Warming Up With Intention','Range, Flexibility, and Control','Building Vocal Stamina'],array['Choose warm-ups for the singing task ahead.','Move safely through low, middle, and higher range.','Prepare without over-singing or tiring early.'],'Advanced Vocal Warm-Ups Assignment','Record 90 seconds including breath work, range movement, and one flexibility exercise.','Submit one .mp4 or .mp3 recording and explain the warm-up purpose.',array['Warm-Up Structure','Range Control','Breath Support','Vocal Safety','Preparation'],'Confirm independent, safe preparation for advanced performance.'),
(3,2,'Head Voice, Chest Voice, and Mix Control','Students strengthen chest, head, and mixed voice with smoother transitions and healthy high-note preparation.','Students will demonstrate awareness and control of chest, head, and mixed voice in a short example.','Register control supports pop, R&B, gospel, musical theater, country, choir, and studio performance.',array['Reviewing Chest and Head Voice','Introducing Mixed Voice','Smooth Register Transitions'],array['Review the sound and feeling of vocal registers.','Learn how mix connects power and ease.','Practice register-crossing patterns without strain.'],'Head Voice, Chest Voice, and Mix Control Assignment','Record chest voice, head voice, and an attempt at mixed voice or a smooth transition.','Submit a .mp4 recording and label each section.',array['Register Awareness','Vocal Control','Transition','Safety','Explanation'],'Evaluate healthier control across vocal registers.'),
(3,3,'Singing With Style: Pop, R&B, Gospel, and Musical Theater','Students explore genre-specific choices in tone, rhythm, phrasing, runs, dynamics, and expression.','Students will perform a short section using style choices matching the selected genre.','Genre fluency supports auditions, recordings, live shows, and professional opportunities.',array['What Makes a Style Recognizable','Adding Style With Control','Making the Song Your Own'],array['Identify choices that distinguish genres.','Add style without losing pitch, timing, or vocal health.','Add personality while respecting the song.'],'Genre Style Performance Assignment','Perform 45-60 seconds in a selected style such as pop, R&B, gospel, musical theater, or country.','Submit a .mp4 performance and name the genre and one style choice.',array['Genre Awareness','Style Choices','Musical Control','Expression','Confidence'],'Confirm controlled, age-appropriate, genre-connected choices.'),
(3,4,'Emotional Storytelling','Students deepen performance by studying lyrics, character, mood, and message.','Students will communicate emotion through voice, expression, phrasing, and presence.','Storytelling helps singers stand out in auditions, showcases, theater, recording, and live performance.',array['Finding the Story in the Lyrics','Connecting Emotion to Vocal Choices','Honest Performance vs. Overacting'],array['Identify what the song says and to whom.','Connect tone, volume, phrasing, and pauses to feeling.','Stay natural and believable.'],'Emotional Storytelling Assignment','Perform a meaningful song section with clear emotional storytelling.','Submit a .mp4 recording and explain the emotion or story before performing.',array['Lyric Understanding','Emotional Connection','Phrasing','Presence','Authenticity'],'Evaluate clear storytelling through vocal and performance choices.'),
(3,5,'Breath Control and Long Notes','Students sustain notes and long phrases with support, consistent tone, clean release, and low tension.','Students will sustain long notes and phrases using controlled breath and steady tone.','Breath control supports ballads, gospel, musical theater, choir, studio work, and live performance.',array['Supporting Long Notes','Keeping Tone Steady','Releasing Notes Cleanly'],array['Use posture and support to sustain sound.','Maintain tone quality through long notes.','End notes intentionally without dropping or forcing.'],'Breath Control and Long Notes Assignment','Record three sustained notes and one longer song phrase with controlled breath support.','Submit a .mp4 or .mp3 recording and stop if strain occurs.',array['Breath Support','Tone Stability','Clean Release','Vocal Safety','Application'],'Confirm safe improvement in sustained sound and phrase control.'),
(3,6,'Singing With Backing Tracks','Students perform with accompaniment while managing timing, entrances, dynamics, listening, and connection.','Students will perform with a backing track while maintaining timing, pitch, and expression.','Track performance is common in showcases, auditions, demos, social content, and live events.',array['Listening to the Track','Staying With the Music','Performing, Not Just Singing Along'],array['Identify form and entry points.','Maintain time with accompaniment.','Use the track as support while delivering a performance.'],'Singing With Backing Tracks Assignment','Perform 60 seconds of a song with a backing track.','Submit a .mp4 recording with both track and voice clear.',array['Track Awareness','Timing','Vocal Balance','Performance Energy','Completion'],'Evaluate accompaniment control and stage focus.'),
(3,7,'Stage Presence and Performance Confidence','Students develop posture, focus, movement, facial expression, and audience connection.','Students will perform using confident stage presence and intentional presentation.','Stage presence matters for live artists, theater performers, worship leaders, and entertainers.',array['What Makes a Performer Look Confident','Movement With Purpose','Connecting With the Audience'],array['Use posture, eye line, and focus.','Use simple movement that supports the song.','Connect through expression and energy.'],'Stage Presence and Performance Confidence Assignment','Perform 60 seconds with intentional stage presence.','Submit a clearly framed .mp4 performance, standing if possible.',array['Posture','Focus','Movement','Expression','Audience Connection'],'Confirm developing confidence, performance awareness, and connection.'),
(3,8,'Recording Your Voice','Students learn quiet-space setup, microphone distance, clean takes, playback review, and consistency.','Students will create a clear vocal recording and identify one improvement after listening back.','Recording skills support demos, auditions, social performances, studio sessions, and songwriting ideas.',array['Setting Up to Record','Recording a Clean Take','Listening Back Like an Artist'],array['Choose a quiet space and useful microphone position.','Capture clear sound at a consistent distance.','Review tone, pitch, diction, timing, and emotion.'],'Recording Your Voice Assignment','Record 45-60 seconds and state or write one improvement identified after playback.','Submit a supported .mp3, .mp4, or audio/video file with a clear voice.',array['Recording Clarity','Setup','Vocal Performance','Self-Review','Professional Habit'],'Evaluate the performance and constructive playback review.'),
(3,9,'Song Interpretation','Students make intentional choices about meaning, tone, phrasing, dynamics, and performance style.','Students will explain and perform a section using intentional interpretation choices.','Interpretation helps singers become artists and supports auditions, recording, theater, and live work.',array['Understanding the Message','Choosing Vocal Moments','Making a Performance Choice'],array['Identify the main idea and intended audience feeling.','Choose moments for softness, strength, pause, or emphasis.','Explain why the song was performed in a chosen way.'],'Song Interpretation Assignment','Perform 60 seconds and explain two interpretation choices.','Submit a .mp4 recording with the explanation before or after.',array['Song Understanding','Vocal Choices','Explanation','Expression','Growth'],'Confirm artistic thinking and intentional decisions.'),
(3,10,'Level 3 Vocal Performance Showcase','Students complete Level 3 with an advanced performance showing technique, expression, style, and stage readiness.','Students will perform a polished showcase selection using advanced technique and artistry.','Advanced showcases prepare students for auditions, recitals, talent shows, competitions, recording, and artist development.',array['Selecting an Advanced Showcase Piece','Polishing the Performance','Final Performance Reflection'],array['Choose a song that demonstrates growth.','Refine technique, expression, style, and presence.','Reflect and set master-level goals.'],'Level 3 Vocal Performance Showcase Final Assignment','Perform a 2-minute vocal showcase piece.','Submit a polished .mp4 performance for an audience.',array['Vocal Technique','Artistry','Stage Presence','Preparation','Reflection'],'Determine readiness for master-level study through consistency, artistry, confidence, and intention.'),
(4,1,'Master-Level Vocal Warm-Up and Routine','Students create a personalized routine for rehearsals, performances, auditions, and recording sessions.','Students will design and perform a personalized routine supporting health, range, tone, and readiness.','Professional singers prepare their voices independently before auditions, sessions, rehearsals, and shows.',array['Knowing What Your Voice Needs','Creating a Personal Vocal Routine','Preparing Like a Professional'],array['Identify exercises for breath, tone, range, and relaxation.','Build a sequence for personal needs and goals.','Adapt preparation for auditions, sessions, and showcases.'],'Master-Level Vocal Warm-Up and Routine Assignment','Record a 2-minute personalized routine and explain each exercise choice.','Submit one .mp4 or .mp3 recording with the explanation.',array['Personalization','Structure','Vocal Safety','Professional Habit','Explanation'],'Confirm independent and safe professional-level preparation.'),
(4,2,'Advanced Vocal Control and Consistency','Students maintain pitch, tone, breath, diction, and rhythm across repeat performances.','Students will perform a section with consistent technique from beginning to end.','Consistency is required for auditions, studio recording, live performance, choir leadership, and artist development.',array['What Vocal Consistency Means','Repeating a Strong Performance','Staying Focused Under Pressure'],array['Coordinate pitch, breath, tone, timing, and energy.','Repeat a section while maintaining quality.','Use strategies for calm, steady performance.'],'Advanced Vocal Control and Consistency Assignment','Record two takes of the same 60-second section and compare consistency.','Submit one combined or two separate .mp4/.mp3 files and identify one consistency and one improvement.',array['Pitch Consistency','Tone Consistency','Breath Control','Self-Review','Professional Focus'],'Evaluate repeatable, dependable vocal control.'),
(4,3,'Vocal Runs, Riffs, and Musical Choices','Students use runs and riffs with control, clarity, and musical purpose.','Students will demonstrate a simple run or stylistic embellishment with control and intention.','Runs and riffs are used in R&B, gospel, pop, soul, musical theater, and contemporary styles.',array['What Makes a Run Musical','Practicing Runs Slowly','Choosing When to Add a Vocal Moment'],array['Keep runs clear and connected to the song.','Break runs into patterns before adding speed.','Avoid over-singing and choose intentional moments.'],'Vocal Runs, Riffs, and Musical Choices Assignment','Record a short phrase with one run, riff, or embellishment and explain its placement.','Submit a controlled, age-appropriate .mp4 or .mp3 recording.',array['Clarity','Control','Musical Purpose','Placement','Explanation'],'Confirm controlled, clear, purposeful embellishment.'),
(4,4,'Audition Preparation','Students prepare song choice, introduction, confidence, and professional presentation for auditions.','Students will perform an audition-style selection with confidence and professionalism.','Audition skills support productions, talent shows, choirs, competitions, agencies, theater roles, and programs.',array['Choosing an Audition Song','Introducing Yourself Professionally','Performing Under Audition Conditions'],array['Select material suited to voice, age, range, and purpose.','State name, song, and purpose confidently.','Continue without stopping when imperfect.'],'Audition Preparation Assignment','Record an introduction and a 60-90 second audition selection.','Submit one clearly framed .mp4 audition video with good posture.',array['Song Choice','Introduction','Vocal Performance','Confidence','Professional Presentation'],'Evaluate preparation, confidence, song choice, vocal control, and presentation.'),
(4,5,'Studio Vocal Preparation','Students prepare clean takes through warm-up, microphone awareness, consistency, emotion, and critical playback.','Students will record a studio-style take and identify specific improvements after review.','Studio preparation supports recording artists, session singers, songwriters, producers, and creators.',array['Preparing Before Recording','Microphone Awareness','Reviewing a Take Like an Artist'],array['Warm up and review lyrics, timing, and emotion.','Manage distance, volume, and unwanted noise.','Listen for tone, timing, pitch, diction, and emotion.'],'Studio Vocal Preparation Assignment','Record a 60-second studio-style vocal take and provide a short self-review.','Submit a clear .mp3 or .mp4 recording.',array['Recording Clarity','Preparation','Microphone Awareness','Vocal Delivery','Self-Review'],'Confirm habits supporting recording readiness and useful self-review.'),
(4,6,'Background Vocals and Harmony Awareness','Students explore lead and background roles, blending, support, and simple harmony parts.','Students will demonstrate awareness of lead vocals, background vocals, and simple harmony support.','Background and harmony skills support studio work, live performance, choir, worship teams, theater, and artist development.',array['Lead Vocal vs. Background Vocal','Blending and Supporting the Lead','Introduction to Harmony Parts'],array['Distinguish melody leadership from support.','Use a softer tone that does not overpower the lead.','Explore simple upper or lower harmony ideas.'],'Background Vocals and Harmony Awareness Assignment','Record a lead phrase and a simple background vocal or harmony response.','Submit a .mp4 or .mp3; the optional JPAC Harmony Generator may be used.',array['Role Awareness','Blend','Harmony Attempt','Listening','Musical Support'],'Evaluate understanding of supportive background and harmony roles.'),
(4,7,'Building Artist Identity','Students reflect on sound, style, message, confidence, image, and repertoire choices.','Students will identify key elements of artist identity and apply them to a performance choice.','Artist identity guides songs, confidence, messaging, and audience connection.',array['What Makes You Unique as a Singer','Choosing Songs That Fit Your Identity','Performing With Your Own Voice'],array['Reflect on voice, personality, story, and interests.','Connect song choices to identity.','Personalize a song without copying another artist.'],'Building Artist Identity Assignment','Create an artist identity reflection and perform a short section representing your style or message.','Submit a .mp4 with spoken reflection or an allowed written reflection.',array['Self-Awareness','Song Choice','Originality','Confidence','Reflection'],'Confirm healthy, age-appropriate artistic identity and personal voice.'),
(4,8,'Professional Performance Preparation','Students plan rehearsal, wardrobe, staging, introduction, emotional delivery, and final presentation.','Students will prepare a plan supporting a polished, confident vocal presentation.','Professionals plan rehearsals, staging, wardrobe, introductions, and performance details.',array['Planning the Performance','Stage Details and Presentation','Final Rehearsal Checklist'],array['Choose a song, schedule rehearsal, and set goals.','Plan posture, movement, expression, framing, and appearance.','Use a checklist before recording or live performance.'],'Professional Performance Preparation Assignment','Submit a preparation plan and record a 60-90 second rehearsal clip.','Submit one .mp4 rehearsal clip with a written or spoken plan when possible.',array['Planning','Presentation','Preparation','Vocal Focus','Professionalism'],'Evaluate organized, mature preparation of performance details.'),
(4,9,'Final Showcase Rehearsal','Students rehearse the final showcase and refine technique, stage presence, expression, and confidence.','Students will complete a final rehearsal demonstrating readiness for the Level 4 showcase.','Final rehearsals prepare performers for concerts, recitals, competitions, auditions, sessions, and showcases.',array['Running the Full Performance','Refining the Details','Preparing Mentally for the Showcase'],array['Run the complete selection without stopping.','Focus on one technical and one performance goal.','Manage nerves and prepare confidently.'],'Final Showcase Rehearsal Assignment','Record a full rehearsal and identify two final improvement goals.','Submit one .mp4 rehearsal with a short reflection.',array['Full Run-Through','Vocal Readiness','Performance Detail','Reflection','Confidence'],'Confirm final-showcase readiness and clear refinement priorities.'),
(4,10,'Final Vocal Showcase and Portfolio Piece','Students finish the Singing pathway with a portfolio-ready performance showing growth, confidence, and artistry.','Students will perform a polished final showcase demonstrating technique, artistry, confidence, and growth.','A final recording can support auditions, portfolios, scholarships, talent submissions, and artist development.',array['Final Performance Setup','Recording the Final Showcase','Portfolio Reflection'],array['Prepare space, track, outfit, framing, and introduction.','Record a polished performance reflecting growth.','Reflect on learning and future goals.'],'Final Vocal Showcase and Portfolio Piece Final Assignment','Perform a 2-3 minute final showcase and complete a short portfolio reflection.','Submit one .mp4 final performance with an introduction and spoken or written reflection.',array['Vocal Technique','Artistry','Stage Presence','Professional Preparation','Reflection'],'Confirm final pathway growth, confidence, preparation, vocal control, and portfolio readiness.');

with targets as (
  select m.id,c.* from singing_l24_content c join public.courses course on course.slug='singing'
  join public.course_levels cl on cl.course_id=course.id and cl.level_number=c.level_number
  join public.course_modules m on m.course_level_id=cl.id and m.level_module_number=c.module_number
)
update public.course_modules m set
  title=t.title, description=t.overview, short_intro=t.overview,
  learning_objectives=array[t.objective], career_connection=t.career,
  portfolio_moment=(t.level_number=4 and t.module_number=10), updated_at=now()
from targets t where m.id=t.id;

with targets as (
  select m.id module_id,c.* from singing_l24_content c join public.courses course on course.slug='singing'
  join public.course_levels cl on cl.course_id=course.id and cl.level_number=c.level_number
  join public.course_modules m on m.course_level_id=cl.id and m.level_module_number=c.module_number
), lesson_rows as (
  select t.*,u.ordinality::int lesson_number,u.title,u.summary
  from targets t cross join lateral unnest(t.lesson_titles,t.lesson_summaries) with ordinality u(title,summary,ordinality)
)
insert into public.lessons(module_id,title,description,lesson_type,duration_minutes,sort_order,xp_value,status,learning_objectives,short_summary,learning_objective,content_blocks,self_check,instructor_notes)
select r.module_id,r.title,r.summary,'studio',15,r.lesson_number,0,'draft',array[r.objective],r.summary,r.objective,jsonb_build_array(r.summary),r.objective,r.teacher_review
from lesson_rows r where not exists(select 1 from public.lessons l where l.module_id=r.module_id and (l.sort_order=r.lesson_number or lower(trim(l.title))=lower(trim(r.title))));

with targets as (
  select m.id module_id,m.course_id,c.* from singing_l24_content c join public.courses course on course.slug='singing'
  join public.course_levels cl on cl.course_id=course.id and cl.level_number=c.level_number
  join public.course_modules m on m.course_level_id=cl.id and m.level_module_number=c.module_number
)
insert into public.activities(course_id,module_id,title,description,activity_type,instructions,submission_type,xp_reward,required,status,rubric,xp_type,passing_score,allows_resubmission,portfolio_candidate)
select t.course_id,t.module_id,t.assignment_title,t.assignment,'performance',t.submission,
  case when t.submission like '%.mp3%' and t.submission not like '%.mp4%' then 'audio' else 'video' end,
  350,true,'draft',jsonb_build_object('criteria',(select jsonb_agg(jsonb_build_object('name',name,'weight',20) order by ord) from unnest(t.rubric_names) with ordinality x(name,ord)),'teacher_review',t.teacher_review),
  'core',70,true,(t.level_number=4 and t.module_number=10)
from targets t where not exists(select 1 from public.activities a where a.module_id=t.module_id and (a.required or lower(trim(a.title))=lower(trim(t.assignment_title))));

do $$ declare b singing_l24_baseline%rowtype; actual text; begin
  select * into b from singing_l24_baseline;
  if (select count(*) from public.lessons l join public.course_modules m on m.id=l.module_id join public.courses c on c.id=m.course_id join public.course_levels cl on cl.id=m.course_level_id where c.slug='singing' and cl.level_number between 2 and 4)<>90 then raise exception 'Expected 90 Singing Level 2-4 lessons'; end if;
  if (select count(*) from public.activities a join public.course_modules m on m.id=a.module_id join public.courses c on c.id=m.course_id join public.course_levels cl on cl.id=m.course_level_id where c.slug='singing' and cl.level_number between 2 and 4)<>30 then raise exception 'Expected 30 Singing Level 2-4 assignments'; end if;
  if exists(select 1 from public.course_modules m join public.courses c on c.id=m.course_id join public.course_levels cl on cl.id=m.course_level_id where c.slug='singing' and cl.level_number between 2 and 4 and m.status<>'draft') or exists(select 1 from public.lessons l join public.course_modules m on m.id=l.module_id join public.courses c on c.id=m.course_id join public.course_levels cl on cl.id=m.course_level_id where c.slug='singing' and cl.level_number between 2 and 4 and l.status<>'draft') or exists(select 1 from public.activities a join public.course_modules m on m.id=a.module_id join public.courses c on c.id=m.course_id join public.course_levels cl on cl.id=m.course_level_id where c.slug='singing' and cl.level_number between 2 and 4 and a.status<>'draft') then raise exception 'Import must remain draft'; end if;
  select md5(coalesce(string_agg(concat_ws('|',m.id::text,coalesce(m.primary_video_url,''),coalesce(m.video_title,''),coalesce(m.video_provider,''),coalesce(m.video_duration_seconds::text,''),coalesce(m.active_instructional_media_id::text,''),(select count(*) from public.module_instructional_media x where x.module_id=m.id)::text),E'\n' order by m.id),'')) into actual from public.course_modules m join public.courses c on c.id=m.course_id where c.slug='singing' and (m.primary_video_url is not null or m.video_title is not null or m.video_provider is not null or m.video_duration_seconds is not null or m.active_instructional_media_id is not null or exists(select 1 from public.module_instructional_media x where x.module_id=m.id)); if actual<>b.video_hash then raise exception 'Singing video/media-count baseline changed'; end if;
  select md5(coalesce(string_agg(to_jsonb(x)::text,'|' order by x.id::text),'')) into actual from public.module_instructional_media x join public.course_modules m on m.id=x.module_id join public.courses c on c.id=m.course_id where c.slug='singing'; if actual<>b.media_hash then raise exception 'Singing instructional media changed'; end if;
  select md5(coalesce(string_agg(concat_ws('|',m.id::text,m.core_xp::text,m.intro_core_xp::text,m.video_core_xp::text,m.assignment_core_xp::text,m.mastery_core_xp::text,m.core_unlock_threshold::text,m.jpac_tool_bonus_xp::text,m.real_world_bonus_xp::text,m.bonus_xp_available::text),E'\n' order by m.id),'')) into actual from public.course_modules m join public.courses c on c.id=m.course_id where c.slug='singing'; if actual<>b.xp_hash then raise exception 'Singing XP contract changed'; end if;
  if b.enrollment_rows<>(select count(*) from public.enrollments) or b.lesson_progress_rows<>(select count(*) from public.lesson_progress) or b.activity_progress_rows<>(select count(*) from public.activity_progress) or b.xp_rows<>(select count(*) from public.xp_ledger) or b.student_xp_rows<>(select count(*) from public.student_xp_ledger) or b.mastery_rows<>(select count(*) from public.student_skill_mastery) or b.submission_rows<>(select count(*) from public.submissions) or b.certificate_rows<>(select count(*) from public.certificates) then raise exception 'Protected academic/access counts changed'; end if;
end $$;

commit;
