begin;

-- Review-only artifact. Do not execute without separate authorization and an approved preflight.
-- Deterministic IDs identify only rows created by this batch; compatible reused rows keep their IDs.
do $$
declare
  v_course public.courses%rowtype;
  v_level public.course_levels%rowtype;
  v_module public.course_modules%rowtype;
  v_level_id uuid;
  v_module_id uuid;
  v_rubric jsonb := jsonb_build_object('criteria',jsonb_build_array(
    jsonb_build_object('name','Technique and safe hand shape','weight',35,'bands',jsonb_build_object('exceeds','Consistently uses a natural, functional hand shape with flexible wrist and independently releases tension.','meets','Generally uses safe hand shape and wrist freedom with minor inconsistency.','developing','Shows partial technique; recurring tension or finger collapse affects control.','not_yet','Evidence is missing, substantially uncontrolled, or presents an unresolved safety concern.')),
    jsonb_build_object('name','Posture and body alignment','weight',25,'bands',jsonb_build_object('exceeds','Setup is balanced, supported, individualized, and consistently maintained.','meets','Setup is functional and generally balanced with minor alignment issues.','developing','Reaching, crowding, instability, or tension affects playing.','not_yet','Setup cannot be evaluated or does not yet support safe functional playing.')),
    jsonb_build_object('name','Finger control and five-finger pattern accuracy','weight',20,'bands',jsonb_build_object('exceeds','Pattern is accurate, clear, controlled, and reasonably even.','meets','Pattern is recognizable and mostly accurate with minor inconsistency.','developing','Repeated accuracy or control problems interrupt the pattern.','not_yet','Pattern evidence is absent or insufficient to evaluate.')),
    jsonb_build_object('name','Student reflection/self-awareness','weight',10,'bands',jsonb_build_object('exceeds','Specifically identifies a strength, adjustment, and useful next step.','meets','Identifies all required reflection elements with adequate understanding.','developing','Reflection is vague, incomplete, or weakly connected to the evidence.','not_yet','Reflection is absent or does not demonstrate meaningful self-awareness.')),
    jsonb_build_object('name','Preparation and submission completeness','weight',10,'bands',jsonb_build_object('exceeds','Evidence is complete, clear, and easy to review.','meets','Required evidence is present with minor clarity issues.','developing','One required component is incomplete or difficult to evaluate.','not_yet','Multiple components are absent or evidence cannot be reviewed reliably.'))
  ));
begin
  if (select count(*) from public.courses where slug='piano')<>1 then raise exception 'Canonical courses.slug=piano is missing or ambiguous'; end if;
  select * into strict v_course from public.courses where slug='piano' for share;
  if v_course.title is distinct from 'Piano' then raise exception 'Canonical Piano academic identity conflicts'; end if;

  select * into v_level from public.course_levels where course_id=v_course.id and level_number=1;
  if found then
    if v_level.title is distinct from 'Beginner'
      or v_level.description is distinct from 'Beginner Piano foundations. Draft review only.'
      or v_level.learning_objectives is distinct from array['Build healthy setup and foundational keyboard control.']::text[]
      or v_level.status is distinct from 'draft' or v_level.core_xp_target is distinct from 6250
      or v_level.review_notes is distinct from 'Piano Module 1 pilot; AI-PROPOSED content requires leadership and piano-teacher review.'
      or v_level.approved_by is not null or v_level.approved_at is not null then raise exception 'Existing Piano Level 1 is not an exact safe draft'; end if;
    v_level_id:=v_level.id;
  else
    insert into public.course_levels(id,course_id,level_number,title,description,learning_objectives,status,core_xp_target,review_notes)
    values('a2610001-0000-4000-8000-000000000001',v_course.id,1,'Beginner','Beginner Piano foundations. Draft review only.',array['Build healthy setup and foundational keyboard control.'],'draft',6250,'Piano Module 1 pilot; AI-PROPOSED content requires leadership and piano-teacher review.')
    returning id into v_level_id;
  end if;

  select * into v_module from public.course_modules where course_level_id=v_level_id and level_module_number=1;
  if found then
    if v_module.course_id is distinct from v_course.id or v_module.title is distinct from 'Piano Posture and Hand Position'
      or v_module.sort_order is distinct from 1 or v_module.status is distinct from 'draft'
      or v_module.xp_value is distinct from 625 or v_module.core_xp is distinct from 625
      or v_module.intro_core_xp is distinct from 50 or v_module.video_core_xp is distinct from 100
      or v_module.assignment_core_xp is distinct from 350 or v_module.mastery_core_xp is distinct from 125
      or v_module.core_unlock_threshold is distinct from 438 or v_module.bonus_xp_available is distinct from 0
      or v_module.primary_video_url is not null or v_module.video_provider is not null or v_module.video_title is not null
      or v_module.video_duration_seconds is not null or v_module.active_instructional_media_id is not null
      or v_module.lab_tool_id is not null or v_module.jpac_tool_activity is distinct from '{}'::jsonb
      or v_module.description is distinct from 'Establish a balanced or adaptive setup, natural hand shape, relaxed wrists, and controlled five-finger movement.'
      or v_module.short_intro is distinct from 'Build a comfortable Piano setup before speed: align, relax, play slowly, observe, and adjust.'
      or v_module.video_brief is distinct from 'NEEDS REVIEW: Validate source video accuracy, availability, licensing, captions, transcript quality, and alignment before creating media.'
      or v_module.aria_coaching_targets is distinct from jsonb_build_object('advisory_only',true,'targets',jsonb_build_array('posture','bench distance','curved fingers','relaxed wrists','finger independence','wrist tension','finger collapse','hand positioning','slow practice','confidence building'),'prohibited',jsonb_build_array('assess','approve evidence','award XP','grant mastery','unlock content','diagnose injury'))
      or v_module.real_world_activity is distinct from '{}'::jsonb or v_module.career_connection is distinct from ''
      or v_module.career_mission_ideas is distinct from '[]'::jsonb or v_module.portfolio_moment is distinct from false
      or v_module.review_notes is distinct from 'AI-PROPOSED — leadership and piano-teacher review required. Media NEEDS REVIEW; tools NEEDS CATALOG REVIEW.'
      or v_module.approved_by is not null or v_module.approved_at is not null then raise exception 'Existing Piano Module 1 is not exactly compatible'; end if;
    v_module_id:=v_module.id;
  else
    if exists(select 1 from public.course_modules where course_id=v_course.id and (sort_order=1 or title='Piano Posture and Hand Position')) then raise exception 'Conflicting Piano Module 1 identity'; end if;
    if exists(select 1 from public.enrollments where course_id=v_course.id and level=1 and status in('pending','active','paused','completed')) then raise exception 'Affected Piano Level 1 enrollment prevents denominator-changing draft module insert'; end if;
    insert into public.course_modules(id,course_id,course_level_id,level_module_number,title,description,short_intro,sort_order,xp_value,core_xp,intro_core_xp,video_core_xp,assignment_core_xp,mastery_core_xp,core_unlock_threshold,bonus_xp_available,jpac_tool_activity,real_world_activity,career_connection,portfolio_moment,status,video_brief,aria_coaching_targets,career_mission_ideas,review_notes)
    values('a2610001-0000-4000-8000-000000000002',v_course.id,v_level_id,1,'Piano Posture and Hand Position','Establish a balanced or adaptive setup, natural hand shape, relaxed wrists, and controlled five-finger movement.','Build a comfortable Piano setup before speed: align, relax, play slowly, observe, and adjust.',1,625,625,50,100,350,125,438,0,'{}','{}','',false,'draft','NEEDS REVIEW: Validate source video accuracy, availability, licensing, captions, transcript quality, and alignment before creating media.',jsonb_build_object('advisory_only',true,'targets',jsonb_build_array('posture','bench distance','curved fingers','relaxed wrists','finger independence','wrist tension','finger collapse','hand positioning','slow practice','confidence building'),'prohibited',jsonb_build_array('assess','approve evidence','award XP','grant mastery','unlock content','diagnose injury')),'[]','AI-PROPOSED — leadership and piano-teacher review required. Media NEEDS REVIEW; tools NEEDS CATALOG REVIEW.')
    returning id into v_module_id;
  end if;

  -- Any pre-existing child is evidence-bearing for reuse purposes unless the complete approved child set already matches.
  if exists(select 1 from public.lessons where module_id=v_module_id) then
    if (select count(*) from public.lessons where module_id=v_module_id)<>3
      or (select count(*) from public.lessons where module_id=v_module_id and wix_lesson_id is null and wix_lesson_url is null and status='draft' and lesson_type='interactive' and xp_value=0 and (
        (sort_order=1 and duration_minutes=20 and title='Bench and Body Alignment' and description='Set up the bench or adaptive playing position so your body feels supported, flexible, and ready to move.' and short_summary='Build a stable and comfortable playing setup.' and learning_objective='Establish supported seating, appropriate keyboard distance, relaxed shoulders, and functional arm alignment.' and content_blocks=jsonb_build_array('Sit near the front of the bench or use an approved adaptive position.','Support both feet or use an appropriate foot support.','Adjust distance so elbows can move without reaching or crowding.','Keep the spine tall but flexible and release shoulders, neck, and jaw.','Make one intentional setup adjustment and explain why it helped.') and technique_cues=array['Shoulders away from ears','Elbows have room to move','Supported, not stiff','Stop and contact staff if playing causes pain']::text[] and common_mistakes=array['Reaching for the keyboard','Crowding the keyboard','Raised shoulders','Rigid posture']::text[] and self_check='Can you name one setup adjustment that improved comfort or balance?' and resource_brief='AI-PROPOSED. Alternatives: wheelchair or adaptive seating, foot support, photographs with narration, live teacher demonstration, or assistive communication.')
        or (sort_order=2 and duration_minutes=20 and title='Curved Fingers and Relaxed Wrists' and description='Practice a natural hand shape, flexible wrist, and gentle controlled key presses.' and short_summary='Use natural hand shape without unnecessary tension.' and learning_objective='Establish a functional finger curve, flexible wrist, relaxed thumb, and controlled press-and-release motion.' and content_blocks=jsonb_build_array('Observe the hand natural resting shape.','Place five fingers on neighboring white keys without pressing.','Press and release one key at a time.','Pause after each sequence and release the wrist.','Name one sign of tension and one reset strategy.') and technique_cues=array['Natural rather than forced curve','Flexible wrist','Release after each note','Slow down when joints collapse']::text[] and common_mistakes=array['Forced finger curve','Rigid or collapsed wrist','Tucked rigid thumb','Excessive finger lifting']::text[] and self_check='What tension sign did you notice, and how did you reset?' and resource_brief='AI-PROPOSED. Alternatives: approved individual hand position, one hand, fewer notes, adaptive keyboard, live or narrated evidence.')
        or (sort_order=3 and duration_minutes=25 and title='Five-Finger Technique Check' and description='Combine setup and hand technique in a slow five-note pattern with each hand separately.' and short_summary='Apply balanced setup to a controlled five-finger pattern.' and learning_objective='Play an approved five-note pattern with functional posture, hand shape, wrist freedom, note-order accuracy, and self-awareness.' and content_blocks=jsonb_build_array('Place one hand over an approved five-note pattern such as C-D-E-F-G.','Play upward and downward slowly.','Pause and release tension before repeating with the other hand.','Use about 60 BPM only when it supports relaxed control.','Identify one strength and one next improvement.') and technique_cues=array['Control before speed','Clear even notes','Pause and reset','Hands separate first']::text[] and common_mistakes=array['Rushing to match the metronome','Continuing through tension','Finger collapse','Unplanned restart']::text[] and self_check='What improved between your first and second controlled attempt?' and resource_brief='AI-PROPOSED. Alternatives: fewer notes, one hand, adapted controller, audio plus teacher-observed setup, or counted pulse without metronome.')
      ))<>3
      then raise exception 'Existing Module 1 lessons conflict; no overwrite allowed'; end if;
  else
    insert into public.lessons(id,module_id,title,description,lesson_type,duration_minutes,sort_order,xp_value,status,short_summary,learning_objective,content_blocks,technique_cues,common_mistakes,self_check,resource_brief) values
    ('a2610001-0000-4000-8000-000000000011',v_module_id,'Bench and Body Alignment','Set up the bench or adaptive playing position so your body feels supported, flexible, and ready to move.','interactive',20,1,0,'draft','Build a stable and comfortable playing setup.','Establish supported seating, appropriate keyboard distance, relaxed shoulders, and functional arm alignment.',jsonb_build_array('Sit near the front of the bench or use an approved adaptive position.','Support both feet or use an appropriate foot support.','Adjust distance so elbows can move without reaching or crowding.','Keep the spine tall but flexible and release shoulders, neck, and jaw.','Make one intentional setup adjustment and explain why it helped.'),array['Shoulders away from ears','Elbows have room to move','Supported, not stiff','Stop and contact staff if playing causes pain'],array['Reaching for the keyboard','Crowding the keyboard','Raised shoulders','Rigid posture'],'Can you name one setup adjustment that improved comfort or balance?','AI-PROPOSED. Alternatives: wheelchair or adaptive seating, foot support, photographs with narration, live teacher demonstration, or assistive communication.'),
    ('a2610001-0000-4000-8000-000000000012',v_module_id,'Curved Fingers and Relaxed Wrists','Practice a natural hand shape, flexible wrist, and gentle controlled key presses.','interactive',20,2,0,'draft','Use natural hand shape without unnecessary tension.','Establish a functional finger curve, flexible wrist, relaxed thumb, and controlled press-and-release motion.',jsonb_build_array('Observe the hand natural resting shape.','Place five fingers on neighboring white keys without pressing.','Press and release one key at a time.','Pause after each sequence and release the wrist.','Name one sign of tension and one reset strategy.'),array['Natural rather than forced curve','Flexible wrist','Release after each note','Slow down when joints collapse'],array['Forced finger curve','Rigid or collapsed wrist','Tucked rigid thumb','Excessive finger lifting'],'What tension sign did you notice, and how did you reset?','AI-PROPOSED. Alternatives: approved individual hand position, one hand, fewer notes, adaptive keyboard, live or narrated evidence.'),
    ('a2610001-0000-4000-8000-000000000013',v_module_id,'Five-Finger Technique Check','Combine setup and hand technique in a slow five-note pattern with each hand separately.','interactive',25,3,0,'draft','Apply balanced setup to a controlled five-finger pattern.','Play an approved five-note pattern with functional posture, hand shape, wrist freedom, note-order accuracy, and self-awareness.',jsonb_build_array('Place one hand over an approved five-note pattern such as C-D-E-F-G.','Play upward and downward slowly.','Pause and release tension before repeating with the other hand.','Use about 60 BPM only when it supports relaxed control.','Identify one strength and one next improvement.'),array['Control before speed','Clear even notes','Pause and reset','Hands separate first'],array['Rushing to match the metronome','Continuing through tension','Finger collapse','Unplanned restart'],'What improved between your first and second controlled attempt?','AI-PROPOSED. Alternatives: fewer notes, one hand, adapted controller, audio plus teacher-observed setup, or counted pulse without metronome.');
  end if;

  if exists(select 1 from public.activities where module_id=v_module_id) then
    if (select count(*) from public.activities where module_id=v_module_id)<>2
      or not exists(select 1 from public.activities where module_id=v_module_id and course_id=v_course.id and lesson_id is null and title='Guided Piano Setup Practice' and description='Low-pressure preparation before the assessed challenge.' and activity_type='practice' and instructions='Check the bench or adaptive position, body alignment, natural hand shape, and wrist. Play the approved five-finger pattern with each hand separately. Identify one strength, make one adjustment, and repeat. No submission is required.' and submission_type='none' and xp_reward=0 and estimated_minutes=20 and xp_type='bonus' and not required and status='draft' and rubric='{}'::jsonb and skill_tags=array['piano setup','posture','hand position','five-finger pattern']::text[] and ai_summary='AI-PROPOSED; optional, non-progressive, and non-assessed.' and passing_score=70 and allows_resubmission and not portfolio_candidate and not certificate_eligible)
      or not exists(select 1 from public.activities where module_id=v_module_id and course_id=v_course.id and lesson_id is null and title='Balanced Piano Setup Challenge' and description='Demonstrate a balanced or adaptive setup and controlled beginner five-finger technique.' and activity_type='performance' and instructions='Submit JPAC video evidence showing or explaining your playing position and keyboard distance, natural hand shape, flexible wrist, and two upward/downward repetitions of an approved five-finger pattern with each hand separately unless an accommodation is approved. Include one strength, one adjustment, and one next improvement. Allowed alternatives through existing teacher review include live demonstration, multiple short angles, photographs plus audio, audio plus teacher-observed setup, adapted keyboard, or one-hand evidence. Stop and contact staff if playing causes pain.' and submission_type='video' and xp_reward=350 and estimated_minutes=30 and xp_type='core' and required and status='draft' and passing_score=70 and allows_resubmission and rubric=v_rubric and skill_tags=array['piano setup','posture','hand position','wrist freedom','five-finger pattern','self-reflection']::text[] and ai_summary='AI-PROPOSED — teacher review required. ARIA cannot assess, approve, award XP, grant mastery, or unlock content.' and not portfolio_candidate and not certificate_eligible)
      then raise exception 'Existing Module 1 activities conflict; no overwrite allowed'; end if;
  else
    insert into public.activities(id,course_id,module_id,title,description,activity_type,instructions,submission_type,xp_reward,estimated_minutes,required,status,rubric,skill_tags,ai_summary,xp_type,passing_score,allows_resubmission,portfolio_candidate,certificate_eligible) values
    ('a2610001-0000-4000-8000-000000000021',v_course.id,v_module_id,'Guided Piano Setup Practice','Low-pressure preparation before the assessed challenge.','practice','Check the bench or adaptive position, body alignment, natural hand shape, and wrist. Play the approved five-finger pattern with each hand separately. Identify one strength, make one adjustment, and repeat. No submission is required.','none',0,20,false,'draft','{}',array['piano setup','posture','hand position','five-finger pattern'],'AI-PROPOSED; optional, non-progressive, and non-assessed.','bonus',70,true,false,false),
    ('a2610001-0000-4000-8000-000000000022',v_course.id,v_module_id,'Balanced Piano Setup Challenge','Demonstrate a balanced or adaptive setup and controlled beginner five-finger technique.','performance','Submit JPAC video evidence showing or explaining your playing position and keyboard distance, natural hand shape, flexible wrist, and two upward/downward repetitions of an approved five-finger pattern with each hand separately unless an accommodation is approved. Include one strength, one adjustment, and one next improvement. Allowed alternatives through existing teacher review include live demonstration, multiple short angles, photographs plus audio, audio plus teacher-observed setup, adapted keyboard, or one-hand evidence. Stop and contact staff if playing causes pain.','video',350,30,true,'draft',v_rubric,array['piano setup','posture','hand position','wrist freedom','five-finger pattern','self-reflection'],'AI-PROPOSED — teacher review required. ARIA cannot assess, approve, award XP, grant mastery, or unlock content.','core',70,true,false,false);
  end if;

  if exists(select 1 from public.module_instructional_media where module_id=v_module_id) or exists(select 1 from public.course_modules where id=v_module_id and (active_instructional_media_id is not null or lab_tool_id is not null)) then raise exception 'Module media or Lab invariant failed'; end if;
  if coalesce((select sum((x->>'weight')::numeric) from public.activities a cross join lateral jsonb_array_elements(a.rubric->'criteria') x where a.module_id=v_module_id and a.title='Balanced Piano Setup Challenge'),-1)<>100 then raise exception 'Rubric total must equal 100'; end if;
end $$;

commit;
