-- JPAC Dance 47-module draft rollout. Run only after preflight PASS and explicit approval.
begin;
do $$
declare
 v_course uuid; v_level uuid; v_module uuid; v_lesson_title text; v_rubric jsonb; v_module_created boolean; r record; i int;
 v_marker constant text := 'Dance full draft rollout 202608140003';
 v_levels constant text[] := array['Beginner','Intermediate','Advanced','Master'];
begin
 if (select count(*) from public.courses where slug='dance')<>1 then raise exception 'Expected exactly one canonical dance course'; end if;
 select id into v_course from public.courses where slug='dance' for share;
 if exists(select 1 from public.enrollments where course_id=v_course)
 or exists(select 1 from public.submissions s join public.activities a on a.id=s.activity_id where a.course_id=v_course)
 or exists(select 1 from public.lesson_progress p join public.lessons l on l.id=p.lesson_id join public.course_modules m on m.id=l.module_id where m.course_id=v_course)
 or exists(select 1 from public.activity_progress p join public.activities a on a.id=p.activity_id where a.course_id=v_course)
 or exists(select 1 from public.practice_logs p join public.activities a on a.id=p.activity_id where a.course_id=v_course)
 or exists(select 1 from public.xp_ledger where course_id=v_course)
 or exists(select 1 from public.certificates where course_id=v_course)
 or exists(select 1 from public.portfolio_projects p join public.activities a on a.id=p.activity_id where a.course_id=v_course)
 or exists(select 1 from public.module_instructional_media mi join public.course_modules m on m.id=mi.module_id where m.course_id=v_course)
 or exists(select 1 from public.lab_tool_courses where course_id=v_course)
 then raise exception 'Dance student/evidence dependencies block rollout'; end if;
 if (select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('jpac_sync_enrollment_progress','jpac_enforce_canonical_enrollment_progress') and (select count(*) from regexp_matches(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m\.status=''published''','g'))=2 and strpos(regexp_replace(lower(pg_get_functiondef(p.oid)),'\s+','','g'),'m.status<>''archived''')=0)<>2 then raise exception 'Safe Draft Isolation is not active'; end if;
 if (select count(*) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='enrollments' and t.tgname='enrollments_enforce_canonical_progress' and not t.tgisinternal and t.tgenabled<>'D')<>1 then raise exception 'Canonical enrollment progress trigger missing'; end if;

 v_rubric:=jsonb_build_object('criteria',jsonb_build_array(
  jsonb_build_object('name','Rhythm & Timing','weight',20,'bands',jsonb_build_object('Exceeds','Consistently exceeds the approved standard.','Meets','Meets the approved standard.','Developing','Partially meets the standard.','Not Yet','Does not yet meet the standard.')),
  jsonb_build_object('name','Technique & Body Control','weight',25,'bands',jsonb_build_object('Exceeds','Consistently exceeds the approved standard safely.','Meets','Meets the approved standard safely.','Developing','Partially meets the standard with further safe practice needed.','Not Yet','Does not yet meet the standard safely.')),
  jsonb_build_object('name','Musicality & Expression','weight',20,'bands',jsonb_build_object('Exceeds','Consistently exceeds the approved standard.','Meets','Meets the approved standard.','Developing','Partially meets the standard.','Not Yet','Does not yet meet the standard.')),
  jsonb_build_object('name','Choreography / Movement Design','weight',20,'bands',jsonb_build_object('Exceeds','Consistently exceeds the approved standard.','Meets','Meets the approved standard.','Developing','Partially meets the standard.','Not Yet','Does not yet meet the standard.')),
  jsonb_build_object('name','Performance Presence & Confidence','weight',15,'bands',jsonb_build_object('Exceeds','Consistently exceeds the approved standard.','Meets','Meets the approved standard.','Developing','Partially meets the standard.','Not Yet','Does not yet meet the standard.'))
 ));

 for r in select * from jsonb_to_recordset('[
 {"level":1,"num":1,"sort":1,"title":"Rhythm & Body Awareness"},{"level":1,"num":2,"sort":2,"title":"Basic Steps & Patterns"},{"level":1,"num":3,"sort":3,"title":"Simple Hip-Hop Grooves"},{"level":1,"num":4,"sort":4,"title":"Rock Energy & Attitude"},{"level":1,"num":5,"sort":5,"title":"Rock and Roll Footwork"},{"level":1,"num":6,"sort":6,"title":"Classic Dance Moves Everyone Knows"},{"level":1,"num":7,"sort":7,"title":"Stretching for Dancers"},{"level":1,"num":8,"sort":8,"title":"Intro to Isolations"},{"level":1,"num":9,"sort":9,"title":"Building Stamina"},{"level":1,"num":10,"sort":10,"title":"Freestyle Your First 8-Count"},{"level":1,"num":11,"sort":11,"title":"Performance & Presentation"},{"level":1,"num":12,"sort":12,"title":"Beginner Showcase: Your Dance Journey"},
 {"level":2,"num":1,"sort":13,"title":"Mastering Isolations"},{"level":2,"num":2,"sort":14,"title":"Turns and Pirouettes"},{"level":2,"num":3,"sort":15,"title":"Jumps and Leaps"},{"level":2,"num":4,"sort":16,"title":"Musicality and Phrasing"},{"level":2,"num":5,"sort":17,"title":"Contemporary Dance Basics"},{"level":2,"num":6,"sort":18,"title":"Intermediate Choreography"},{"level":2,"num":7,"sort":19,"title":"Freestyle and Improvisation Skills"},{"level":2,"num":8,"sort":20,"title":"Dynamics and Textures"},{"level":2,"num":9,"sort":21,"title":"Strength and Conditioning"},{"level":2,"num":10,"sort":22,"title":"Audition and Performance Prep"},{"level":2,"num":11,"sort":23,"title":"Teaching Dance Basics"},{"level":2,"num":12,"sort":24,"title":"Intermediate Showcase: Artistic Growth"},
 {"level":3,"num":1,"sort":25,"title":"Complex Rhythms and Syncopation"},{"level":3,"num":2,"sort":26,"title":"Advanced Turns and Combinations"},{"level":3,"num":3,"sort":27,"title":"Storytelling Through Movement"},{"level":3,"num":4,"sort":28,"title":"Partnering and Lifts"},{"level":3,"num":5,"sort":29,"title":"Ayo & Teo: Dance Revolution"},{"level":3,"num":6,"sort":30,"title":"Jazz and Lyrical Fusion"},{"level":3,"num":7,"sort":31,"title":"Advanced Improvisation Structures"},{"level":3,"num":8,"sort":32,"title":"Floorwork and Transitions"},{"level":3,"num":9,"sort":33,"title":"The Business of Dance"},{"level":3,"num":10,"sort":34,"title":"Creating a Dance Concept Video"},{"level":3,"num":11,"sort":35,"title":"Exploring Dance for Social Impact: Community Building and Activism"},{"level":3,"num":12,"sort":36,"title":"Advanced Blues Dance Choreography: Mastering the Art of Expression"},
 {"level":4,"num":1,"sort":37,"title":"Developing Your Signature Style"},{"level":4,"num":2,"sort":38,"title":"Advanced Choreographic Principles"},{"level":4,"num":3,"sort":39,"title":"Teaching and Leading a Class"},{"level":4,"num":4,"sort":40,"title":"Artist Study: Michael Jackson"},{"level":4,"num":5,"sort":41,"title":"Artist Study: Beyoncé"},{"level":4,"num":6,"sort":42,"title":"Directing and Producing a Dance Show"},{"level":4,"num":7,"sort":43,"title":"Dance for Camera"},{"level":4,"num":8,"sort":44,"title":"Grant Writing and Funding"},{"level":4,"num":9,"sort":45,"title":"Grant Writing and Project Funding"},{"level":4,"num":10,"sort":46,"title":"Legacy and Mentorship"},{"level":4,"num":12,"sort":47,"title":"Master''s Magnum Opus: Dance Legacy"}
 ]'::jsonb) as x(level int,num int,sort int,title text) order by sort loop
  select id into v_level from public.course_levels where course_id=v_course and level_number=r.level;
  if v_level is null then
   insert into public.course_levels(id,course_id,level_number,title,description,learning_objectives,status,core_xp_target,review_notes)
   values(gen_random_uuid(),v_course,r.level,v_levels[r.level],'Draft Dance level; source-aligned review only.',array['Develop source-aligned Dance movement, musicality, choreography, and performance skills safely.'],'draft',case when r.level<4 then 7500 else 6875 end,v_marker||'; batch-created level; metadata target reconciliation deferred.') returning id into v_level;
  elsif not exists(select 1 from public.course_levels where id=v_level and title=v_levels[r.level] and status='draft' and approved_by is null and approved_at is null) then raise exception 'Incompatible Dance level %',r.level; end if;

  select id into v_module from public.course_modules where course_id=v_course and (sort_order=r.sort or (course_level_id=v_level and level_module_number=r.num));
  if v_module is null then
   insert into public.course_modules(id,course_id,course_level_id,level_module_number,title,description,short_intro,sort_order,xp_value,core_xp,intro_core_xp,video_core_xp,assignment_core_xp,mastery_core_xp,core_unlock_threshold,bonus_xp_available,jpac_tool_activity,real_world_activity,career_connection,portfolio_moment,status,video_brief,aria_coaching_targets,career_mission_ideas,review_notes)
   values(gen_random_uuid(),v_course,v_level,r.num,r.title,'Develop and demonstrate source-aligned Dance skills for '||r.title||'.','Draft source-aligned Dance module.',r.sort,625,625,50,100,350,125,438,0,'{}'::jsonb,jsonb_build_object('title',r.title||' Guided Practice','instructions','Rehearse in a clear safe space using a teacher-approved accessible adaptation.'),'',false,'draft','NEEDS REVIEW: no media is activated.',jsonb_build_object('advisory_only',true,'targets',jsonb_build_array('movement safety','warmup and preparation','rhythm and timing','musicality','coordination','creativity','performance confidence','choreography feedback'),'prohibited',jsonb_build_array('assess','approve','diagnose injury','award XP','grant mastery','unlock')),'[]'::jsonb,v_marker||'; source-aligned module; AI-PROPOSED lesson and assessment criteria require Dance teacher review. Media NEEDS REVIEW; Tools NEEDS CATALOG REVIEW; no media or tool records are created.'||case when r.level=4 and r.num in(8,9) then ' NEEDS REVIEW: grant/funding modules retained separately pending future consolidation review.' else '' end) returning id into v_module;
   v_module_created:=true;
  elsif not exists(select 1 from public.course_modules where id=v_module and course_level_id=v_level and level_module_number=r.num and sort_order=r.sort and title=r.title and description='Develop and demonstrate source-aligned Dance skills for '||r.title||'.' and short_intro='Draft source-aligned Dance module.' and status='draft' and xp_value=625 and core_xp=625 and intro_core_xp=50 and video_core_xp=100 and assignment_core_xp=350 and mastery_core_xp=125 and core_unlock_threshold=438 and bonus_xp_available=0 and jpac_tool_activity='{}'::jsonb and real_world_activity=jsonb_build_object('title',r.title||' Guided Practice','instructions','Rehearse in a clear safe space using a teacher-approved accessible adaptation.') and career_connection='' and not portfolio_moment and video_brief='NEEDS REVIEW: no media is activated.' and lab_tool_id is null and active_instructional_media_id is null and primary_video_url is null and approved_by is null and approved_at is null) then raise exception 'Incompatible Dance module L% M%',r.level,r.num; end if;

  if v_module_created is distinct from true then
   if (select count(*) from public.lessons where module_id=v_module)<>3
   or (select count(*) from public.lessons where module_id=v_module and status='draft' and xp_value=0 and title in(r.title||': Foundations and Safety',r.title||': Guided Application',r.title||': Performance and Reflection'))<>3
   or (select count(*) from public.activities where module_id=v_module)<>2
   or (select count(*) from public.activities where module_id=v_module and title=r.title||' Guided Practice' and status='draft' and activity_type='practice' and not required and xp_reward=0 and xp_type='bonus')<>1
   or (select count(*) from public.activities where module_id=v_module and title=r.title||' Core Challenge' and status='draft' and activity_type='performance' and required and xp_reward=350 and xp_type='core' and passing_score=70 and allows_resubmission and rubric=v_rubric)<>1
   then raise exception 'Existing Dance module children are not exact-compatible L% M%',r.level,r.num; end if;
  else
   for i in 1..3 loop
    v_lesson_title:=case i when 1 then r.title||': Foundations and Safety' when 2 then r.title||': Guided Application' else r.title||': Performance and Reflection' end;
    insert into public.lessons(id,module_id,title,description,lesson_type,duration_minutes,sort_order,xp_value,status,short_summary,learning_objective,content_blocks,technique_cues,common_mistakes,self_check,resource_brief)
    values(gen_random_uuid(),v_module,v_lesson_title,'Study and apply '||v_lesson_title||'.','interactive',25,i,0,'draft','Source-aligned Dance lesson; draft review only.','Study and apply '||v_lesson_title||'.',jsonb_build_array('Check space, surface, footwear, and pain-free readiness.','Warm up gradually and rehearse the source-aligned movement at an appropriate intensity.','Reflect on timing, control, musicality, and one safe next step.'),array['Control before speed or range','Use pain-free movement and teacher-approved adaptations','Stop for pain, dizziness, instability, numbness, or unsafe fatigue'],array['Skipping preparation','Forcing range or intensity','Continuing through pain or unsafe fatigue'],'Can you demonstrate the objective safely and explain one movement or musical choice?','AI-PROPOSED accessibility/no-tool alternatives require Dance teacher review.');
   end loop;
   insert into public.activities(id,course_id,module_id,title,description,activity_type,instructions,submission_type,xp_reward,estimated_minutes,required,status,rubric,skill_tags,ai_summary,xp_type,passing_score,allows_resubmission,portfolio_candidate,certificate_eligible) values
   (gen_random_uuid(),v_course,v_module,r.title||' Guided Practice','Optional source-aligned Dance preparation.','practice','Warm up, confirm a clear safe space, and rehearse using a teacher-approved accessible alternative. CapCut and Cakewalk are optional examples only.','none',0,20,false,'draft','{}'::jsonb,'{}'::text[],'AI-PROPOSED; optional, non-progressive, non-assessed; teacher review required.','bonus',70,true,false,false),
   (gen_random_uuid(),v_course,v_module,r.title||' Core Challenge','Required source-aligned Dance Core Challenge.','performance','Submit a safe source-aligned movement performance and reflection through the existing JPAC submission and teacher-review workflow. Teacher-approved live, adapted, seated, reduced-impact, annotated, or other accessible evidence is allowed when it demonstrates the objective.','video',350,30,true,'draft',v_rubric,'{}'::text[],'AI-PROPOSED; teacher review required; Aria advisory only.','core',70,true,false,false);
  end if;
  v_level:=null; v_module:=null; v_module_created:=false;
 end loop;
 if exists(select 1 from public.course_modules where course_id=v_course and course_level_id in(select id from public.course_levels where course_id=v_course and level_number=4) and level_module_number=11) then raise exception 'Fake Master Module 11 must not exist'; end if;
end $$;
commit;
