import type{AcademyCourse,CourseLesson,CourseModule,LessonProgress}from'../../lib/studentAccess';
import type{CoachContext,CoachLink}from'./types';

export function buildDashboardCoachContext(courses:AcademyCourse[],nextLink:CoachLink):CoachContext{const recent=[...courses].filter(course=>course.last_accessed_at).sort((a,b)=>String(b.last_accessed_at).localeCompare(String(a.last_accessed_at)))[0]||courses[0];return{surface:'dashboard',title:recent?.title||'My Academy',summary:recent?`Your next authorized learning step is in ${recent.title}.`:'Your enrolled programs will appear when Academy access is available.',nextLink}}
export function buildCourseCoachContext(course:{id:string;title:string;description?:string},modules:CourseModule[],lessons:CourseLesson[],progress:LessonProgress[]):CoachContext{const progressById=new Map(progress.map(item=>[item.lesson_id,item]));const next=lessons.find(lesson=>progressById.get(lesson.id)?.status!=='completed');return{surface:'course',title:course.title,summary:course.description||`${modules.length} published modules are available in this authorized course.`,nextLink:next?{label:`Continue: ${next.title}`,to:`/courses/${course.id}/lessons/${next.id}`}:{label:'Review published modules',to:`/courses/${course.id}`}}}
export function buildModuleCoachContext(input:{courseId:string;module:CourseModule;instructions?:string;rubric?:unknown;teacherFeedback?:string|null;hasPreparedEvidence?:boolean}):CoachContext{return{surface:'module',title:input.module.title,objective:input.module.short_intro||input.module.description,authoredInstructions:input.instructions,rubric:input.rubric,teacherFeedback:input.teacherFeedback,hasPreparedEvidence:input.hasPreparedEvidence,nextLink:{label:'Review module lessons',to:`/courses/${input.courseId}/modules/${input.module.id}`}}}
export function buildLessonCoachContext(courseId:string,module:CourseModule,lesson:CourseLesson,nextLesson:CourseLesson|null):CoachContext{return{surface:'lesson',title:lesson.title,objective:lesson.learning_objective||lesson.short_summary||lesson.description,summary:`This lesson belongs to ${module.title}.`,nextLink:nextLesson?{label:`Next lesson: ${nextLesson.title}`,to:`/courses/${courseId}/lessons/${nextLesson.id}`}:{label:'Return to module',to:`/courses/${courseId}/modules/${module.id}`}}}
export function buildToolCoachContext(title:string,description:string):CoachContext{return{surface:'tool',title,summary:description,practiceLink:{label:'View all Creator Tools',to:'/studio'}}}
export function buildExtraCreditCoachContext(summary:string,submission?:{status:string;teacher_feedback?:string|null}):CoachContext{return{surface:'extra_credit',title:'Creator Tool extra credit',summary:summary.slice(0,240),submissionStatus:submission?.status,teacherFeedback:submission?.status==='needs_revision'?submission.teacher_feedback:null}}
